### ISSUE TITLE
Split velocity.ui into its own repo

### ISSUE THREAD

**Issue by ekryski** [julianshapiro/velocity#131]
The reason I'm suggesting this is so that you can require them independently. Otherwise you need to start mucking around with paths in order to load `velocity.ui`. As an example, I'm using browserify... it would be nice to be able to just do:

``` js
require('velocity');
require('velocity-ui');
```

Currently not possible with npm or bower. Thoughts @julianshapiro?

**Comment by oompt** [comment]
This would help a lot with jspm.
