### ISSUE TITLE
Feature: Pause/Resume

### ISSUE THREAD

**Issue by ngokevin** [julianshapiro/velocity#14]
I wonder if https://github.com/tobia/Pause/blob/master/jquery.pause.js can be repurposed to wrap over $.velocity instead of $.animate to enable pausing/resuming velocity animations.

**Comment by albertogasparin** [comment]
+1

**Comment by wlindner** [comment]
I ended up implementing the animation using the ```animation-play-state``` (https://developer.mozilla.org/en-US/docs/Web/CSS/animation-play-state) css property and relying on CSS animation instead of using Velocity.js. My animation is very simple and repetitive so it was relatively straightforward to implement using CSS animations.

Here was the simple prototype I tested it with: http://codepen.io/wlindner/pen/AiqKD and this was the more complex animation I was trying to create: http://codepen.io/wlindner/pen/qItdC

Unfortunately, this doesn't resolve anything with Velocity.js, but is an approach worth considering.

**Comment by MiincGu** [comment]
+1

**Comment by bobiblazeski** [comment]
+1

**Comment by tconroy** [comment]
+1

**Comment by pmaroncelli** [comment]
+1

**Comment by bin3** [comment]
+1

**Comment by emiled** [comment]
+1

**Comment by FuzzyWobble** [comment]
plus one

**Comment by mu3** [comment]
+1

**Comment by troygrosfield** [comment]
@julianshapiro, here's a use case for you, I'm the creator of [Moving Media](https://moving.media) where users can create movies from media and animate it along a timeline.  I was looking to implement your library for movie animations for the fact that it works well with SVG.  

I'm currently using [jquery.transit](https://github.com/rstacruz/jquery.transit) for all movie animations which leverages the browsers ``animation-play-state`` as @wlindner has mentioned above.  It works well, but again, doesn't have SVG support like velocity does.  Plus, I'm not sure if jquery.transit is still being actively maintained so I was looking for an alternative.  

Why not just implement an additional method on an object that immediately stops the css property animation iteration?

```js
$('#myObj').velocity('pause');
```

That just looks at the current state and freeze it?  Seems fairly trivial to me. The final results would allow a developer to do something like the following (see play/pause functionality in the movie below):

- https://moving.media/movies/17/image-motion-demo-with-effects

**Comment by morunas** [comment]
+1

**Comment by breedx2** [comment]
+1

Even though I've read prior comments to the effect of "Well, velocity is a UI library and it doesn't have this use case" -- the efficient/optimized drawing/caching of velocity and easy of code use make some of us use it for other (artistic) things.  Play/pause would help here for sure!

**Comment by Rycochet** [comment]
Coincidentally #718 will probably get pulled sometime over the weekend - and we'll get another release to go with it ;-)

**Comment by gaorongfu** [comment]
I also need the pause ability in my game .

**Comment by Rycochet** [comment]
@gaorongfu It got added over a month ago...

**Comment by gaorongfu** [comment]
@Rycochet That's great!
