### ISSUE TITLE
All-edges scrolling

### ISSUE THREAD

**Issue by MzHub** [julianshapiro/velocity#150]
Two feature suggestions:

Option to scroll the bottom of the element to the bottom of the page instead of scrolling the top of the element to the top of the page. Also right instead of left.
Maybe `{axis: x|y}` -> `{side: top|left|right|bottom}` or similar.

Option to scroll the element into view by using the feature above, preferrably with an offset.
I.e. only scroll the element if it is outside of the viewport and scroll it to the correct side.

Would these be out of scope for velocity? I think they might benefit from the caching and ability read properties/subproperties.

EDIT: Use case: an element that is off-screen or partially off-screen is focused or activated and needs to be scrolled into view.

**Comment by aristidesfl** [comment]
It would be also useful to be able to center an element in the page with the scroll animation
