### ISSUE TITLE
[ TESTERS WANTED ] Velocity UI Pack Feature: "animateParentHeight"

### ISSUE THREAD

**Issue by julianshapiro** [julianshapiro/velocity#161]
The UI pack has a new (and currently undocumented) option entitled `animateParentHeight`.

First, update your copies of Velocity and the UI pack.

Second, simply pass the `animateParentHeight` property into a UI pack effect call to have the targeted elements' containing element expand/contract vertically as the animating children are transitioned in/out of view. (`animateParentHeight` can naturally only be used with transition effects  -- whose names end in In/Out.)

```javascript
$elements.velocity("transition.bounceIn", { animateParentHeight: true });
```

Example CodePen: http://codepen.io/julianshapiro/pen/wrAqI/ . You can play around with `stagger` and `backwards` options.

Prior to this feature existing, transitioning elements that were inside a containing element would cause the container's height to jump in discrete steps (equal to the targeted elements' individual heights) instead of fluidly animate. (This same problem naturally occurs with every other animation library.)

**I need you guys to test this out in your own environments/use cases and point out any issues before I finalize the feature and document it.** Note: Do not implement this in production environments yet. If this feature turns out to be buggy, it may very well be dropped altogether.

**Comment by aristidesfl** [comment]
This looks awesome. 
Would be nice to be able to use the one object notation as well to make it more explicit and readable, specially since the minimum use case for this function is by default complex.

```
$.Velocity.shift({
    parentElement: parentElement,
    duration: 1000, // The durations specified in the options objects below are ignored
    outgoing: { elements, propertiesMap, options },
    incoming: { elements, propertiesMap, options }
});
```

**Comment by aristidesfl** [comment]
animateParentHeight: padding + border-box = parent too tall 
http://jsbin.com/xakipigino/1/edit?html,css,js,output

**Comment by Rycochet** [comment]
Padding is not taken into account with border-box any more
