### ISSUE TITLE
[Docs] Bluebird's docs actually state it supports IE back to 7

### ISSUE THREAD

**Issue by ydaniv** [julianshapiro/velocity#167]
> IE7 and IE8 had to be removed from tests due to SauceLabs bug but are supported and pass all tests

You probably saw the tests coverage and skipped ahead (:

**Comment by QuantumInformation** [comment]
Is ie8 supported?

**Comment by Rycochet** [comment]
http://julian.com/research/velocity/ - third paragraph is "Compatibility" - and that's a yes - the Bluebird bug report has also been closed with a fix apparently ;-)
