### ISSUE TITLE
Infinite looping

### ISSUE THREAD

**Issue by mylesthedev** [julianshapiro/velocity#175]
This is my humble request for you to please implementing infinite looping.

**Comment by macsupport** [comment]
I've made some spinner examples  using an icon font and rotateZ with a long duration. Here is my example: http://codepen.io/macsupport/pen/myrPjL
 I have tried loop:true to make them "infinite" but I don't get the smooth rotation I would like: http://codepen.io/macsupport/pen/wBoWaN
Any way to get the spinner animation looping in a smoother rotation using loop:true?

**Comment by oliver-eifler** [comment]
@macsupport: to get smooth animations I always calculate the duration on a steps per frame (1/60sec.) basis:
for example: translateX:300 in 25 steps => duration: 60*(300/25)
In your pen:

function veloSpinner() {
      ...
      var value = 360; //animate to  
      var steps = 6; //animation steps per frame (1/60sec.) 
      var time = 60*(value/steps); //animation time
      $('.vel').velocity({rotateZ: value}, {duration:time,easing:'linear',loop:true});
}

here's a modified fork of your pen: http://codepen.io/anon/pen/yyVJJN

**Comment by sivan** [comment]
Same [animation-direction](https://github.com/julianshapiro/velocity/issues/175#issuecomment-60631568) problem like codyleach, and the solution [he posted](https://github.com/julianshapiro/velocity/issues/175#issuecomment-60664175) works for me.

Hope if there is a loopAlternate option. It's very useful with a step easing & loop animation.[[example](http://codepen.io/sivan/pen/meBqYZ)]
