### ISSUE TITLE
Add support for calc()

### ISSUE THREAD

**Issue by tobz-nz** [julianshapiro/velocity#193]
Currently setting a value using css the calc() function fails.
eg:

``` js
$(el).velocity({width: 'calc(100% - 10px)'});
```

The result is `0px` instead.

**Comment by yunyuyuan** [comment]
I'll just use jQuery

**Comment by Rycochet** [comment]
> I'll just use jQuery

This is a six year old post, Velocity v2 beta has supported calc since the start of it...
