### ISSUE TITLE
Ordering of transform properties is not preserved

### ISSUE THREAD

**Issue by parinck** [julianshapiro/velocity#197]
I want 
rotateX(abc) rotateY(cde) and then translateZ(asdf)

![selection_005](https://cloud.githubusercontent.com/assets/7147507/3655812/9bfb7c6c-117e-11e4-975b-acb1d388009a.png)

but sometimes 

![selection_004](https://cloud.githubusercontent.com/assets/7147507/3655823/c623f4c4-117e-11e4-8d70-efd5d7eaa66a.png)

I get rotateX(abc) translateZ(asdf) and then rotateY(cde)

because of that I am unable to achieve desired effect.

**Comment by samuelhorwitz** [comment]
I implemented a solution for this. Basically, there is an options argument which is by default an empty array. It can be filled with an ordered list of transform properties. It will sort the `transformCache` before applying it. 7fc7bdd815c01639df96a24728f607d81f0b84f2.

**Comment by julianshapiro** [comment]
Interesting......................... You should clear the whitespace change commits and open a new GH issue with your changes and a copy of the description you just wrote. I really like this.

**Comment by samuelhorwitz** [comment]
Yeah I just updated it, check 643cd0b9ef6dd62af51c9c49f22b5b8895a479da
