### ISSUE TITLE
Add a zIndex option

### ISSUE THREAD

**Issue by Rycochet** [julianshapiro/velocity#200]
Where there's already options for Display and Visibility, having a zIndex one may be useful.

It would remember the old value, and only set the zIndex while animating, then reset to the saved value after finishing or being stopped (sort of like how the translateZ value is set for mobile acceleration etc).

While the alternative (setting a z-index on the .animating class) works very well for my specific use, it wouldn't work so well if I was only wanting to set the z-index on one specific animation etc - hence I'm going to reference #194 here since being able to change the animating class in an option could achieve the same effect.

**Comment by gabemartin** [comment]
In case this can help someone else, here is how I handled it using the `complete` callback:

`
$(".element")
  .delay(500)
  .velocity("transition.slideDownIn", { duration: 500, complete: 
    function() { 
      $(this).css("transform","");
  }
})
`
