### ISSUE TITLE
Should Velocity continue to auto-remove transform values when they hit default values?

### ISSUE THREAD

**Issue by justnorris** [julianshapiro/velocity#224]
Here is what I'm doing:

~~~coffeescript
		$container
			.find('.pfentry__info')
			.velocity('stop')
			.velocity
				properties:
					opacity: 1
					scale: [1, 0.9]
				options:
					display: 'block'
					duration: 225
~~~

I have this in my CSS:

~~~css
.pfentry__info {
 opacity: 0;
 transform: scale(0.9);
}
~~~

When Velocity is run, it scales with forcefeeding from 0.9 to 1, and then it drops `scale(1)`, but keeps `opacity: 1`.

How do I fix it ? ( a tmp fix would be to remove the transform from CSS,  but I'm thinking that this could be a Velocity bug ? )

**Comment by MattyBalaam** [comment]
Should velocity remove attributes if fed an empty string, similar to the way jQuery's css function?

I am getting a load of stacking context issues with default values being left on the element, and am wondering if this is what hook should be used for, rather than jQuery css.

**Comment by ydaniv** [comment]
@MattyBalaam I can't find any sense in telling Velocity to animate something to `""`. Or perhaps I don't follow you.

**Comment by MattyBalaam** [comment]
As an example if you animate translateY to its default value of '0' you get an inline style left-over 'transform: translateY(0px);' Usually this is desired behavior, but the stacking-context as a result of this style can give unwanted results.A previous version of velocity did clear styles when hitting the default, and I wondered if an empty string could be a good way of signalling an intention to clear the style as this is how jQuery's css function will work.

It seems at the moment I need to clear styles outside of velocity, trying using the hook function with an empty string does nothing. I am worried that in the case of using jQuery's CSS it will introduce some extra lag - although I am not an expert on the full impact on performance.

**Comment by bl-inc** [comment]
For my use, I ended up reverting commit 1369de1. Now the inline transform: translateY(0px); is removed at the end of the animation.  This fixed the strange zindex and positioning issues I was encountering.

**Comment by ikixxx** [comment]
@bl-inc If you don't want to modify the source you can use `complete` callback to "manually" remove the transformation from the element.

**Comment by julianshapiro** [comment]
<3

**Comment by bl-inc** [comment]
@ikixxx sure using the complete callback was my first solution mentioned earlier in the thread.  Unfortunately in a series of staggered animations, the complete callback is only called once at the end and is not per element.  It can be seconds before the complete is called.

**Comment by ikixxx** [comment]
Oh, I understand it needs to be done immediately, and  stagger is the
problem. Also somehow I missed that post when you mentioned `complete`
callback.
I apologize.

**Comment by MattyBalaam** [comment]
I have hit the z-index stacking-context issue again in a different project, it seems to come up quite often for me when using velocity, and while it is a solution to add in extra commands on complete to clear the styles, would it be feasible to have an option to remove animated styles back? As it stands you can't even use the hook function as an empty string produces no result.

I have produced a synthetic test case, as you can see, once an element has been animated once, lower numbered items will always stack behind.

http://jsfiddle.net/5gzzzg8e/9/

**Comment by ydaniv** [comment]
@MattyBalaam I think what you refer to as z-index stack is actually a promotion of an element you're animating into a separate layer by the browser's rendering engine, since you're animating transforms.
Promoted layers will appear on top, regardless of z-index, and the only solution is to clear transform styles.

@julianshapiro worth investigating whether this can be fixed programmatically since it will probably bite many users animating transforms, especially on Webkits and the like.

**Comment by MattyBalaam** [comment]
@ydaniv Yes, that is exactly what I was trying to say, but getting my terminology slightly wrong, thanks for clarifying.

**Comment by Yalpe** [comment]
Just chiming in to say that I've had this bug in my app for a few months and I finally tracked it down to this issue. It took me a couple of debugging sessions here and there as it is not really obvious why it interacts so badly with mobile dragging on android (only?). It seems counter-intuitive to leave style attributes on elements after the animation is done.

Maybe you could add a flag that we can pass in the options so that velocity can revert all the CSS it adds after it is done? I love velocity so far as it is one of the few plugins I've never had to edit manually so keep up the good work.

**Comment by justnorris** [comment]
This is marked as help wanted - what kind of help are you looking for :) ? 


By the way - it's currently impossible to remove a value with Velocity hook:
~~~js
$.Velocity.hook($('#page'), 'translateY', ''); // Doesn't remove translateY
~~~

**Comment by ydaniv** [comment]
Thanks for the heads up @justnorris, currently these calls are not available in the API, but might be worth considering.

Actually, all it takes is check (https://github.com/julianshapiro/velocity/blob/master/velocity.js#L1981)[here] for `''`/`null`/`false` and use `removeProperty()` instead.

**Comment by silentFred** [comment]
Gosh i'm in a pickle now. I'm using this angular wrapper for velocity ui pack: https://github.com/rosslavery/velocity-ui-angular @rosslavery

I'm also struggling with the leftover translateY styles messing with the original order of the elements in the div.

**Comment by dcalhoun** [comment]
I'm also interested in the ability that @justnorris describes. The fact that inline `translate` values remain after the animation is causing scrolling issues on touch devices for me.

I'm currently removing then in the `complete` callback with `$(element).removeAttr('style')`, but it'd be nice to use `$.Velocity.hook($(element), 'translateX', '')`.

**Comment by quickstep25** [comment]
much appreciated @dcalhoun !  the callback was just what I needed to fix the issue -- works perfectly now.

**Comment by drewbaker** [comment]
I'm having the same issue @MattyBalaam described above.

If I have an element like this:

```
    <div id="menu"></div>
```

```
    // Slide over container
    jQuery('.closed #menu').velocity({ 
        translateX: '160px'
    }, 400);
```

Then this:
```
    jQuery('.opend #menu').velocity({ 
        translateX: '0'
    }, 400);
```

The div will look like this:
```
    <div id="menu" style="transform: translateX(0px);"></div>
```

Which is not right. There should not be any inline style left on `#menu`. It messes up Z-index, and fixed positioned elements inside of menu.

**Comment by pajaroblanco** [comment]
I'm having the same problem as @silentFred using the angular velocity wrapper to animate views in. After the animation the left over transform style causes things like a date picker modal window to render completely out of view.

**Comment by Rycochet** [comment]
v1 is now feature locked, so not changing.
