### ISSUE TITLE
Feature: Horizontal Scrolling Support *** Done. Please report any bugs. ***

### ISSUE THREAD

**Issue by nltesown** [julianshapiro/velocity#24]
The `scroll` command seems to be only dealing with vertical scrolling. How about implementing horizontal scrolling too?

**Comment by arunsn43** [comment]
As i understand, it always scroll towards right and 'reverse' helps in reversing the animation. It looks like, still scrollToLeft is required for moving towards left.  Whats the best option?

**Comment by Rycochet** [comment]
@arunsn43 Not sure what you mean. Maybe try asking on StackOverflow as this doesn't sound like a bug report...
