### ISSUE TITLE
Posibility to stop all current and pending animations

### ISSUE THREAD

**Issue by DanEEStar** [julianshapiro/velocity#241]
Background: I have a quiz-game application with several animations. It is possible to restart the whole thing in the middle of the game with some animations still running. I coded the game with Backbone and Marionette. In a restart the whole quiz-subpage (with its DOM-elements) get removed from the page, but there is not a reload of the page.

Now I have the problem, that after a restart the complete-callbacks of some of the velocity-animations still get triggered, even when the DOM-elements are not on the page anymore, which results in errors by selecting outdated elements.

One solution IMO would be a global method to stop all animations in velocity.
Is this possible anyhow?

Thanks in advance.

**Comment by vedmant** [comment]
How do I do this without jQuery, using Velocity() api?
