### ISSUE TITLE
Delay in animations during touchmove events on mobile Safari

### ISSUE THREAD

**Issue by macgyver** [julianshapiro/velocity#261]
I just noticed this on an iPhone 5S - velocity animations triggered by a touch event don't execute until after the touch has ended. I'm guessing this is somehow due to the requestAnimationFrame implementation in Safari for iOS, it seems like it doesn't invoke the functions queued up until all touches have ended.
jQuery animations behave the same way in this situation, possibly setTimeout/Interval also suffer from the same feature. So, not really a velocity bug, but I'm just wondering if you had noticed this and might have any thoughts about how to address it? I'm thinking it's best to just use CSS transitions triggered by class changes in this scenario..

**Comment by Jaylala03** [comment]
Hello Julian

Sir i have been using velocity.js for a long time. I am using version 1.2.3 but facing a animation pause issue for sometime. Was it a bug in older version or should i update to new version. Please need your guidance on this. 

Thank you.

**Comment by Rycochet** [comment]
@Jaylala03 Pause was added in 1.4 - you need to update.

**Comment by Jaylala03** [comment]
The issue is not about adding a pause. Animation scroller stops for few seconds and then resumes scrolling.

**Comment by Rycochet** [comment]
@Jaylala03 In which case update and see if it's fixed, if not then follow the [guidelines](https://github.com/julianshapiro/velocity/blob/master/CONTRIBUTING.md) for creating a new issue and add a JSFiddle reproducing it.

**Comment by Jaylala03** [comment]
Thank you sir.
