### ISSUE TITLE
Stopping a UI pack effect doesn't fulfill promise

### ISSUE THREAD

**Issue by julianshapiro** [julianshapiro/velocity#268]
Stopping a UI pack effect (w/ or w/o clearing the remainder of the element's queue) doesn't trigger promise fulfillment because the UI pack effect's final animation call's complete option is what contains the promise handling logic.

Might have to introduce a boolean `always` option that works with the `complete` callback so that it's always triggered.

**Comment by filipeskeeled** [comment]
Hey julian, how do you use the always callback? I've been playing with it but didn't manage to get it to work.

**Comment by Rycochet** [comment]
The ui-pack is now standard animations within Velocity
