### ISSUE TITLE
fontSize can be animated, but font-size cannot

### ISSUE THREAD

**Issue by andrewspode** [julianshapiro/velocity#27]
I've been using .animate to change font-sizes as an animation to display scaling to fit a box. I then replaced this with the jQuery Transit's plugins .transition and it also worked. Changing to .velocity and this breaks.

In my list of properties I have:

{"font-size" : "100px"}

If I do this, it ends up with the font-size as 0px. 

The only way I've managed to get this to work is by using:

{"fontSize" : "100px"}

Is this intended behaviour, or a bug?

**Comment by Lalnuntluanga** [comment]
I tried to animate font size but, what It does is it resize down to 0 first and then comeback to desired size. I just want it to resize for a few range.

**Comment by Rycochet** [comment]
http://julian.com/research/velocity/#forcefeeding

**Comment by Lalnuntluanga** [comment]
Thanks, it work. @Rycochet
