### ISSUE TITLE
Is it possible to reveal animation on scroll?

### ISSUE THREAD

**Issue by sam-tse** [julianshapiro/velocity#279]
Hi, have a question - using velocity.js alone, is it possible to reveal/trigger an animation when scrolling? For example, like the animations shown on wow.js at http://mynameismatthieu.com/WOW/. Or do I need to use another javascript library (such as wow.js) to achieve this?

Any tips is appreciated. Thank you!

**Comment by palashkaria** [comment]
Any workaround which will suffice temporarily?
