### ISSUE TITLE
Animating elements that have initial values declared in CSS

### ISSUE THREAD

**Issue by fluxxus** [julianshapiro/velocity#280]
Hi, this is a newbie question. I want to animate one element that needs to be initially hidden off screen, and brought into view by click of a button.
I've read the documentation and the tradeoffs, and tried playing with forcefeeding, but with no luck.

I am currently doing it like this, first by having this line in the document ready function:
`$('.home-box:nth-of-type(1)').velocity({translateX: "-100%"}, 1)`

And then animating it back on click event:
`$('.home-box:nth-of-type(1)').velocity({translateX: "0"}, 1000);`

What is the right way to do this, as this is surely wrong what I am doing :)

**Comment by alvarotrigo** [comment]
@julianshapiro the problem with that is that you still need to use `transform:translateX(-100%);` on the CSS styles. Which makes it incompatible with old browsers such as IE < 10.

The other option would be using the `left` property instead, but... [would that be slower](https://github.com/julianshapiro/velocity/issues/423)?

**Comment by MattyBalaam** [comment]
It will work on IE9, but IE8 will not, as always it depends on your target audience.

**Comment by alvarotrigo** [comment]
So the only case would be using `left`. Right? Which... is slower?

**Comment by MattyBalaam** [comment]
Try testing yourself: http://jsfiddle.net/
