### ISSUE TITLE
velocity alternative to jquery switchClass?

### ISSUE THREAD

**Issue by cocodrino** [julianshapiro/velocity#290]
Hi Julian and everybody, I know than this kind of transitions are really simple to achieve using pure css but I really notice the difference between css animations and velocity and I feel than I can tune better my animations using velocity

basically, I need change between classes, I don't know the properties because I'm using a grid framework and I need animate the transition between class changes

jquery 
http://api.jqueryui.com/switchclass/

is there something similar to it inside velocity??..thanks so much and thanks julian for this amazing library.....

**Comment by Bheam** [comment]
Second this, would be a great improvement if velocity could incorporate a velocitySwitchClass(). 

Velocity is much better than animate(). I even resolved some animate() bugs by simply switching to Velocity.

**Comment by rigorojas** [comment]
This would really help make velocity that much more powerful.

**Comment by silicakes** [comment]
+1 for this one
