### ISSUE TITLE
Progress callback only called in the first animation loop

### ISSUE THREAD

**Issue by raphaelrauwolf** [julianshapiro/velocity#292]
When you loop any velocity animation, the progress callback is called only in the first loop and after that it is ignored.

``` javascript
$("div").velocity(
  { scale: 1.5 },
  {
    duration: 5000,
    loop: true,
    progress: function(elements, percentComplete, timeRemaining, timeStart) {
      console.log('percent : ', percentComplete);
      // Stops after the first loop and never gets called again
    }
});
```

**Comment by TiagoSousa26** [comment]
I think the problem of ingoring the `loop` still there because I am using the `progress` and `complete`and before I do `loop:4` and it ignore the `loop` but if I do` loop: true` it ingore the loop and ingore the `complete`.
