### ISSUE TITLE
Add a "dummy" css value / option

### ISSUE THREAD

**Issue by Rycochet** [julianshapiro/velocity#293]
We've all been there - wanting to have a totally custom animation that only works with code on every tick - so how about helping us out and allowing us to enter "dummy" as a css attribute so we can leverage the  rAF calls, easings, and `progress` callback.

The reason for the dummy attribute (instead of a special "dummy" value etc) would be the ability to force-feed the start and end values to make the maths on it simpler (though technically Progress doesn't actually pass the current values, just the percent complete, so maybe not that useful lol).

Downside would be the overhead of checking it every frame. Maybe an option to be passed to prevent animations setting values, something like `{dummy:true}` instead?

**Comment by julianshapiro** [comment]
I'm making a call on what to do with this issue tomorrow.

**Comment by julianshapiro** [comment]
This will be implemented in tonight's release. Stay tuned for the commit log.
