### ISSUE TITLE
Promise is not returned from Velocity() in IE10.

### ISSUE THREAD

**Issue by Zenwolf** [julianshapiro/velocity#298]
`Velocity()` returns `null` instead of a promise in IE10, although animation works.

Example jsfiddle that breaks in IE10:
http://jsfiddle.net/q59rwwg9/

Example code:

``` JavaScript
var slice = Array.prototype.slice;
var elems = slice.call(document.getElementsByTagName('div'));

Velocity(
    elems,
    'callout.shake'
).then(function() {});
```

**Comment by SgtPooki** [comment]
Hehe... I was getting ready to do some whining but realized that the "polyfill" I was using was not defining the Promise global.. as a polyfill should..

Fixed with 

```
window.Promise = window.Promise || require('es6-promise');
```

**Comment by SgtPooki** [comment]
OL, nevermind.
with Promise on the window:
[![Imgur](http://i.imgur.com/Y8EfgSS.png)](http://i.imgur.com/Y8EfgSS.png)

And with Promise defined explicitly on Velocity using
```
var velocity = require('velocity');
var Promise = require('es6-promise');
velocity.Promise = Promise;
```
Gives me this:
[![Imgur](http://i.imgur.com/GEfXgd6.png)](http://i.imgur.com/GEfXgd6.png)
and
[![Imgur](http://i.imgur.com/DORZrQV.png)](http://i.imgur.com/DORZrQV.png)

**Comment by SgtPooki** [comment]
Aahaha... I'm a dummy =) woooow. you gotta do ```Promise = require('es6-promise').Promise``` with the es6-promise package.

=) Carry-on..
