### ISSUE TITLE
slideUp/slideDown Problem When Combined with Stop and Rapid Clicking

### ISSUE THREAD

**Issue by jackrugile** [julianshapiro/velocity#304]
Using Velocity 1.0.0 and Chrome 27 Stable for my tests on this.

I decided to give Velocity's slideUp/slideDown methods a try today. They work great! However, there seems to be a problem when using `.velocity( 'stop' )` and stopping an animation midway through. Here is a pen showing the issue: http://codepen.io/jackrugile/pen/c1d4d39ebab2dba702f3a07a09156970

If you click the toggler button and let the animation finish before toggling again, it works fine. However, if you click midway through the animation, it seems to get stuck at that height for subsequent slideUps/slideDowns.

Quick image demonstrating the problem:

![velocity](https://cloud.githubusercontent.com/assets/726153/4295306/8d76951e-3de8-11e4-9198-f65296a0e3e0.gif)

When the problem occurs, the element's inline style seems to be stuck with something along the lines of the following: `style="overflow: hidden; display: block; height: 8.35930990000873px; margin-top: 0px; margin-bottom: 0px; padding-top: 0px; padding-bottom: 0px;"`

**Comment by sodbileg** [comment]
Has it been fixed yet? I have the same problem.

**Comment by julianshapiro** [comment]
See the faq for a solution
