### ISSUE TITLE
Feature Request: "Finish" command

### ISSUE THREAD

**Issue by brandonkelly** [julianshapiro/velocity#321]
jQuery has a [finish()](http://api.jquery.com/finish/) function which will fast-forward any animations from the matched elements to their ending styles.

Would be really great if Velocity had something similar. Imaginging the API would be similar to the Stop command:

```js
$element.velocity("finish"); // Normal finish
$element.velocity("finish", "myQueue"); // Finish a custom queue
$element.velocity("finish", true); // Finishes all queues
```

**Comment by julianshapiro** [comment]
Done. Will be live in the release going out this weekend.

**Comment by brandonkelly** [comment]
Awesome!
