### ISSUE TITLE
Unexpected flicker in Safari and IE9- when force-feeding

### ISSUE THREAD

**Issue by macgyver** [julianshapiro/velocity#346]
I am trying to transition the height of an element between two states and I want for the height to be computed automatically in both states. The example looks as I would expect in Firefox, Chrome, and IE10+, but in Safari and IE9- there is a brief flicker displaying the expanded state before the animation begins.

See here: http://codepen.io/jrz/full/zGaor/

I can work-around this by explicitly setting the element's height to the `initialHeight` before the velocity function is run but I would have expected for this to be handled by force-feeding the value.

Please let me know if I'm doing anything wrong, thanks again for the awesome library!

**Comment by julianshapiro** [comment]
So integrating this would actually result in a performance hit because I'd be setting CSS values outside of a rAF tick. I'm ultimately not going to do this, but if I stumble into this problem in my own animations, I'm going to consider adding a flag that allows you to toggle this feature on.

**Comment by macgyver** [comment]
It's only come up for me when animating between auto-computed values for two different states, where height changes between the states. Thanks for looking into it.

**Comment by levitanong** [comment]
Hey guys, any updates on whether this fix has been implemented, and what the flag is?
