### ISSUE TITLE
Velocity slideup/down on hover

### ISSUE THREAD

**Issue by pmbennett** [julianshapiro/velocity#347]
I am using the slideup/down for a navigation menu drop down, which I trigger on mouseover/mouseout.

If a further mouseover/mouseout event is triggered during the animation, then it queues it up and executes them as expected.

To stop that behaviour, I am using the stop command, as I dont want a long chain of animation to continue. However, using this causes velocity to calculate the animating elements height incorrectly and stores it. So the next time a mouseover event occurs, the element gets animated to the incorrect height, not it's actual height.

That height gets lower and lower until it gets to 0, and then it no longer displays.

I am using the latest version of Velocity.

**Comment by julianshapiro** [comment]
I can't really solve for this inside Velocity itself. So here's my recommended solution:

Before having the menu slide up or down, check that the menu isn't already animating by sniffing for the presence of a `velocity-animating` class. This will prevent constant requeueing.

```javascript
$navContainer.on({
    mouseover: function() {
        if (!$nav.hasClass("velocity-animating")) {
            $nav.velocity("slideDown");
        }
    },
    mouseout: function() {
        if (!$nav.hasClass("velocity-animating")) {
            $nav.velocity("slideUp");
        }
    }
});
```

**Comment by azharijelek** [comment]
my solution is not to use slideDown/slideUp. 

Here's the code:
```js
$('.menucontainer').find('li.menu-item-has-children').each(function(){
	var $nav = $(this).find('> ul.sub-menu'),
		$height = $nav.height(); // declare sub-menu's original height
	$(this).hover(function() {
		$nav.velocity("stop").velocity({
			height: [$height, '0'] // [now, from]
		}, {
			duration: 400,
			display: "block",
			easing: "easeOutQuart"
		});
	}, function(){
		$nav.velocity("stop").velocity({
			height: ['0', $height] // [now, from]
		}, {
			duration: 400,
			display: "none",
			easing: "easeOutQuart"
		});
	});
});
```
