### ISSUE TITLE
NS_ERROR_FAILURE: animating svg mask

### ISSUE THREAD

**Issue by andrespi** [julianshapiro/velocity#352]
i'm  trying to animate the width property of a mask rect in svg  , and i get this error: " NS_ERROR_FAILURE:	
propertyValue = element.getBBox()[property];"

**Comment by julianshapiro** [comment]
Silly FF'ers won't fix the bug, so I've just thrown a try/catch around it. This will be implemented in the upcoming release (this weekend). Thanks a bunch @andrespi and @ydaniv!
