### ISSUE TITLE
Why not moving the jquery shim out?

### ISSUE THREAD

**Issue by JSteunou** [julianshapiro/velocity#356]
Could it be possible to move out to a separate file all the jquery shim part? That would make velocity.js thinner for those still using velocity with jquery.

**Comment by Kay2dan** [comment]
+1 for the native JS version :)

**Comment by julianshapiro** [comment]
>@JSteunou: All you are going to save is ~1.7KB minified+gzipped by removing the shim. If you add up the size of your entire page with all assets, what percentage is 1.7KB out of that? On a page that's around 200KB, the shim would be less than 1% of the data transferred.

@msheakoski Made a really good point there. I'm thinking that those who are using Velocity without jQuery can simply select+delete the code at the top of Velocity. It's really simple and safe to do. Just delete all the code that comes before this:

```javascript
/******************
    Velocity.js
******************/
```

I don't think enough people are using Velocity by itself to bother adding a new file to my build cycle, and potentially confusing new users with too many build options.
