### ISSUE TITLE
Request for new version

### ISSUE THREAD

**Issue by tommiehansen** [julianshapiro/velocity#363]
**Some requests for future versions of Velocity.js**

a) Make Velocity more modular so that one can use and choose only the parts one need. This also gets rid of the need of Velocity UI. Combine this with also having a velocity_all.js for dev.

b) Add option to slice staggering ie `stagger: [60, 6, 'fadeIn']` (stagger 60ms, stop staggering from 6+, use fadeIn on 6+). Example: http://jsfiddle.net/tommiehansen/nq94kt90/embedded/result/

Slicing staggering is very useful for when one got long lists of objects where one want to use a fancier transition on X first but doesn't want the rest of the items to animate forever or use unnecessary resources (that can cause jank etc).

c) Sequencing in its current form is  a bit lacking since one can't perform (?) non-velocity functions in-between since the complete-function doesn't work. In UI's one often want to perform more then just pure animations. A _really_ simple example would be something like (pseudo code):

 `element
.fadeOut()
.changeHTML()
.showStuff1()
.showStuff2()
`

rAF could be a problem though since stuff not getting animated doesn't have such things. But in the way Sequence work now i find that i still need to use complete at lot for sequences which defeats its purpose if one isn't doing pure animations only.

**Comment by julianshapiro** [comment]
a) not happening, but see my other response in a related thread
b) will solve this problem through stagger values that approach 0. feature coming soon
c) i will add this feature in tomorrow. stay tuned, yay!!!!

thanks, tommie! you're a good man! and i appreciate these suggestions.

**Comment by tommiehansen** [comment]
@julianshapiro Did c) get implemented in 1.2? I haven't seen any documentation for it and what happend to b) ?

Keep up the great work! :+1:

**Comment by julianshapiro** [comment]
See my other open thread. I'll be doing it soon

**Comment by julianshapiro** [comment]
@tommiehansen: Could I email you? If so, what's your address?

**Comment by tommiehansen** [comment]
Sure, my mail is myname@gmail.com. Replace myname with my name... :)
