### ISSUE TITLE
VMD not working on some sites

### ISSUE THREAD

**Issue by dagomar** [julianshapiro/velocity#364]
Hi, 

I'm pretty excited by velocity, I just came across this last week and have been dying to get this integrated into some projects. I would love to try out the VMD, but it turns out that it's not working for Drupal sites. You can see this by going to drupal.org and try the VMD, it gives an error:
Uncaught TypeError: undefined is not a function

Just thought I'd post that here since I couldn't find anything pointing to a solution or even documenting the problem. Anyway, thanks for an amazing animation engine!

**Comment by gstout** [comment]
Any progress on this? Just test on a Drupal 7 site and received the same error.
