### ISSUE TITLE
Reset {bottom, top} to "auto" doesn't work and it remains "0px".

### ISSUE THREAD

**Issue by ghost** [julianshapiro/velocity#366]
I'm using Velocity in [this way](http://jsbin.com/buzige/1/edit?html,output).

I need Velocity reset the top:"0px" to "auto", but id doesn't work.

It's a bug? Or it's me?

http://jsbin.com/buzige/1/edit?html,output

**Comment by dcalhoun** [comment]
@julianshapiro is there any way to accomplish removing "prep" position styles (i.e. – `position`, `bottom`, etc) outside of doing so manually within the `complete` callback?

I have attempted to use the `reset` property from Velocity UI Pack's [`RegisterEffect`](http://velocityjs.org/#uiPack), but, as you pointed out, it only accepts integer values. The following has no effect:

```javascript
Velocity.registerEffect('slideInUp', {
  defaultDuration: 1000,
  calls: [
    /* ...animations... */
  ],
  reset: {
    bottom: 'auto',
    left: 'auto',
    position: 'static',
    right: 'auto',
    top: 'auto'
  }
})
```

**Comment by Rycochet** [comment]
If you open this as a separate issue for supporting non-integer values (such as ```"auto"``` or ```""```) then I'll add it to the todo list - technically there should be a way to remove changed values, and setting to a blank string should be the right way to do it - while letting Velocity know that it's not cached any more.
