### ISSUE TITLE
Unable to stop non-queued animation 

### ISSUE THREAD

**Issue by andywhite37** [julianshapiro/velocity#368]
I'm not sure if this is an issue, or expected behavior, but it seems you can't stop an animation that was started with `queue: false`.  I read through the documentation and searched through the issues, but didn't see anything that mentioned this.  I tried just using `stop` by itself, and also with the `true` parameter to clear the queue.

http://codepen.io/andywhite37/pen/NPqYPw/

Thanks for your work on this project.

**Comment by julianshapiro** [comment]
I'll be coming to a conclusion on this tomorrow. (Velocity's next release is tomorrow night.)

**Comment by julianshapiro** [comment]
New behavior beginning with tonight's release:

```
                               - options === true --> stop current default queue calls (and queue:false calls), including remaining queued ones.
                               - options === undefined --> stop current queue:"" call and all queue:false calls.
                               - options === false --> stop only queue:false calls.
                               - options === "custom" --> stop current queue:"custom" call, including remaining queued ones (there is no functionality to only clear the currently-running queue:"custom" call). 
```
