### ISSUE TITLE
loop:true backgroundpositionX

### ISSUE THREAD

**Issue by Omniferum** [julianshapiro/velocity#371]
Rummaging around I can't seem to find any method that just allows for an infinite loop without it reversing the animation at the end of the current animation. Is there any syntax/trick to looping without reversing?

**Comment by julianshapiro** [comment]
Fixed! coming in tomorrow's release :)

**Comment by MathieuLoutre** [comment]
Any way to get that for 360 rotations too? Or maybe an `alternate` option to set to `true` or `false`? That would be pretty useful for loaders and such. Thanks for the hard work!

**Comment by julianshapiro** [comment]
That should already work with rotation. Does it not work for you?

**Comment by MathieuLoutre** [comment]
Sorry, haven't actually tried it, I just based my comment off the commit log. Will report if I have any problems but good to hear it's been taken into account already!
