### ISSUE TITLE
Simple rotation not working

### ISSUE THREAD

**Issue by BernhardBehrendt** [julianshapiro/velocity#372]
Thanks for that great library. Love to work with it because it's soo similar to jquery's animate and very intuitive.
I have a question how to implement a simple rotation animation using velocity.
Just tried to rotate an element this way and it wasn't working.
So for sure this isn't a bug but how is a simple rotation with an centered axis working in velocity?

Thats' my html:

`
   <div class='spinner'></div>
`

Thats the js I tried to apply on the div:

`
    oSpinner.velocity({rotate: '360deg'}, {duration: 1000, loop: true});
`

Thanks in advance for any inspiration how to get this working.

**Comment by dxcqcv** [comment]
If I only wanna use 2d rotate not transform 3d rotateZ, how do I do it?

**Comment by Rycochet** [comment]
Use completely normal css - `rotate(22deg)` style...

**Comment by dxcqcv** [comment]
thanks @Rycochet , but not working, my part of code is 

```
function rotateAndPopup(res) {
  $(window).scrollTop(0);
  var res = res.toLowerCase()
  prizeEl =$(`.prize${res.toUpperCase()}`) 
  var mySequence = [
    // {e: $('#rotate'), p: {rotateZ: [turnplateDeg[res],0]}, o: {duration: 1000,
    // {e: $('#rotate'), p: {transform: `rotate(${turnplateDeg[res]}deg)`}, o: {duration: 1000,
    {e: $('#rotate'), p: {transform: "rotate(360deg)"}, o: {duration: 1000,
      complete(el) {
        $('.mask').show()
        prizeEl.css({top:'3rem',left:'calc(50% - 2.4rem)'}).appendTo('.shareBoxInner')
        // make innerMask over other cards
        cardsTag
          .filter(c => c !== res )
          .map(c => $(`.prize${c.toUpperCase()}`).css({zIndex:3}))
        // change share words
        Object 
          .keys(shareWords)
          .filter(item => item === res)
          .map(el => $('.shareWords').text(shareWords[el]))
      }
    }},
    {e: prizeEl, p: { scale:'1'}, o: {
      begin(elements) { elements.map(el => {
        $('.shareBox').show()
        $('#shareLight').show()
        // $('#shareLight')
        //   .show()
        //   .velocity({rotateZ:value},{duration:time,easing:'linear',loop:true,display:'none',visibility:'hidden'})
        // make rotate z-index under share box
        $('#rotate').css({zIndex: 5})
        // $(el).velocity({
        //   scale:1,
        // })
      }); }
    }}
  ]
  $.Velocity.RunSequence(mySequence)
}
```

**Comment by dxcqcv** [comment]
Even not to use `velocity ui`, add `transform: 'rotate(30deg)'` to velocity does not work too, like:

```
        $('#rotate').velocity({
          // top: '1rem' // works
          transform: 'rotate(30deg)' // not working
        })
```

**Comment by Rycochet** [comment]
Sorry - the docs are completely out of date and missing this - for `transform` you *must* use forcefeeding - http://velocityjs.org/#forcefeeding

You cannot mix `transform` and any of the shortcuts (`rotate`, `scale` `translate`) - CSS itself doesn't give access to any of them for reading (see #269).

So it should be -

```javascript
$('#rotate').velocity({
   transform: ['rotate(30deg)', 'rotate(0deg)']
})
```

**Comment by dxcqcv** [comment]
still not working

```
$('#rotate').velocity({
   transform: ['rotate(30deg)', 'rotate(0deg)']
})
```

**Comment by Rycochet** [comment]
This tracker is for issues with Velocity, not learning how to use CSS - https://developer.mozilla.org/en/docs/Web/CSS/transform

**Comment by dxcqcv** [comment]
sorry for again, I think css is right and simple, `transform: rotate(30deg)`, but use it in Velocity is not working, `$('#rotate').velocity({ transform: ['rotate(30deg)', 'rotate(0deg)'] })`

so it's still Velocity problem, and I think maybe Velocity does not support 2D transform, right?

**Comment by makshh** [comment]
@dxcqcv use `rotateZ`

```js
$('div').velocity({
  rotateZ: -30
});
```

[Codepen](https://codepen.io/makshh/pen/qXyGob)

**Comment by Rycochet** [comment]
Velocity has nothing to do with CSS values, it simply passes them through. `rotate(30deg)` is partially invalid as it does not state what axis you are rotating in - hence I linked to a page that lists all the transform properties allowed. `rotate` is there, but you should be using one of the other properties such as `rotateZ` which is probably what you are after. Coincidentally I even said that in the first reply on this thread almost 3 years ago.

Learn to use the DOM Inspector (right click on an element and Inspect it), to see what is happening...

**Comment by dxcqcv** [comment]
thanks again for reply, nothing to add in the DOM Inspector when use `$('#rotate').velocity({ transform: ['rotate(30deg)', 'rotate(0deg)'] })`

Well, `rotate()`  and `rotateZ` **is different**, one for 2D and one for 3D, velocity only support `rotateZ` but not to support `rotate()` in my test.

**Comment by Rycochet** [comment]
FFS... Learn basic CSS - go and find a tutorial somewhere, and listen to what you're being told. Velocity animates values, there is no "supports", either the browser does or it doesn't.
