### ISSUE TITLE
FEATURE REQUEST: timing functions 

### ISSUE THREAD

**Issue by lukePeavey** [julianshapiro/velocity#373]
Hi, I hope this is an appropriate place to post a feature request. What I would love to see is a way to differentiate duration and delay values for each element in a multi element call.  I know the UI pack provides  this ability via the stagger and drag options, but only for registered UI effects. I think it would be extremely useful to have this functionality available on all velocity calls.  This is just a suggestion, but would it be possible for delay and duration to accept a function (similar to value functions) that would be passed the index of the current element as it's first argument? Or to make the stagger and drag options available on all velocity calls when the UI pack is loaded. Many thanks!! Velocity is an amazing plugin!!

**Comment by julianshapiro** [comment]
so it's not possible to differentiate delay or durations with normal velocity calls, nor will it be possible going forward (it would require a major animation engine rewrite). the only way to get this is via the ui pack, which i actually plan on updating tomorrow with features that may accommodate this. in particular, i want to bake in the ability to provide a function for duration/delay. stay tuned, and see this thread: #398.
