### ISSUE TITLE
begin/complete callback allways called after .velocity('stop')

### ISSUE THREAD

**Issue by epineight** [julianshapiro/velocity#376]
The begin and complete callbacks are allways executed after I stop the animation with the stop command. 
The begin callback is executed after the delay period which is good. Which gives time to cancel the animation. But after the stop command it is still triggered.

Is this expected behaviour? Is there a way to not execute the callback functions when i stop the animation?

**Comment by julianshapiro** [comment]
will close this since i didn't get a fiddle and i'm not experiencing the issue myself.
