### ISSUE TITLE
version numbers

### ISSUE THREAD

**Issue by tomByrer** [julianshapiro/velocity#380]
Seems like you accidentally made a new 'release' before updating the version number.  ([ref](https://github.com/jsdelivr/jsdelivr/pull/2669) & [zip](https://github.com/julianshapiro/velocity/archive/1.1.0.tar.gz) files show v1.0.0).  Not a big deal, just for next time, please don't confuse us ;)

Maybe time for a new release as a Christmas present please?

**Comment by julianshapiro** [comment]
new release coming shortly. will have correct numebrs.

**Comment by tomByrer** [comment]
cheers!
