### ISSUE TITLE
Stop sequence

### ISSUE THREAD

**Issue by webstacker** [julianshapiro/velocity#381]
Really liking velocity, great work.

Is there the ability to stop a sequence? I've read through the docs and looked at other issues but I can't see any reference. I've included an example below which breaks if the user hovers too quickly:

http://jsfiddle.net/g6x3L0ds/3/

**Comment by julianshapiro** [comment]
You could do $(".velocity-animating").velocity("stop", true) to forcefully target all elements currently animating and remove their animation chains :-D short of that, there's no programmatic way to stop a sequence so to speak. if you feel like cooking up an implementation for `velocity.ui.js`, lemme know!

thanks for the good question.

**Comment by webstacker** [comment]
I'd be happy to contribute to this.

It was a while ago that I was working with it, but I remember thinking it would be great if a sequence was treated as a single reusable entity. While "RegisterEffect" allows for a reusable effect for a single element, I see a sequence as a reusable effect for multiple elements, a collection of effects. This could be completely the wrong way to think about this?

I've listed some potential syntax options below. It would be good to get your thoughts:

## Syntax A

Sequence tied to elements.

```javascript
var mySequence = $.Velocity.Sequence([
	{ e: $element1, p: { translateX: 100 }, o: { duration: 1000 } },
	{ e: $element2, p: { translateX: 200 }, o: { duration: 1000 } },
	{ e: $element3, p: { translateX: 300 }, o: { duration: 1000 } }
]);

//current api
mySequence.velocity('run');
mySequence.velocity('stop');
mySequence.velocity('finish');
mySequence.velocity('reverse');

//or this??
mySequence.run();
mySequence.stop();
mySequence.finish();
mySequence.reverse();
```

## Syntax B

For reusability separate elements from the sequence definition.

```javascript
var mySequenceCalls = [
		{ p: { translateX: 100 }, o: { duration: 1000 } },
		{ p: { translateX: 200 }, o: { duration: 1000 } },
		{ p: { translateX: 300 }, o: { duration: 1000 } }
	];

var mySequence = $.Velocity.Sequence({
		calls: mySequenceCalls,
		elements: [
			$element1,
			$element2,
			$element3	
		]
	});

var myOtherSequence = $.Velocity.Sequence({
		calls: mySequenceCalls,
		elements: [
			$element4,
			$element5,
			$element6	
		]
	});

mySequence.velocity('run');
mySequence.velocity('stop');
...

myOtherSequence.velocity('run');
myOtherSequence.velocity('stop');
...
```

## Syntax C

```javascript
$.Velocity.RegisterSequence('my-sequence-name', [
	{ p: { translateX: 100 }, o: { duration: 1000 } },
	{ p: { translateX: 200 }, o: { duration: 1000 } },
	{ p: { translateX: 300 }, o: { duration: 1000 } }
]);

//would need to return some sort of sequence instance
var sequenceInstance = $elements.velocity('my-sequence-name');

sequenceInstance.velocity('stop');
```

**Comment by julianshapiro** [comment]
Thanks for this, Stephen. Busy work for me, but I will get back to you :)

**Comment by julianshapiro** [comment]
I unfortunately don't think I'll be implementing this at this time. Will have to use $el.stop(true) for now. The proper implementation of this feature would warrant an overhaul of Velocity's internal queueing logic.

**Comment by kokarn** [comment]
I've ran into this exact problem now. 
If you have a sequence where you in the complete callback changes the content of the targeted element, sometimes it doesn't stop on the correct value.

I'll try to whip up a reduced test case but here's some pseudo code on how i do it

```
function doAnimation( value ){
    sequence = [];
    $elements = $( 'selector' );
    $elements.velocity( 'finish' );
    foreach( $elements as $element ){
        sequence.push( {
            e: $element,
            p: 'transition.slideDownOut',
            o: {
                complete: function( element ){
                    $( element )
                        .text( value )
                        .velocity( 'transition.slideDownIn', {
                            display: 'block'
                        });
                    },
                sequenceQueue: false
            }
        } );
    }
    $.Velocity.RunSequence( sequence );
}
doAnimation( 1 );
doAnimation( 2 );
doAnimation( 3 );
doAnimation( 4 );
```

I understand that this is a bit messy, but the gist of it is that the final state of all the elements isn't always 4, as it should be if i read the documentation correct.
