### ISSUE TITLE
Q: Velocity + Phonegap?

### ISSUE THREAD

**Issue by sogen** [julianshapiro/velocity#383]
Sorry to distract you but my google-fu powers have ultimately failed me. 
Is it needed to improve jQuery speed? 
Can it play nice with jQuery mobile?
How does Velocity work in Phonegap, specially in animation speed, HA in iOS and HA in Android?

I appreciate your time and if anyone can give some insight or link to a demo, a stackoverflow answer or  a blog post I'll be more than glad.

Thx

**Comment by julianshapiro** [comment]
heyo, @sogen! @ydaniv is right. but:

- yes, i always recommend using velocity over jquery for mobile animations.
- yes, it will play nice with jquery mobile
- velocity should be the fastest possible implementation of js-based animations for mobile devices. in many cases, it is faster than css animations triggered by js.

**Comment by sogen** [comment]
Thanks Julian!
