### ISSUE TITLE
UI plugin 'Out' transitions with stagger leave space in parent element

### ISSUE THREAD

**Issue by cgwyllie** [julianshapiro/velocity#384]
Hi,

When using a staggered 'out' transition from the UI plugin, the elements are not set to `display: none` until the whole set of elements has finished animating.

However, if using the effect to hide items from a list (for example on user filtering), this results in a strange experience because the elements still take up space in the parent until the whole animation is complete.

Would it be possible to set the display to `none` on completion of each individual element's transition, or to provide a per-element complete callback so that the desired behaviour can be added?

Fiddle with (exaggerated) example of issue: http://jsfiddle.net/f9cvxquc/

Reference to the use case that drew this to my attention: https://github.com/cgwyllie/angular-velocity/issues/3

Thanks!

**Comment by julianshapiro** [comment]
hey, @cgwyllie!

let's continue the discussion here: https://github.com/julianshapiro/velocity/issues/161

let me know your thoughts in that thread. i want to attack this issue.

**Comment by cgwyllie** [comment]
@julianshapiro Thanks! Had previously played with that and not observed what I was expecting (could just be whilst it was still quite young). Will pull latest and have a play then add any thoughts.

Cheers
