### ISSUE TITLE
Add box-shadow inset animation support for IE

### ISSUE THREAD

**Issue by MattyBalaam** [julianshapiro/velocity#388]
I have spotted this on two versions: IE9 and IE11, but it works as expected on Firefox and Chrome.

http://codepen.io/MattyBalaam/pen/LEZRWY

Just spotted this in the source:

`Todo: Add support for inset boxShadows. (webkit places it last whereas IE places it first.) `

**Comment by julianshapiro** [comment]
Yo! I'll rework this issue into a feature request :)

**Comment by MattyBalaam** [comment]
Thanks. In case anyone needs a quick and dirty solution to this before the enhancement you can do some browser checking and animate boxShadowY instead.

**Comment by Rycochet** [comment]
It's lost the relevant source line, but this still occurs in Edge
