### ISSUE TITLE
Feature: Supporting filter: blur()?

### ISSUE THREAD

**Issue by cfenzo** [julianshapiro/velocity#39]
Is there planned support for the 'blur' filter ?
I know it's webkit-only\* at the moment, but it's what's missing from my 'magic_animations' port :)

*http://caniuse.com/#feat=css-filters

**Comment by oskarrough** [comment]
Thanks for the blur. How about brightness (and grayscale, contrast and hue)? Would be great.

**Comment by julianshapiro** [comment]
Unlike for now :(

**Comment by oskarrough** [comment]
Alright, is it possible to extend velocity somehow? Tried to duplicate your blur code buuuut it needs some more time for me to understand what's going on. With jQuery this works:

```JavaScript
$('div').animate({
  brightness: 5
}, {
  duration: 1000,
  step: function(now) {
    $(this).css({
      '-webkit-filter': 'brightness('+ this.brightness +')'
    });
  }
});
```

**Comment by julianshapiro** [comment]
see velocityjs.org/#progress :)

**Comment by oskarrough** [comment]
ah, of course, thank you! :)
