### ISSUE TITLE
Animations don't work on cloned elements

### ISSUE THREAD

**Issue by herschel666** [julianshapiro/velocity#390]
Hi.

Great tool, thanks for your work!!

I came along a bug, where animations don't work, when the event bindings of a cloned element are cloned as well (`$('.foobar').clone(true)`). I made a [JSBin to demonstrate the bug](http://jsbin.com/hixelu).

Best regards

**Comment by julianshapiro** [comment]
hey @herschel666. thanks for putting together that demo. super helpful, and much appreciated. also, a great question.

@ydaniv is of course right. thanks for pointing this out! 

there's nothing i can do within velocity to fix this, but i will add a mention of this to the FAQ right now :)
