### ISSUE TITLE
complete callback executed befone animation is complete?

### ISSUE THREAD

**Issue by ncortines** [julianshapiro/velocity#391]
Hi,

I'm not sure if I understand correctly the use case, but it seems to me that the `complete` callback is executed *just slightly* before the animation is complete.

I have prepared a simple example:
http://jsfiddle.net/ncortines/0vvhyyr9/

My browser is Google Chrome 39.0.2171.95 (Official Build) m (Windows 7)

Thanks

**Comment by julianshapiro** [comment]
Thanks, @ncortines and @ydaniv. Please def file that bug with Chromium, and get back to me!

And, smart solutions, Mr. Daniv! And, good question, Mr. Cortines :)

**Comment by dcalhoun** [comment]
@ncortines @ydaniv @julianshapiro was a Chromium bug ever created for this?
