### ISSUE TITLE
Opacity continues Looping After Object Removed

### ISSUE THREAD

**Issue by fingermaster** [julianshapiro/velocity#392]
Velocity opacity,display:none on a rotateZ object - opacity seems to continue looping in devtools .

$(".loading").velocity({ rotateZ: "360" }, {  duration: 1000, loop: true });
    $(".overlay").on("click", function () { 
        $(".loading").velocity({ opacity: 0 }, { display: "none" });
    });

![screenshot 2014-12-22 15 37 17](https://cloud.githubusercontent.com/assets/307229/5530862/1d3f67ba-89f3-11e4-9a85-b15770fe7a66.png)

**Comment by julianshapiro** [comment]
you're a good man, @ydaniv!

**Comment by fingermaster** [comment]
Hey Yehonatan,

Sorry to bother you with trivialities, but I've studied the docs and did
some stackoverflow searches - and can't find a way to append and animate
with velocity - like this: *$element.append(tr).velocity("slideDown",
delay, 500);*  with a flash or slide or anything? Any tips would be greatly
appreciated.

Peter

On Wed, Dec 24, 2014 at 10:36 AM, Yehonatan Daniv <notifications@github.com>
wrote:

> [image: :beer:] ! Damn! I knew I'm missing something :P
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/julianshapiro/velocity/issues/392#issuecomment-68059017>
> .
>



-- 
Peter Dillon
fingermaster@gmail.com

**Comment by MattyBalaam** [comment]
try $(tr).appendTo($element).velocity.......

On 6 February 2015 at 13:40, Peter <notifications@github.com> wrote:

> Hey Yehonatan,
>
> Sorry to bother you with trivialities, but I've studied the docs and did
> some stackoverflow searches - and can't find a way to append and animate
> with velocity - like this: *$element.append(tr).velocity("slideDown",
> delay, 500);* with a flash or slide or anything? Any tips would be greatly
> appreciated.
>
> Peter
>
> On Wed, Dec 24, 2014 at 10:36 AM, Yehonatan Daniv <
> notifications@github.com>
> wrote:
>
> > [image: :beer:] ! Damn! I knew I'm missing something :P
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/julianshapiro/velocity/issues/392#issuecomment-68059017
> >
> > .
> >
>
>
>
> --
> Peter Dillon
> fingermaster@gmail.com
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/julianshapiro/velocity/issues/392#issuecomment-73237395>
> .
>



-- 
Matthew Balaam
____________________
development and design

matthewbalaam.co.uk <http://www.matthewbalaam.co.uk>
@matthewbalaam <https://twitter.com/matthewbalaam>
07730 953486

**Comment by fingermaster** [comment]
That did it, thanks! I really appreciate this.

Peter

On Fri, Feb 6, 2015 at 8:54 AM, MattyBalaam <notifications@github.com>
wrote:

> try $(tr).appendTo($element).velocity.......
>
> On 6 February 2015 at 13:40, Peter <notifications@github.com> wrote:
>
> > Hey Yehonatan,
> >
> > Sorry to bother you with trivialities, but I've studied the docs and did
> > some stackoverflow searches - and can't find a way to append and animate
> > with velocity - like this: *$element.append(tr).velocity("slideDown",
> > delay, 500);* with a flash or slide or anything? Any tips would be
> greatly
> > appreciated.
> >
> > Peter
> >
> > On Wed, Dec 24, 2014 at 10:36 AM, Yehonatan Daniv <
> > notifications@github.com>
> > wrote:
> >
> > > [image: :beer:] ! Damn! I knew I'm missing something :P
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/julianshapiro/velocity/issues/392#issuecomment-68059017
> > >
> > > .
> > >
> >
> >
> >
> > --
> > Peter Dillon
> > fingermaster@gmail.com
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/julianshapiro/velocity/issues/392#issuecomment-73237395
> >
> > .
> >
>
>
>
> --
> Matthew Balaam
> ____________________
> development and design
>
> matthewbalaam.co.uk <http://www.matthewbalaam.co.uk>
> @matthewbalaam <https://twitter.com/matthewbalaam>
> 07730 953486
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/julianshapiro/velocity/issues/392#issuecomment-73239208>
> .
>



-- 
Peter Dillon
fingermaster@gmail.com
