### ISSUE TITLE
bower.json missed

### ISSUE THREAD

**Issue by attenzione** [julianshapiro/velocity#393]
i'm installing with ```bower install -S velocity``` but in the installed directory there is no ```bower.json``` file (but ```.bower.json``` exists), so rails could not load ```velocity```

any help?
please don't write something like "create bower.json yourself"

**Comment by julianshapiro** [comment]
this will be fixed in this weekend's release.

**Comment by julianshapiro** [comment]
added.

**Comment by attenzione** [comment]
thanx!
