### ISSUE TITLE
UI pack: gradient staggering, durationPercentage splitting

### ISSUE THREAD

**Issue by julianshapiro** [julianshapiro/velocity#398]
- When registering a UI pack effect for calls that have no specified durationPercentage, they should all split the overall duration equally
- Look into allowing functions to be passed as values into `delay`, `duration`, and `stagger`. Also, look into combining drag and stagger features. (Perhaps rework drag so that it actually affects stagger instead of durations.)
- Oh, and accepting functions as sequence items.
- Why not merge the whole damn thing into Velocity proper? Just leave the packaged effects in the external file. You can drop the semver check. You can also replace Velocity's default fade functions.

**Comment by tommiehansen** [comment]
"Externalize the packagedEffects data so that they can optionally be modified and re-registered." like it say in ui.js. :)

**Comment by Rycochet** [comment]
* Should (can?) easings be split over the entire UI pack animation when they have no specified durationPercentage?

**Comment by Rycochet** [comment]
The ui-pack animations are now effectively css animations, so need to provide a % for each step - allowing you to split equally
