### ISSUE TITLE
VELOCITY 1.2.1 IS OUT! GET IT WHILE IT'S HOT!

### ISSUE THREAD

**Issue by julianshapiro** [julianshapiro/velocity#399]
Introducing [custom easings](http://VelocityJS.org/#easing) and [custom tweens](http://VelocityJS.org/#progress)!

See [commit log](https://github.com/julianshapiro/velocity/commit/2a28e3812c6fe9262244ed3b6d41d12ae9a107c6) for more.

Let me know if you run into any new issues.

**Comment by jessegrosjean** [comment]
Love the new version, thanks for all the useful changes.

**Comment by julianshapiro** [comment]
Thanks a bunch, man. Much appreciated, Jesse! Thanks for your suggestions.

**Comment by julianshapiro** [comment]
Oops! Thanks. Fixed.

**Comment by renatocarvalho** [comment]
:+1:

**Comment by ydaniv** [comment]
Good job @julianshapiro! Thanks a bunch for this push!
