### ISSUE TITLE
Error using shorthand in sequences

### ISSUE THREAD

**Issue by pwynn** [julianshapiro/velocity#400]
Hi Julian,

Getting an error when using shorthand in sequences.  When shorting elements to e: `nextCall.elements is undefined` is thrown at velocity.ui 737.

Also some options are being ignored when using o: shorthand.
If you expand the elements key on the fiddle below (so that it works), you'll notice only the last call's options are working.

http://jsfiddle.net/ww2qk6zq/

**Comment by julianshapiro** [comment]
Oops! Fixed and pushed. See release 1.2.1. Thanks :)
