### ISSUE TITLE
Timeline control via setProgress method

### ISSUE THREAD

**Issue by julianshapiro** [julianshapiro/velocity#401]
Note to self:

`Velocity.Utilities.data(element, "velocity").opts.duration = NEW_VALUE;`

h/t @janpaepke

**Comment by christopherscott** [comment]
Just curious, would this feature give the ability to **scrub** through timelines/animations - like in response to touchMove or scroll events? Or maybe that's already supported? (didn't see mention in the docs).

**Comment by janpaepke** [comment]
That is the general idea, yes. It is a feature we discussed to enable scrollbar bound animations using ScrollMagic and Velocity.

**Comment by julianshapiro** [comment]
I don't plan on implementing this at this time, but I am looking at a full internal timeline overhaul in the near future. When I do, I will revisit this thread and update y'all!
