### ISSUE TITLE
How do you rotate an svg around center ?

### ISSUE THREAD

**Issue by ibrierley** [julianshapiro/velocity#402]
Hiya, new to velocity and was just taking a look at integrating it with svg.

I can see how one can rotate a div around itself with rotateZ for example, which works fine.

With an SVG this seems to rotate around 0,0 though, example (does it animate css or svg attributes?)..
http://jsfiddle.net/L5h3ah9g/

So I was wondering, is there a way to specify the rotation center point, like rotate(x,cx,cy) in svg ?

Thanks!

**Comment by ydaniv** [comment]
Did you try setting `transform-origin` in your CSS?

**Comment by ibrierley** [comment]
Ah thanks, I wasn't quite sure if velocity just used CSS or animated the attributes somehow, but I guess that answers the question!

**Comment by CoDEmanX** [comment]
GSAP has a smooth-origin option, which makes subsequent rotations around varying transform origins a breeze on SVG (a change of origin resets the SVG element by default). Is this something velocity supports as well, or does one need to deal with this manually?
