### ISSUE TITLE
Set arbitrary (non-animated) CSS properties for the duration of the animation

### ISSUE THREAD

**Issue by barneycarroll** [julianshapiro/velocity#403]
I have a scenario of 'cards' that slide in and out. In their day-to-day existence, these cards are elements without any special display or positioning criteria that exist within the 'natural' document layout. But in order to animate their position without forcing undesirable repaints, I need to temporarily give them absolute positioning.

Could we conceivably allow the Velocity API to consume 'un-animateable' CSS properties like `position` for the duration of an animation? For the sake of example:

``` javascript
// Unreasonable:
Velocity( document.body, {
    left : ['0%', '100%'],
    position : 'fixed' // WTF you can't tween position values
} );

// Reasonable?
Velocity( document.body, {
    left : ['0%', '100%'],
    position : ['fixed', 'fixed'] // OK, apply `position: fixed` for the duration, then remove it
} );
```

Without jQuery, setting position before Velocity invocation and reverting it in a `complete` callback is less appealing than using native DOM methods to set CSS property values and listen for `transitionend`.

**Comment by ydaniv** [comment]
I don't see why it's less appealing then the CSS transitions' flow, however, it makes sense to have a `position` option, just like `display`, that takes s string value that can also be "force-fed, just as a little sugar.

**Comment by julianshapiro** [comment]
Not a bad suggestion at all. Will chew on it.

**Comment by julianshapiro** [comment]
Could anyone please chime in with additional example use cases? I like the idea of this but don't want to implement it just for the sake of positioning performance.

**Comment by barneycarroll** [comment]
It's purely an API convenience thing. It feels right to be able to express the position as part of the animated properties syntax and feels contrived stepping outside of Velocity to toggle positioning beforehand and in the callback.

**Comment by Rycochet** [comment]
Animating position on an element within an overflow:hidden, and moving it outside of the bound box (ie, with spring easings) - setting position:fixed while moving stops it from being cut off...

**Comment by tommiehansen** [comment]
i don't know if i understand this but is this really  a Velocity thing since it already got support for before and complete?

Take this:
```
<div>
 <i>Box 1</i>
 <i>Box 2</i>
 <i>Box 3</i>
</div>
```

How would Velocity know that if i move Box 2 out of view it should:

1. Create a copy of Box 2 + set opacity to 0 (so that Box 3 doesn't jump into document flow)
2. Move Box 2 out of view
3. Transition copy height from its current high to 0 (so that Box 3 smoothly jumps into the flow; this causes repaints though)
4. Remove the copy

There are a number of situations where just setting position is nice but won't work without doing more things than that and those extra things can be quite a lot of different things.

**Comment by Rycochet** [comment]
Velocity changes css values (plus scroll, but we'll ignore that), so only 2, 3 - both 1 and 4 require non-css changes, so would require begin/complete callbacks with your own code...

**Comment by Rycochet** [comment]
There are some new easings specifically for text based properties such as this - "`at-start`", "`at-end`" and "`during`" (the names may be subject to change before release). The old `display` and `visibility` options are becoming plain properties using them.
