### ISSUE TITLE
Website navigation

### ISSUE THREAD

**Issue by sir-dunxalot** [julianshapiro/velocity#405]
The navigation on the [website](http://julian.com/research/velocity) is cut off with no way to scroll below the link to `#ember`. Please see the attached image.

Browser: Chrome 39.0.2171.95
OS: OS X Yosemite 10.10.1

![image](https://cloud.githubusercontent.com/assets/4495352/5708017/824a0b7c-9a85-11e4-8fb0-764ada91c41b.png)

**Comment by MattyBalaam** [comment]
It is scrollable for me.

**Comment by ibrierley** [comment]
Has a similar problem for me. It looks like in some browsers (eg Opera), there is a scrollbar for the menu (as opposed to the outer scroll bar), so Opera has 2 scrollbars if the menu is larger than the window size, which I assume is expected.

In Chrome (Yosemite) a menu scroll bar never appears no matter what the size. In Chrome (Linux Mint) a scrollbar does appear.

Similar in Safari, no scrollbar appears.

You can two finger scroll within either for me though, so you can get there, just not intuitive.

**Comment by Rycochet** [comment]
Rather than adding an ugly scrollbar, I'd suggest just making the various sections foldable with a "[+]" or "[-]" beside them - would still cut off on a short display, but it become easy to get at the rest. Add a little support js for remembering which are open/closed and it makes things nicer ;-)

**Comment by julianshapiro** [comment]
Thanks, guys! I'll look into this shortly.

**Comment by julianshapiro** [comment]
fiiiiiiiixed. <3 u all
