### ISSUE TITLE
.velocity("scroll"{'duration:1500}) does not respond properly if used inside a $window.scroll()

### ISSUE THREAD

**Issue by zubairanwar2** [julianshapiro/velocity#406]
Lately, I have been working in a website where I want to shoot specific effects at different scroll positions hence all the elements are in the $(window).scroll() . So now when I reach a specific scroll element, where I am firing the command scroll it gets stuck, or sometimes keeps jumping back, basically gets unstable and I cannot scroll forward nor backward and it overrides the jquery.scroll(). So what do I do to get rid of this issue if you could help me out here I would really really appreciate it. Here is a Fiddle that elaborates the issue: http://jsfiddle.net/zubairanwar2/65xCP/58/

I am fairly new in using Velocity JS and trust me I fell in love with it already. I will wait for your response.

**Comment by Rycochet** [comment]
Not looked at the specific issue here, but going to point you at http://ejohn.org/blog/learning-from-twitter/

My one idea (without doing any checking) is that you need to make sure you "stop" the animation before adding the new one - and also debounce the whole function (ie, stop it from firing dozens of times a second in some browsers) - which is basically what John is doing in his example at the end.

**Comment by ydaniv** [comment]
@zubairanwar2 what you're trying to do seems flawed by definition. Your telling the browser to scroll down on every scroll event and that's what it gets stuck.

You'll have to fix your logic, not Velocity issue as far as I can tell.

**Comment by zubairanwar2** [comment]
@ydaniv Thanks for your reply, however, even if I dont keep any condition still the scroll gets stuck as long as it is inside the $(window).scroll(function(){}); Thats the issue here. Its quite strange actually here's a fiddle : jsfiddle.net/zubairanwar2/65xCP/61

**Comment by MattyBalaam** [comment]
As it stands everytime you are scrolling you are asking the window to scroll to 500 offset from div 1, so that is why it is getting stuck.
