### ISSUE TITLE
Inconsistency in UI pack animations

### ISSUE THREAD

**Issue by ImpGuard** [julianshapiro/velocity#407]
There seems to be some inconsistency in how VelocityJS handles its 3D transitions in the UI pack. Here's a [JSFiddle](http://jsfiddle.net/09m3smt2/8/).

Notice that I initially use velocityJS to set my 3D cube into a standard position. Then there are four buttons for four various velocityJS transitions, one of which is my own. 

* persectiveUpIn: Does not reset the properties that it sets, namely the transform origin.
* perspectiveDownIn: Does reset the properties, leading to a jump at the end of the transition
* cubeIn: My custom transition works great, based off of perspectiveDownIn without the perspective since it has already been applied
* swoopIn: Seems to not hook properly onto my already applied transforms. Therefore, after you use it, the cube is bigger than it's supposed to be

What's the correct behavior? I'm worrying about accidentally depending on something that was not intended. I'm also unsure if I'm just missing something and these are all intended consequences.

EDIT: As an addon, I've ran into issues where the remanent "transform: translate(0)" etc. also causes GPU rendering issues when not desired. Seems an easy fix is to reset these to none etc.

**Comment by julianshapiro** [comment]
Thanks for this. Will look into this over the weekend.

**Comment by julianshapiro** [comment]
Tonight's update will fix the perspectiveUpIn reset inconsistency. Thank you so much for pointing this out.

Overall, these effects aren't meant to work off of existing transform values. They're really expected to be used carte blanche as means of animating elements into and out of view from the non-transformed states. If there are more glaring inconsistencies like the perspectiveUpIn one, however, please absolutely let me know. Those are outright bugs.

As per your EDIT: Very good point. Take a look at https://github.com/julianshapiro/velocity/issues/224. Please do chime in there. I plan to address it shortly.

Sorry if my general tone seems dismissive. This has been a helpful post, Kevin. Given me a few things to chew on. If you can nail down any specific issues, it'd be my pleasure to solve them.
