### ISSUE TITLE
scale from one image to other with velocity

### ISSUE THREAD

**Issue by saniko** [julianshapiro/velocity#408]
Hi,
I'm quite new to velocity, i'm trying to migrate my code from css to velocity for better look and feel :)
can some one please advice on what is the best way to accomplish this?
when user hovers an menu item its transforms (scale) in size, basicly its a transition from one image to other

this is the pure css:

.site nav li a.active-page  {
	background-color: #00b2ff;
	background-image: url('../images/img/menu-1-hover.png');
	border: 2px solid #fff;
	height: 94px;
	right: -8px;
	width: 94px;
	margin-top:-2px;
	-webkit-transition: all 0.09s easy;
        -moz-transition: all 0.09s easy;
        -ms-transition: all 0.09s easy;
        -o-transition: all 0.09s easy;
        transition: all 0.09s easy;
}
.site #menu-2 {
	background-image: url('../images/img/menu-2.png');
}
.site #menu-2.active-page {
	background-image: url('../images/img/menu-2-hover.png');

Thanks!

**Comment by ydaniv** [comment]
Sorry, these questions belong on StackOverflow, please close.
