### ISSUE TITLE
Animating backgroundColorAlpha from rgba(0,0,0,0.0) results in a white flash.

### ISSUE THREAD

**Issue by miklschmidt** [julianshapiro/velocity#409]
See: http://jsfiddle.net/22wLxfdy/1/

Notice how rgba(1,0,0,0.0) works as expected.

**Comment by ydaniv** [comment]
I see it on Chrome, but not on FF. And setting `rgba(1,0,0,0.0)` doesn't help on Chrome.

Where are you seeing it?

**Comment by miklschmidt** [comment]
That's not at all what i'm getting. I'm using chrome too. I get the flash in rgba(0,0,0,0.0) and not with rgba(0,0,0,0.0). Keep in mind there the initial page render flash when you run the script. That's not what i'm talking about.

**Comment by miklschmidt** [comment]
firefox has the exact same problem.. It's the black transparent box that flashes white.

**Comment by ydaniv** [comment]
OK, I see now. Worth checking out
