### ISSUE TITLE
Velocity.scroll() offset value is different on chromium based browsers

### ISSUE THREAD

**Issue by thco** [julianshapiro/velocity#411]
Hi.

I noticed that offset property has to be tweaked on chromium browsers (Chrome 39 & Opera 26) if we want an exact behavior as Firefox / IE. 

Currently I try "window.chrome" var to tweak this value or not but I think it should be handle by Velocity itself :-)

**Comment by thco** [comment]
Here is how I currently "fix" it 
```javascript
$(element).velocity('scroll', {
  container: $('.parent'), 
  axis: 'y', 
  duration: 500, 
  delay: 250, 
  offset: window.chrome ? -10 : -140 // Chrome & Opera fix
});
```

**Comment by julianshapiro** [comment]
Interesting... Will look into it this weekend. Are you sure it's not a box model issue? Can you quickly throw together a fiddle?

**Comment by julianshapiro** [comment]
Checking back in re. fiddle.

**Comment by thco** [comment]
Hi. Sorry. I'm currently far from my computer, sick. I'll try to that asap.

**Comment by thco** [comment]
Hello.
I'm currently tryin to build a JSFiddle but I got some issues... I come back here when it's ready. Sorry

**Comment by julianshapiro** [comment]
yo! unsure :-/ ty for helping out with this. appreciated
