### ISSUE TITLE
Support custom easing in VelocityUI transitions.

### ISSUE THREAD

**Issue by giuseppelt** [julianshapiro/velocity#412]
This is something I find very usefull to personalize builtin transitions.

On line 118, I just piped `redirectOptions`:

```javascript
opts.easing = callOptions.easing || redirectOptions.easing /* < added this*/ || "ease";
```
Because other options like duration and queue are backed by redirectOptions, is there a reason why easing is missing?

I created marvelous effects by providing custom easing.
Maybe you can switch the pipe order to achieve an override instead of a fallback. But it's just an idea, for me, fallback is ok.

**Comment by julianshapiro** [comment]
Ahh, yes. Very good question. The reason is that providing easing control for built-in functions will very often have unintended animation behavior since the packaged effects consist of multiple animations whose for which new easing types will alter the smooth handoff from one effect to another -/
