### ISSUE TITLE
Duration in sequences not working as expected.

### ISSUE THREAD

**Issue by JamesAtkinson** [julianshapiro/velocity#413]
When creating a sequence with velocity ui pack the duration's don't seem to work as expected.

Here is a fiddle - http://jsfiddle.net/JamesAtkinson/qq66v5nt/

The three boxes should all take 3 seconds to move, but it only works for the last one.

**Comment by julianshapiro** [comment]
yikes, that's a huge bug. will fix this. ty!

**Comment by julianshapiro** [comment]
I'll look into fixing this tomorrow.

**Comment by julianshapiro** [comment]
So the issue only happens with the e/p/o shorthands. Figuring out why now...
