### ISSUE TITLE
Pre-Registered UI Pack effects don't use Velocity.defaults

### ISSUE THREAD

**Issue by aristidesfl** [julianshapiro/velocity#414]
http://jsbin.com/puwotetaco/4/edit

**Comment by julianshapiro** [comment]
correct :) they have their own per-effect default that i deemed most appropriate when testing them. (not all effects should really run at 1000ms -- they're all quite unique.)

good q, though. and ty for fiddle!

**Comment by aristidesfl** [comment]
Thanks for the quick reply!
