### ISSUE TITLE
Error when removing element with infinitely looped animation

### ISSUE THREAD

**Issue by dabernathy89** [julianshapiro/velocity#415]
Example: http://jsfiddle.net/dabernathy89/9kxh2077/1/

I think this just needs to be wrapped with `if (Data(element)) {}`:

    change line 3698:
    if (opts.loop === true && !isStopped) {

    to:
    if (Data(element) && opts.loop === true && !isStopped) {

**Comment by ydaniv** [comment]
Looks like yer right, thanks! @julianshapiro :calling:

**Comment by julianshapiro** [comment]
thanks, @dabernathy89! Will implement this.
