### ISSUE TITLE
jQuery's property: 'toggle'

### ISSUE THREAD

**Issue by aristidesfl** [julianshapiro/velocity#416]
How to achieve the following with Velocity?
http://jsbin.com/wenajojifa/2/edit?html,css,js,output

1. `height` is set to `auto`
2. `overflow: hidden` is set automatically by jQuery
3. The animation automatically starts from `height: 0` because `display: none` is set

Thanks!

-------------------

Bonus: The parent element doesn't need to be animated with this one!

**Comment by ydaniv** [comment]
@aristidesfl this is a good question, but more for StackOverflow (:

Unless you have a feature request, in which case you should open a more specific thread. Thanks!
