### ISSUE TITLE
jQuery.animate({property: 'toggle'})

### ISSUE THREAD

**Issue by aristidesfl** [julianshapiro/velocity#419]
This is a feature request for the implementation of a new command called `toggle` like it exists in `jQuery.animate()`. 
The purpose of this feature is to be able to achieve effects like this easily: http://jsbin.com/wenajojifa/2/edit?html,css,js,output

This command achieves 2 things:
1. Animates the value of the selected property between 0 and it's original value, even if it is `auto`.
2. Sets the value of `display` automatically in order to show/hide the element as appropriate, like [Fade & Slide] (http://julian.com/research/velocity/#fade)

In addition to that, if `display` is originally set to `none`, it automatically animates from 0 to the value set in CSS, even if it's auto. 

This is very useful to introduce elements in/out of the interface with minimal code like [Fade & Slide] (http://julian.com/research/velocity/#fade), while still allowing full flexibility of effects. It doesn't seem to be possibly otherwise to achieve the effect demonstrated in the fiddle easily with Velocity while having `height` set to `auto`.

**Comment by paulirish** [comment]
This feature relies on velocity to getComputedStyle on every invocation. This forces a layout thrash and isn't really desirable.

The sugar the API affords isn't worth papering over the performance losses, IMO.

**Comment by ydaniv** [comment]
@paulirish, by "every invocation" do you mean every `tick`? Or every invocation of `velocity`?

**Comment by paulirish** [comment]
Every invocation of `toggle()`

**Comment by aristidesfl** [comment]
It could be implemented with `reverse`, and something special only on the 1st invocation, depending on the `display` value. http://jsbin.com/jikutusuya/1/edit?css,js,output

**Comment by ydaniv** [comment]
IIRC there are many cases where the initial invocation thrashes layout, e.g. when not force-feeding, isn't it?

**Comment by julianshapiro** [comment]
Fair feature suggestion. I appreciate you taking the time to write up the breakdown for us, @aristidesfl.

Half of the feature is already implemented via Velocity's UI pack. Specifically, designating "In" and "Out" prefixes on effects name (see docs if you are unfamiliar). The other half has legitimate utility, but I don't plan to implement it at this time. If I do in the near future, I will incorporate it into a larger overhaul of Velocity's animation workflow improvements.

Thanks again :)
