### ISSUE TITLE
Infinitely looped element reset position

### ISSUE THREAD

**Issue by Globegitter** [julianshapiro/velocity#420]
Right now when I have code like

```
      $element.velocity({
        translateX: "326px"
      },{
        duration: 2000,
        delay: 0,
        easing: "linear",
        loop: true
      });
```
velocity animates nicely to 326px but then also back to 0. I would love to have an option to immediately reset to 0. So it only animates 0->326px, 0->326px, etc. I found a stackoverflow solution using recursion, but would prefer a 'native' one.

**Comment by ydaniv** [comment]
@Globegitter what you ask for is a *repeat* functionality, which isn't what `loop` does, though it's specifically implemented for some properties, like `rotateX/Y/Z` and `backgroundPositionX/Y`.

@julianshapiro you think it's worth adding a `repeat` option?

**Comment by Globegitter** [comment]
@ydaniv Yep exactly a `repeat` functionality would be really useful. Also how could I test that for `backgroundPositionX/Y`?

**Comment by Globegitter** [comment]
```
      function start1() {
        if (this.get('stop')) {
          return;
        }
        Ember.$('.background-jazzy').velocity({
          translateZ: 0, // Force HA by animating a 3D property
          translateX: [ 326, 0 ]
          // backgroundPosition: "326px"
        },{
          duration: 2000,
          delay: 0,
          easing: "linear",
          complete: start1
        });
      }
```

Another issue I have with this current solution, I can not make it general (in such a way that `function start` takes parameters), because as soon as I try to call something `complete: start(element, translateX, duration)` I get the error `too many recursions`.

**Comment by ydaniv** [comment]
On a side note, of course, you don't want to invoke `start()` immediately, what you want is to partially implement it with `.bind()` like `complete: start.bind(element, translateX, duration)`.

Regarding testing backgroundPosition you'll have to fiddle it (:

**Comment by Globegitter** [comment]
Thank you for that @ydaniv works now but when it resets you can clearly see a lag. Any way to improve that specifically?

**Comment by ydaniv** [comment]
First of all, don't force HA, it's written in the docs. If you have to, use the `mobileHA` option.
Second, a fiddle will be helpful, but you better move that thread to SO.

**Comment by julianshapiro** [comment]
this is a pretty uncommon feature request, so i'll close this for now. if others pipe in with examples of where this would be useful, i'll absolutely consider implementing it!

thank you very much for the suggestion. and, thanks for your help in here @ydaniv!

**Comment by badtant** [comment]
I'm also interested in a `repeat `option
