### ISSUE TITLE
Sequencing in UI Pack doesn't work on display: none if not the last item

### ISSUE THREAD

**Issue by AlexeyGorokhov** [julianshapiro/velocity#421]
animSequence = [
    // Hide the spinner
    {
      e: $spinner,
      p: { opacity: 0 },
      o: {
        duration: 150,
        display: "none"
      }
    },
    // Show the button
    {
      e: $btn,
      p: { opacity: 1 },
      o: {
        duration: 150,
        visibility: "visible"
      }
    }
];
$.Velocity.RunSequence(animSequence);

The spinner won't get display: none. Although, if it goes after the button, everything works correctly.

**Comment by ydaniv** [comment]
A fiddle would be most appreciated.

**Comment by AlexeyGorokhov** [comment]
Here's a fiddle: http://jsfiddle.net/AlexeyGorokhov/gjLft5ch/2/

**Comment by ydaniv** [comment]
Thanks! @julianshapiro looks like a bug.

**Comment by JamesAtkinson** [comment]
This looks to be linked to issue #413

**Comment by julianshapiro** [comment]
I'll look into fixing this tomorrow.
