### ISSUE TITLE
I can't get force feeding to work

### ISSUE THREAD

**Issue by ccorcos** [julianshapiro/velocity#422]
This doesnt work...
```
    $node.insertBefore(next)
      .velocity {translateX: ['0%', '100%']},
        duration: 500
        easing: 'ease-in-out'
        queue: false
```
It only works when I use a hook:

```
    $.Velocity.hook($node, "translateX", "100%");
    $node.insertBefore(next)
      .velocity {translateX: '0%'},
        duration: 500
        easing: 'ease-in-out'
        queue: false
```

Am I missing something?

**Comment by julianshapiro** [comment]
fiddle :)

**Comment by ccorcos** [comment]
lol.

What should I fiddle with? Is this your way of saying that it *should* would?

**Comment by julianshapiro** [comment]
most errors are due to users' own code. as is stated in the contributing faq, submitting q/bug with fiddle helps remove that uncertainty so that people helping out can be extra certain they're not wasting their time.

not saying that reflects in any way on your particular question

**Comment by ydaniv** [comment]
And assuming you're familiar with http://jsfiddle.net/

**Comment by ccorcos** [comment]
Ok. So I've fiddled around a little more ;)

Force-feeding works. But on certain browsers (every time with firefox, sometimes with Safari, never with Chrome), you'll see a brief flash when the element is inserted before velocity catches it and moves it.

For example, check out the slide left button on this demo: http://transition-demo.meteor.com/

P.S. I'm using velocity to make a much needed page transitioning package for meteor: https://github.com/ccorcos/meteor-transitioner

And great job with this framework.

**Comment by ccorcos** [comment]
Ok. Here we go:

Here's the code:
https://gist.github.com/anonymous/23f0f73678bc81354908

and here it is on CodePen:
http://codepen.io/ccorcos/pen/gbxGpZ

You'll notice there is a flash of red when you press the button

**Comment by ydaniv** [comment]
@ccorcos that's because how you're inserting the second page into the DOM dynamically on click. Try giving us a clean example where the elements are present in the DOM before you move them around with Velocity.
To be more specific, it's probably due to the fact you're inserting an element that's initially *in* view when inserted.

**Comment by ccorcos** [comment]
Yeah, I see. The problem for me is that this is the way meteor works. I'm given and insert and remove function and I need to to insert it into the dom and do this animation. The odd thing is that any of the built-in effects don't have this flickering problem:

https://github.com/julianshapiro/velocity/blob/master/velocity.ui.js#L535

But the ones I wrote do have this problem:

```
$.Velocity.RegisterEffect 'transition.pushRightIn', 
  defaultDuration: 500,
  calls: [
    [{translateX: ['0%', '100%'], translateZ: 0, easing: "ease-in-out"}]
  ]

$.Velocity.RegisterEffect 'transition.pushLeftOut', 
  defaultDuration: 500,
  calls: [
    [{translateX: ['-100%', '0%'], translateZ: 0, easing: "ease-in-out"}]
  ]
```

Notice the difference between slideLeft and slideRight in this demo: http://transition-demo.meteor.com

Any ideas?

**Comment by julianshapiro** [comment]
Taking a look now.

**Comment by julianshapiro** [comment]
The UI pack addresses the flashing by immediately setting `opacity` upfront: https://github.com/julianshapiro/velocity/blob/master/velocity.ui.js#L134.

I would try doing that with your code as well. Let me know how that works out.

**Comment by ccorcos** [comment]
Interesting. I see whats going on here. [Every effect animates opacity](https://github.com/julianshapiro/velocity/blob/master/velocity.ui.js#L315). Is it possible to immediately animate the opacity to prevent the flash?

Here's what I have going right now...

```
$.Velocity.RegisterEffect('transition.pushRightIn', {
  defaultDuration: 500,
  calls: [
    [
      {
        translateX: ['0%', '100%'],
        translateZ: 0,
        easing: "ease-in-out"
      }
    ]
  ]
});
```

**Comment by julianshapiro** [comment]
oh shit, you're right! it's because you have to explicitly animate opacity in there. either throw it in as a dummy property (E.g. opacity: [ 1, 1]) or manually set opacity to 0 before the animation begins

**Comment by ccorcos** [comment]
Much better! That works. Thanks.

**Comment by az-iB** [comment]
i suggest to remove the style attribute after the transition complete

` var start = '100%';
      $.Velocity.hook(node, 'translateX', start);
      $(node)
      .insertBefore(next)
      .velocity({translateX: [0, start]}, {
        duration: ANIMATION_DURATION,
        easing: 'ease-in-out',
        queue: false,
        complete: function() {
          $(node).removeAttr("style");
        }
      });`
