### ISSUE TITLE
Performance `translateX` vs `left`

### ISSUE THREAD

**Issue by alvarotrigo** [julianshapiro/velocity#423]
Thanks for the project! It makes it much easier for old browsers compatibility!

Is there any difference in performance between using `translateX` or `left` for an animation using velocity?

There's clearly a difference when using jQuery. Does it happen the same here?

```javascript
$('.arrow').velocity({
    'translateY': '90px',
    'translateX': '95px'
}, 250, 'easeOutCubic');

//vs

$('.arrow').velocity({
    'top': '90px',
    'left': '95px'
}, 250, 'easeOutCubic');
```

**Comment by ydaniv** [comment]
Basically, a `left` change causes reflow, where as a `transform:transition` change may cause just repaint, which is way way faster.

Besides that, If I'm not mistaken (at least in CSS3 transitions/animations it is) `left/right` values are integers, where as `transition`s can have floating point values, so they appear much more smooth.

Usuaully for animation you'll want to use `transition`, but for some use-cases you'll have to resort to `left`.

**Comment by alvarotrigo** [comment]
I believe I had it wrong, it seems necessary to add the starting position as well:

```javascript
$('.arrow').velocity({
    'translateY': [90, 0],
    'translateX': [95, 0]
}, 250, 'easeOutCubic');
```

Which makes things even more tedious to maintain, as the same initial values should be placed in the styles sheet having them duplicated.

**Comment by julianshapiro** [comment]
This is a question better suited for Google. Short answer: translateX is faster.
