### ISSUE TITLE
Forcefeeding not working inside `complete` callback

### ISSUE THREAD

**Issue by alvarotrigo** [julianshapiro/velocity#424]
This won't work as expected:
```javascript
$('.point').velocity({
    translateX: [150, 0]
}, {
    duration: 300,
    easing: 'easeOutCubic',
    complete: function () {
       $('.demo').velocity({
            translateX: [100, -400]   /*  --> won't have -400px on start */
        }, 400, 'easeOutCubic');
    }
});
```

You can check an [example here](http://jsfiddle.net/5v1mbah6/).

**Comment by MattyBalaam** [comment]
Forcefeeding starts when the animation is triggered.

**Comment by alvarotrigo** [comment]
Does it mean then that I have to add those values in the CSS style sheet and then, in the javascript code as well? 

This doesn't happen when applying `left` instead.

**Comment by ydaniv** [comment]
Read the docs, you must provide unit types for transforms.

**Comment by alvarotrigo** [comment]
@ydaniv [here](http://jsfiddle.net/5v1mbah6/2/) you have it with units, not working either. 
And, this is the example provided in the docs:

```javascript
$element.velocity({
    /* Two-item array format. */
    translateX: [ 500, 0 ],
    /* Three-item array format with a per-property easing. */
    opacity: [ 0, "easeInSine", 1 ]
});
```

**Comment by ydaniv** [comment]
Right, my bad, probably just in hooks.

And to answer your question, it does work, force-feeding is only for telling JS what's the initial value so it won't have to query the DOM and thrash layout. In other words, it won't reset initial state of your elements' styles.

So yes, you have to use CSS.

Such is the life of a frontend dev (:
