### ISSUE TITLE
How to smooth scroll to the top and bottom of the page using Velocity JS ? 

### ISSUE THREAD

**Issue by zubairanwar2** [julianshapiro/velocity#426]
Velocity JS has a cool feature of smooth scrolling to specific div. However, is it possible to smooth scroll to bottom of a page or top using Velocity JS ?

**Comment by julianshapiro** [comment]
this is explained in docs. see scrolling section :)

**Comment by zubairanwar2** [comment]
Alright I just checked it out but I dint understand what you mean by an arbitrary offset value as in any value that I think is the height of the page ? Just want to get that cleared.

**Comment by obihill** [comment]
@zubairanwar2 I had the same issue with this. Offset is just the pixel distance from the top of the page. So, an offset of `0` is the very top of the page. Here's the code that worked for me:

```
Velocity(document.body, "scroll", {offset: "0", mobileHA: false});
```

This will scroll to the top of the page.

If you're using JQuery, it'll be something like this:
```
$("body").velocity("scroll", { offset: "0", mobileHA: false });
```

You've probably figured it out by now, but I just wanted to post this for posterity.
