### ISSUE TITLE
Run tests only in command line.

### ISSUE THREAD

**Issue by DamianRodziewicz** [julianshapiro/velocity#427]
Hi guys,

We would like to use mocha to test our meteor app only using command line, when we directly run 
```meteor --test```. However we haven't been able to configure velocity so that HTML does not show up on the app.

Is it possible to configure the package so that velocity does not start together with the app during development?

**Comment by ydaniv** [comment]
It's not really clear from your description what you want to accomplish. What is it exactly you want to prevent Velocity from doing?

**Comment by DamianRodziewicz** [comment]
Thanks for the response Yehonatan.

The aim is to test the app on demand only without having HTML Reporter attached in frontend and without velocity running in background during development. We have found suggestions to set NODE_ENV to production to disable velocity, however this is too general and affects other parts of code.

Any idea on how to this could be accomplished?

**Comment by ydaniv** [comment]
I assume you want to test on a headless browser, like PhantomJS? I think you have 2 options:

1. Use the [`mock: true` property](http://julian.com/research/velocity/#mock) to force all animations run in 0 duration.
2. Mock Velocity with another script, which you'll have to create yourself.

I hope I'm following you correctly.

**Comment by DamianRodziewicz** [comment]
Oh, I made a mistake and posted this question in wrong repository - it was supposed to be in meteor velocity.

I am sorry for the confusion.
