### ISSUE TITLE
Bug when calling same animation += (ie background-position +=50px) on completion, reverts back to initial value instead of keeping new value

### ISSUE THREAD

**Issue by rnlke** [julianshapiro/velocity#428]
This code in Jquery correctly moves the background 50px and then another 50px on repeat:

function moveBackground(){
    $('#div').animate({'background-position': '+=50'}, 1000, moveBackground)
}
moveBackground()

The same code with velocity() incorrectly resets the background-position back to the initial value before adding the 50px.

Here is a CodePen:
http://codepen.io/anon/pen/yyzgzP

**Comment by ydaniv** [comment]
Thanks! @julianshapiro looks like a bug

**Comment by rnlke** [comment]
To follow up on this, after further reading the docs, looks like you need to use the 'backgroundPositionX' property and not the 'background-position' according to the "one numeric value per property" velocity rule. I will close the issue.
