### ISSUE TITLE
function inside of a velocit.js sequence

### ISSUE THREAD

**Issue by carlosdv4** [julianshapiro/velocity#429]
What is the best way to run this? I get all kind the erros

I need to add a function after the sequence is finished. 

Using jquery with velocity.js

		$(".close").click(function(){	
				var mySequence = [
				                  { e: $(".bt_1"), properties: 'fadeIn' }
				                  { e: $(".bt_2"), options:  complete: function() { alert("123"); }  }
				              ];
				$.Velocity.RunSequence(mySequence);	
		 });

**Comment by ydaniv** [comment]
1. Fix your JS syntax.
2. See the docs again and fix you code.

**Comment by Rycochet** [comment]
The logic is correct, but that's completely invalid javascript - if you use an editor with syntax highlighting then it'll show where the problems are (though it's up to you to correct them).

**Comment by carlosdv4** [comment]
This is what I did, however I'm not a fully js dev, but I know is not the best way.

I will appreciate all the help.

$(".close").click(function(){   
            var mySequence = [
                              { e: $(".bt_1"), properties: 'fadeIn' }
                              { e: $(".bt_2"), options:  complete: function() { alert("123"); }  }
                          ];
            $.Velocity.RunSequence(mySequence); 

				window.setTimeout(function(){
					$(".nav_order_2").toggleClass("posAbsolute");
				}, 3000);
     });

**Comment by ydaniv** [comment]
@carlosdv4 for help please publish this question on StackOverflow. Thanks.

**Comment by carlosdv4** [comment]
No help at all. :-1: 

			$(this)
				.velocity.RunSequence(mySequence)
				.velocity({ complete: function() { alert("123"); }});

**Comment by MattyBalaam** [comment]
You will be much better off asking for JavaScript help on http://stackoverflow.com/

**Comment by Rycochet** [comment]
http://julian.com/research/velocity/#arguments
http://www.sitepoint.com/back-to-basics-javascript-object-syntax/

You're missing some of the most basic knowledge of JS - I'd strongly suggest working through some of the various tutorials or books around.

This issue tracker is for bugs inside Velocity - for problems that are entirely due to your own coding ability ask on https://stackoverflow.com/

**Comment by carlosdv4** [comment]
Answer is here: 

http://stackoverflow.com/questions/28319078/function-inside-of-velocit-js-sequence/28381155#28381155

test

http://codepen.io/shubhra/pen/yyPPrp

thx to shubhra.
