### ISSUE TITLE
Velocity translate used together with hammer.js

### ISSUE THREAD

**Issue by tehmaestro** [julianshapiro/velocity#430]
Hey, so I'm trying to use velocity together with hammer.js. I need to have a draggable box, which, when released, animates back to it's original position.

Here's an example: http://jsfiddle.net/8xLe7m4b/ . In this demo, I'm using velocity to animate the box for another 30 pixels, when the mouse is released. The problem is that, as you can see, the animation doesn't start from the last position of the element, it starts from the original position.

  Am I using the velocity animate wrong? I'm not sure what's happening or how I can fix this. For each mouse movement, I'm translating the box using CSS directly, cause using animation doesn't make sense.

 I would really really appreciate any help. It would be great if I could get an example on how I can make the box animate itself back to the initial position, after mouse release. I guess I don't fully understand the css translations .. ?
 Thanks a lot, and yes, thank you for this library which I'm only starting to discover.

**Comment by MattyBalaam** [comment]
Velocity caches the objects position, but you need to have used velocity to
move it. Velocity has a 'hook' function which can directly set CSS:

http://jsfiddle.net/wv9vmqqy/1/

On 3 February 2015 at 21:51, tehmaestro <notifications@github.com> wrote:

> Hey, so I'm trying to use velocity together with hammer.js. I need to have
> a draggable box, which, when released, animates back to it's original
> position.
>
> Here's an example: http://jsfiddle.net/8xLe7m4b/ . In this demo, I'm
> using velocity to animate the box for another 30 pixels, when the mouse is
> released. The problem is that, as you can see, the animation doesn't start
> from the last position of the element, it starts from the original position.
>
> Am I using the velocity animate wrong? I'm not sure what's happening or
> how I can fix this. For each mouse movement, I'm translating the box using
> CSS directly, cause using animation doesn't make sense.
>
> I would really really appreciate any help. It would be great if I could
> get an example on how I can make the box animate itself back to the initial
> position, after mouse release. I guess I don't fully understand the css
> translations .. ?
> Thanks a lot, and yes, thank you for this library which I'm only starting
> to discover.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/julianshapiro/velocity/issues/430>.
>



-- 
Matthew Balaam
____________________
development and design

matthewbalaam.co.uk <http://www.matthewbalaam.co.uk>
@matthewbalaam <https://twitter.com/matthewbalaam>
07730 953486

**Comment by ibrierley** [comment]
Or could you just forcefeed like http://jsfiddle.net/8xLe7m4b/2/ ?

**Comment by tehmaestro** [comment]
Thank you both so so much. Yes, it works in both versions, but in both versions the performance was really bad on an iPhone. The trick was to add a translateZ property, to trigger Hardware Acceleration I guess.
  Here's the fiddle.
 Thanks again.

**Comment by Rycochet** [comment]
As a side note, Velocity auto-adds the translateZ with the ```mobileHA:true``` option (the default), however it doesn't actually do anything till the first frame after your call - so potentially there can be a flash of something wrong in between things (and mobileHA is specifically for mobile, so doesn't necessarily add it on desktop etc).

**Comment by ydaniv** [comment]
I'll add to what @Rycochet said (for future reference), since hardware acceleration is a process of transferring a layer from CPU to GPU and this process takes some time to calculate, the initialization will appear jittery. To avoid that, if possible, add `translateZ` to the animated element before you move it, if the intention already exists.

**Comment by julianshapiro** [comment]
thanks for all the great responses in here :)
