### ISSUE TITLE
boxShadowColor etc. not supported & messing up supported properties

### ISSUE THREAD

**Issue by BracketBulldog** [julianshapiro/velocity#432]
http://jsfiddle.net/adejqdtf/1/

According to the docs and this fiddle, it seems that boxShadowColor etc. are not supported :( (Wouldn't that be nice? btw I can have missed something)

I also don't really get why the supported properties at the second button are messing up, okay probably due to the non-supported ones, but that is not the expected behavior, is it?

Thanks in advance!

p.s. It would also be nice if shorthand properties would be supported, from what I know, I think it can't be that difficult using the currently available template and hook systems. :)

**Comment by Rycochet** [comment]
I'll point you at #263 from August last year (the search is your friend ;-) )

**Comment by BracketBulldog** [comment]
Well, then it seems Google is not as effective as everyone says :p (and yes I know Github has a search box, but I've some bad habits ;p)

Anyway, is there currently a hack/workaround or does someone know a more concrete date? I'd very much appreciate this function!

If I really have to I'm willing to have a closer look at the code and develop a "patch" (but that would be against the contributing notes xD)

**Comment by ydaniv** [comment]
@BracketBulldog you're welcome to submit a patch, though @julianshapiro is notorious for messing up merges :laughing: , it might still help speeding things up.

**Comment by julianshapiro** [comment]
@ydaniv yep! haha

@BracketBulldog: you're welcome to dig into a patch, but the reason i reframed from incorporating this was sadly because it basically would require a totally rethink of the velocity property hook animation system. it would indeed be pretty handy, though. let me know if you feel up to it! so sorry about this.
