### ISSUE TITLE
Velocity: IE8 and below require jQuery to be loaded before Velocity (using Zepto)

### ISSUE THREAD

**Issue by heldrida** [julianshapiro/velocity#433]
Hi,

I'm loading zepto js just before velocity js and this error is triggered on IE8 (that unfortunately I have to support).

The error is the following:
"Velocity: IE8 and below require jQuery to be loaded before Velocity"

Thanks for looking!

**Comment by ydaniv** [comment]
Just curious, Zepto doesn't support IE8, so why you want to load it there?

**Comment by heldrida** [comment]
@ydaniv I should've double checked that then. Thanks for mentioning!
