### ISSUE TITLE
Tween color

### ISSUE THREAD

**Issue by Rycochet** [julianshapiro/velocity#434]
Somebody just mentioned the BoxShadowColor feature request #263 and it gave me an idea.

Currently we have the ```tween:123``` support for custom animations, but we don't have anything that can make use of Velocity's built in color animation (http://julian.com/research/velocity/#colors) - so as a suggestion somthing like passing a string to tween (ie something like ```tween:["red", "blue"]``` to have the tween value return the in-between color codes.

An alternative would be to expose some sort of method like ```$.Velocity.color(from, to, percent)```.

**Comment by julianshapiro** [comment]
you can already animate colors in velocity using forcefeeding, and you can independently target rgb values. i'm considering additional support (hsla) in the near future :)

if i misunderstood, lemme know!

**Comment by Rycochet** [comment]
I was thinking about it more in terms of where you have multiple comma separated values - ie being able to animate a background gradient smoothly - something that would either need a lot of code bloat, or the use of tween and progress callbacks ;-)
