### ISSUE TITLE
Can't get sequenceQueue: false to work

### ISSUE THREAD

**Issue by MikaAK** [julianshapiro/velocity#435]
I've made a pen over [here](http://codepen.io/Snowfiring/pen/EabLOY), I can't seem to get turning off the sequenceQue for a specific element to work. 

My code is as follows

```javascript
var ele = document.getElementById('item'),
    ele2 = document.getElementById('item2'),
    sequence = [
      
      {e: ele2, p: {left: '+=300px', top: '+=200px', backgroundColor: '#01f'}, o: {duration: 2500}},
      
      {e: ele, p: {left: '+=300px', top: '+=200px', backgroundColor: '#01f'}, o: {duration: 2500, sequenceQueue: false}},
      
      {e: ele2, p: {left: '+=150px', top: '-=150px', backgroundColor: '#83f'}, o: {duration: 2500, sequenceQueue: false}},
      
      {e: ele, p: {left: '+=150px', top: '+=100px', backgroundColor: '#1f9'}, o: {duration: 2500}},      
    ]

  Velocity.RunSequence(sequence)
```

**Comment by distilledhype** [comment]
I have the same problem.

**Comment by ydaniv** [comment]
Try the latest velocity.ui version `5.0.3`

**Comment by distilledhype** [comment]
Ah yes that was better. Although I had to switch to just using the `begin:` callback because the two elements were still slightly delayed.

**Comment by MikaAK** [comment]
Updated the (pen)[http://codepen.io/Snowfiring/pen/EabLOY], still doesn't seem to work for me. *note*: The library is imported via another pen since I couldn't find 5.0.3 via CDN.

**Comment by julianshapiro** [comment]
there seems to be a larger bug in sequence running. looking into it tonight.

**Comment by julianshapiro** [comment]
going to push a change tonight. let me know if it fixes it.

**Comment by MikaAK** [comment]
This fixes it thanks!

**Comment by jscheel** [comment]
I'm on 5.0.4, but it still isn't working for me. Two out of the three run in parallel, but the second one doesn't.

```
  var payProcessingSequence = [
    {
      e: $('.pay-card'),
      p: {
        translateY: '-100px'
      },
      o: {
        easing: 'easeOut',
        duration: 700,
        sequenceQueue: false
      }
    },
    {
      e: $('.btn-pay'),
      p: {
        width: '100px',
        height: '100px',
        borderRadius: '100px'
      },
      o: {
        easing: 'easeOut',
        duration: 700,
        sequenceQueue: false
      }
    },
    {
      e: $('.btn-pay i'),
      p: {
        fontSize: '50px'
      },
      o: {
        easing: 'easeOut',
        duration: 700,
        sequenceQueue: false
      }
    }
  ];
```

**Comment by julianshapiro** [comment]
did you update the ui pack too?

**Comment by jscheel** [comment]
@julianshapiro yep, 5.0.4. It's only the one with the width, height, and borderRadius, no matter where in the sequence it is.

**Comment by jscheel** [comment]
@julianshapiro so, I fixed this on the plane the other day, and don't remember what was causing it. If I can recreate, I'll let you know. It was something really wonky.

**Comment by julianshapiro** [comment]
;)

**Comment by efusien** [comment]
I noticed the same problem. Seems relative to the element.
We can't use two effects on a same element at the same time. Like a translateX + translateY move.
Here is a codePen fork to see the problem: http://codepen.io/anon/pen/azjBWG
Is there any solution?
