### ISSUE TITLE
Moving RegisterEffect in Velocity

### ISSUE THREAD

**Issue by MathieuLoutre** [julianshapiro/velocity#436]
Hi there!

The UI Pack is pretty awesome, but for some reason I rarely used the bundled effects (or just a couple)  but I use RegisterEffect to make my own (mostly when I need `stagger`). In a quest to remove some bytes to my browserify bundle, I was wondering if moving the RegisterEffect method inside Velocity and leaving the UI Pack with all the bundled effects wouldn't make more sense? Any thoughts on this?

Thanks for the hard (and awesome!) work.

**Comment by julianshapiro** [comment]
Yo! Very good question. I've considered this myself. I might move RegisterEffect and SequenceRunning into Velocity, yes. I'm just concerned about bloat, so I'd want to remove something from Velocity in the process.

What I might do in the near future is a backwards-incompat upgrade to Velocity (2.0) that'll be a bit leaner by removing bezier curve support and include the UI pack's functionality instead. I don't have an ETA yet on this, but stay tuned.

**Comment by MathieuLoutre** [comment]
Great to hear that it's being considered. I'll keep an eye out for sure! Thank you!
