### ISSUE TITLE
Can you pass data to complete function?

### ISSUE THREAD

**Issue by AtheistP3ace** [julianshapiro/velocity#438]
I can't find anything in the documentation or in any existing issues. Thank you.

**Comment by Rycochet** [comment]
Use javascript's function binding - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind

**Comment by AtheistP3ace** [comment]
Thanks for the reply. I ended up using an IIFE actually. I was looping over objects and losing some values I needed in the callback.

So can I take your answer as there is no built in way within velocity itself to pass extra data to its callbacks?

Thanks again.

**Comment by Rycochet** [comment]
Nope, the third alternative is to use $.data() to set things on the elements themselves - loads of tools for the same job ;-)

**Comment by AtheistP3ace** [comment]
Yea I considered data but I read it has terrible performance. Well thank you so much for the replies and suggestions. Really appreciate it!!!

**Comment by Rycochet** [comment]
```$(el).data(key[, value])```  used to be significantly slower than ```$.data(el, key[, value])``` - now there's not quite so much in it - http://jsperf.com/jquery-data-vs-jqueryselection-data/94 - definitely not the fastest operation, but if it does what's needed etc... ;-)
