### ISSUE TITLE
From Julian (Author): Velocity.js + UI pack updates coming tomorrow.

### ISSUE THREAD

**Issue by julianshapiro** [julianshapiro/velocity#439]
Oh, and while I have your attention, you can now pre-order the upcoming Velocity.js book: https://twitter.com/Shapiro/status/559572916560343041.

**Comment by ydaniv** [comment]
Congrats! :tada:

**Comment by Rycochet** [comment]
Anyone would think you knew something about animating things on the web... :-P

**Comment by julianshapiro** [comment]
Also, a huge thanks to @ydaniv  for all his support with GitHub issues. @Rycochet  and @MattyBalaam  have also been total gentlemen.
