### ISSUE TITLE
Request: Add Velocity to a CDN

### ISSUE THREAD

**Issue by kokarn** [julianshapiro/velocity#44]
[jsDelivr](http://www.jsdelivr.com/) has some phenomenal features where you can generate one single js file from multiple ones and in that way reduce the number of requests needed.

It would be great if you would consider adding velocity to their list of repos.

Thanks for something awesome <3

**Comment by MattyBalaam** [comment]
Should the CDN have auto updated by now, or am I misunderstanding?

**Comment by MattyBalaam** [comment]
OK, I assume someone needs to merge manually still? https://github.com/jsdelivr/jsdelivr/pull/2928

**Comment by MattyBalaam** [comment]
This has now been done. Apologies for the noise.

**Comment by julianshapiro** [comment]
Np! Will update shortly

**Comment by jimaek** [comment]
I wanted to let you know that the new backend is live. It pulls files directly from npm and github https://github.com/jsdelivr/jsdelivr#usage

Example https://cdn.jsdelivr.net/npm/jquery@3.1.1
Example directory listing https://cdn.jsdelivr.net/npm/jquery@3.1.1/
