### ISSUE TITLE
Is reverse always applied to only the most recently run animation?

### ISSUE THREAD

**Issue by macsupport** [julianshapiro/velocity#443]
I am working on adding velocity.js animations to the magnific-popup lightbox using the Ui pack. I have one animation for opening the slide image from the thumbnail and a different animation for prev-next in the gallery. I would like to  to reverse the slide image opening animation style when I close the lightbox. Is reverse only for the most recent animation run or can it be associated to a set animation?

Here is a  [jsfiddle](http://codepen.io/macsupport/pen/xbWGZo) of what I have so far. 
(Excuse my code...still learning)

**Comment by ydaniv** [comment]
Yes, I believe it's mentioned in the docs.

**Comment by macsupport** [comment]
Thanks. I did see *To animate an element back to the values prior to its last Velocity calI* 
I thought possibly there might be an option to make an element unique for that particular animation vs just the most recent animation. As I said, still learning.
