### ISSUE TITLE
Site flashing before velocity events.

### ISSUE THREAD

**Issue by jeremypbeasley** [julianshapiro/velocity#444]
Any idea what's going on here?

http://www.goodcorps.com/

The site appears, then disappears, then fades in. How and in what order should I be handling events here?

Thanks so much for your time.

**Comment by julianshapiro** [comment]
set the content that is flashing to have its opacity default to 0 to begin with so it doesn't first appear on page load

**Comment by Rycochet** [comment]
Safest is to have ```<script>$(hidden content).css("opacity",0)</script>``` right at the end of the html rather than within the css - that way the ~1% of people running without javascript still get a site to see ;-)

**Comment by MattyBalaam** [comment]
Or alternatively have a .no-js class on the document which you remove with
javascript.

On 20 February 2015 at 09:07, Rycochet <notifications@github.com> wrote:

> Safest is to have <script>$(hidden content).css("opacity",0)</script>
> right at the end of the html rather than within the css - that way the ~1%
> of people running without javascript still get a site to see ;-)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/julianshapiro/velocity/issues/444#issuecomment-75208396>
> .
>



-- 
Matthew Balaam
____________________
development and design

matthewbalaam.co.uk <http://www.matthewbalaam.co.uk>
@matthewbalaam <https://twitter.com/matthewbalaam>
07730 953486
