### ISSUE TITLE
Is nwjs(node-webkit) supported?

### ISSUE THREAD

**Issue by leader22** [julianshapiro/velocity#445]
@julianshapiro 

Hi, thank you for nice lib ;D

I'm now developing my app with Velocity on nwjs(node-webkit).
And I have to support both two nwjs versions below.

```
// maintained stable
node-webkit: "0.8.6"
chromium: "30.0.1599.66"
node: "0.10.22"
v8: "3.20.15.5"
```
and
```
// maintained latest
node-webkit: "0.11.6"
chromium: "38.0.2125.104"
node: "0.11.13-pre"
v8: "3.28.71.2"
```

My problem is "Error occurs **only** on maintained stable".
Minimal sample is below.

```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>nwjs - Velocity</title>
</head>
<body>
<div id="test" style="background-color: blue; color: #fff; width: 300px; height: 300px;">Fadeout</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/velocity/1.2.2/velocity.js"></script>
<script>
Velocity(document.getElementById('test'), 'fadeOut', {
  complete: function() { alert('Done'); }
});
</script>
</body>
</html>
```

Animation has completed but, it's end up with some error.

```
Uncaught TypeError: object is not a function velocity.js:3691
Uncaught TypeError: Property 'resolver' of object #<Object> is not a function velocity.js:3681
```

According to my examined, implementation of 'Promise' was different.

Latest one(with node v11) has native Promise, works propery.
But stable one has nwjs original? Promise, occurs error.

Both has ``window.Promise``, so same code executed, but it works different...
Is there a way to avoid this?

Sorry to my poor english X(

**Comment by ydaniv** [comment]
Try including a library that implements it according to the Promises A+ spec and set its `Promise` to `Velocity.Promise`.

**Comment by leader22** [comment]
Thank you for the comment.

Is hard to say, but my problem is a little more complicated..
This error occurs in ``iframe`` contentWindow, so I can't fix ``Promise`` from outer.

Of course, I can load Promise A+ shim(like bluebird) on outer.
But it does not seem to affect the in ``iframe`` scope.

**Comment by ydaniv** [comment]
So this is not a Velocity issue, then.

**Comment by leader22** [comment]
Hmm, ok.

Thanks anyway.

**Comment by Duder-onomy** [comment]
If anyone stumbles here through google. 

The posted solution works for me, on LG Smart TV's (nodeWebkit) Velocity does not work because the Promise implementation is incorrect.

Patching Velocity.Promise with [bluebird](https://github.com/petkaantonov/bluebird/blob/master/API.md) solves the issue.

```javascript
var velocity = require('velocity'),
    bluebird = require('bluebird');
    
velocity.Promise = bluebird;
```
