### ISSUE TITLE
Complete event listener not removed after execution...

### ISSUE THREAD

**Issue by asleepinglion** [julianshapiro/velocity#446]
I'm using velocity 1.2.2 from the ember-velocity-mixin and the having an issue with the following code. I have an action handler that is hit when the login is successful:

```javascript
loginSuccess: function() {
  var self = this;
    self.animate($('.spinner'), {opacity: 0}, { duration: 100, complete: function() {
      self.css($('.spinner'), 'display', 'none');
      alert('wtf');
      self.get('controller').transitionToRoute('dashboard');

    }});
}
```

Basically a loading spinner is animated out, and when complete, it removes the spinner and triggers the transition to the dashboard route. If i return to the login screen, and this function executes again, the complete method gets called twice. One of those works and one errors out because the `self` that was being referenced in the first one no longer exists. Shouldn't the complete event remove its listener automatically after firing? Do i need to manually do something?

**Comment by julianshapiro** [comment]
sounds like you should be asking this in the ember mixin repo?

**Comment by asleepinglion** [comment]
Its directly calling the velocity api, this.animate is equal to:

```
$.Velocity.animate.apply(null, args);
```

**Comment by asleepinglion** [comment]
Just tested with the following code and the same result: 

```javascript
 loginSuccess: function() {
    var self = this;
    $('.spinner').velocity({opacity: 0}, { duration: 100, complete: function() {
      self.css($('.spinner'), 'display', 'none');
      alert('wtf');
      self.get('controller').transitionToRoute('dashboard');

    }});
  },
```

**Comment by ydaniv** [comment]
Did you verify that the handler for `loginSuccess` isn't executed twice?

**Comment by asleepinglion** [comment]
Ah hah! Good call sir! Really appreciate the prompt replies! Love the library! :)
