### ISSUE TITLE
Add more easing types

### ISSUE THREAD

**Issue by jackmu95** [julianshapiro/velocity#447]
Velocity.js already comes with a great amount of available easing types but three ones (easeInBack, easeOutBack, easeInOutBack) are missing from the available on [this](http://easings.net) site.

Is it possible to add them to Velocity.js too or is there some sort of limitation with negative cubic-bezier values?

**Comment by julianshapiro** [comment]
yo! check out the FAQ on github. it talks about adding those back :)

i won't be adding them into velocity by default

**Comment by jackmu95** [comment]
Thanks for the quick reply :) I haven't seen the FAQ - my bad...
