### ISSUE TITLE
Suggestion: Add support for "will-change"

### ISSUE THREAD

**Issue by Rycochet** [julianshapiro/velocity#448]
https://dev.opera.com/articles/css-will-change-property/
http://dev.w3.org/csswg/css-will-change/
http://caniuse.com/#feat=will-change (~41% browser share, )

Currently `mobileHA:true` is used to promote animated elements via `transform:translateZ(0)` and (hopefully) optimise whatever happens to be moving. This is set at the start of the animation (ie, first frame _after_ creating it).

Basically this change would set the `will-change:<keys>` css attribute when the animation is created instead of setting translateZ when it starts (so only useful on browsers that support it - fallback to translateZ in all other cases), then deleting it when finished.

The benefit would be slightly smoother animations and slightly less thrashing on the first frame as the browser would have the opportunity to create any layers (if they're even needed) before it starts.

Questions: if using the `tween` key, or a `progress` function should it still try to predict or should it just use translateZ, or should there be an option that we can manually set things that are going to change?

**Comment by julianshapiro** [comment]
Good stuff. Will get back to you on this before the next update.

**Comment by Rycochet** [comment]
Apparently Chrome has completely screwed with this to make it unusable, a pretty good writeup is available here - https://greensock.com/will-change
