### ISSUE TITLE
Support for Left Scrolling an Element

### ISSUE THREAD

**Issue by dhruvparmar372** [julianshapiro/velocity#450]
Does velocity have support for scrolling an element in the horizontal direction if the content inside is overflowing ? 
I have the following fiddle http://jsfiddle.net/65xCP/87/.
$.animate seems to work but $.velocity doesn't.

**Comment by ydaniv** [comment]
Read the docs, you need to operate on the element you want to scroll to: http://jsfiddle.net/65xCP/88/
