### ISSUE TITLE
Suggestions: Add separate timings to ui pack for ease-in vs ease-out

### ISSUE THREAD

**Issue by MikaAK** [julianshapiro/velocity#451]
It would be great to be able to set different easings for animation-in vs animation-out for default timing. It would enable out of the box ui-animations use while being able to keep to http://www.google.com/design/spec/animation/authentic-motion.html since they have different timings!

**Comment by julianshapiro** [comment]
Thanks, Mika!

**Comment by Rycochet** [comment]
You can manually override the durations for the new ui-pack animations, they are set to match the animate.cs animations by default
