### ISSUE TITLE
Rotate negative value rotates back in clockwise

### ISSUE THREAD

**Issue by domiSchenk** [julianshapiro/velocity#453]
with 

```
Velocity({ e: $elem, p: {rotateZ: "-360"}, o: {duration: 2500, easing:'linear', loop: true}});
```

the element rotates to -360 deg counterclockwise
then back to 0 deg clockwise

it should keep rotating counterclockwise

demo: bit.ly/1zPzWHk

**Comment by julianshapiro** [comment]
Thanks, man! Yessir. Will fix.

**Comment by Rycochet** [comment]
In V2 use true `transform` properties, this puts the developer in control of direction.
