### ISSUE TITLE
Remove transitional fade as text animates in

### ISSUE THREAD

**Issue by richgcook** [julianshapiro/velocity#456]
Any way to remove the transitional fade as the text animates in and have it simply as show/hide or 0/1 etc. 

```
function featuredProjectTextAnimation(incomingSlideEl) {
    var $animated = $(incomingSlideEl).find('.text-container.animated');
        $animated
	.blast({
        delimiter: 'word'
    })
	.velocity('transition.fadeIn', {
        display: null,
        duration: 0,
        stagger: 100,
        delay: 400,
        begin: function () {
            $animated.css('opacity', 1);
        },
        complete: function () {
            //
        }
    });
}
```

**Comment by julianshapiro** [comment]
say wuh

**Comment by richgcook** [comment]
@julianshapiro Haha! Sorry! In your own example, http://codepen.io/julianshapiro/pen/xmElz, and in a GIF of my example (http://g.recordit.co/0kMBmoPUqL.gif) you can see the text fades in, whereas I'd prefer to have something with no fade, just show. (like this: http://g.recordit.co/dznyLg3zq8.gif) I'm curious to know if this is possible :+1:

**Comment by julianshapiro** [comment]
Ahh!

Yes: What's wrong with just duration: 1?

```javascript
function featuredProjectTextAnimation(incomingSlideEl) {
    var $animated = $(incomingSlideEl).find('.text-container.animated');
        $animated
    .blast({
        delimiter: 'word'
    })
    .velocity('transition.fadeIn', {
        display: null,
        duration: 1,
        stagger: 100,
        delay: 400
    });
}
```

**Comment by richgcook** [comment]
@julianshapiro HAH wuh? I thought 0 would've nailed this, but didn't... but 1 definitely does. Not sure how or why I overlooked this. Thank you for the swift help and reply.

**Comment by julianshapiro** [comment]
np. btw you can also use the step easing feature to cause immediate value jumps :)

**Comment by richgcook** [comment]
@julianshapiro I saw that but didn't quite figure out how to implement that with blast and my current code.  I'm curious though as I'd like to be able to control the speed of the animation as setting the duration to 1 revokes this.

**Comment by richgcook** [comment]
@julianshapiro Actually, I suppose that's stagger ;)
