### ISSUE TITLE
VMD UI Pack dropdown

### ISSUE THREAD

**Issue by alanontheweb** [julianshapiro/velocity#457]
Can the VMD have a dropdown for the UI pack effects to save on typing, similar to how you have it for the easing effects? It would just auto-insert the text into the field.

**Comment by julianshapiro** [comment]
I'm actually looking for someone to completely rewrite VMD. Will open a new thread about this shortly :) Will have the UX improved, including seriously considering your suggestion. Thanks, Alan :)

**Comment by alanontheweb** [comment]
Awesome thanks! You know what might be cool is if there was a velocity chrome extension that built on top of this - https://www.youtube.com/watch?v=U9xfYbKxosI @julianshapiro
