### ISSUE TITLE
Interrupting/additive animations

### ISSUE THREAD

**Issue by boyswan** [julianshapiro/velocity#458]
Firstly thank you for velocity.js, it's by far the most realistic animation library I've come across!

I'm currently using with React.js and it works great, however one problem I'm finding is that animations are not able to be interrupted. I've looked at the doc's but couldn't find anything about it. I'm ideally looking for an additive approach, similar to the third option here:

https://rawgit.com/chenglou/react-tween-state/master/examples/index.html

Is this something that's currently achievable?

**Comment by Rycochet** [comment]
http://julian.com/research/velocity/#queue or http://julian.com/research/velocity/#stop ?

**Comment by julianshapiro** [comment]
Did @Rycochet's links help? Will close for now. Let us know!

**Comment by Yaffle** [comment]
@boyswan @Rycochet  @julianshapiro  https://code.google.com/p/chromium/issues/detail?id=437696 ?

**Comment by maximelebreton** [comment]
+1 @boyswan 

@Rycochet i dont understand your answer, how queue/stop can resolve the **additive** animation question?

@julianshapiro, i think you should consider this feature request, because that's a _new standard_ since iOS8 and cheng lou's [react motion](https://github.com/chenglou/react-motion).

### [Building Interruptible and Responsive Interactions](https://developer.apple.com/videos/play/wwdc2014/236/)
![image](http://i.imgur.com/2jki7kY.png)
(The part about additive animations starts at around 25min)

**Comment by Rycochet** [comment]
The video is unwatchable on Windows btw - so an alternative link would be welcome (needs Safari, which is officially unsupported and has always been broken on Windows, or specific software - which by definition is a "no chance")

Myself and @kenwheeler have taken over coding on here - but I think this sort of thing is something we will talk about and do something about (whether it's this specifically or not is another matter) - it sort of hooks into queues and repeating sections and several other things at the same time so needs to be well thought out and designed before being implemented - not simply something that's bolted on to the top of what we have not, but an almost rewrite to allow more flexibility and some different approaches while still keeping the simplicity there when not needed...

**Comment by maximelebreton** [comment]
You can find it in [Resources](https://developer.apple.com/videos/play/wwdc2014/236/) tab:
- **[236_hd_building_interruptible_and_responsive_interactions.mov](http://devstreaming.apple.com/videos/wwdc/2014/236xxwk3fv82sx2/236/236_hd_building_interruptible_and_responsive_interactions.mov)**
- [PDF slides](http://devstreaming.apple.com/videos/wwdc/2014/236xxwk3fv82sx2/236/236_building_interruptible_and_responsive_interactions.pdf)

I can imagine how complicated is this when it's not designed upstream.

Please keep us informed!

**Comment by Rycochet** [comment]
When we get a time to talk it over, or once the code is getting the time to be updated (and we're releasing again) then it'll get a separate issue opened for discussion if we work out multiple ways to get the same thing and need feedback :-)
