### ISSUE TITLE
Add Velocity to jQuery

### ISSUE THREAD

**Issue by AndyF** [julianshapiro/velocity#461]
Why not make merge Velocity with jQuery instead of making this a separate library?

**Comment by arthurvr** [comment]
@AndyF https://github.com/jquery/jquery/issues/2053

**Comment by goranefbl** [comment]
There is open talk on jquery git page of merging it into jquery. https://github.com/jquery/jquery/issues/2053

**Comment by julianshapiro** [comment]
Thanks, @arthurvr and @goranefbl :)
