### ISSUE TITLE
Remove stagger from second velocity animation

### ISSUE THREAD

**Issue by goranefbl** [julianshapiro/velocity#462]
Here is simple animation http://jsfiddle.net/65xCP/95/

if i add stagger on first animation, its transfered to second, even if i define stagger 0. on it. So my question is how to make elements shrinkOut all at once, it seems that it cant have stagger lower then what was on first velocity. Still going through documentation if this is explained in it.

Thanks

**Comment by julianshapiro** [comment]
It's because of the way animations are queued directly back-to-back onto one another. Draw out a diagram of how your animation plays out, and you'll see what I mean.

You'll want to introduce a delay between the time they all shrink in and they all shrink out at once.

**Comment by goranefbl** [comment]
Actually I did add delay between them, you can see on jsfiddle above:
    
$("div").velocity("transition.shrinkIn",{stagger:200}).delay(1200).velocity("transition.shrinkOut",{stagger:0});

thats what i first tried, but again same results.
