### ISSUE TITLE
slideDown height issue

### ISSUE THREAD

**Issue by sodbileg** [julianshapiro/velocity#463]
Hi, I'm creating a dropdown menu with `slideDown` and `slideUp` functions. But when I hover on a parent element, dropdown menu height is decreasing to animation's stopped height. I recorded my screen and the video is [here](https://www.dropbox.com/sc/plk3rbv27kolcvi/AABOF3xLW-DApeO5v4dwlGc2a).

Here is the script I wrote. I used `stop` function, but it's not fixing my issue.

```javascript
menuItem.mouseenter( function() {
	$( this ).children( '.sub-menu' ).velocity( 'stop' ).velocity(
		{
			translateY: ['0', '-5px'],
			opacity: 1,
		},
		{ display: 'block' }
	).velocity( 'slideDown', { queue: false } );
} );
menuItem.mouseleave( function() {
	$( this ).children( '.sub-menu' ).velocity( 'stop' ).velocity(
		{
			translateY: '-5px',
			opacity: 0,
		},
		{ display: 'none' }
	).velocity( 'slideUp', { queue: false } );
} );
```

**Comment by julianshapiro** [comment]
See the FAQ for a solution to this. Let me know if it doesn't help, and I'll re-open this thread.
