### ISSUE TITLE
[DOCS, SITE}

### ISSUE THREAD

**Issue by netaisllc** [julianshapiro/velocity#464]
The site content for command STOP looks broken to me. At the very least it is confusing... see attached.
![3-11-2015 9-50-41 am](https://cloud.githubusercontent.com/assets/1242423/6601738/92596ba8-c7d4-11e4-9772-9c4893c2818f.jpg)

I will cure if you want a PR.

**Comment by julianshapiro** [comment]
Ooops! I will fix this shortly. Thanks so much for the heads up, Kevin. Much appreciated.

**Comment by netaisllc** [comment]
LOL. I have done same many.

On Wed, Mar 11, 2015 at 9:56 AM, Julian Shapiro <notifications@github.com>
wrote:

> Ooops! I will fix this shortly. Thanks so much for the heads up, Kevin.
> Much appreciated.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/julianshapiro/velocity/issues/464#issuecomment-78305586>
> .
>



-- 
*Kevin McGee*
415.886.7090 (*office*)
415-990-7169 (*mobile*)

/ Web application UI/UX
/ Technical writing
/ Project management

*Netais LLC - "Let's be clear"*

** Sending me a file?  *
   Just pop 'em into this free, secure webspace.
   No limits, and I'll receive them in no time at all.
   https://www.hightail.com/u/KevinMcGee363880
<http://dropbox.yousendit.com/KevinMcGee363880>

**Comment by julianshapiro** [comment]
Fixed. Thanks again.
