### ISSUE TITLE
Licensing 

### ISSUE THREAD

**Issue by mrcoder16** [julianshapiro/velocity#465]
I was thinking of using velocity.js in an app and was wondering how to fulfill the stipulations in the MIT license. Do I just make sure the license header is kept intact as per the jQuery requirements or do I have to explicitly mention the copyright and license in an end user viewable portion of the app?

**Comment by Rycochet** [comment]
https://stackoverflow.com/questions/6138915/can-i-use-mit-licensed-library-in-my-closed-source-application

You should really list all open source / licensed code your app uses and include the text of the various licenses in your app - if there's no source view (the license text can be long etc) with it then generally linking to the various license and library sources is considered good form instead.

**Comment by mrcoder16** [comment]
Thank you
