### ISSUE TITLE
.hook() does not allow for setting multiple properties at once

### ISSUE THREAD

**Issue by kpeatt** [julianshapiro/velocity#466]
The documentation states that `.hook()` matches jQuery's `.css()` API but it doesn't exactly. It looks like `hook` only allows for setting single properties at a time whereas `css` allows for setting an object of properties for setting multiple properties at once.

This works:

``` js
$('.div').css({
    'top': '10px',
    'bottom': '10px'
});
```

While this doesn't:

``` js
$.Velocity.hook($('.div'), {
    'translateX': '10px',
    'translateY': '10px'
});
```

Would be nice to have this map 1:1. Thanks!

**Comment by konistehrad** [comment]
+1 love this idea.

**Comment by konistehrad** [comment]
I like it so much I made [a patch](https://github.com/konistehrad/velocity/commit/e387c0c7122ac9d11b76a4143d31f355489e8b3d) to support this!

**Comment by kpeatt** [comment]
Woo!

**Comment by andrerfneves** [comment]
@julianshapiro Any idea when you're going to get around to implementing this? If I am in need for something like this, should I use @konistehrad's quick patch? Has anyone tested @konistehrad's path by any chance?

**Comment by julianshapiro** [comment]
I get back to velocity development this weekend. Will respond then :)

**Comment by andrerfneves** [comment]
@julianshapiro Thanks for the quick reply. I'll wait for a response from you then! Cheers mate!

**Comment by konistehrad** [comment]
@andrerfneves my patch is being used in production: https://datenighto.com/game/starfighter-eclipse (NSFW content ahoy)

**Comment by Rycochet** [comment]
In v2 (develop branch), Velocity.hook has been removed, however there is an exposed API for doing this:

```typescript
var get = Velocity(element, "style", "property"); // value
var get = Velocity(elements, "style", "property"); // array of values, one per element

Velocity(elements, "style", "property", "value");
Velocity(elements, "style", {property: "value", ... });
```

You can also save the results of any Velocity call that is supplied a list of elements and then chain calls to that:

```typescript
var anim = document.querySelectorAll("div").velocity(properties..., options... etc);

anim.velocity("style", "property"); // as above
```
