### ISSUE TITLE
Velocity book is now out on Amazon!

### ISSUE THREAD

**Issue by julianshapiro** [julianshapiro/velocity#470]
**It's $15 USD. You can buy the Kindle version right now**: http://www.amazon.com/Web-Animation-using-JavaScript-Develop-ebook/dp/B00UNKXVDU/ref=tmm_kin_title_0?_encoding=UTF8&sr=&qid=

*It's also on iTunes (search for "Web Animation").*

It's not just about Velocity; it also dives into important topics like **animation performance, motion design theory, animation workflow**, and a lot more.

This book was a lot of work, and I truly hope you get a ton of value from it. If you like it, I'd love it if you could find the time to leave a review on Amazon. If you hate it, email me at info@julianshapiro.com and tell me exactly why. I'll absolutely respond, and I'll see if I can point you toward other resources.

Julian

**Comment by ibrierley** [comment]
Out of interest, I note its £21 ($31) n the UK for the Kindle edition. Thought it would be cheaper than the US. Is it actually still $15 in the US ? Feels quite a lot for a kindle book, as much as I'd like to read it.

**Comment by julianshapiro** [comment]
Dang, that is expensive. That irks me. Yes, it's actually $15.50 in the US. You can also buy it on the publisher's site, which may work out better in terms of currency conversion: www.peachpit.com/store/web-animation-using-javascript-develop-design-9780134096667

Thanks for asking, and for considering purchasing the book.

**Comment by tommiehansen** [comment]
It's $19 at Amazon and $22.39 (eBook) or $27.99 (book) at publisher site from Sweden. Currency conversion from hell? :)

**Comment by julianshapiro** [comment]
Yeah, sounds like it. It's pretty expensive in Canada too :(

**Comment by netaisllc** [comment]
So **fx** might actually mean foreign-exchange in this context?  :)

**Comment by julianshapiro** [comment]
haha :-D
