### ISSUE TITLE
[Branding, Reach, Not-A-Bug] Please consider being a guest and tell your story

### ISSUE THREAD

**Issue by netaisllc** [julianshapiro/velocity#473]
I suggested the guys on The ChangeLog podcast talk to you, now that the book is out. Please consider their invite should it indeed come. (Full disclosure: I'm involved with the podcast only as a listener/community member, and a consumer of VelocityJS.)

------
![3-20-2015 2-56-46 pm](https://cloud.githubusercontent.com/assets/1242423/6761548/b626e60c-cf11-11e4-9775-9f48d108095c.jpg)

**Comment by julianshapiro** [comment]
Thanks a lot, Kevin. That's super thoughtful of you. I'd be interested in chatting with them if they feel like reaching out. Again, tremendously humbled by your interest and energy here. Ty.
