### ISSUE TITLE
[DOC] Possibly alien text-string confuses explanation of Queue feature

### ISSUE THREAD

**Issue by netaisllc** [julianshapiro/velocity#475]
Dunno, maybe I'm obtuse, but I can't work out how **function call">** makes sense in the paragraph. See attached image for details.

---
![selection_087](https://cloud.githubusercontent.com/assets/1242423/6767637/390260b0-cff8-11e4-8cdc-a141419f1b2e.png)

**Comment by julianshapiro** [comment]
thanks for this. this is a bug relating to the rainbow code highlighter engine. nothing i can atm without swapping in a new engine. will consider it in the near future :)

**Comment by netaisllc** [comment]
Cool with me. Thanks.

On Sun, Mar 22, 2015 at 1:13 PM, Julian Shapiro <notifications@github.com>
wrote:

> Closed #475 <https://github.com/julianshapiro/velocity/issues/475>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/julianshapiro/velocity/issues/475#event-261706106>.
>



-- 
*Kevin McGee*
415.886.7090 (*office*)
415-990-7169 (*mobile*)

/ Web application UI/UX
/ Technical writing
/ Project management

*Netais LLC - "Let's be clear"*

** Sending me a file?  *
   Just pop 'em into this free, secure webspace.
   No limits, and I'll receive them in no time at all.
   https://www.hightail.com/u/KevinMcGee363880
<http://dropbox.yousendit.com/KevinMcGee363880>
