### ISSUE TITLE
curved trajectory

### ISSUE THREAD

**Issue by oallouch** [julianshapiro/velocity#476]
Hi,
I'd like to a animation that doesn't follow a line, like in http://www.google.com/design/spec/animation/meaningful-transitions.html#meaningful-transitions-consistent-choreography
(see the Consistent choreography paths)

What do you suggest ?

Thx a lot in advance,

Olivier Allouch
www.illicotravel.com

**Comment by ydaniv** [comment]
I believe there's already an open issue on this subject.

**Comment by oallouch** [comment]
I couldn't find it.

**Comment by ydaniv** [comment]
No, sorry, there isn't.

**Comment by oallouch** [comment]
ein baya
The movement so so fast, maybe I could do 3 fast linear translations.

**Comment by ydaniv** [comment]
Basically this should be as simple as playing simultaneously with `translateX` and `translateY` with different `easing`s and `duration`s per different values.
At least, for the example you've provided.

IMHO, it's not necessary to implement a full blown feature for this ATM, unless as a separate plugin.

**Comment by oallouch** [comment]
I thought about this, but my mind was stuck on CSS mode where everything is mixed.
Thx a lot ! I'll try that.

**Comment by ydaniv** [comment]
np
