### ISSUE TITLE
Wordpress problems

### ISSUE THREAD

**Issue by vectorscripts** [julianshapiro/velocity#480]
I am trying to load this demo http://julian.com/research/velocity/demo.html into my WP website.  However I seem to be having problems loading velocity.min.js.  I am receiving this error from the console "Uncaught TypeError: undefined is not a function” even with this simple code below.

<script src="./wp-content/themes/Divi/js/velocity.min.js"></script>

<div>
    I am a teapot.
</div>
<script>
/* You have access to Velocity, Velocity UI, and jQuery. */

$("div").velocity();
</script>

I also tried using enqueue with velocity.min.js, I even tried putting the entire velocity.min.js script inside script tags in the page.

Real simple problem I’m sure any idea how much it will cost me to get help on this?

**Comment by ydaniv** [comment]
What other scripts you have there? Sounds like either a collision of namespaces, or perhaps your DOM isn't ready. Have you tried debugging?

**Comment by vectorscripts** [comment]
admin_post_settings.js
advanced_options.js
custom.js
html5.js
imagesloaded.js
jquery.easypiechart.js
jquery.fitvids.js
jquery.hashchange.js
jquery.magnific-popup.js
jquery.magnific-popup.min.js
list.txt
masonry.js
smoothscroll.js
theme-customizer.js
velocity.min.js
waypoints.min.js

i will take a closer look at the debugger now.

**Comment by vectorscripts** [comment]
i removed all of the extra js files except the ones included in the wordpress core. still no luck.

**Comment by ydaniv** [comment]
Can I haz a link?

**Comment by vectorscripts** [comment]
sry local development I will try to upload it soon.

**Comment by ydaniv** [comment]
Well, then just put a breakpoint where this is failing and see what's colliding there.
Doesn't seem like a Veloctiy issue, so better close and move it to SO.

If you *DO* find this error to be some fault of Velocity do tell.

**Comment by vectorscripts** [comment]
alright

**Comment by Oliboy50** [comment]
I think ydaniv is right when he talks about conflicts with other libs.

I'm not sure if that could help you but here is what I always do when I start a Wordpress site:

    function dequeue_then_requeue_my_jquery() {
        if (!is_admin()) {
            wp_dequeue_script('jquery');
            wp_deregister_script('jquery');

            wp_register_script('jquery', '/js/path-to/jquery.min.js', array());
            wp_enqueue_script('jquery');

            wp_register_script('velocity', '/js/path-to/velocity.min.js', array('jquery'));
            wp_enqueue_script('velocity');
        }
    }
    add_action('wp_enqueue_scripts', 'dequeue_then_requeue_my_jquery', 20);

Because I already had problems with default jQuery from WP.

**Comment by vectorscripts** [comment]
thanks I will give that a try

**Comment by vectorscripts** [comment]
You can see the problem here http://www.vectorscripts.com/ it is as bare bones as it gets.  Just see the console.

The code i'm using is from here http://jsfiddle.net/ozgrozer/7AuQM/light/

$jQuery=$("#jQuery");
$velocity=$("#velocity");

$jQuery
	.animate({top:"60%"},{duration:1000})
	.animate({top:"0"},{duration:2000});

$velocity
	.velocity({top:"60%"},{duration:1000})
	.velocity("reverse",2000);

**Comment by ydaniv** [comment]
Just use jQuery instead of $. Please use the debugger, it will save you a
lot of time.
