### ISSUE TITLE
Slide and scroll

### ISSUE THREAD

**Issue by dfcarpenter** [julianshapiro/velocity#481]
So I have some text on a page that is hidden and when I click a button the text is revealed with a "transition.slideDownIn' and when a button is clicked the text is hidden again using a "transition.slideDownOut". The problem is that the reader is left further down the page and I want them to be brought pack up to the parent div of the text which is slid down/up, ideally animated simultaneously with the slideDownOut. I have tried several different things (queues, etc) but I can't seem to figure out what I am doing wrong. Am I approaching to problem incorrectly or misusing the functions?

Below is my most recent attempt.

```javascript
   $read_close.velocity('transition.slideDownOut', 1000, function() {
         $('#services').velocity("scroll", {duration:1000, easing: "spring"} );
    });
```

**Comment by ydaniv** [comment]
This is a question for SO, not really a Velocity issue [:

**Comment by dfcarpenter** [comment]
You're right. Thanks.
