### ISSUE TITLE
height and width animation with "box-sizing: border-box" faulty in IE

### ISSUE THREAD

**Issue by Ceremony64** [julianshapiro/velocity#482]
When animating the dimensions of an element that has box-sizing set to border-box, the animation in IE jumps in the beginning, as it does not consider the element's dimension to include both padding and border when calculating the initial dimensions for the transformation.

Works fine in Firefox, but not in IE. jQuery.animate() is not affected in either browser.

Testcase: http://jsfiddle.net/2pkhwxfb/ (click in the result panel for the animation)

**Comment by julianshapiro** [comment]
Thanks. Will ensure this is addressed.

**Comment by paulfalgout** [comment]
ping

**Comment by Rycochet** [comment]
Hopefully things will start getting updated soon - just waiting for the new code layout to get in :-)

**Comment by Rycochet** [comment]
You can use innerWidth / outerWidth etc now (working branch, not released) to force things to be correct. The IE issue is separate and still open however.
