### ISSUE TITLE
Infinite looping never truly stops and can leave cpu at 100%

### ISSUE THREAD

**Issue by jscheel** [julianshapiro/velocity#484]
When stopping or finishing an infinite loop, the velocity-animating class is never removed, and the value is actually still being updated, even though it never changes. If you leave the page alone long enough, it will result in 100% cpu usage. Did a cpu profile and saw that it was continuously trying to update the property, even though it wasn't animating. Here's a fiddle to play with.

https://jsfiddle.net/jscheel/faez8ruv/

**Comment by jscheel** [comment]
Also, it's interesting that infinite looping always animates forward, but numbered looping reverses the values each loop. Would love a way for that not to happen.

**Comment by ydaniv** [comment]
Regarding the issue, that looks alarming, needs checking.

As for the forward/reverse comment, since you used `rotate` for this example, this property specifically, and a few others, are continuously looped forward. All other properties and numbered loops always alternate direction.

**Comment by julianshapiro** [comment]
Will fix this upon upcoming release.
