### ISSUE TITLE
How to get current state of animation

### ISSUE THREAD

**Issue by bobiblazeski** [julianshapiro/velocity#489]
I want to stop the animation and resume or switch to another one with the same element. Is there a way to get state of animation (like percentage of completion)  in order to avoid my own bookkeeping?

**Comment by ydaniv** [comment]
There's nothing OOTB now, besides stopping and finishing a stopped animation.

**Comment by julianshapiro** [comment]
No plans to do this atm, but might change if I implement timeline control. Stay tuned!
