### ISSUE TITLE
fadeIn and fadeOut quirks

### ISSUE THREAD

**Issue by ccorcos** [julianshapiro/velocity#491]
I noticed some interesting quirks today:

1. When I use transition.fadeOut, the element display is set to none when complete. This creates an undesirable hiccup in the animation. Thus I'm simply using `{opacity: [0,1]}` instead. I'm not sure why this is happening but it looks like it might have to do with [this](https://github.com/julianshapiro/velocity/blob/master/velocity.ui.js#L171).

[Here's a demo for 1](http://codepen.io/ccorcos/pen/JoQPLw).

2. If I want to insert an element an animate the opacity as it enters, if I simply use `{opacity: [1,0]}`, then the element flashes for a moment (not on Chrome, but it does with Safari and Firefox). However, if I use transition.fadeIn, then theres no flash, but I also get the undesired side-effect of `display: block;`.

[Here's a demo for 2](http://codepen.io/ccorcos/pen/WbqeYO)

**Comment by ccorcos** [comment]
just read this

> Elements automatically switch to display: block/inline when transitioning in, and back to display: none after transitioning out. (To prevent this behavior, pass display: null as an option into the UI Pack call.)

**Comment by ccorcos** [comment]
That fixed everything...

Very odd default functionality, no?

**Comment by MattyBalaam** [comment]
It’s (rightly or wrongly) the default jQuery animate pattern, so is duplicating this to keep with the consensus convention.

**Comment by ccorcos** [comment]
I see. weird... Well at least its working for me :)
