### ISSUE TITLE
"finish" a "loop:true" animation

### ISSUE THREAD

**Issue by Rycochet** [julianshapiro/velocity#495]
If you try to call `.velocity("finish")` on an element with `loop:true` then the animation goes somewhat strange.

A better solution would be either cancel it properly (ie, change the loop option to 0 and let it finish the current iteration) or ignore them entirely (hopefully not).

My current use has a looped hover animation that I want to cleanly finish (and call a `complete` on) when the mouse moves away or when triggered by something else, it's not hard to work around this - but the code doesn't look as neat as it could ;-)

**Comment by danyj** [comment]
:100:   same here #586
