### ISSUE TITLE
npm module without jQuery dependency

### ISSUE THREAD

**Issue by freeqaz** [julianshapiro/velocity#497]
Now that velocity doesn't require jQuery, it would be awesome to remove the dependency from the `package.json`.

I'm using React and I don't need jQuery for my app as I can call `React.findDOMNode(element)`. It's not possible for me to grab a version for Browserify that doesn't include jQuery with the current npm module.

https://www.npmjs.com/package/velocity-animate

Thanks!

**Comment by freeqaz** [comment]
Open to having 2 npm packages to retain compatibility with anybody's existing codebase. But that's what semver is for!

**Comment by gonsfx** [comment]
I'd also like to see the dependency removed if it's no longer one.

**Comment by silvenon** [comment]
That's what's been bumping my file size by 500 kB!

**Comment by igl** [comment]
+1

**Comment by kenwheeler** [comment]
On it

**Comment by rtsao** [comment]
Great! This would be awesome, especially in conjunction with https://github.com/twitter-fabric/velocity-react (which has a `velocity-animate` npm dependency)

**Comment by davidspiess** [comment]
Really looking forward to this! Besides that, any reasons why Velocity gets registered as global variable when i require it?

**Comment by jalooc** [comment]
+1

Package explicitly claiming not being dependend on jQuery has jQuery as the only dependency on npm :) Would be better without it.

**Comment by rtsao** [comment]
This is closed by: https://github.com/julianshapiro/velocity/commit/927b7313e2c34a3fe7b2a65553aa9e3c70dfcd55

**Comment by leader22** [comment]
Hi.
It seems 927b731 is merged into `master` as v`1.3.1`.
But in npm, latest version is still v`1.2.3`.

Could you please publish latest version to npm by `npm publish`?
