### ISSUE TITLE
Release 1.2.2 incorrectly titled as 1.2.1

### ISSUE THREAD

**Issue by aristidesfl** [julianshapiro/velocity#499]
[![screenshot](http://i.imgur.com/cLeybjK.png)](https://github.com/julianshapiro/velocity/releases/tag/1.2.2)
https://github.com/julianshapiro/velocity/releases/tag/1.2.2

**Comment by julianshapiro** [comment]
fixed. ty :)

**Comment by aristidesfl** [comment]
Do you even sleep? :+1:
