### ISSUE TITLE
Help Wanted: Shims for jQuery independence and Zepto support

### ISSUE THREAD

**Issue by julianshapiro** [julianshapiro/velocity#5]
These jQuery functions need to be stripped out into their own Velocity add-on -- preferably all encapsulated under a new prefix to indicate their connection, but also their differentiation, from their jQuery counterparts: 

$.extend()
$.data()
$.queue()
$.dequeue() 
$.offset()
$.isPlainObject()
$.isEmptyObject()

The goal would be to separate out these shims into an independent file to be optionally loaded alongside Velocity in production.

If anyone's willing to tackle this, feel free to reach out to me about it. For now, my personal focus is on addressing any bugs that arise so I can ensure Velocity is a reliable long-term replacement for jQuery's $.animate().

**Comment by SiteSplat** [comment]
Just double checking on this, is jquery out of the plugin for good?

**Comment by ydaniv** [comment]
yep
