### ISSUE TITLE
Animate window.scrollBy()

### ISSUE THREAD

**Issue by aristidesfl** [julianshapiro/velocity#500]
Is there a shortcut to scroll the page relative to the current page scroll position, like with `window.scrollBy()`?
I was hoping something like `$('html').velocity('scroll', {offset: +=100px})`, but it is not documented.

**Comment by Rycochet** [comment]
http://julian.com/research/velocity/#propertiesMap - then read the "Values" subsection.

If passing "+100px" doesn't work then it'd be a bug, otherwise this is a stackoverflow support question...

**Comment by aristidesfl** [comment]
What is not documented is how to animate scroll relative to the current position, instead of a specific element. There are a few examples but not this one – http://julian.com/research/velocity/#scroll
The "+=100px" feature is known and documented, but it doesn't work in this case: http://jsbin.com/kixibotiju/2/

**Comment by Rycochet** [comment]
Sounds like a bug report then ;-)

**Comment by ydaniv** [comment]
@aristidesfl this is not implemented. You could ask this as an enhancement, however, simply checking current scroll position and adding that offset to the result will get you there.

**Comment by aristidesfl** [comment]
@ydaniv thank you, doing everything manually is always an option. 
Having an abstraction to achieve animated window.scrollBy() would be convenient though.
jQuery supports this feature with `$('html').animate({scrollTop: '+=700'})`

**Comment by ydaniv** [comment]
@aristidesfl actually, you're right, since we're wrapping the DOM API, wrapping `window.scrollBy()` *would* be nice.

**Comment by paulpflug** [comment]
snippet:
```js
body = document.body
docEl = document.documentElement
scrollTop = window.pageYOffset || docEl.scrollTop || body.scrollTop
scrollTop += scrollby
Velocity(docEl, "scroll", {offset:scrollTop})
```

**Comment by Rycochet** [comment]
Scrolling is being completely rewritten in v2 (develop branch), so closing.
