### ISSUE TITLE
Open VMD Overlay outside parent div?

### ISSUE THREAD

**Issue by ajhalls** [julianshapiro/velocity#502]
I am trying to use the VMD (which is awesome) to animate elements on my page that are draggable. Problem is that when the overlay is added, it is a child element of the draggable div which will not allow me to type into the input fields, or move sliders as all of that is considered to be a handle of the parent div. Is there a way to attach it to the right side of the element, or outside?

I can make the modal window draggable with only the title being the handle with this:
VMD.js line 5526:
        o.css({
            position: "absolute",
            left: "50%",
            marginLeft: "-6rem",
            width: "300px",
            minHeight: "150px",
            backgroundColor: "white",
            borderRadius: "3px",
            boxShadow: "0px 0px 3px 0px rgba(50, 50, 65, 0.5)",
            padding: "0.6rem 0.5rem 0.5rem 0.5rem",
            opacity: "0.975"
        }).addClass("draggableModal");

then later:
    $(".draggableModal").draggable({handle:"div"});

But as long as it is a child of a draggable element, I can't input anything.

**Comment by ajhalls** [comment]
I made some progress, but the designer clears the style info of the target when it applies the effects, and when you hover over the element you previously clicked on, the modal doesn't appear, you have to go to the target div. Also if you click again, it adds another instance of the modal.

http://jsfiddle.net/moLxhod3/

**Comment by demetriusnunes** [comment]
+1

**Comment by Rycochet** [comment]
Sounds like a StackOverflow question (if still relevant) - but I'd look at classes and z-index / transform to see if something is messing with the display context.
