### ISSUE TITLE
duration has no effect for animations

### ISSUE THREAD

**Issue by dcsan** [julianshapiro/velocity#505]
I'm using  ` $.Velocity.RunSequence(introAnim) ` but the `duration` param seems to have no effect.

Am I using the syntax wrong? I removed all other params in case `delay: x` was somehow interfering.

all the effects below seem to take place in 500ms (eyeballing), so it seems some default value is overriding.

additionally, the delay option doesn't seem to work at the beginning of a sequence, but does nearer to the end.

```
  curtain = document.getElementById("curtain")
  coverTall = document.getElementById("coverTall")
  bgImage = document.getElementById("bgImage")
  title = document.getElementById("title")
  mainImage = document.getElementById("mainImage")
  inset1 = document.getElementById("inset1")
  bottomBar = document.getElementById("bottomBar")

  b1 = 1000

  introAnim = [
    # { e: coverTall, p: { opacity: 1 }, o: {duration: 1, delay: 5000} }
    { e: bgImage, p: { opacity: 1 }, o: {duration: 5000} }
    { e: curtain, p: { width: 0 }, o: {duration: 10000} }
    { e: title, p: { opacity: 1 }, o: {duration: 500} }
    { e: inset1, p: { opacity: 1 }, o: {duration: 2000} }
    { e: mainImage, p: { opacity: 1 }, o: {duration: 50} }
    { e: bottomBar, p: { opacity: 1 }, o: {duration: 5000, delay: 500} }
  ]
  
  console.log("running anim", introAnim)
  $.Velocity.RunSequence(introAnim)

```

**Comment by julianshapiro** [comment]
are you running latest versions from github?

**Comment by dcsan** [comment]
I'm running what looks like an official meteor package:

    velocityjs:velocityjs

**Comment by dcsan** [comment]
```
$.Velocity.version
Object {major: 1, minor: 2, patch: 1}
```

**Comment by julianshapiro** [comment]
you'll want to update both velocity and its ui pack. those are old versions.

i see the link for the meteor package. i don't maintain that; i'm not sure how they'll pulling from github, but they're pulling an old version. very confusing.

apparently this is popular on meteor: https://atmospherejs.com/percolate/velocityjs. would you mind trying that?

**Comment by julianshapiro** [comment]
hmm i think it's because of the way i updated tags on github a short while back. for now, just replace your velocity downloads with ones from github then on the next release (later this month), i'll make sure release tags are synced! 

thanks a bunch :)
