### ISSUE TITLE
IE 8, filter attribute isn't persisted

### ISSUE THREAD

**Issue by msurguy** [julianshapiro/velocity#506]
It appears that velocity is not keeping track of existing 'filter:' attributes that are on the object and instead is overwriting them with a single 'filter' (in case of opacity). According to MS specs, there could be multiple filters applied simultaneously by separating them with a space: https://msdn.microsoft.com/en-us/library/ms532847(v=vs.85).aspx. It would be nice if Velocity would keep existing filters such as blur intact and only add additional filters (opacity) separated by a space.

Here is a demo that doesn't work properly in IE8 because of this bug:
http://codepen.io/msurguy/pen/pJjdrz

**Comment by ydaniv** [comment]
Thanks @msurguy. @julianshapiro needs considering if this doesn't require DOM reading and is worth the overhead.

**Comment by Rycochet** [comment]
IE8 is no longer supported in v2 - there will be a legacy layer at some point, but how this is dealt with is now totally different.
