### ISSUE TITLE
can you use UI pack effects with RunSequence?

### ISSUE THREAD

**Issue by dcsan** [julianshapiro/velocity#507]
rather than just animating basic properties is there a way to combine UIpack effects in a sequence?

```
  curtain = document.getElementById("curtain")
  coverTall = document.getElementById("coverTall")

  introAnim = [
    { e: coverTall, p: { opacity: 1 }, o: {duration: 100} }
    { e: curtain, p: { width: 1 }, o: {duration: (2*step)} }
  ]

  $.Velocity.RunSequence(introAnim)
```

**Comment by dcsan** [comment]
also related question, using the browser selectors seems a bit of a wordy approach here

```
  elem = document.getElementById("curtain")
  introAnim = [
    { e: elem

```

i read this is to avoid jquery pinging the dom, is that correct or is there a shorter hand syntax?

**Comment by ydaniv** [comment]
Your questions aren't clear.

In the 1st q you asked about effects but show animating props in the example. You can replace the prop objects with names of effects (strings) and it will work.

As for the 2nd q, it's not clear what you wanted to write there.

**Comment by dcsan** [comment]
thanks on (1)

for (2) i was asking if there is a shorter syntax
eg passing in just an element ID to the `e:` property or a JQ selector. I think not but checking my understanding of the docs.

**Comment by ydaniv** [comment]
nope
בתאריך 11 במאי 2015 01:53,‏ "dc" <notifications@github.com> כתב:
