### ISSUE TITLE
Debug Mode - slowed animations

### ISSUE THREAD

**Issue by bzmwillemsen** [julianshapiro/velocity#508]
We've been using Velocity for a bit now and whenever we're doing testing we manually set our animation durations to 10000ms so that we can better see how the elements are interacting.

I see that there is a debug mode that post info to the console. Thoughts on increasing all animations to 10000ms when debug mode is on?

**Comment by ydaniv** [comment]
See [mock option](http://julian.com/research/velocity/#mock).

**Comment by bzmwillemsen** [comment]
Thanks @ydaniv !
