### ISSUE TITLE
Got issues with "smartresize" or "debouncedresize" and velocity.js

### ISSUE THREAD

**Issue by albi** [julianshapiro/velocity#509]
Hi there,

seems that velocity.js got problems with the two scripts

https://github.com/louisremi/jquery-smartresize and http://www.paulirish.com/2009/throttled-smartresize-jquery-event-handler/

If I combine velocity and one of these scripts at my site, it seems to break things like $(window).on('debouncedresize',function(){}); They won't execute.

I can provide a working ("broken") example for you.

Kind regards
Alex

**Comment by ydaniv** [comment]
give us an example
בתאריך 12 במאי 2015 18:29,‏ "Alexander Albrecht" <notifications@github.com>
כתב:

**Comment by albi** [comment]
Got a reduced testcase. Seems the issue is another one.
