### ISSUE TITLE
Velocity.hook for borderColor returning incorrect result

### ISSUE THREAD

**Issue by simonlast** [julianshapiro/velocity#511]
Calling `Velocity.hook(el, "borderColor", "#00ff00")` does not set the border color and returns `["borderColor", "rgba(#00ff00)"]`.

JSBin: http://jsbin.com/pekumugowo/1/edit?html,console,output

**Comment by ydaniv** [comment]
Thanks @simonlast!
@julianshapiro needs fixing

**Comment by Rycochet** [comment]
In v2 the calling has changed, and colours are only changed to `rgba()` when animating -

```
Velocity(el, "style", "borderColor", "#00ff00");
Velocity(el, "style", "borderColor"); // => "#00ff00"
```
