### ISSUE TITLE
Add StackOverflow link to CONTRIBUTING.md

### ISSUE THREAD

**Issue by Rycochet** [julianshapiro/velocity#514]
Just mentioned in #510 - there's no link to SO, so people are coming on here asking questions and getting redirected because it's not bug/feature/idea related.

**Comment by ydaniv** [comment]
:+1:

**Comment by julianshapiro** [comment]
I agree. How would you guys like to word it?

**Comment by ydaniv** [comment]
**Qestions? Problems?**

Ask on [StackOverflow with `velocity.js` tag](http://stackoverflow.com/tags/velocity.js).

**Comment by Rycochet** [comment]
**Found a Possible Bug**

Report it as an issue on here.

**Questions or Problems?**

Ask on [StackOverflow](http://stackoverflow.com/tags/velocity.js) (make sure you add the ```velocity.js``` and ```javascript``` tags).

**Comment by julianshapiro** [comment]
Thanks, guys! Adding this now.
