### ISSUE TITLE
do some options disable hardware acceleration?

### ISSUE THREAD

**Issue by dcsan** [julianshapiro/velocity#516]
I'm trying some animations using `top` and `left` properties and getting *very* chunky animations.
just animating three divs positions on a page for a background animation. 

is there some catch to not using certain property names?
I also tried using transformX and Y but get similar results.

code below

```
animateDiv = (el) ->
  size = Math.round Math.random()*300

  newq = makeNewPosition(el,size)
  oldq = $(el).offset()
  
  distance = Math.sqrt((oldq.top - newq.top) * (oldq.top - newq.top) + (oldq.left - newq.left) * (oldq.left - newq.left))
  distance = Math.round distance
  
  duration = distance*10
  color = rgb2hex makeNewColor()

  $(el).velocity(
    {
      top: newq.top
      left: newq.left
      # translateY: newq.top
      # translateX: newq.left
      # backgroundColor: color
      # height:size
      # width:size
    },
    duration: duration
    easing: "easeinout"
    complete: ->
      console.log("new anim")
      animateDiv(el);
  );
```

**Comment by ydaniv** [comment]
Sorry, @dcsan your questions are not issues of Velocity, but rather questions for StackOverflow. Please close all your issues here and open questions on SO with the `#velocity.js` tag.
