### ISSUE TITLE
Can velocity work together with virtual-dom?

### ISSUE THREAD

**Issue by ArnoBuschmann** [julianshapiro/velocity#517]
As for what I can see, Velocity works well without jQuery which is neat and I wonder, if it would be possible to connect Velocity to a virtual-dom instead of the real dom.

So would it be possible to run Velocity together with https://github.com/Matt-Esch/virtual-dom anyhow?

Vrtual-dom itself is able to render svg elements, so that might be a starting point to get it handled?

**Comment by ydaniv** [comment]
Velocity is for animation. Why would you want to animate JS objects?

**Comment by ArnoBuschmann** [comment]
@ydaniv Yes, Velocity ist for animation and virtual-dom is an alternative to the real dom for rendering dom elements. So I want is to animate dom elements via virtual-dom with velocity. But as velocity is acting on the real dom, I'm afraid it will not working that way.

**Comment by ydaniv** [comment]
"Virtual DOM" is JS objects that represent a real DOM structure in memory. It's an optimization for rendering and manipulating DOM.
After you render an element, you can animate it, not before.

**Comment by ArnoBuschmann** [comment]
Ah ok, then I'll try it later today. I just got confused by this statement:
>
 "I wanted to re-use Velocity directly, but Velocity works directly on the real DOM, which I wanted to avoid. So I had to port the good ideas of Velocity into React virtual DOM, and make sure performance or usability wouldn't be lost in the process"

Comes from -> https://github.com/elierotenberg/react-styling-demo

**Comment by ydaniv** [comment]
Thanks for the link! I really think this guy got it backwards :(

**Comment by ArnoBuschmann** [comment]
Here we have further discussions with the topic
>
"How would one do animations using virtual-dom?"

-> https://github.com/Matt-Esch/virtual-dom/issues/112

As I haven't used Velocity yet, I'll have to stick my head deeper into it and see ;)

**Comment by Rycochet** [comment]
Feel free to re-open if you have any further info on this - if it doesn't work then a jsfiddle would be appreciated as I don't see any reason why not.
