### ISSUE TITLE
RunSequence when using Browserify

### ISSUE THREAD

**Issue by brandondurham** [julianshapiro/velocity#518]
Getting an error when trying to use RunSequence (AWESOME!!!) in a Browserify module:

```js
var Velocity = require('Velocity-animate');
var openBlogPost = [
	{ e: $('body'), p: 'scroll', o: { duration: 100, duration: 500, easing: 'easeInOutQuart', } },
	{ e: _this.$el, p: 'fadeIn', o: { duration: 200 } }
];
$.Velocity.RunSequence(openBlogPost);
```

The error:

```
Uncaught TypeError: $.Velocity.RunSequence is not a function
```

Any suggestions? I know it's something I'm doing wrong with my require…

**Comment by ydaniv** [comment]
@brandondurham could you reproduce this in a jsFiddle? But I believe it's not an issue with Velocity, so better to ask on SO.

**Comment by brandondurham** [comment]
Sure thing. Gimme a bit…

**Comment by brandondurham** [comment]
Moved the question to SO: http://stackoverflow.com/questions/30306032/how-can-i-access-velocity-runsequence-when-using-velocity-js-with-browserify

**Comment by ydaniv** [comment]
Tnx, plz close here.
