### ISSUE TITLE
Sequence running syntax with 'scroll' type animation

### ISSUE THREAD

**Issue by pruett** [julianshapiro/velocity#519]
Is it possible to use a `scroll` animation within a Velocity sequence? I'm trying something like the following without success

```js
let introAnimation = [
  { e: document.querySelector('header'), p: { height: ['100vh', '80px'] }, o: { duration: 2000 } },
  document.querySelector('section'), "scroll", { duration: 1000 },
  { e: document.querySelector('section'), p: { opacity: 1 }, o: { duration: 2000 } }
]
```

`Error: Velocity: First argument (undefined) was not a property map, a known action, or a registered redirect. Aborting.`

**Comment by ydaniv** [comment]
Could you reproduce in a jsFiddle?

**Comment by pruett** [comment]
@ydaniv http://jsfiddle.net/65xCP/119/

**Comment by ydaniv** [comment]
Nope, working: http://jsfiddle.net/ozaddhdk/1/
You have syntax error

**Comment by pruett** [comment]
indeed i do! thanks @ydaniv :palm_tree:
