### ISSUE TITLE
Velocity adds translate3d` when not necessary (only in mobile devices)

### ISSUE THREAD

**Issue by alvarotrigo** [julianshapiro/velocity#520]
[Reproduction of the issue](http://jsfiddle.net/tbpwe6ob/) (test on mobile or in Chrome Device Mode iPad, for example)

Having this animation:

```javascript
$('#beforeEmptyTruck').velocity({
    opacity: 1
}, {
    delay: 1200,
    duration: 600,
    easing: "easeOutCubic"
})
.velocity({
    left: '139px',
    top: '166px',
    delay: 600
}, 1000);
```

In the last step, when I'm changing the css property `left` and `top`, velocity is adding the following style to my element:

```css
transform: translate3d(0px, 0px, 0px)
```

This happens only when using Chrome Device Simulator or even when running it directly on my iPhone.
It doesn't do it on normal desktop browsers.

![truck](https://cloud.githubusercontent.com/assets/1706326/7724421/53349294-fee9-11e4-8372-0ee1be8b26c8.PNG)

This is overriding my `transform` property which was rotating the object and therefore whenever the animation takes place, my object loses its rotation or scale properties.

[Reproduction of the issue](http://jsfiddle.net/tbpwe6ob/) (test on mobile or in Chrome Device Mode iPad, for example)

**Comment by Rycochet** [comment]
http://julian.com/research/velocity/#mobileHA

Tell it not to ;-)

**Comment by alvarotrigo** [comment]
Do I have to tell it per object?

**Comment by ydaniv** [comment]
per `.velocity()` call

**Comment by alvarotrigo** [comment]
So, something like this:

```javascript
$('#demo').velocity({
    opacity: 1,
}, 600, 'easeOutCubic');
```

Has to become:

```javascript
$('#demo').velocity({
    opacity: 1,
}, {
    duration: 600,
    easing: 'easeOutCubic',
    mobileHA: false 
});
```

**Comment by Rycochet** [comment]
```$.Velocity.defaults.mobileHA = false;```

Unless you're using transforms on everything that's being animated that transform trick can make a significant difference to mobile devices - why it's better to only set it when needed (but the option is in there for when you know what you're doing etc) :-)

**Comment by alvarotrigo** [comment]
Thanks for the info.

**Comment by zonakusu** [comment]
Isn't it better to make it false by default? This causes for flashy animation for many, and it isn't that easy to find. 

Or maybe change it to a will-change?
