### ISSUE TITLE
cssHooks equivalent in velocityjs? 

### ISSUE THREAD

**Issue by onnerby** [julianshapiro/velocity#521]
Is it possible to extend velocity on your own in the same way that jquery does with cssHooks?

I know there is the `progress` to manipulate during animations, but it would be nice for the community to be able to extend velocity with new styles.
For instance I would like to implement a `glow`-style with extra `glowColor`, `glowRadius` or something similar that probably translates to a `filter:drop-shadow....` in the end.

**Comment by ydaniv** [comment]
Nothing easy OOTB now. It will need some tweaking to allow an easy API for adding hooks.

**Comment by Rycochet** [comment]
In v2 (develop branch) there's a new ```"registerAction"``` method, documentation to follow. This allows you to register a function against a property. The first argument to this function must be a single element, the second argument  is either ```undefined``` - to get the value, or a string value - to set it.

Internally this is now used for properties such as ```display``` (to support the ```"auto"``` value) and scroll (when added).
