### ISSUE TITLE
Dynamically Added DOM elements

### ISSUE THREAD

**Issue by migreva** [julianshapiro/velocity#522]
I'm using Velocity + React to render some DOM elements and animate them from time to time. I'm not using jQuery for this project so using $.velocity() is out of the question.

I have two Codepens that depict the problem I'm having

* [Working codepen](http://codepen.io/migreva/pen/rVMpYV)
* [Not working codepen](http://codepen.io/migreva/pen/qdapbZ)

They do functionally the same thing, the difference is that the [not working codepen](http://codepen.io/migreva/pen/qdapbZ) dynamically adds the DOM elements that Velocity animates.

It seems like Velocity is having trouble animating the objects that are dynamically rendered - except for the final-rendered element. I can't quite figure out why, any thoughts? Is there something fundamentally wrong with the way I'm using Velocity and dynamically rendering the HTML?

I notice that the velocity-animating class is present on the improperly-functioning DOM elements, so it looks like Velocity tried to animate it at some point and failed in the process. I can't quite pinpoint where that is.

**Comment by ydaniv** [comment]
Sorry, this is not a Velocity issue. Please open on SO.

**Comment by migreva** [comment]
You're right. The problem was my lack of vanilla JavaScript knowledge. My apologies

http://stackoverflow.com/questions/30397261/velocity-js-and-dynamically-added-dom-elements/30398083#30398083
