### ISSUE TITLE
Weird bug related to orientation change (broken current x position?)

### ISSUE THREAD

**Issue by thehappycoder** [julianshapiro/velocity#524]
I wasn't able to isolate the problem so here is a real-world example.

Bug:
1. Go to http://happycoders.xf.ee using mobile device like ipad/iphone/android phone (at least all listed have this problem) in landscape mode.
2. Click any row at the middle of the row and right column will appear with animation.
3. Rotate the device
4. Click the X icon. Underneath the hood this is what is done: $('.side_view').velocity({translateX: 0}, 600)
5. Weird animation.

No bug:
1. Same as above but in portrait mode
2. Click any row at the middle of the row and side column will appear with animation.
3. Click the X icon. It is supposed to animate nicely. Underneath the hood the same code is run.
4. Nice animation.

The same problem is happening with different elements on the page after rotation. I tried to do animation using jquery.transit and there were no problems. Therefore, I assumed that velocity has a bug.

There is some hardcore CSS and javascript going on on rotation.

I also tested this using browser console by connecting devices via USB. There were nothing in CSS that could cause this.

**Comment by Rycochet** [comment]
Not sure what's going on however I did see you are using a viewport meta - this needs to be moved near (or at) the top of the head - can't remember where I read about that, but it seemed important at the time - might be worth looking into that meta element a little more too ;-)

**Comment by thehappycoder** [comment]
Thanks! I will move it to the top inside <head>.

It didn't help with the problem though :)

**Comment by thehappycoder** [comment]
It seems because I do this on device orientation change:
```
$('.side_view').css('transform', "translateX(-100%)")
```

When I do like this, then animation works. Some app logic doesn't work though but I will find out.
```
sideView.velocity({translateX: '-100%'}, 0)
```

**Comment by ydaniv** [comment]
what you need is force-feeding. See the docs.
בתאריך 27 במאי 2015 17:09,‏ "thehappycoder" <notifications@github.com> כתב:
