### ISSUE TITLE
Animation complete error

### ISSUE THREAD

**Issue by ccorcos** [julianshapiro/velocity#526]
I'm getting some errors in the complete callbacks to my animations and it simply reads:

`velocity.min.js:3 Uncaught TypeError: Spinner is not a function`

It would be great if I could get a stack trace. I honestly have very little idea how error handling works, but it would be nice if I could get a line number or something that traces back to my code.

**Comment by ydaniv** [comment]
This is not a Velocity issue. The error is coming from your code.
If you want to develop, use a version that's not minified and open dev tools. For more help please ask on SO.

**Comment by ccorcos** [comment]
Yes, definitely my code, but where?  -- you're saying that if I dont use the min.js file, I'll see more information?
