### ISSUE TITLE
Forced synchronous layout

### ISSUE THREAD

**Issue by Webysther** [julianshapiro/velocity#532]
In Chrome Devtools i receive warning: "Forced synchronous layout is a possible performance bottleneck." in this line:

https://github.com/julianshapiro/velocity/blob/master/velocity.js#L660

**Comment by ydaniv** [comment]
Thanks, but this is done once, when the code is loaded in the browser.

**Comment by julianshapiro** [comment]
Indeed. Thanks, Webysther :)
