### ISSUE TITLE
Issue with stopping animations

### ISSUE THREAD

**Issue by vanils** [julianshapiro/velocity#535]
For some reason stopping animation on element sometimes stops future animations too. I don't know if I'm doing something wrong.

Demo here: http://jsfiddle.net/6gvdqhaz/2/

Here's how to reproduce this issue:

``` javascript

var content = $('#my-element');

content.velocity({
    opacity: 0
}, {
    complete: function () {
        content.velocity('stop');
        content.velocity({
            opacity: 1
        });
    }
});
```

Content is animated out as it should, but it never animates opacity to 1.

**Comment by ydaniv** [comment]
That does look inappropriate. @julianshapiro :calling:

**Comment by pcole** [comment]
I'm having the same issue. It looks like the stop is async so if you try and start a new animation right after calling stop it won't work. It works if you start the new animation after a short timeout though: http://jsfiddle.net/vsjakyng/

``` 
var element = $("#stop-me");

element.velocity({
    opacity: 0
}, {
    complete: function () {
        element.velocity('stop');
        setTimeout(function(){
          element.velocity({
            opacity: 1
          });
        }, 1);
        
    }
});
```

**Comment by ydaniv** [comment]
Thanks @pcole! That's what I suspected.

**Comment by Rycochet** [comment]
Stop has been rewritten so this can't happen - it sets a flag for normal operation and calls the complete handler directly
