### ISSUE TITLE
$.Velocity and global Velocity

### ISSUE THREAD

**Issue by AtheistP3ace** [julianshapiro/velocity#536]
Is it possible for both of these to exist? 

I work on an application that generates websites. For the front end we use velocity for animations and do not include jQuery by default but our application allows users to include their own third party libraries which will then be included in the generated website.

The issue I have is if someone includes jQuery all the Velocity calls now expect to be called using $.Velocity which essentially breaks everything. So I am just wondering is there any specific reason why both of these functions can't exist so at least the global Velocity is always available? I can add code that would bring it up to the window object if jQuery is detected but I am not sure if it would cause issues.

**Comment by ydaniv** [comment]
What if you simply do `window.Velocity = $.Velocity`?

**Comment by AtheistP3ace** [comment]
That was my plan. Check if jquery had been loaded and assign it to the window object.  :) Was really just trying to check and make sure it wouldn't cause any issues.

**Comment by ydaniv** [comment]
No issues.
It already works with jQuery, see the docs.
If there aren't any issues using Velocity that way you can close this thread.
