### ISSUE TITLE
Trouble animating elements in that are  positioned with flexbox

### ISSUE THREAD

**Issue by Madebym** [julianshapiro/velocity#538]
Animating them out I have no trouble, but when I try to animate in flexbox positioned elements, after the animation they are wrongly placed, better to say displaced :))

Here is the link I've put a put up. Preloading screen is fine, cause I am animating out.
http://madebym.me/test/velocity-flexbox/

The three animated elements should be aligned horizontally next to each other. They don't have any flexbox properties themselves, but are nested inside flexbox containers. 

I use a simple `fadeIn` effect from UI pack. If I switch to `fadeOut`, they are positioned correctly and animate out as supposed.

Also, I tried to do a `fadeIn` on the main container, that one has flexbox properties dirrectly applied. The animation creates a total mess, all three elements are pushed to the top of the screen. 
Again, if I animate out everything is fine, with any of the premade UI pack animations.

These are all basic animations and I believe it has something to do with Flexbox, I don't see and other reason for this.

Edit: If I animate without the UI pack everything is normally fine.

**Comment by ydaniv** [comment]
Did you put `flex` in `display` option? [See here](http://julian.com/research/velocity/#displayAndVisibility)
