### ISSUE TITLE
VelocityJS Meteor package will not install in Docker within a Circle CI build

### ISSUE THREAD

**Issue by benwiley** [julianshapiro/velocity#539]
You can recreate the issue easily by SSHing into any circle ci build (that has Docker) and executing these commands.

```bash
docker run -a stdin -a stdout -a stderr -i -t ubuntu /bin/bash
apt-get install curl
curl https://install.meteor.com/ | sh
apt-get install vim
cd /home/
meteor create app
cd app/
vim .meteor/packages
```

Once in VI, append a newline with velocityjs:velocityjs. Then exit VIM and run this command to execute the installation: 

```bash
meteor update
```

You will get this error:

```bash
Error: EINVAL, chown '/tmp/<random dir>/<package you added>'
```

Running this in docker on my machine (Mac OS X) works correctly, but in CI, it always throws the error.

Questions I am trying to answer: 
- Why does it happens on a circle box, even though it's all within a docker container?
- Why do certain packages (like velocityjs:velocityjs) trigger the error? bjwiley2:server-watch does as well.

What I've tried with no success:
- Switching the directories that the meteor app is created in
- Using sudo to try and fix the chown issue
- chown nobody:nogroup /tmp
- Cloning bjwiley2:server-watch into my projects packages directory to see if it would run locally (it did)
- Installing package dependencies directly (like http and jquery) to see if one of those was the problem
- Tried to recreate problem on Ubuntu Server to see if it was working locally only because I was on OS X. It worked. the problem is still only on circle boxes.

**Comment by ydaniv** [comment]
@benwiley you should post this in the Meteor package.

**Comment by Rycochet** [comment]
Please follow up if this wasn't fixed. Velocity now has no dependencies (such as jQuery), but Meteor / Docker are pretty specialised subjects to know about.

This sort of question often works better on StackOverflow - though bugs / changes relating directly to Velocity should always end up back here :-)
