### ISSUE TITLE
Remove jquery from bower.json

### ISSUE THREAD

**Issue by mattbailey** [julianshapiro/velocity#542]
jQuery is no longer an actual dependency for Velocity anymore, right?

This is the only module left that makes me download jquery every time :)

**Comment by ydaniv** [comment]
:+1:

**Comment by albertogasparin** [comment]
:+1: +1

**Comment by klausgao** [comment]
:+1: +1

**Comment by johannesjo** [comment]
+1

**Comment by JKillian** [comment]
:+1:

**Comment by relferreira** [comment]
+1

**Comment by lennerd** [comment]
Same for the `package.json`. 👍
