### ISSUE TITLE
Problem animating svg gradient 'stop' offset

### ISSUE THREAD

**Issue by Loac-fr** [julianshapiro/velocity#544]
So basically I'd like to animate the color stop offset to 'move' a Lineargradient's color around, from Velocity's docs I understand this is possible, but doesn't seem to work.

I made a quick demo here : http://codepen.io/loac-fr/pen/waPWep

```
$('#stop').velocity({
    offset       : "80%", // not working ?
    stopColor : "#00BFFF" // working
});
```

Am I doing something wrong here ?

I tried to add stuff (offset attribute/prop ?) to velocity's source (lines 1007 & 1479) just for fun but of course didn't change anything ;-)

Thanks a lot for looking at it, and thanks again for all the velocity's work :100: !

**Comment by pixeltherapy** [comment]
I'm guessing this has something to do with the fact that offset is not a CSS defined property (http://www.w3.org/TR/SVG/styling.html#SVGStylingProperties). I ran into a similar issue trying to translate with Velocity. Try as I might it was always implemented as a CSS style ```style="transform:translate(x,y)"``` rather than the SVG attribute that I wanted ```transform="translate(x,y)"```

A workaround for you is to not modify Velocity but instead use a function to set/change the attribute. Try this:

```
$('#stop').velocity({
    offset : function (newOffset) {
        $(this).attr("offset", function () {
            var newOffset=0.8;
            return newOffset;});
        }, 
    stopOpacity : "20%",
    stopColor : "#00BFFF"
});
```
A fork of your fiddle: http://codepen.io/anon/pen/bdaMLQ

Maybe there's tidier JS that someone can suggest. :o)

**Comment by Rycochet** [comment]
Following on from @pixeltherapy - I think it's because offset isn't a known property, so Velocity isn't aware it's a % value - maybe use a progress callback instead -

```javascript
$('#stop').velocity({
    stopColor: "#00BFFF"
}, {
    progress: function(elements, complete) {
        $(elements).attr("offset", complete * 100);
    }
});
```

**Comment by Loac-fr** [comment]
Thanks a lot, 
I'll try that ! still weird that Velocity is able to animate "x" or "y" attributes but not this one...
@Rycochet thanks for the tip, that's my first time posting on Github ;)

**Comment by Rycochet** [comment]
In v2 all svg attributes are now correctly identified on the correct element - so this should work correctly.

**Comment by quickstep25** [comment]
I have been struggling with a similar issue involving SVG rotate and scale on a rectangle so I went back to the basics and used the original model from [VelocityJS SVG demo](http://velocityjs.org/#svg) that was demonstrated to be working just fine:

https://codepen.io/julianshapiro/pen/wmtEH

```javascript
$("#rect")
    .delay(500)
	  .velocity({ translate: 0, x: "+=200", y: "25%" })
    .velocity({ fillGreen: 255, strokeWidth: 2 })
	  .velocity({ height: 50, width: 50 })
    .velocity({ rotateZ: 90, scaleX: 0.5 })
    .velocity("reverse", { delay: 250 });
```

Perplexed at why my code was working, I started making my model look identical to the demo and it still didn't work.  After hours of troubleshooting, I finally determined that it has to be an issue with Velocity version 2.  I forked the demo model and just changed the VelocityJS scripts that it uses to demonstrate that it does not work:

https://codepen.io/quickstep25/pen/jZpyRv

Both are identical, only the VelocityJS scripts changed.

**Comment by Rycochet** [comment]
None of the old demos are relevant as they're V1 demos - the entire old website should be ignored, and just the wiki looked at right now (until we're out of beta, at which point the "public" documentation will get updated).

Relative numbers (the `"+=200"` bit) don't work - and I just realised that they'd been copied into the wiki, so I've fixed that. They will be making a comeback before leaving beta, but not in the same form - see #843.

**Comment by quickstep25** [comment]
@Rycochet  Thanks so much for the quick reply.  That explains a lot. I'll revert back to v1 until the new and improved v2 is up and running out of beta!

**Comment by Rycochet** [comment]
You can use proper css values now if it helps - `{x: ["calc(10% + 50px)", "calc(10% + 0px)"]}`

**Comment by quickstep25** [comment]
That is an idea! 

However, `x` and `y` worked just fine in version 2. At least it does on `<line>`.  I haven't tried it on other tags as of yet.

**Comment by Rycochet** [comment]
In V2 it gets all the SVG attributes correct based on the correct type of SVG element. As far as the Transform shortcuts - they've all been removed as the premise behind them is a bit broken (loads of issues about trying to get them right) - now you just use `transform` properly, which lets you keep the correct order and get more control over them.
