### ISSUE TITLE
SlideUp / SlideDown without changing height

### ISSUE THREAD

**Issue by tassosm** [julianshapiro/velocity#547]
Hello Julian,
Thank you for this awesome plugin. 

I am trying to implement a custom transition, but I am missing something.

Here is what I want to do:

I want to register a new effect based on the "SlideUp/SlideDown" transition and instead of changing the height of the element I want to change just the position from -100% to 0.

Here is my code.

    $.Velocity.RegisterEffect("mySlideUpIn", {
        calls: [
        	[ { bottom: "-100%", opacity: 1 }, 0.01 ],
            [ { bottom: 0 }, 0.99 ]
        ]
    });

    $.Velocity.RegisterEffect("mySlideUpOut", {
        calls: [
        	[ { bottom: "-100%" }, 0.99 ],
            [ { opacity: 0 }, 0.01 ]
        ]
    });

This works for the "mySlideUpIn" but for the "mySlideUpOut" the transition is much faster. 
What am I missing?
Also is this the best approach?

Thanks in advance.

**Comment by tassosm** [comment]
I think I figured it out.


			$.Velocity.RegisterEffect("my2SlideUpIn", {
				defaultDuration: 450,
                calls: [
                    [ { translateY: "100%", opacity: 1 }, 0.05 ],
                    [ { translateY: 0 }, 0.95 ]
                ]
			});

			$.Velocity.RegisterEffect("my2SlideUpOut", {
				defaultDuration: 450,
                calls: [
                    [ { translateY: "100%" }, 0.95 ],
                    [ { opacity: 0 }, 0.05 ],
                ]
			});

What do you think?

**Comment by ydaniv** [comment]
@tassosm is there a Velocity issue? Or usage question? If the latter then you should move this question to SO (:

**Comment by tassosm** [comment]
Hello, is a usage question.

Thanks.

**Comment by ydaniv** [comment]
Then please move it to StackOverflow
