### ISSUE TITLE
scroll issue

### ISSUE THREAD

**Issue by n-for-all** [julianshapiro/velocity#548]
The code below behaves strangely

 <pre>jQuery(".scrollingdiv").velocity('scroll', { duration: 1000, axis:"x", container: jQuery(".scrollingdiv"), offset: 0}); </pre>

if you run the code above it always scrolls even if the offset is 0

On line 2536:
 <pre>scrollPositionEnd = (scrollPositionCurrent - $(element).position()[scrollDirection.toLowerCase()]) + scrollOffset; </pre>

it always adds the element position to the scrollposition which never ends, the behavior should be scroll to an offset and not with an offset, so basically if i set the offset to 0, then i will go to position 0 in the scroll, currently i am not sure how it behaves.

the fix was to replace it with 
 <pre>
scrollPositionEnd = scrollOffset; </pre>

let me know your input

**Comment by TeHMoroS** [comment]
I kinda worked my way around this issue by neutralizing the offset calculations. What I did was to take the scroll top position, make it negative and use it as an offset:

`scrollPosition = scrollContainer.scrollTop(); // I'm also using jQuery in my project
element.velocity('scroll', {
    container: scrollContainer,
    offset: -scrollPosition,
    duration: 500
});`



It made the issue go away at least. :)

**Comment by Rycochet** [comment]
Scrolling has been rewritten in V2

**Comment by 9mm** [comment]
@Rycochet so are you saying I can animate scroll using curve functions like I can with jQuery animate? I looked around how to do this and tried various approaches with V2 but couldn't get it to work.

`yard add velocity-animate@beta`...

```
import Velocity from 'velocity-animate';

Velocity(element, { scrollTop: '100px' }, { duration: 500 });
```

**Comment by Rycochet** [comment]
@9mm You need to make sure you're scrolling the element that needs it - the jQuery one (from memory) does some magic to figure out the element you mean, but this just forwards the props to the DOM - so easy to get the wrong one - check that setting the `scrollTop` on the element directly does what you want first :-)
