### ISSUE TITLE
opacity always resets to zero when passing display:"block" option

### ISSUE THREAD

**Issue by tommillard** [julianshapiro/velocity#549]
Example here: http://codepen.io/anon/pen/aOKvzJ

When display: "block" is passed to an animation it starts by resetting the opacity to zero, rather than using the current opacity value as its starting point. This can be remedied by passing element.style.opacity as the 2 value in a force-fed array but seems like a bug in its current form to me.

**Comment by ydaniv** [comment]
@julianshapiro looks valid

**Comment by Rycochet** [comment]
getComputedStyle reports opacity as 0 when an element isn't visible - can't remember where I was reading about the issue, but we need a workaround in this case.
