### ISSUE TITLE
Android scaling issue <1.0 is not in Chrome anymore

### ISSUE THREAD

**Issue by marian-r** [julianshapiro/velocity#550]
I've come across the issue causing blurred elements with initial scale <1.0 which you fixed some time ago - #59. However, today I checked it in Chrome on Android and the bug is probably not there anymore, as this example works properly: http://codepen.io/MattyBalaam/pen/ewdvt.

Chrome: 43
Android: 4.4.2

The bug is still present in Android WebKit browser, but we could remove the workaround for Chrome? I can make a PR after you agree @julianshapiro.

**Comment by Rycochet** [comment]
Pull requests are now welcome - I've not got an Android device to test this on, but should have been something they fixed a while ago now :-)
