### ISSUE TITLE
Velocity destroys other bound events when finishing

### ISSUE THREAD

**Issue by patrickkeenan** [julianshapiro/velocity#552]
I'm using hammerjs, trying to also use velocity, but there's a conflict.

// SET THE PANNING BEHAVIOR
var hammertime = new Hammer($element);
  hammertime.on('pan', function(ev) {
      $.Velocity.hook($(ev.target),'translateX',ev.deltaX+'px')
  });

// SET THE END PAN BEHAVIOR
  hammertime.on('panend', function(ev) {
      $.Velocity($(ev.target),{translateX:0})
  });

Result = when the element finishes animating, all panning events are dead.

**Comment by ydaniv** [comment]
@patrickkeenan you'll have to provide an example on fiddle/codepen
