### ISSUE TITLE
Issue with velocity('stop') when use delay

### ISSUE THREAD

**Issue by Christophe-Mercatante** [julianshapiro/velocity#553]
Hi,

When I use delay on velocity animation, velocity('stop') ignore animations which hasn't started.
So the animations started after delay.

If after creating animations (with delay), I decide to stop them to destroy in DOM, some exceptions will occurs.

For the moment, I decide not use delay in velocity animation and I use timeout. I save the timer in the animated object. When I want to stop animation (before destroy), I have to clearTimeout and stop velocity animations which has started.

Can you please fix this bug ?

**Comment by ydaniv** [comment]
@Christophe-Mercatante it's not really clear what you're saying. Can you provide jsFiddle examples for each of the issues you describe?

**Comment by Christophe-Mercatante** [comment]
https://jsfiddle.net/v3bxx5yg/5/

**Comment by Rycochet** [comment]
Fixed in v2 (develop branch)
