### ISSUE TITLE
Animation timing out of sync when switching tabs in Chrome

### ISSUE THREAD

**Issue by milkmangames** [julianshapiro/velocity#554]
I see the[ comment](https://github.com/julianshapiro/velocity/blob/8be6219de47c999c2556ddf138e66dd2c541f282/velocity.js#L3315) about this in the source but it doesn't seem to be working as intended.

Inside a setInterval() callback, I perform animations with Velocity, triggering a 200ms animation every 5 seconds.  If I switch tabs, wait 30 seconds, and return to the original tab, I will see the animation played 6 times in rapid succession before resuming normal behavior.

Browser: Chrome 43

**Comment by ydaniv** [comment]
@milkmangames  you'll have to provide a working example.

**Comment by milkmangames** [comment]
Thank you.  Was unable to reproduce with example until I realize it only happens when Chrome Dev tools is in Emulation mode.  Closing issue.
