### ISSUE TITLE
Feature Request: built-in management of visibility starting state for animations with delay

### ISSUE THREAD

**Issue by milkmangames** [julianshapiro/velocity#555]
Thank you for this excellent library!

The docs say:

> Velocity's incorporation of CSS display/visibility changing allows for all of your animation logic to be contained within Velocity, meaning you no longer have to sprinkle jQuery's $.hide() and $.show() functions throughout your code.

But I have a common use case where this could be expanded.  My page has elements that I wish to start out hidden, then fade into view- but I'd like to perform these animations with a delay, and without setting their initial visibility state via markup or css.

For instance:

`Velocity(myThing, "transition.fadeIn", {delay: 1000});`

Will result in `myThing` being visible for 1 second, then immediately invisible, then fading in over the course of one second.  I could set it invisible with additional code beforehand, but it would be neat if Velocity could have a flag for this use case (`begin` argument won't cut it because it waits until after the delay, and `display` and `visibility` arguments will only apply to the end state of the animation.)

**Comment by Rycochet** [comment]
http://julian.com/research/velocity/#displayAndVisibility

**Comment by milkmangames** [comment]
@Rychochet thank you for your response.  You are linking to the exact paragraph that I have already quoted, as far as I can tell- and the problem I am describing is applicable to a specific case that is **not covered by the current implementation**, with regards to animating with a `delay` and the timing with which the `display` and `visibility` arguments take effect.  Please have another quick look at my issue as described, and let me know if perhaps I have misread the documentation and you are pointing out that I'm missing something.

**Comment by Rycochet** [comment]
Sorry - I just saw this and didn't see ```display:"auto"``` in the code so linked to the docs - I thought there was another issue relating to the ui pack and things not working quite right with regards to delay, but can't see it in a quick look (weekend and not much time etc).

Putting a quick jsfiddle together to show what's happening often helps btw - why it's mentioned in the "please read before posting" page ;-)

I know there's an update due later in the month - but don't know if this'll be affected etc...

**Comment by milkmangames** [comment]
Hey Rychochet, I totally get it.  Thanks for working on free software btw.

Not sure about a jsfiddle's value, it would be only a single line, and since everything is working as intended (this is a feature request, not a bug report) I think it requires reading some prose.  I'll try rephrasing it as succinctly as possible:

#### In the current version of Velocity:

    <div id="myThing">Hello</div>

    ...

    Velocity(myThing, "transition.fadeIn", {delay: 1000});


**Result:**

myThing does nothing for one second, then becomes opacity 0 instantaneously, than fades in to 100% opacity.

#### Suggested enhancement:

    <div id="myThing">Hello</div>

    ...

    Velocity(myThing, "transition.fadeIn", {delay: 1000, processVisibilityBeforeDelay: true });

**Result with suggested enhancement:**

Instead of waiting until the delay has completed to set the visibility/opacity to 0, Velocity will parse 'processVisibilityBeforeDelay', and instead, set the opacity 0 immediately, wait 1000 ms, and then perform the animation.

**Use case example for this enhancement:**

Developer wishes to gradually fade in a dozen elements on the page, with different delays, at page load.  Developer wishes to do this without having to set css opacity or visibility manually for each element in the stylesheet, html, or javascript.

#### Additional notes:

Not sure that processVisibilityBeforeDelay is a great name or suggesting this is the right implementation of the feature- just trying to clarify my request.

Thanks!

**Comment by Rycochet** [comment]
Apart from ideas and the occasional snippet I'm just a lurker on here like most people ;-)

Ah, got you - if there's reason enough for something, or enough people indicate that it'd be used, or sometimes even if it's just a small code change - then it's more likely to get added.

In this case I think the response is probably going to be add a duration 0 call to set the opacity first - as you can write your own ui effects you can copy what's already there and add an extra delay at the start...

Saying that, a flag does make sense - just not sure how easy it would be to add - more of a ```delayFirst:false``` (as default would be true) - then everything such as the visibility / display / begin could run before or after the delay from a simple boolean. Not sure of a good use-case for that, but if people chime in... ;-)

**Comment by bewildergeist** [comment]
This is essentially the same feature request as #242 — `processVisibilityBeforeDelay` == `animation-fill-mode`.

And for the record, I would like this feature too. I'm currently doing `Velocity.CSS.setPropertyValue(element, "opacity", 0)` before declaring my actual animation (which has a delay).

**Comment by Rycochet** [comment]
V2 now handles `visibility` and `display` as properties directly, when the UI Pack is updated this will no longer be an issue.
