### ISSUE TITLE
bug with transform: translate(x,y) being overwritten by values from previous animation

### ISSUE THREAD

**Issue by alexfoxy** [julianshapiro/velocity#559]
I'm encountering a problem where I am setting a translate value manually before an animation but it's being overwritten by a previous resulting value from an animation. Here's a fiddle:
https://jsfiddle.net/9cLkt5mj/

I'm expecting the red block to slide downwards off the yellow block (which it does!) and then red block to slide back over yellow block from right to left. Even though I set the translate y of the red block to "0vh" (see line 26 of the JS) the red block retains the vertical position of the end of the first animation.

Tested in Chrome and Webkit.

Thanks!

**Comment by MattyBalaam** [comment]
Velocity caches values. Use Hook to override the cached values: https://jsfiddle.net/19ew0eux/

**Comment by alexfoxy** [comment]
Ah brilliant - thanks
