### ISSUE TITLE
Stagger order

### ISSUE THREAD

**Issue by brittneykernan** [julianshapiro/velocity#560]
Hello and thank you for this amazing script.

Would like to control the order of when elements stagger. Is this currently supported? With jQuery I tried selecting them in the desired order, then calling velocity with stagger.

Thanks

**Comment by ydaniv** [comment]
On the next release passing a `function` as a stagger value will be supported.
:calling: @julianshapiro (:

**Comment by Rycochet** [comment]
jQuery will add elements in the order they appear on screen, so until you can pass a function you can treat the jQuery object as an array and manually sort them (or even add them) that way.

**Comment by Rycochet** [comment]
Supplying the elements in the order you want works as expected - jQuery doesn't respect the order you want as it puts them in the order they are in the DOM, so either sort (it behaves as an array), or use something else.
