### ISSUE TITLE
Re: .velocity({ rotateZ: 90, scale: 0.5 }) - Feature: SVG

### ISSUE THREAD

**Issue by ugajin-nijagu** [julianshapiro/velocity#561]
An issue running the above exemplar code. Firefox appears to interpret code differently to Google Chrome, and Safari just fails. Google Chrome interprets CSS transform-origin: as belonging to the rect element, such that, transform-origin: 50% 50%; rotates about the rext element's centre. Whereas, Firefox interprets CSS transform-origin: as belonging to the rect element's parent svg element. Safari does not seem to support 3DTransform, and usually requires -webkit- prefix. All running on OS X.

I hope this helps and/or is of interest.

-u

**Comment by ydaniv** [comment]
Is this something velocity can/should help with? If so, you should provide a code example.
If not then it's better you close this here and open either on SO or the bug trackers of Chromium/Firefox/Safari.

**Comment by u-gajin** [comment]
Indeed, is this something Velocity can/should help with? Possibly, it is. You can find the example at http://julian.com/research/velocity/ (see codePen at Feature SVG).

**Comment by ydaniv** [comment]
I'll need live example of the issue you mentioned. The example you mention works the same on Chrome and Firefox.
SVG has many inconsistencies across platforms, and I don't believe Velocity could/should deal with all of these.

**Comment by u-gajin** [comment]
The example does not work the same on when tested on OS X.

**Comment by u-gajin** [comment]
Referring again to http://julian.com/research/velocity/ the reader will see that the section immediately below: Basics: Properties Map states: ‘Velocity auto-prefixes properties (e.g. transform becomes webkit-transform on WebKit browsers); do not prefix properties yourself.’ 

Nonetheless, properties such as ‘transform-origin: 0% 0%’ declared in a style-sheet (as in the example at Feature: SVG), or so it seems, do need to be prefixed. This is true for Safari, not Chrome. In addition, for cross browser consistency (amongst those tested) it may be best to avoid using the ‘%’ unit. This will side-step the behaviour described earlier.

**Comment by CoDEmanX** [comment]
Something simple like 50% 50% should be supported under all circumstances :cry:

**Comment by u-gajin** [comment]
@CoDEmanX Thanks.

**Comment by Rycochet** [comment]
See #501
