### ISSUE TITLE
Loop Sequence

### ISSUE THREAD

**Issue by franciscolourenco** [julianshapiro/velocity#563]
Is there an built in option to make a sequence loop?

**Comment by julianshapiro** [comment]
unfortunately, not at the moment. i might try to add this soon

**Comment by coreyk** [comment]
+1 for nice to have, and could use right now :)

**Comment by PascalPencil** [comment]
Any way to trigger itself when the sequence ends? @Rycochet @julianshapiro

**Comment by Rycochet** [comment]
Not sure - but I'd think a complete callback to start it again might work - a delayed re-start would do it...

Having sequences treated like "normal" animations for options such as loop might become part of v2, going to reopen this as a reminder :-)

**Comment by clemsontiger** [comment]
@Rycochet any chance you have a working example of loops a sequence through a complete callback?

**Comment by Rycochet** [comment]
Sadly not - a setTimeout restarting it would be the first thing I checked though...

**Comment by Rycochet** [comment]
The old style sequences have been removed. New style sequences are defined in a similar way to css animations. You can provide any options you wish to them, including loops, repeats, callbacks etc
