### ISSUE TITLE
Problem with multiple animation playback

### ISSUE THREAD

**Issue by janstieler** [julianshapiro/velocity#566]
HI,
I have an strange behaviour an really simple velocity using.
on http://sevendays.janstieler.de/de/partner you can see a multiple playback of the transition.slideLeftIn if you reload the site through multiple klick on the menulink.
On a reload though the browser (strg+r) this behaviour is not used.

Kind regards

**Comment by ydaniv** [comment]
If you've found an issue with Velocity please reproduce it in a jsFiddle/codepen in a minimal form. Thanks.

**Comment by gjr-qm** [comment]
This is not an issue with Velocity. Your partner boxes are initially visible, so they appear, disappear when velocity starts the animation to slide them in. Hope the following codepen helps (first two divs are initially visible, second group of divs are not):

http://codepen.io/anon/pen/EVxbpx
