### ISSUE TITLE
progress callback function not working

### ISSUE THREAD

**Issue by pratiknagariya** [julianshapiro/velocity#567]
I have used velocity.js to animate something on page but in progress callback function does not working for me. I am getting null value for the tweenValue argument.

$element.velocity({
    opacity: 0,
    tween: 1000 // Optional
}, {
    progress: function(elements, complete, remaining, start, tweenValue) {
        console.log((complete * 100) + "%");
        console.log(remaining + "ms remaining!");
        console.log("The current tween value is " + tweenValue)
    }
});

**Comment by ydaniv** [comment]
Which version of Velocity are you using? Could you reproduce this in a jsFiddle?
