### ISSUE TITLE
Issue found with scrollLeft

### ISSUE THREAD

**Issue by ffxsam** [julianshapiro/velocity#568]
I've got the below code which fails:

    $imgContainer.velocity({scrollLeft: 200});

But if I change `.velocity` to `.animate`, it works just fine.

**Comment by ydaniv** [comment]
Well of course, please [read the docs](http://julian.com/research/velocity/#scroll) first. I believe there's also an open issue with request to support jQuery's scrolling API.

**Comment by ffxsam** [comment]
Ok. The Velocity page says that you can totally replace `.animate` with `.velocity`, but apparently that's not true in every case.
