### ISSUE TITLE
Velocity UI without jQuery

### ISSUE THREAD

**Issue by subpublic** [julianshapiro/velocity#569]
Hi!

I'm importing Velocity in ES6 as
import Velocity from 'velocity-animate';

Works fine with
Velocity($('.hello'), { opacity: 0.2 });
but not with
Velocity($('.hello'), 'callout.shake', 1000);

Getting Error: Velocity: First argument (undefined) was not a property map, a known action, or a registered redirect. Aborting.

**Comment by ydaniv** [comment]
You need the velocity.ui package for that.

**Comment by subpublic** [comment]
Yes well I have the npm package velocity-animate, which includes the velocity.ui files.
But that doesn't seem to be enough. I'm using webpack and ES6 (babel).

The velocity docs doesn't show any examples using 'callout.shake' (or similar) directly with Velocity, only connected to jQuery-elements (as in $('div').velocity).

**Comment by nmec** [comment]
I got this working by passing a non-jQuery element and animation name as the arguments:

```js
Velocity( document.getElementById('main'), 'transition.bounceUpIn');
```

**Comment by ydaniv** [comment]
Correct @nmec, that's the mistake here, if you use `Velocity()` directly you need to use DOM elements and not jQuery objects.
