### ISSUE TITLE
Transform Scale

### ISSUE THREAD

**Issue by jondavidchristopher** [julianshapiro/velocity#571]
I have a fun issue with sarafi/iOS and transform/scale. I am building an image zooming animation that zooms via scaleX and scaleY for a thumbnail image and then loads a higher resolution image over the top of that. It works in all browsers just great except for safari and iOS. 

I made a simple example below (fyi, it takes a while for the larger image to load and may flash white for sometime before it comes in):

     http://jsfiddle.net/870609w6/4/

You will notice if you open this in chrome or FF it looks great, but in safari it comes through blurry. From all the research I have done this appears to be an issue with safari converting the div to an image before the transform thus rendering the layer fuzzy after the fact. 

You would experience the same issue for any CSS transform, and I have attempted to find a workaround for this via a CSS attribute or JS to no avail. I was wondering if you have ever seen anything like this or possibly have a workaround?

**Comment by ydaniv** [comment]
From my experience with iOS anything you try to scale up becomes blurry. If possible, load a large image and scale it down.

**Comment by ydaniv** [comment]
Found [this old issue](http://stackoverflow.com/questions/4641522/how-to-force-re-render-after-a-webkit-3d-transform-in-safari) which is kinda related, only it's about text and works in 2D, and breaks in 3D.

So a list of a few tricks to try:

* Try using SVG instead.
* Try forcing the browser to re-render the image during the animation.
* Try creating a duplicate element in the maxed zoom in state, hoping the browser will cache that as an image on the GPU, and then scale that one down, and back up.

**Comment by benjamincharity** [comment]
@julianshapiro specifically calls out in this video that using Velocity should _not_ leave your text blurry: [Velocity.js: UI Pack Overview (@ 3:45)](https://youtu.be/CdwvR6a39Tg?t=3m45s)

**Comment by Rycochet** [comment]
Looks like a browser issue - not sure we can do anything about it beyond giving advice...
