### ISSUE TITLE
Delay between full loop alternations

### ISSUE THREAD

**Issue by ilyashubin** [julianshapiro/velocity#572]
Is there any way to specity delay between full loop cycles, i.e. when an object moves up and down (up-down-delay), not a delay between each loop alternations (up-delay-down-delay)?

```js
{
  { e: el.pinguin, p: {
    translateY: '-25%'
  }, o: {
    duration: 200,
    loop: jumpingCount,
    delay: 1000,
    complete: update
  }
}
```

**Comment by ydaniv** [comment]
No, [this](http://julian.com/research/velocity/#loop) is what happens when you feed it a `number`.
If you want a delay between repeats use a custom `complete` function.

**Comment by ilyashubin** [comment]
Got it, thank you.
