### ISSUE TITLE
translateX(negativeValue) issue

### ISSUE THREAD

**Issue by sayawan** [julianshapiro/velocity#573]
I have a box with predefined css translateX(-50px) property. When I want to animate it, the initial value begins with zero. 

```
<style>
#box {
    width: 100px;
    height: 100px;
    background-color: red;
    transform: translateX(-50px);
}
</style>

<script>
$("div").velocity({ translateX: '50px' }, 500);
</script>

<div id="box"></div>
```

what I expect is to translate from -50px to 50px, but it animates from 0
http://jsfiddle.net/maak81ye/2/

with css I get what I expect
```
#box:hover {
    transform: translateX(50px);
    transition: all 0.5s ease
} 
```

**Comment by MathieuLoutre** [comment]
Velocity doesn't read from the CSS and starts with default values for each of the attributes. You can change these values by using forcefeeding: http://julian.com/research/velocity/#forcefeeding

`$("div").velocity({ translateX: [50, -50] }, 500);` should work

**Comment by sayawan** [comment]
Got the idea. I missed it, thanks
