### ISSUE TITLE
bower / npm package name should be same

### ISSUE THREAD

**Issue by Hagith** [julianshapiro/velocity#574]
Library should have same name within bower and npm registry. Different name causes problems when it's used as a dependency. For example here in [ScrollMagic](https://github.com/janpaepke/ScrollMagic/blob/master/scrollmagic/uncompressed/plugins/animation.velocity.js#L34), it will work with bower but not using npm.

**Comment by ydaniv** [comment]
The name `velocity` on npm is already taken. What would you suggest?

**Comment by Hagith** [comment]
It can be added to bower registry as "velocity-animate" - same like in npm.

**Comment by Rycochet** [comment]
All the same as of 2.0.2 beta
