### ISSUE TITLE
Adding delay on a sequence disables sequenceQueue:false

### ISSUE THREAD

**Issue by Superpencil** [julianshapiro/velocity#575]
If I add a delay to an element in a sequence, I expect it to run the delay from the first sequence not having sequenceQueue:false. Instead adding delay disables sequenceQueue:false entirely.

I am very happy you implemented sequences, and I admit to being a dummy. I can work around the limitation but thought I'd drop a note. Thanks!

**Comment by ydaniv** [comment]
This a feature request, right? Could you clarify more about what you're asking?

If I understand correctly, you wish that a `delay` on a call in a sequence that also has `sequenceQueue: false` set will have its delay calculated from the first preceding call that didn't have its `sequenceQueue` set to `false`?

**Comment by dbulli** [comment]
@ydaniv I think that is what superpencil was referring to. The documentation doesn't really say it can't be done, but putting a value for `delay` kills the run `sequenceQueue:false`.

**Comment by Superpencil** [comment]
@ydaniv yes @dbulli yes
![tumblr_m62z16fd8t1qbhetko1_500](https://cloud.githubusercontent.com/assets/3094044/9753383/f9299a5e-570f-11e5-9ffa-7f177e6fcae5.gif)

**Comment by ydaniv** [comment]
Could you put the code you're trying to run in fiddle/pen?

**Comment by Rycochet** [comment]
Old style sequences have been removed
