### ISSUE TITLE
Unable to stop delayed non-queued animation

### ISSUE THREAD

**Issue by pkaminski** [julianshapiro/velocity#577]
I can't find a way to stop an animation created with `queue: false` and `delay: N` (before N expires and the animation actually starts).  `velocity('stop', true)` works if only one of those is present, but not if both are.  Repro here: http://codepen.io/anon/pen/zvYeML

**Comment by Mat-Moo** [comment]
I think I have the same issue with "Finish", I have X commands queued up
Object {scale: "+=0.1"} Object {duration: 1625, delay: 0, easing: "linear", queue: false}
Object {scale: "-=0.1"} Object {duration: 1625, delay: 1625, easing: "linear", queue: false}
but if I send a finish command, the delayed item still plays... The docs for finish are a bit confusing as it talks about sending a second parameter and finally a second parameter, so I'm not quite sure what I should be sending?

**Comment by dagobertrenouf** [comment]
Same here, animations that use the delay parameter are not cleared with stop or finish, as long as the delay hasn't expired.

**Comment by Rycochet** [comment]
Queues have been rewritten, delay is now part of an active animation, and not a separate thing
