### ISSUE TITLE
Separate the jQuery shim to its own js file

### ISSUE THREAD

**Issue by psoares** [julianshapiro/velocity#578]
The jQuery shim at the top of velocity.js breaks dojo builds when I try to integrate velocity in my dojo projects. The reason for this is that the dojo build system works with Rhino on the server, and the jQuery shim has a dependency on the window object, which does not exist in server-side javascript engines, and therefore throws errors.

It would be nice if this could be in a separate file, so that dojo builds are not broken and no code edits are needed.

**Comment by ydaniv** [comment]
@julianshapiro  perhaps if this issue goes beyond the "React issue" it's worth patching?

**Comment by psoares** [comment]
As a workaround, for dojo users, I did a quick and dirty fix by wrapping the code around this :
```javascript
define(['dojo/_base/kernel'], function (kernel) {
    var window = kernel.global;
    (function (window) {
        /***************
         Setup
         ***************/
        // [...]
    })(window);

    /******************
     Velocity.js
     ******************/


    return function (global, window, document, undefined) {

        /***************
         Summary
         ***************/
        // [...]
        return Velocity;
    }((window.jQuery || window.Zepto || window), window, document);
});
```

**Comment by kenwheeler** [comment]
Moving discussion to #579
