### ISSUE TITLE
Scroll animation doesn't work as expected without jQuery 

### ISSUE THREAD

**Issue by Nyana** [julianshapiro/velocity#581]
I tried to use Velocity.js without jQuery and without velocity.ui.js
But it seems that scrollTop cannot be animated by velocity.
this is what I am trying to do : 
```javascript
Velocity(document.getElementById('element3'), 'scroll' ,{
    duration: 500,
    container: document.getElementById('mainContainer')}
);
```
Where 'element3' is the element i want to scroll to.

But it tend to react as a scrollBy each time I call the animation.

Am I doing things wrong ?

**Comment by kenwheeler** [comment]
Can you please create a JSFiddle recreating the issue using our template, which is available here:

http://jsfiddle.net/65xCP/4/

Once I can view the reduced test case, I can more effectively isolate and address your issue.

**Comment by benjaminmikiten** [comment]
Nyana, did you ever figure this out? 

kenwheeler —I went to go about creating a jsfiddle of the similar problem I'm having, but the template doesn't seem to allow for the use of Velocity without also using JQuery.

The question here is simply whether or not the Velocity scroll function supports a syntax that doesn't require jQuery. 

The only examples in the docs as far as I can tell require it comes off of a jQuery element.

**Comment by MattyBalaam** [comment]
Remove JQuery from fiddle: http://jsfiddle.net/bbttwn3t/

**Comment by benjaminmikiten** [comment]
Y'all, I ended up finding out how this works, so I just want to note it here for future people until it gets added to the docs.

To use the 'scroll' action without Jquery, use the following params in the following format: 

`Velocity(targetElement, "scroll", {duration: 1000, container: scrollContainer, axis: 'x', offset:0});`

That is, the `targetElement` (as with the normal jquery-free syntax) that you want the container to scroll to be visible, the `'scroll'` action, then the `scrollData` options object, which includes the options in the docs.

Important detail being to pass along the `scrollContainer` if you don't want it to scroll the body.

Hope this helps!

**Comment by Rycochet** [comment]
...erm, that sounds exactly like it states in the docs - http://julian.com/research/velocity/#dependencies and http://julian.com/research/velocity/#scroll

**Comment by astrotim** [comment]
I can't get this to work without jQuery either. See [example on CodePen](http://codepen.io/astrotim/pen/YGGWqb/)

If I try this in the console, I can see that it returns a pending promise, but nothing visible happens.

What am I missing?

**Comment by Rycochet** [comment]
Not quite sure what I'm looking for there as it's working as expected without jQuery?

**Comment by EveLuty** [comment]
Hello, it is not working without Jquery and scroll the element(not body) even in the least version
in your example, http://velocityjs.org/#scroll
just change the code from
```
$("#element3").velocity("scroll", { 
  container: $("#container"),
  duration: 800,
  delay: 500
});
```
to
```
Velocity($("#element3"), "scroll", {
  container: $("#container"),
  duration: 800,
  delay: 500
})
```

the scroll will not scroll to element 3

in fact, I found that if we use it to scroll of document.body, it works. so could you check it? maybe in without Jquery version, you just let it to use for document.body??

thank you very much, if you want see the demo.
https://codepen.io/evemicky/pen/mqNdOm

Thank you by advance,
Best regards,
Tianyu LU

**Comment by Rycochet** [comment]
Version 2 is being coded on the develop branch right now, and the scroll code is not related to the old code at all - when done you will be able to treat scroll / scrollTop / scrollLeft transparently as another property.

**Comment by tankBug** [comment]
Hi! I'm considering this library, mostly for a non-jquery animate/scroll alternative. Have I understood correctly that this function is currently not working without jquery? If so, can we expect a fix soon?

**Comment by Rycochet** [comment]
This is an old issue - scroll now works as a property for animations - there is absolutely no link to jQuery at all in V2, in V1 it would use jQuery if it existed, but happily ran without it.

Have a look at the wiki on here for current docs (they're not brilliant, but they are current, while the website should be ignored until it's out of beta).
