### ISSUE TITLE
Queued animations an easing

### ISSUE THREAD

**Issue by Mat-Moo** [julianshapiro/velocity#582]
If' I create a queue with 4 animations, up/down/up/down does the easing apply to each call, or is the easing applied over the 4 changes (e.g. split the easing into 4). 

I *think* it applies the easing to each queued animation (which is not what I want), so is there a way to achieve multiple animations with a single easing?

**Comment by Rycochet** [comment]
The easing applies to each individual animation - building a UI pack animation has the same thing, however I'm annotating this as "enhancement" to suggest an overriding easing for a single UI Pack entry.

**Comment by Rycochet** [comment]
Linking to #398
