### ISSUE TITLE
Easing on a transition?

### ISSUE THREAD

**Issue by nathanhornby** [julianshapiro/velocity#583]
I've tried Googling but couldn't find anyting. Is it simply not possible to add easing to transitions, or do I have to approach it differently?

```
$('#user nav').velocity('transition.slideDownIn', {
   duration: 1000,
   easing: [300,8]
});
```

Doesn't effect the easing at all.

Is this documented somewhere?

**Comment by Rycochet** [comment]
Related to #580

**Comment by kenwheeler** [comment]
Moving discussion to #580
