### ISSUE TITLE
How do I use the utility function in Angular

### ISSUE THREAD

**Issue by sharpmachine** [julianshapiro/velocity#584]
Hi there,

I'm finding myself to add `transform: none` to elements have been animated so my elements that `position: fixed` aren't messed up. However to be able to use `element.css('transform', 'none')` I have to use it in a `$timeout` function so wait for the DOM to fully render, like so: 

```javascript
function create(element) {
      element
      .velocity('transition.expandIn', {duration : 450, display: 'block', delay: 350})
      .velocity('callout.flash');
      $timeout(function() {
        element.css('transform', 'none');
      }, 1000);
    }
```
I would rather run `element.css('transform', 'none')` using a promise. However to use promises with Velocity I have to run the utility function, as per your docs. But when I do that I get an error that says `$ is undefined`, so how do I use the utility function in an Angular service so that I run `element.css('transform', 'none')` after the animation is complete using a promise rather than the janky `$timeout`?

**Comment by ydaniv** [comment]
Have you tried `$.Velocity.hook(element, "transform", "none");`?

**Comment by sharpmachine** [comment]
@ydaniv Thanks for this. 

In my previous comment I mentioned: I get an error that says `$ is undefined`, so your suggestion would also give me the same error.
