### ISSUE TITLE
How to stop after the animation is finished

### ISSUE THREAD

**Issue by danyj** [julianshapiro/velocity#586]
I am creating a pulsating effect  on hover  but have trouble stooping the animation after it has finished. On mouseout it stops or should stay it pauses where it is instead to finish the animation and than stop.

Any help is appreciated

        $(".box").hover(function () {

            $(this).find('.effect-holder').velocity({
                scale: [1.2, 0.9],
                opacity: [1, 0]
            }, {
                easing: 'ease-out',
                duration: 800,
                loop: true
            }, {
                queue: false
            }).velocity("reverse");

        }, function () {

            $(this).find('.effect-holder').velocity("stop");

        });

https://jsfiddle.net/02vu80kc/1/

here stack if you want to get few points 
http://stackoverflow.com/questions/32852526/how-to-stop-velocity-js-animation-after-the-animation-is-finished

**Comment by Rycochet** [comment]
http://julian.com/research/velocity/#finish ?

**Comment by kenwheeler** [comment]
Moving discussion to #495
