### ISSUE TITLE
The reverse isn't working for paddings in firefox

### ISSUE THREAD

**Issue by tsvetant** [julianshapiro/velocity#587]
It doesn't seems to have any issues reversing my `height` and `padding` in chrome, but in firefox it leaves the `padding` to 0 after a reverse.

```javascript
$('a.open').on("click", function(e){
     $('#breadcrumb').velocity({height: 50, padding: 0}, {duration: 200});
});
$('a.close').on("click", function(e){
     $('#breadcrumb').velocity("reverse");
});
```

Lazy
``` javascript
$('#breadcrumb').velocity("reverse", { 
	begin: function(elements) { 
		var FF = !(window.mozInnerScreenX == null);
		if(FF)
			$(this).velocity({paddingTop: 100, paddingBottom: 59}, {duration: 200})
	} 
});
```

Taking a note that I could've messed something up or misread the docs. Correct me if so.

**Comment by kenwheeler** [comment]
Can you please create a JSFiddle recreating the issue using our template, which is available here:

http://jsfiddle.net/65xCP/4/

Once I can view the reduced test case, I can more effectively isolate and address your issue.
