### ISSUE TITLE
Velocity fadeIn/fadeOut does not use transition and changes opacity directly

### ISSUE THREAD

**Issue by sunprophit** [julianshapiro/velocity#589]
Why fadeIn/fadeOut animation does not use transition and changes inline element's opacity (I can see intermediate values in DOM-element style property in chrome developer tools). I am having some blinking on fadeIn/fadeOut in OS X Chrome and not sure if it better to use transition-based animation for fadeIn/fadeOut.

**Comment by kenwheeler** [comment]
Can you please create a JSFiddle recreating the issue using our template, which is available here:

http://jsfiddle.net/65xCP/4/

Once I can view the reduced test case, I can more effectively isolate and address your issue.

**Comment by josephbergdoll** [comment]
+1

**Comment by MattyBalaam** [comment]
What exactly are you +1ing here? Velocity is a library which uses JavaScript to animate inline styles. If you want to use a css transition, use a transition.
