### ISSUE TITLE
Cannot animate style attribute with important marked

### ISSUE THREAD

**Issue by rerefreelancer** [julianshapiro/velocity#590]
Cannot animate style attribute with important marked

**Comment by Rycochet** [comment]
```!important``` overrides css, and it's not something simple to add to inline css at all - there's certainly no code within Velocity to support that (even jQuery needs you to run around in circles for it - https://stackoverflow.com/questions/2655925/how-to-apply-important-using-css ) - better would be a css decleration that has a ```:not(.velocity-animating)``` on it to only have the flag when it's not animating.

Not a bug, and better as a StackOverflow question.

**Comment by julianshapiro** [comment]
Thanks, @Rycochet !
