### ISSUE TITLE
Generate Docs? 

### ISSUE THREAD

**Issue by tx4x** [julianshapiro/velocity#594]
Hi,
we'd like to build & integrate the documentation (also for offline). Are there any chance to do that ? 
thanks!
g

**Comment by kenwheeler** [comment]
Working on this for the next release

**Comment by gbaumgart** [comment]
@kenwheeler thank you! We're using we are using primarily daux.io (builds static pages from Markdown directories).

**Comment by Inoir** [comment]
Any new Infos for this? http://VelocityJS.org shows only "pageok". Cant get the docs.

**Comment by Rycochet** [comment]
The website and docs are actively getting worked on, so it should just be temporary (it was up yesterday) :-)

**Comment by Rycochet** [comment]
For V2 the source code now contains a lot more documentation style comments. The documentation itself resides on the wiki (until we get out of beta), and will then be migrated to the website - when it will also be integrated into the source tree.
