### ISSUE TITLE
backgroundColor animation that also apply translate3d?

### ISSUE THREAD

**Issue by jjalonso** [julianshapiro/velocity#595]
Hello guys,
Im only executing this:

$('.myclass').velocity({
        backgroundColor: 'white'
      }, 500)

Over this markup:

      <div>
        <a class='myclass'>
          OK
        </a>
      </div>

And the color change, but also change the translate3d, is applying to style a movement down of around 10 pixels and another up, like a slow and fancy bounce. 

Bug or mistake?

**Comment by kenwheeler** [comment]
Can you please create a JSFiddle recreating the issue using our template, which is available here:

http://jsfiddle.net/65xCP/4/

Once I can view the reduced test case, I can more effectively isolate and address your issue.

**Comment by jjalonso** [comment]
Unfortunately. The ticket was raised 11months ago and I'm not working anymore on that project.

Let's hope nobody else have it.
Thanks.

**Comment by Rycochet** [comment]
I'd rather someone else did actually have the same issue - then it can be found and fixed ;-)
