### ISSUE TITLE
Infinite loop without reverse (repeat:true)

### ISSUE THREAD

**Issue by sivan** [julianshapiro/velocity#598]
I think volecity should have an loopAlternate option works exactly like css animation-direction.

Thisi is  a same issue metioned [here](https://github.com/julianshapiro/velocity/issues/175#issuecomment-60631568), and the solution [here](https://github.com/julianshapiro/velocity/issues/175#issuecomment-60664175) works for me.

It's very useful with a step easing & loop animation like a loading spinner, walking animation etc.[[example](http://codepen.io/sivan/pen/meBqYZ)]

**Comment by alvipeo** [comment]
Can you guys do something about it! Really useful feature.

**Comment by Rycochet** [comment]
Needs thinking about and internal changes on code I don't want to touch yet - but I've done this before by running a forcefed animation, then reversing and looping the reverse ;-)

**Comment by alvipeo** [comment]
I actually made it work with tweene.

**Comment by autr** [comment]
This seems like a pretty basic feature missing from Velocity -  would prefer not having more overheads with Tweene or GSAP in my Vue app

**Comment by Rycochet** [comment]
In v2 there is are options for `loop`, `repeat` and `reverse`.
