### ISSUE TITLE
Remove use of /deep/ combinator

### ISSUE THREAD

**Issue by triune** [julianshapiro/velocity#601]
From Chrome console whenever using Velocity 1.2.3 >>

velocity.min.js:3 /deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.

**Comment by Rycochet** [comment]
Just wondering where exactly any Shadow DOM code is used in Velocity - certainly not seen any in there and it's not relevant to what it does, but maybe I'm missing something?

**Comment by triune** [comment]
When using the non-minified js, I get this warning instead:

velocity.js:1685 /deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.

Adding a line @1686:
console.info(computedStyle); 

Produces this output:

velocity.js:1686 
CSSStyleDeclaration {0: "animation-delay", 1: "animation-direction", 2: "animation-duration", 3: "animation-fill-mode", 4: "animation-iteration-count", 5: "animation-name", 6: "animation-play-state", 7: "animation-timing-function", 8: "background-attachment", 9: "background-blend-mode", 10: "background-clip", 11: "background-color", 12: "background-image", 13: "background-origin", 14: "background-position", 15: "background-repeat", 16: "background-size", 17: "border-bottom-color", 18: "border-bottom-left-radius", 19: "border-bottom-right-radius", 20: "border-bottom-style", 21: "border-bottom-width", 22: "border-collapse", 23: "border-image-outset", 24: "border-image-repeat", 25: "border-image-slice", 26: "border-image-source", 27: "border-image-width", 28: "border-left-color", 29: "border-left-style", 30: "border-left-width", 31: "border-right-color", 32: "border-right-style", 33: "border-right-width", 34: "border-top-color", 35: "border-top-left-radius", 36: "border-top-right-radius", 37: "border-top-style", 38: "border-top-width", 39: "bottom", 40: "box-shadow", 41: "box-sizing", 42: "caption-side", 43: "clear", 44: "clip", 45: "color", 46: "cursor", 47: "direction", 48: "display", 49: "empty-cells", 50: "float", 51: "font-family", 52: "font-kerning", 53: "font-size", 54: "font-stretch", 55: "font-style", 56: "font-variant", 57: "font-variant-ligatures", 58: "font-weight", 59: "height", 60: "image-rendering", 61: "isolation", 62: "left", 63: "letter-spacing", 64: "line-height", 65: "list-style-image", 66: "list-style-position", 67: "list-style-type", 68: "margin-bottom", 69: "margin-left", 70: "margin-right", 71: "margin-top", 72: "max-height", 73: "max-width", 74: "min-height", 75: "min-width", 76: "mix-blend-mode", 77: "motion-offset", 78: "motion-path", 79: "motion-rotation", 80: "object-fit", 81: "object-position", 82: "opacity", 83: "orphans", 84: "outline-color", 85: "outline-offset", 86: "outline-style", 87: "outline-width", 88: "overflow-wrap", 89: "overflow-x", 90: "overflow-y", 91: "padding-bottom", 92: "padding-left", 93: "padding-right", 94: "padding-top", 95: "page-break-after", 96: "page-break-before", 97: "page-break-inside", 98: "pointer-events", 99: "position"…}0: "animation-delay"1: "animation-direction"2: "animation-duration"3: "animation-fill-mode"4: "animation-iteration-count"5: "animation-name"6: "animation-play-state"7: "animation-timing-function"8: "background-attachment"9: "background-blend-mode"10: "background-clip"11: "background-color"12: "background-image"13: "background-origin"14: "background-position"15: "background-repeat"16: "background-size"17: "border-bottom-color"18: "border-bottom-left-radius"19: "border-bottom-right-radius"20: "border-bottom-style"21: "border-bottom-width"22: "border-collapse"23: "border-image-outset"24: "border-image-repeat"25: "border-image-slice"26: "border-image-source"27: "border-image-width"28: "border-left-color"29: "border-left-style"30: "border-left-width"31: "border-right-color"32: "border-right-style"33: "border-right-width"34: "border-top-color"35: "border-top-left-radius"36: "border-top-right-radius"37: "border-top-style"38: "border-top-width"39: "bottom"40: "box-shadow"41: "box-sizing"42: "caption-side"43: "clear"44: "clip"45: "color"46: "cursor"47: "direction"48: "display"49: "empty-cells"50: "float"51: "font-family"52: "font-kerning"53: "font-size"54: "font-stretch"55: "font-style"56: "font-variant"57: "font-variant-ligatures"58: "font-weight"59: "height"60: "image-rendering"61: "isolation"62: "left"63: "letter-spacing"64: "line-height"65: "list-style-image"66: "list-style-position"67: "list-style-type"68: "margin-bottom"69: "margin-left"70: "margin-right"71: "margin-top"72: "max-height"73: "max-width"74: "min-height"75: "min-width"76: "mix-blend-mode"77: "motion-offset"78: "motion-path"79: "motion-rotation"80: "object-fit"81: "object-position"82: "opacity"83: "orphans"84: "outline-color"85: "outline-offset"86: "outline-style"87: "outline-width"88: "overflow-wrap"89: "overflow-x"90: "overflow-y"91: "padding-bottom"92: "padding-left"93: "padding-right"94: "padding-top"95: "page-break-after"96: "page-break-before"97: "page-break-inside"98: "pointer-events"99: "position"100: "resize"101: "right"102: "speak"103: "table-layout"104: "tab-size"105: "text-align"106: "text-decoration"107: "text-indent"108: "text-rendering"109: "text-shadow"110: "text-overflow"111: "text-transform"112: "top"113: "touch-action"114: "transition-delay"115: "transition-duration"116: "transition-property"117: "transition-timing-function"118: "unicode-bidi"119: "vertical-align"120: "visibility"121: "white-space"122: "widows"123: "width"124: "will-change"125: "word-break"126: "word-spacing"127: "word-wrap"128: "z-index"129: "zoom"130: "-webkit-appearance"131: "backface-visibility"132: "-webkit-background-clip"133: "-webkit-background-composite"134: "-webkit-background-origin"135: "-webkit-border-horizontal-spacing"136: "-webkit-border-image"137: "-webkit-border-vertical-spacing"138: "-webkit-box-align"139: "-webkit-box-decoration-break"140: "-webkit-box-direction"141: "-webkit-box-flex"142: "-webkit-box-flex-group"143: "-webkit-box-lines"144: "-webkit-box-ordinal-group"145: "-webkit-box-orient"146: "-webkit-box-pack"147: "-webkit-box-reflect"148: "-webkit-clip-path"149: "-webkit-column-break-after"150: "-webkit-column-break-before"151: "-webkit-column-break-inside"152: "-webkit-column-count"153: "-webkit-column-gap"154: "-webkit-column-rule-color"155: "-webkit-column-rule-style"156: "-webkit-column-rule-width"157: "-webkit-column-span"158: "-webkit-column-width"159: "-webkit-filter"160: "align-content"161: "align-items"162: "align-self"163: "flex-basis"164: "flex-grow"165: "flex-shrink"166: "flex-direction"167: "flex-wrap"168: "justify-content"169: "-webkit-font-smoothing"170: "-webkit-highlight"171: "-webkit-hyphenate-character"172: "-webkit-line-box-contain"173: "-webkit-line-break"174: "-webkit-line-clamp"175: "-webkit-locale"176: "-webkit-margin-before-collapse"177: "-webkit-margin-after-collapse"178: "-webkit-mask-box-image"179: "-webkit-mask-box-image-outset"180: "-webkit-mask-box-image-repeat"181: "-webkit-mask-box-image-slice"182: "-webkit-mask-box-image-source"183: "-webkit-mask-box-image-width"184: "-webkit-mask-clip"185: "-webkit-mask-composite"186: "-webkit-mask-image"187: "-webkit-mask-origin"188: "-webkit-mask-position"189: "-webkit-mask-repeat"190: "-webkit-mask-size"191: "order"192: "perspective"193: "perspective-origin"194: "-webkit-print-color-adjust"195: "-webkit-rtl-ordering"196: "shape-outside"197: "shape-image-threshold"198: "shape-margin"199: "-webkit-tap-highlight-color"200: "-webkit-text-combine"201: "-webkit-text-decorations-in-effect"202: "-webkit-text-emphasis-color"203: "-webkit-text-emphasis-position"204: "-webkit-text-emphasis-style"205: "-webkit-text-fill-color"206: "-webkit-text-orientation"207: "-webkit-text-security"208: "-webkit-text-stroke-color"209: "-webkit-text-stroke-width"210: "transform"211: "transform-origin"212: "transform-style"213: "-webkit-user-drag"214: "-webkit-user-modify"215: "-webkit-user-select"216: "-webkit-writing-mode"217: "-webkit-app-region"218: "buffered-rendering"219: "clip-path"220: "clip-rule"221: "mask"222: "filter"223: "flood-color"224: "flood-opacity"225: "lighting-color"226: "stop-color"227: "stop-opacity"228: "color-interpolation"229: "color-interpolation-filters"230: "color-rendering"231: "fill"232: "fill-opacity"233: "fill-rule"234: "marker-end"235: "marker-mid"236: "marker-start"237: "mask-type"238: "shape-rendering"239: "stroke"240: "stroke-dasharray"241: "stroke-dashoffset"242: "stroke-linecap"243: "stroke-linejoin"244: "stroke-miterlimit"245: "stroke-opacity"246: "stroke-width"247: "alignment-baseline"248: "baseline-shift"249: "dominant-baseline"250: "text-anchor"251: "writing-mode"252: "glyph-orientation-horizontal"253: "glyph-orientation-vertical"254: "vector-effect"255: "paint-order"256: "cx"257: "cy"258: "x"259: "y"260: "r"261: "rx"262: "ry"alignContent: "start"alignItems: "start"alignSelf: "start"alignmentBaseline: "auto"all: ""animation: "none 0s ease 0s 1 normal none running"animationDelay: "0s"animationDirection: "normal"animationDuration: "0s"animationFillMode: "none"animationIterationCount: "1"animationName: "none"animationPlayState: "running"animationTimingFunction: "ease"backfaceVisibility: "visible"background: "rgb(255, 255, 255) none repeat scroll 0% 0% / auto padding-box border-box"backgroundAttachment: "scroll"backgroundBlendMode: "normal"backgroundClip: "border-box"backgroundColor: "rgb(255, 255, 255)"backgroundImage: "none"backgroundOrigin: "padding-box"backgroundPosition: "0% 0%"backgroundPositionX: "0%"backgroundPositionY: "0%"backgroundRepeat: "repeat"backgroundRepeatX: ""backgroundRepeatY: ""backgroundSize: "auto"baselineShift: "0px"border: "0px none rgb(68, 120, 170)"borderBottom: "0px none rgb(68, 120, 170)"borderBottomColor: "rgb(68, 120, 170)"borderBottomLeftRadius: "2px"borderBottomRightRadius: "2px"borderBottomStyle: "none"borderBottomWidth: "0px"borderCollapse: "separate"borderColor: "rgb(68, 120, 170)"borderImage: "none"borderImageOutset: "0px"borderImageRepeat: "stretch"borderImageSlice: "100%"borderImageSource: "none"borderImageWidth: "1"borderLeft: "0px none rgb(68, 120, 170)"borderLeftColor: "rgb(68, 120, 170)"borderLeftStyle: "none"borderLeftWidth: "0px"borderRadius: "2px"borderRight: "0px none rgb(68, 120, 170)"borderRightColor: "rgb(68, 120, 170)"borderRightStyle: "none"borderRightWidth: "0px"borderSpacing: "0px 0px"borderStyle: "none"borderTop: "0px none rgb(68, 120, 170)"borderTopColor: "rgb(68, 120, 170)"borderTopLeftRadius: "2px"borderTopRightRadius: "2px"borderTopStyle: "none"borderTopWidth: "0px"borderWidth: "0px"bottom: "auto"boxShadow: "rgba(200, 200, 200, 0.74902) 0px 2px 4px 0px"boxSizing: "border-box"bufferedRendering: "auto"captionSide: "top"clear: "none"clip: "auto"clipPath: "none"clipRule: "nonzero"color: "rgb(68, 120, 170)"colorInterpolation: "sRGB"colorInterpolationFilters: "linearRGB"colorRendering: "auto"content: ""counterIncrement: "none"counterReset: "none"cssFloat: "none"cssText: "animation-delay: 0s; animation-direction: normal; animation-duration: 0s; animation-fill-mode: none; animation-iteration-count: 1; animation-name: none; animation-play-state: running; animation-timing-function: ease; background-attachment: scroll; background-blend-mode: normal; background-clip: border-box; background-color: rgb(255, 255, 255); background-image: none; background-origin: padding-box; background-position: 0% 0%; background-repeat: repeat; background-size: auto; border-bottom-color: rgb(68, 120, 170); border-bottom-left-radius: 2px; border-bottom-right-radius: 2px; border-bottom-style: none; border-bottom-width: 0px; border-collapse: separate; border-image-outset: 0px; border-image-repeat: stretch; border-image-slice: 100%; border-image-source: none; border-image-width: 1; border-left-color: rgb(68, 120, 170); border-left-style: none; border-left-width: 0px; border-right-color: rgb(68, 120, 170); border-right-style: none; border-right-width: 0px; border-top-color: rgb(68, 120, 170); border-top-left-radius: 2px; border-top-right-radius: 2px; border-top-style: none; border-top-width: 0px; bottom: auto; box-shadow: rgba(200, 200, 200, 0.74902) 0px 2px 4px 0px; box-sizing: border-box; caption-side: top; clear: none; clip: auto; color: rgb(68, 120, 170); cursor: auto; direction: ltr; display: block; empty-cells: show; float: none; font-family: 'Open Sans'; font-kerning: auto; font-size: 16px; font-stretch: normal; font-style: normal; font-variant: normal; font-variant-ligatures: normal; font-weight: normal; height: 560px; image-rendering: auto; isolation: auto; left: auto; letter-spacing: normal; line-height: 24px; list-style-image: none; list-style-position: outside; list-style-type: disc; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; margin-top: 0px; max-height: none; max-width: none; min-height: 0px; min-width: 460px; mix-blend-mode: normal; motion-offset: 0px; motion-path: none; motion-rotation: auto 0deg; object-fit: fill; object-position: 50% 50%; opacity: 1; orphans: auto; outline-color: rgb(68, 120, 170); outline-offset: 0px; outline-style: none; outline-width: 0px; overflow-wrap: normal; overflow-x: visible; overflow-y: visible; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px; page-break-after: auto; page-break-before: auto; page-break-inside: auto; pointer-events: auto; position: static; resize: none; right: auto; speak: normal; table-layout: auto; tab-size: 8; text-align: start; text-decoration: none; text-indent: 0px; text-rendering: auto; text-shadow: none; text-overflow: clip; text-transform: none; top: auto; touch-action: auto; transition-delay: 0s; transition-duration: 0.333s; transition-property: opacity; transition-timing-function: linear; unicode-bidi: normal; vertical-align: baseline; visibility: visible; white-space: normal; widows: 1; width: 940px; will-change: auto; word-break: normal; word-spacing: 0px; word-wrap: normal; z-index: auto; zoom: 1; -webkit-appearance: none; backface-visibility: visible; -webkit-background-clip: border-box; -webkit-background-composite: source-over; -webkit-background-origin: padding-box; -webkit-border-horizontal-spacing: 0px; -webkit-border-image: none; -webkit-border-vertical-spacing: 0px; -webkit-box-align: stretch; -webkit-box-decoration-break: slice; -webkit-box-direction: normal; -webkit-box-flex: 0; -webkit-box-flex-group: 1; -webkit-box-lines: single; -webkit-box-ordinal-group: 1; -webkit-box-orient: horizontal; -webkit-box-pack: start; -webkit-box-reflect: none; -webkit-clip-path: none; -webkit-column-break-after: auto; -webkit-column-break-before: auto; -webkit-column-break-inside: auto; -webkit-column-count: auto; -webkit-column-gap: normal; -webkit-column-rule-color: rgb(68, 120, 170); -webkit-column-rule-style: none; -webkit-column-rule-width: 0px; -webkit-column-span: none; -webkit-column-width: auto; -webkit-filter: none; align-content: start; align-items: start; align-self: start; flex-basis: auto; flex-grow: 0; flex-shrink: 1; flex-direction: row; flex-wrap: nowrap; justify-content: start; -webkit-font-smoothing: auto; -webkit-highlight: none; -webkit-hyphenate-character: auto; -webkit-line-box-contain: block inline replaced; -webkit-line-break: auto; -webkit-line-clamp: none; -webkit-locale: auto; -webkit-margin-before-collapse: collapse; -webkit-margin-after-collapse: collapse; -webkit-mask-box-image: none; -webkit-mask-box-image-outset: 0px; -webkit-mask-box-image-repeat: stretch; -webkit-mask-box-image-slice: 0 fill; -webkit-mask-box-image-source: none; -webkit-mask-box-image-width: auto; -webkit-mask-clip: border-box; -webkit-mask-composite: source-over; -webkit-mask-image: none; -webkit-mask-origin: border-box; -webkit-mask-position: 0% 0%; -webkit-mask-repeat: repeat; -webkit-mask-size: auto; order: 0; perspective: none; perspective-origin: 470px 280px; -webkit-print-color-adjust: economy; -webkit-rtl-ordering: logical; shape-outside: none; shape-image-threshold: 0; shape-margin: 0px; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); -webkit-text-combine: none; -webkit-text-decorations-in-effect: none; -webkit-text-emphasis-color: rgb(68, 120, 170); -webkit-text-emphasis-position: over; -webkit-text-emphasis-style: none; -webkit-text-fill-color: rgb(68, 120, 170); -webkit-text-orientation: vertical-right; -webkit-text-security: none; -webkit-text-stroke-color: rgb(68, 120, 170); -webkit-text-stroke-width: 0px; transform: none; transform-origin: 470px 280px; transform-style: flat; -webkit-user-drag: auto; -webkit-user-modify: read-only; -webkit-user-select: text; -webkit-writing-mode: horizontal-tb; -webkit-app-region: no-drag; buffered-rendering: auto; clip-path: none; clip-rule: nonzero; mask: none; filter: none; flood-color: rgb(0, 0, 0); flood-opacity: 1; lighting-color: rgb(255, 255, 255); stop-color: rgb(0, 0, 0); stop-opacity: 1; color-interpolation: sRGB; color-interpolation-filters: linearRGB; color-rendering: auto; fill: rgb(0, 0, 0); fill-opacity: 1; fill-rule: nonzero; marker-end: none; marker-mid: none; marker-start: none; mask-type: luminance; shape-rendering: auto; stroke: none; stroke-dasharray: none; stroke-dashoffset: 0px; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 4; stroke-opacity: 1; stroke-width: 1px; alignment-baseline: auto; baseline-shift: 0px; dominant-baseline: auto; text-anchor: start; writing-mode: lr-tb; glyph-orientation-horizontal: 0deg; glyph-orientation-vertical: auto; vector-effect: none; paint-order: fill stroke markers; cx: 0px; cy: 0px; x: 0px; y: 0px; r: 0px; rx: 0px; ry: 0px;"cursor: "auto"cx: "0px"cy: "0px"direction: "ltr"display: "block"dominantBaseline: "auto"emptyCells: "show"fill: "rgb(0, 0, 0)"fillOpacity: "1"fillRule: "nonzero"filter: "none"flex: "0 1 auto"flexBasis: "auto"flexDirection: "row"flexFlow: "row nowrap"flexGrow: "0"flexShrink: "1"flexWrap: "nowrap"float: "none"floodColor: "rgb(0, 0, 0)"floodOpacity: "1"font: "normal normal normal normal 16px / 24px 'Open Sans'"fontFamily: "'Open Sans'"fontKerning: "auto"fontSize: "16px"fontStretch: "normal"fontStyle: "normal"fontVariant: "normal"fontVariantLigatures: "normal"fontWeight: "normal"glyphOrientationHorizontal: "0deg"glyphOrientationVertical: "auto"height: "560px"imageRendering: "auto"isolation: "auto"justifyContent: "start"left: "auto"length: 263letterSpacing: "normal"lightingColor: "rgb(255, 255, 255)"lineHeight: "24px"listStyle: "disc outside none"listStyleImage: "none"listStylePosition: "outside"listStyleType: "disc"margin: "0px"marginBottom: "0px"marginLeft: "0px"marginRight: "0px"marginTop: "0px"marker: ""markerEnd: "none"markerMid: "none"markerStart: "none"mask: "none"maskType: "luminance"maxHeight: "none"maxWidth: "none"maxZoom: ""minHeight: "0px"minWidth: "460px"minZoom: ""mixBlendMode: "normal"motion: "none 0px auto 0deg"motionOffset: "0px"motionPath: "none"motionRotation: "auto 0deg"objectFit: "fill"objectPosition: "50% 50%"opacity: "1"order: "0"orientation: ""orphans: "auto"outline: "rgb(68, 120, 170) none 0px"outlineColor: "rgb(68, 120, 170)"outlineOffset: "0px"outlineStyle: "none"outlineWidth: "0px"overflow: "visible"overflowWrap: "normal"overflowX: "visible"overflowY: "visible"padding: "0px"paddingBottom: "0px"paddingLeft: "0px"paddingRight: "0px"paddingTop: "0px"page: ""pageBreakAfter: "auto"pageBreakBefore: "auto"pageBreakInside: "auto"paintOrder: "fill stroke markers"parentRule: nullperspective: "none"perspectiveOrigin: "470px 280px"pointerEvents: "auto"position: "static"quotes: ""r: "0px"resize: "none"right: "auto"rx: "0px"ry: "0px"shapeImageThreshold: "0"shapeMargin: "0px"shapeOutside: "none"shapeRendering: "auto"size: ""speak: "normal"src: ""stopColor: "rgb(0, 0, 0)"stopOpacity: "1"stroke: "none"strokeDasharray: "none"strokeDashoffset: "0px"strokeLinecap: "butt"strokeLinejoin: "miter"strokeMiterlimit: "4"strokeOpacity: "1"strokeWidth: "1px"tabSize: "8"tableLayout: "auto"textAlign: "start"textAnchor: "start"textDecoration: "none"textIndent: "0px"textOverflow: "clip"textRendering: "auto"textShadow: "none"textTransform: "none"top: "auto"touchAction: "auto"transform: "none"transformOrigin: "470px 280px"transformStyle: "flat"transition: "opacity 0.333s linear 0s"transitionDelay: "0s"transitionDuration: "0.333s"transitionProperty: "opacity"transitionTimingFunction: "linear"unicodeBidi: "normal"unicodeRange: ""userZoom: ""vectorEffect: "none"verticalAlign: "baseline"visibility: "visible"webkitAppRegion: "no-drag"webkitAppearance: "none"webkitBackgroundClip: "border-box"webkitBackgroundComposite: "source-over"webkitBackgroundOrigin: "padding-box"webkitBorderAfter: "0px none rgb(68, 120, 170)"webkitBorderAfterColor: "rgb(68, 120, 170)"webkitBorderAfterStyle: "none"webkitBorderAfterWidth: "0px"webkitBorderBefore: "0px none rgb(68, 120, 170)"webkitBorderBeforeColor: "rgb(68, 120, 170)"webkitBorderBeforeStyle: "none"webkitBorderBeforeWidth: "0px"webkitBorderEnd: "0px none rgb(68, 120, 170)"webkitBorderEndColor: "rgb(68, 120, 170)"webkitBorderEndStyle: "none"webkitBorderEndWidth: "0px"webkitBorderHorizontalSpacing: "0px"webkitBorderImage: "none"webkitBorderStart: "0px none rgb(68, 120, 170)"webkitBorderStartColor: "rgb(68, 120, 170)"webkitBorderStartStyle: "none"webkitBorderStartWidth: "0px"webkitBorderVerticalSpacing: "0px"webkitBoxAlign: "stretch"webkitBoxDecorationBreak: "slice"webkitBoxDirection: "normal"webkitBoxFlex: "0"webkitBoxFlexGroup: "1"webkitBoxLines: "single"webkitBoxOrdinalGroup: "1"webkitBoxOrient: "horizontal"webkitBoxPack: "start"webkitBoxReflect: "none"webkitClipPath: "none"webkitColumnBreakAfter: "auto"webkitColumnBreakBefore: "auto"webkitColumnBreakInside: "auto"webkitColumnCount: "auto"webkitColumnGap: "normal"webkitColumnRule: "0px none rgb(68, 120, 170)"webkitColumnRuleColor: "rgb(68, 120, 170)"webkitColumnRuleStyle: "none"webkitColumnRuleWidth: "0px"webkitColumnSpan: "none"webkitColumnWidth: "auto"webkitColumns: "auto auto"webkitFilter: "none"webkitFontFeatureSettings: "normal"webkitFontSizeDelta: ""webkitFontSmoothing: "auto"webkitHighlight: "none"webkitHyphenateCharacter: "auto"webkitLineBoxContain: "block inline replaced"webkitLineBreak: "auto"webkitLineClamp: "none"webkitLocale: "auto"webkitLogicalHeight: "560px"webkitLogicalWidth: "940px"webkitMarginAfter: "0px"webkitMarginAfterCollapse: "collapse"webkitMarginBefore: "0px"webkitMarginBeforeCollapse: "collapse"webkitMarginBottomCollapse: "collapse"webkitMarginCollapse: ""webkitMarginEnd: "0px"webkitMarginStart: "0px"webkitMarginTopCollapse: "collapse"webkitMask: ""webkitMaskBoxImage: "none"webkitMaskBoxImageOutset: "0px"webkitMaskBoxImageRepeat: "stretch"webkitMaskBoxImageSlice: "0 fill"webkitMaskBoxImageSource: "none"webkitMaskBoxImageWidth: "auto"webkitMaskClip: "border-box"webkitMaskComposite: "source-over"webkitMaskImage: "none"webkitMaskOrigin: "border-box"webkitMaskPosition: "0% 0%"webkitMaskPositionX: "0%"webkitMaskPositionY: "0%"webkitMaskRepeat: "repeat"webkitMaskRepeatX: ""webkitMaskRepeatY: ""webkitMaskSize: "auto"webkitMaxLogicalHeight: "none"webkitMaxLogicalWidth: "none"webkitMinLogicalHeight: "0px"webkitMinLogicalWidth: "460px"webkitPaddingAfter: "0px"webkitPaddingBefore: "0px"webkitPaddingEnd: "0px"webkitPaddingStart: "0px"webkitPerspectiveOriginX: ""webkitPerspectiveOriginY: ""webkitPrintColorAdjust: "economy"webkitRtlOrdering: "logical"webkitRubyPosition: "before"webkitTapHighlightColor: "rgba(0, 0, 0, 0)"webkitTextCombine: "none"webkitTextDecorationsInEffect: "none"webkitTextEmphasis: ""webkitTextEmphasisColor: "rgb(68, 120, 170)"webkitTextEmphasisPosition: "over"webkitTextEmphasisStyle: "none"webkitTextFillColor: "rgb(68, 120, 170)"webkitTextOrientation: "vertical-right"webkitTextSecurity: "none"webkitTextStroke: ""webkitTextStrokeColor: "rgb(68, 120, 170)"webkitTextStrokeWidth: "0px"webkitTransformOriginX: ""webkitTransformOriginY: ""webkitTransformOriginZ: ""webkitUserDrag: "auto"webkitUserModify: "read-only"webkitUserSelect: "text"webkitWritingMode: "horizontal-tb"whiteSpace: "normal"widows: "1"width: "940px"willChange: "auto"wordBreak: "normal"wordSpacing: "0px"wordWrap: "normal"writingMode: "lr-tb"x: "0px"y: "0px"zIndex: "auto"zoom: "1"

**Comment by triune** [comment]
However, where this warning is coming from is still not obvious to me...

**Comment by Rycochet** [comment]
Maybe someone else has come across this - it looks like a Chrome bug reporting bug - the more recent releases have been lacking in some checking in some other places too - got a fiddle that shows the report happening?

**Comment by triune** [comment]
Not a fiddle, but it's in use and can be seen here:
https://pl.nlm.nih.gov/eqsouthasia2015/report

**Comment by kenwheeler** [comment]
Can you please create a JSFiddle recreating the issue using our template, which is available here:

http://jsfiddle.net/65xCP/4/

Once I can view the reduced test case, I can more effectively isolate and address your issue.

**Comment by triune** [comment]
I think this may have been a Polymer issue and not a Velocity issue as the problem / warning message seems to have disappeared in recent bower updates to Polymer.

**Comment by kenwheeler** [comment]
Awesome, thanks
