### ISSUE TITLE
Using latest version, console.logs say latest features aren't available...

### ISSUE THREAD

**Issue by finetype** [julianshapiro/velocity#602]
```   
<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script src="../bower_components/velocity/velocity.min.js"></script>
    <script src="../bower_components/velocity/velocity.ui.min.js"></script>
    <script type="text/javascript" src="../bower_components/Materialize/dist/js/materialize.min.js"></script>
  </body>
</html>
```

That's the bottom of my html document. 

When I try to call

`$('i.mdi-navigation-menu').velocity("callout.bounce");`

I get this in my console:

`Velocity: First argument (callout.bounce) was not a property map, a known action, or a registered redirect. Aborting.`

I also find that when I try to use a sequence by calling

`$.Velocity.RunSequence(mySequence);`

I get 

`Uncaught TypeError: $.Velocity.RunSequence is not a function(…)`

However, velocity IS working, and I am using it to manipulate my navbar while getting these errors. 

What's going on? Am I missing something stupid obvious, or is there a bug?

I did a fresh bower install just earlier tonight, and have version 1.2.3, which appears to indeed be the latest version...

**Comment by Rycochet** [comment]
Just curious - but when you say "at the bottom of my html" - if you run the same line in the console itself is it working? Just wondering if you somehow have a race condition from not putting it in the <head> as normal (yes, it's perfectly valid nearly everywhere - but better to ask the obvious questions first) ;-)

**Comment by finetype** [comment]
Yes, while troubleshooting, I tested all in the console and in the code. 

Have access to the velocity that works in the code. Can animate elements on my page from the console in any way I normally can. Cannot do any of the things I mentioned above that I cannot do in the console or in the code.

**Comment by finetype** [comment]
Just to be clear. I can type:

`$.Velocity.animate($("i.mdi-navigation-menu"),"callout.bounce")`

in the console and I get the above error, but if I type

`$.Velocity.animate($("i.mdi-navigation-menu"),{"padding-left":200})`

things move.

**Comment by kokarn** [comment]
Seems like ui pack isn't working as intended. Try loading it from jsdelivr instead perhaps?

**Comment by finetype** [comment]
Tried loading from jsdelivr, no difference. (Both packaging uipack & regular together, or just uipack by itself).

Worth noting: if I copy/paste the entirety of velocity.ui.js into my console, I do get its contents. So something silly is going on. Going to paste my html page here, maybe I'm overlooking something obvious...

```
<!DOCTYPE html>
<html>
  <head>
    <!--Import Google Icon Font-->
    <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!--Import materialize.css-->
    <link type="text/css" rel="stylesheet" href="../bower_components/Materialize/dist/css/materialize.min.css"  media="screen,projection"/>

    <link type="text/css" rel="stylesheet" href="../test.css"  media="screen,projection"/>
    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link rel="icon" href="./water.png">

    <script src="../bower_components/mithril/mithril.min.js"></script>
    <script src="../bower_components/moment/min/moment.min.js"></script>
  </head>

  <body>
    <div id="SPA"></div>    
    <script src="./mithril_app_new/models/User.js"></script>
    <script src="./mithril_app_new/routes.js"></script>
    <script src="./mithril_app_new/models/Card.js"></script>
    <script src="./mithril_app_new/models/Deck.js"></script>
    <script src="./mithril_app_new/landing.js"></script>
    <script src="./mithril_app_new/sidebar.js"></script>
    <script src="./mithril_app_new/home.js"></script>
    <script src="./mithril_app_new/viewDeck.js"></script>
    <script src="./mithril_app_new/shared.js"></script>
    <script src="./mithril_app_new/newDeck.js"></script>
    <script>
      if(localStorage.mindSeal === "true") User.getDecks(router);
      else router();
    </script>

<!-- 
    <script src="./mithril_app/settings.js"></script>
    <script src="./mithril_app/about.js"></script>
 -->

    <!--Import jQuery before materialize.js-->
    <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <!-- // <script src="../bower_components/velocity/velocity.min.js"></script> -->
    <!-- // <script src="../bower_components/velocity/velocity.ui.min.js"></script> -->
    <script src="https://cdn.jsdelivr.net/g/velocity@1.2.3(velocity.ui.min.js+velocity.min.js)"></script>
    <script type="text/javascript" src="../bower_components/Materialize/dist/js/materialize.min.js"></script>
  </body>
</html>

```

**Comment by kenwheeler** [comment]
Looking into this

**Comment by finetype** [comment]
I don't know why, but as a shot in the dark I just moved materialize above velocity right after I posted the above, but below jquery, and it looks like it's working now. No idea why that would affect it, but apparently something in materialize interferes... Might go post something over there and ask them about it?

**Comment by kokarn** [comment]
Probably. What even is materialize?

**Comment by finetype** [comment]
@kokarn

http://materializecss.com/

**Comment by kokarn** [comment]
Oh, cool. Like a modern bootstrap ^^

**Comment by Rycochet** [comment]
Had a very brief look - and Materialize includes it's own copy of Velocity (an out of date one too from the looks of it) - so at a guess there's some conflict going on between the two versions - https://github.com/Dogfalo/materialize/blob/master/js/velocity.min.js

**Comment by finetype** [comment]
That would explain it. Mystery solved, thanks.

**Comment by finetype** [comment]
I did a pr to update materialize. Now has 1.2.3 of velocity, but also
refuses to overwrite jQuery.Velocity if it exists and puts a console log
notification. Should help some people in the future avoid this issue (UI
pack being silently overwritten mysteriously).
