### ISSUE TITLE
Can auto-removal of default transform values be disabled?

### ISSUE THREAD

**Issue by GiedriusT** [julianshapiro/velocity#603]
Hello,

as I understand it is the expected behavior for Velocity to remove individual transform values if they reach the default. Can this be turned off somehow?

Example of the problem would be a translateZ: 0 hack that enables you to force browser to give an element separate composite layer. If i set it inside .velocity animation call, it gets removed from the inline style declaration. And since other transform properties are left in the inline style declaration, the whole transform rule gets overridden, so even if I had translateZ: 0 defined for that element in my stylesheet, it gets overridden and my composite layer is gone. The only workaround I found is to set translateZ to something line 0.0000001px. Then it doesn't get removed, but...it's really ugly. 

Is there a nicer way to achieve what I want using Velocity?

**Comment by MattyBalaam** [comment]
At the moment Velocity does leave values if used correctly. See https://github.com/julianshapiro/velocity/issues/224

I agree that this should be a customisable option to enable or disable though.

**Comment by GiedriusT** [comment]
I see that it is true for properties like translateX, but I don't the same behavior with translateZ. Here's a quick example: http://codepen.io/anon/pen/avjvoY

As you will notice transformZ is placed on element when animation takes place, but is completely removed after.

**Comment by MattyBalaam** [comment]
That looks like a bug in Velocity to me.

**Comment by GiedriusT** [comment]
To me too. Maybe it has something to do with HA. I read that Velocity automatically enables HA on elements. And "enables" probably means using translateZ: 0 hack, as there's no better way to achieve that as far as I know.

**Comment by Rycochet** [comment]
V2 no longer removes any values itself, though it also doesn't supply (semi-broken) helper properties for the transform property
