### ISSUE TITLE
[Improve Scroll] Detect end of page 

### ISSUE THREAD

**Issue by franciscolourenco** [julianshapiro/velocity#604]
When velocity tries to scroll to an element, and the page is not long enough for the element to reach the top of the page, the scroll abruptly stops when the page reaches the end, in practice discarding the final easing. Example: http://jsbin.com/xopiyeweto/1/edit?html,css,js,console,output

The proposal is for velocity to detect when the page is not long enough, and in those cases adjust the scrolling amount so that the end of the animation matches the end of the page reaching the bottom of the screen.

**Comment by Rycochet** [comment]
The issue with scrolling down is that you might be loading more content as it scrolls - with scrolling up you already know that it can get as far as 0 and no further.

Not sure if this wants an optional bounds check (default on), or if it should be totally left up to the user.

Anyway, using bounding box, check target.bottom against container.bottom and container.height and then fiddle the numbers...

**Comment by aristidesfl** [comment]
I would say the cases where extra content is loaded are fewer than the cases where you want to scroll to an element on a normal page which might be at the end. The idea is that this case is covered by default, as a general rule.

**Comment by Rycochet** [comment]
Content changing length is probably more of a situation for progress callbacks to change - will think about this a bit more, but seems like a good plan for v2 :-)

**Comment by Rycochet** [comment]
For version 2 `scrollTop` and `scrollLeft` will be properties, and will use units including % which will take into account the visible height and the total height (so 0% is top to the top, and 100% is bottom to the bottom).

**Comment by Rycochet** [comment]
You can supply a % to `scrollTop` as well as a simply `px` value, which lets it animate to the correct pixel value semi-automatically.
