### ISSUE TITLE
Is CSS transform skew (x,Y) Equivalent exist for Velocity.js ? 

### ISSUE THREAD

**Issue by fleyer** [julianshapiro/velocity#605]
Hello Julian,

I notice that i can't have the same result from css transform skew(x,y) with Velocity.
http://jsfiddle.net/xqhqwyL3/
I think it's not an issue so sorry if my post isn't in the right place.

My idea is that I want to create a personal web site with a " star menu". So i need to use skew transformation with animation. I know I have to define transform in js otherwise the animation will overwrite the transform property.

Also, I know a part of the problem is that Velocity respect "SVG transformation", so we can't use skew with 2 arguments.

I tried to find something in Velocityt's source file but I only found that there is no merge for skew property.

My problem is very particular and i might be the only one who want to do that but still, if you have a solution for me it would be great =).

Velocity is a stunning work men thanks a lot !

Cordialy Romain.

PS : Sorry for my english I have tried my best but ... I know it's bad.

**Comment by ibrierley** [comment]
Indeed, I think what you are saying is that skew(35,35) != skewX(35) skewY(35) ? Which is correct, so they aren't interchangeable like that. In the absence of any other solutions, you could roll your own with progress. I'm not sure if this method loses any efficiency brought about with Velocity, but it should be ok if necessary as a workaround. 
```
$(".loxange").velocity(
    { tween: 35 },
    { progress: skewFunc },
    1000);

function skewFunc(elements, complete, remaining, start, tweenValue) {
  var t = 'skew(' + tweenValue + 'deg,' + tweenValue + 'deg)'
  elements[0].style.transform = t ;
}
```

http://jsfiddle.net/ian_b/xqhqwyL3/4/

**Comment by fleyer** [comment]
Hello julian,
Thanks for your answer, I didn't know this tips. It's quite interesting and
I will try as soon as I can. Thanks again !

Cordialy Romain
