### ISSUE TITLE
animations not working on gh-pages

### ISSUE THREAD

**Issue by dbrusky1** [julianshapiro/velocity#607]

**Comment by dbrusky1** [comment]
I have been two working sites with Velocity animations that have their own github pages.
Both sites animations are non existent.  Couldnt find a fix for this and was wondering if this was something I missed in velocity documentation.

**Comment by kenwheeler** [comment]
Are you seeing any errors in your console?

**Comment by dbrusky1** [comment]
Sorry, looks like its not loading my main.js file with animation script in
it.
I was loading jquery, then velocity, then the ui, then my main file.
Works on local.  But not on github.
