### ISSUE TITLE
Internal reference to requestAnimationFrame is not being replaced with wrapped setTimeout during execution time

### ISSUE THREAD

**Issue by Iwasawafag** [julianshapiro/velocity#611]
Little over a year ago a problem with native implementation of  `requestAnimationFrame` was reported. Any repainting (actually execution of passed functions) queued while page is resting on the background are being delayed and executed only when tab becomes visible (#176 - requestAnimationFrame background handling). 

It was fixed later in 5508fea, however fix wasn't quite perfect. For some reason check if page is hidden or not only being made when this state changes, implying it's always visible during loading and execution time, which is false. So if page happened to be on the background when Velocity's  code was executed - every animation still will be delayed and played only when tab will become visible.

Unless there was a reason for this (I don't see any), I think [event subscription](//github.com/julianshapiro/velocity/blob/f28c610da721048abee0be4f88a5d32d71ae8ea4/velocity.js#L3336..L3351) code should be changed to something like

``` javascript
if (!Velocity.State.isMobile && document.hidden !== undefined) {
    function spoofTicker() {
        /* Reassign the rAF function (which the global tick() function uses) based on the tab's focus state. */
        if (document.hidden) {
            ticker = function(callback) {
                /* The tick function needs a truthy first argument in order to pass its internal timestamp check. */
                return setTimeout(function() { callback(true) }, 16);
            };

            /* The rAF loop has been paused by the browser, so we manually restart the tick. */
            tick();
        } else {
            ticker = window.requestAnimationFrame || rAFShim;
        }
    }

    document.addEventListener("visibilitychange", spoofTicker);
    spoofTicker();
}
```

but with a better name for the function than the one I came up with. 

That's probably unnecessary, but here's a [very basic fiddle](http://fiddle.jshell.net/3d3bhsdh/show/) you can observe problem at. (Just click the link with Mouse3 button or Ctrl+Mouse1 to open it in a new tab without switching to it). After page is loaded wait for more than 2 seconds (that's the duration of initialized animation) and switch to it - you will see animation playing.

**Comment by Rycochet** [comment]
I noticed this myself elsewhere - needs to be fixed for pages loading in the background at the very least!
