### ISSUE TITLE
Velocity won't work on Safari 9.0.1!!!!

### ISSUE THREAD

**Issue by jkiss** [julianshapiro/velocity#614]
## Velocity will encounter problem on *Safari 9.0.1* !!! It will stop running all animation, and the element won't come out!

**Comment by kenwheeler** [comment]
Just tested 1.2.3 with 9.0.1 and it is indeed working. Care to share any more detail on the nature of your problem? Are you getting a particular message in the error log?

**Comment by jkiss** [comment]
My version is 1.2.2, and when I change to animate, it will work, but no transition. Maybe my web use up a lot of resource.

**Comment by jkiss** [comment]
when i run below in console :
```javascript
> $('#loading_wrap').velocity({opacity:0}, 1000);
> m [<div id="loading_wrap">] (1) = $1
```
The element still there, it's not work....

**Comment by jkiss** [comment]
Sorry, guys, it's my fault. I haven't  shutdown my MB for a long time, and chrome opened a lot of tabs. It's ok after i restart...but only safari has this problem.
