### ISSUE TITLE
fadeIn/faceOut on div with fixed/absolute positioned element is laggy in IE 10/Edge

### ISSUE THREAD

**Issue by eweseong** [julianshapiro/velocity#617]
When i tried to animate a div with an element that is fixed or absolute, the fix element fading will be slightly lag or some what delay. Create a fiddle to recreate the scenario, kindly test it on IE 10/Edge in comparison to Chrome. https://jsfiddle.net/z05ojckg/

**Comment by Rycochet** [comment]
The ui-pack animations have been rewritten and should be almost identical performance to css animations.
