### ISSUE TITLE
Documentation is confusing

### ISSUE THREAD

**Issue by basickarl** [julianshapiro/velocity#622]
Can I use this library as a stand alone without any dependencies? If So can you please make a simple example of a fadeout on an element in pure JavaScript/velocity.

```
<script src="/js/velocity.min.js"></script>
<script>
 var div = document.getElementById'(myElement');
Velocity(div, {
        opacity: 0.0
     }, {
        duration: 2000
});
</script>
```

I get the error:
```
'Velocity' is undefined
```

**Comment by MrGeneric** [comment]
You problem is here:  '(myElement'); 

The first quote should be inside the parentheses.
