### ISSUE TITLE
Why   animation element z-index will be changed      when I use velocity. js animation element z-index will be changed   such transition.slideLeftBigIn

### ISSUE THREAD

**Issue by ShiXiaoyYu** [julianshapiro/velocity#626]
Why   animation element z-index will be changed      when I use velocity. js animation element z-index will be changed   such transition.slideLeftBigIn ; It can not be covered ，Although the z-index is relatively small

**Comment by kenwheeler** [comment]
Can you please create a JSFiddle recreating the issue using our template, which is available here:

http://jsfiddle.net/65xCP/4/

Once I can view the reduced test case, I can more effectively isolate and address your issue.

**Comment by ShiXiaoyYu** [comment]
i saw the source code     scale /*   Chrome on Android has a bug ...... ensure that its first value is always 1*/

**Comment by Rycochet** [comment]
Are you sure it' the `z-index` changing? When animating a `transform:translateZ(0);` is added which moves the animation into the GPU making it far smoother (there's lots of information around proving the need for it) - but that takes the element out of the current z-index context and forces it to the front - have you tried adding `mobileHA:false` to your options?

**Comment by renestalder** [comment]
Please try setting mobile acceleration to false.

Example:
```js
$element.velocity(propertiesMap, { mobileHA: false });
```

Most of those problems occur because of the translateZ which is added during animation to hardware accelerate. You can deactivate this for specific animations to get rid of z-index problems.
