### ISSUE TITLE
Use velocity without jquery, even when available

### ISSUE THREAD

**Issue by renestalder** [julianshapiro/velocity#627]
I always try to write my own modules without jQuery dependency. However, there are still some components depending on jQuery, so It's loaded on the website.

The problem: When jQuery is available, it seems not possible to use `Velocity()`function from the global scope. Instead I guess I have to stick to the jQuery implementation.

Or can I force use the Velocity function?

**Comment by MattyBalaam** [comment]
You could wrap it in something like an IIFE.

```javascript
(function(window, document, Velocity, undefined){
	
//code here

}) (window, document, window.jQuery.Velocity);
```

**Comment by renestalder** [comment]
hmm. That's a nice idea and I guess it will work as it should work without jQuery then?

**Comment by MattyBalaam** [comment]
If you aren’t sure if you will have jQuery, change the final line to: 

```javascript
}) (window, document, window.jQuery ? window.jQuery.Velocity : window.Velocity);
```

**Comment by renestalder** [comment]
I like that. Thank you.
