### ISSUE TITLE
scrollTop problem?

### ISSUE THREAD

**Issue by teuz80** [julianshapiro/velocity#628]
Hi, i've tried velocity and it works great! 

I think there's a problem with scrollTop property.
jQueryElement.velocity({scrollTop:'+=300'}, 400); -> it doesn't work
jQueryElement.animate({scrollTop:'+=300'}, 400); -> it works

**Comment by kenwheeler** [comment]
Can you please create a JSFiddle recreating the issue using our template, which is available here:

http://jsfiddle.net/65xCP/4/

Once I can view the reduced test case, I can more effectively isolate and address your issue.
