### ISSUE TITLE
Display none when slideup animation finishes

### ISSUE THREAD

**Issue by axul** [julianshapiro/velocity#630]
Is it necessary for the  slideup animation to set the element to display:none after is finished? this create a small issue for when I wanna do some calculations on those elements giving that i'm using it in an accordion menu and the initial state is all contents collapsed. No a big issue but, can the slideup state be just height:0px?

**Comment by rizadh** [comment]
I feel at this point, they won't change the behaviour as it could break a lot of people's code. But in your case you could use "display: null" as an option to prevent the default behaviour.

**Comment by kenwheeler** [comment]
If enough people think this is a good idea, I can update it as a major bump, but is there a workaround you can use?

**Comment by axul** [comment]
@kenwheeler yep I can go back to my own made animations (that are not as good) since I don't wanna touch the code. The calculations I was talking about before are for text selections using rangy, and the code already works and syncs fine with the server, I'm scared to go back and change it haha.

You count with my vote to make the update but I see that is not that easy.

**Comment by axul** [comment]
@rizadh to this day I didn't now about display: null, I'll try with that, it would be nice to keep the velocity slideup in my code

**Comment by rizadh** [comment]
@kenwheeler  I personally believe it's better to just keep the current "slideUpOut" behaviour as it's consistent with the other "Out" transitions (in that that `display` is set to `none`) , especially since we DO have the `display: null` option if needed.

**Comment by rizadh** [comment]
@axul Haha, I knew my time spent pouring over the documentation couldn't have been in vain. Hope display: null ended up working for your case!

**Comment by axul** [comment]
@rizadh  I'll let you know later!

**Comment by kenwheeler** [comment]
Ok lets leave this one alone. Closing, thanks!

**Comment by axul** [comment]
@rizadh  @kenwheeler  thanks, it worked using velocity options 'display:null' and setting height auto on slideDown begin and height 0px on slideUp complete
