### ISSUE TITLE
Animate css clip-path

### ISSUE THREAD

**Issue by alexandre-works** [julianshapiro/velocity#631]
Enabled animation of clip-path as we do for clip: rect

**Comment by Rycochet** [comment]
That's unlikely to happen as clip-path is not a simple/single number - use the progress callback and tween values to put in exactly what you want to animate - there was a somewhat related comment somewhere for parsing out values within a string for animation, but can't remember exactly which one it was under (it was part of a longer discussion).

**Comment by kenwheeler** [comment]
Thanks @Rycochet

**Comment by alexandre-works** [comment]
@Rycochet thanks ;)
But would be nice to have a exemple how to use that. Anyway cheers and thank you man

**Comment by Rycochet** [comment]
Look at the "**Custom Easings (Advanced)**" heading under here - http://julian.com/research/velocity/#easing

*or*

The entire Progress section here - http://julian.com/research/velocity/#progress

Please not they're mutually exclusive for what you want - choose one and stick to it (personally I prefer the Progress section style)
