### ISSUE TITLE
Sequence error

### ISSUE THREAD

**Issue by SndrL** [julianshapiro/velocity#633]
Trying to make a sequence, copied and adjusted the code from the codepen example.

var $element1 = $(".navigation"),
    $element2 = $(".navigation .hidden");

var mySequence = [
    { e: $element1, p: { translateX: "100" } },
    { e: $element2, p: { translateX: "100" }, options: { sequenceQueue: false } }
  ];

$.Velocity.RunSequence(mySequence);

I get the following console error: **"Uncaught TypeError: Cannot read property 'RunSequence' of undefined"**

**Comment by SndrL** [comment]
I was using jQuery 1.12.0,
changed it to 2.2.0 and it started working.

Might want to look into this, or mention it in the docs.

**Comment by Rycochet** [comment]
The only difference between 1.* and 2.* *should* be the old legacy IE code - if you've got the time to track down exactly what's going on then it would help :-)

**Comment by filippolcr** [comment]
Worked for me with jquery 1.12.0

Try to code in this way:

```
var mySequence = [
{ e: $element1, p: { translateX: "100" } },
{ e: $element2, p: { translateX: "100" }, o: { sequenceQueue: false } }
];
```

**Comment by SndrL** [comment]
Haven't gotten the time to track it down, but problem probably exists between keyboard and chair ;-)
Sorry and thanks for your time guys! This can be closed.
