### ISSUE TITLE
Duplicate data property in object literal not allowed in strict mode

### ISSUE THREAD

**Issue by damusix** [julianshapiro/velocity#634]
Happening on some iPhone 6 Safari's and Android native browser. Everything else is fine. Just a heads up. Here's the culprit (as per TrackJS)

    kipedia.org / wiki / MIT_License.Portions copyright Daniel Eden, Christian Pucci.*/! function(e) {
            "function" == typeof require && "object" == typeof exports ? module.exports = e() : "function" == typeof define && define.amd ? define(["velocity"], e) : e()
        }(function() {
                return function(e, t, n, r) {
                        function i(e, t) {
                                var n = [];
                                return

**Comment by Rycochet** [comment]
v1.3.0 is strict, if this still happens when updated then feel free to reopen.
