### ISSUE TITLE
can not visit http://julian.com/research/velocity/

### ISSUE THREAD

**Issue by Wumingla** [julianshapiro/velocity#637]
hello,friends! The http://julian.com/research/velocity/ may be something wrong and we can not visit

**Comment by ibrierley** [comment]
Works fine for me.

**Comment by Rycochet** [comment]
Things like this are always worth checking somewhere like http://www.isitdownrightnow.com/julian.com.html before reporting, as *most* issues will be a routing issue at your own end and not the server end.

**Comment by kenwheeler** [comment]
Working on my end, but expect to see the docs in markdown format right in the repo in the very near future

**Comment by Wumingla** [comment]
It is ok know,thanks!
