### ISSUE TITLE
Forcefeeding with Value function doesn't work

### ISSUE THREAD

**Issue by bravedick** [julianshapiro/velocity#639]
Hi. Things like doesn't:

`Velocity(stackedPhotosShadows, {
        translateY: function(i) {
          return [0, -10 - 5 * (5 - i)];
        }
      }, {
        delay: 700,
        duration: 900,
        easing: 'easeInOutSine'
      });`

**Comment by kenwheeler** [comment]
Hey, trying to understand the exact issue, could you create a JSFiddle to reproduce and show the issue happening?

**Comment by bravedick** [comment]
@kenwheeler sure: https://jsfiddle.net/7k5Lfjch/1/

**Comment by Rycochet** [comment]
I'm not sure either - [Forcefeeding](http://julian.com/research/velocity/#forcefeeding) requires an array to be passed with the second (or third) value to be the array. This is using [Value Functions](http://julian.com/research/velocity/#valueFunctions).

Changing the example to use a direct array works identically to the function, regardless of whether it's meant for forcefeeding or value functions...

**Comment by Rycochet** [comment]
Changing from

```
Velocity(stackedPhotosShadows, {
  translateY: function(i) {
    return [0, -35 - 5 * i];
  }
})
```

to -

```
Velocity(stackedPhotosShadows, {
  translateY: [0, function(i) {
    return -35 - 5 * i;
  }]
});
```

works - so looks like a single function should be evaluated before checking if it's force-fed.
