### ISSUE TITLE
"offsetHeight" & "offsetParent" deprecated and will be removed in Chrome M50

### ISSUE THREAD

**Issue by thiphariel** [julianshapiro/velocity#643]
Hi.

Is there an update scheduled about this ? Chrome console warn me about deprecated properties, and the problem is that these properties will be removed around April 2016.

Two screenshots about it :
![1](https://cloud.githubusercontent.com/assets/3125705/13315628/193b9416-dbac-11e5-83bb-8381ace9e2b4.png)
![2](https://cloud.githubusercontent.com/assets/3125705/13315629/193e6178-dbac-11e5-8f93-6b3f8a30ed4e.png)

Link : https://www.chromestatus.com/features/5724912467574784

Thanks

**Comment by Rycochet** [comment]
SVG in Velocity is a bonus - so things like this are somewhat "caveat emptor" - if we've got any code that references those directly then it would be a good idea to get away from them anyway..
