### ISSUE TITLE
change destination values while tweening

### ISSUE THREAD

**Issue by mh-cbon** [julianshapiro/velocity#645]
Hi,

I m looking for a way to change destination values of an animation while it runs.

Any ideas ?

thanks

**Comment by Rycochet** [comment]
Please note this is a question on how to do something and should be on stackoverflow, not the issue tracker.

Not possible to change a direct animation, however a progress callback and tween value would let you do it.

**Comment by mh-cbon** [comment]
thanks, i was not sure if i missed something or not. i ll see on SO, as it does not seem so easy, to me.
