### ISSUE TITLE
Promises resolve before loop completion

### ISSUE THREAD

**Issue by patience-tema-baron** [julianshapiro/velocity#648]
When an animation is set to loop, it completes its final iteration in its initial state. So if it was `{ opacity: 1 }` initially and looped to `{ opacity: 0.5 }`, it'll return to `{ opacity: 1 }` in its final resting state. However, its Promise resolves when it reaches the last `{ opacity: 0.5 }`. I made a [little fiddle](http://jsfiddle.net/rwfj49L2/) to illustrate.

Not sure if this is intended, but the behavior different from what I expected so I thought I'd report. Either way, thanks for this amazing library!

**Comment by Rycochet** [comment]
Possibly link this in to #654

**Comment by Rycochet** [comment]
Promises in V2 resolve correctly in this situation.
