### ISSUE TITLE
backgroundColorAlpha always transitions with 'white' as base

### ISSUE THREAD

**Issue by renestalder** [julianshapiro/velocity#650]
Not sure what I'm doing wrong.

When I transition an element with backgorundColorAlpha to a color opacity of 0 and then transition it back, it doesn't seem to work correctly for me.

Set transparent background:

``` javascript
elements.$dialog.velocity({
  backgroundColor: '#000000',
  backgroundColorAlpha: 0
})
```

Set alpha transparent background (same as rgba(0,0,0,0.5)).

``` javascript
elements.$dialog.velocity({
  backgroundColor: '#000000',
  backgroundColorAlpha: 0.5
})
```

The element results in different color, transitions with white instead of black, `background-color: rgba(255, 255, 255, 0.498039);`

<img width="698" alt="screenshot 2016-03-15 23 54 11" src="https://cloud.githubusercontent.com/assets/105358/13796803/42aa84bc-eb09-11e5-8054-45017ab1635a.png">

**Comment by Rycochet** [comment]
Needs a demo / test case for us to look at - but definitely looks like an inconsistency there.
