### ISSUE TITLE
CSS Transform Skew reset to default while animating the width in Mobile.

### ISSUE THREAD

**Issue by Lalnuntluanga** [julianshapiro/velocity#651]
I am using CSS transform skew to make it skew shape on the images. While changing the width of the images, these skew don't work and come back to skew shape after animation in Mobile (Android and iOS)

[Widget.zip](https://github.com/julianshapiro/velocity/files/176108/Widget.zip)

**Comment by MattyBalaam** [comment]
I can't see anything obviously wrong on an Ipad Air 2

**Comment by Lalnuntluanga** [comment]
Hi Matt.

Sorry for the link. I have updated the unit to use CSS3 animation to handle that particular gallery.

Please find the attached zip file so that you will able to reproduce the issue.
https://github.com/julianshapiro/velocity/files/176108/Widget.zip

**Comment by MattyBalaam** [comment]
Could be a bug. To workaround I would suggest forcefeeding the skew value, and removing the 'begin' function.

			{e: $("#lastImageFrame"), p : {
				width: collapsedWidth,
				skewX: ['-6deg', '-6deg']
			}, o : {delay: delay-700, duration: duration+200, easing: "easeOutSine", }},

**Comment by Lalnuntluanga** [comment]
Hi Matt,

Thanks for the suggestion. I'm a big fan of velocity and want it to be as stable as possible. I will implement your workaround in my project.

**Comment by philippklodt** [comment]
I do not think it's a bug.

Transform values that are not set via Velocity are ignored, it's in the [docs][http://julian.com/research/velocity/#transforms].
This includes css-files and the `$.css()` function, which was used here if I saw it right.

To *set* (not animate) a single transform value, there's the hook function as a clean solution:
```
$.Velocity.hook($elements, 'skewX', '6deg');
```

**Comment by Rycochet** [comment]
It's not so much that they're ignored as Velocity uses what's called Mobile Hardware Acceleration - http://julian.com/research/velocity/#mobileHA - which basically adds `transform:translateZ(0)` to the element while animating on mobile devices - unfortunately that can't be merged with existing `transform:xyz` values, hence the need to forcefeed the value you want so it can add it to the css used. There was talk about adding transform parsing which would have worked, but I don't think it ever got resolved.
