### ISSUE TITLE
Improve documentation regarding promises polyfill usage.

### ISSUE THREAD

**Issue by MattyBalaam** [julianshapiro/velocity#652]
It took me a couple of hours to track down why I couldn't use a polyfill to get promises support in IE11 and lower.

It turns out including the polyfill is not enough and you need to attach the Promise function to velocity. e.g.   $.Velocity.Promise = Promise;

Example here: http://codepen.io/MattyBalaam/pen/RaKVbM

It would make sense I think to include this in the documentation section on using a polyfill for promises usage.

**Comment by lddubeau** [comment]
Velocity grabs its value for `$.Velocity.Promise` from `window.Promise` *at the time Velocity is loaded*. If it is undefined when Velocity is loaded, then it will remain undefined even if a polyfill *later* installs itself as `window.Promise`.

The codepen you link to has the polyfill loaded after Velocity. To get the behavior you want (Velocity using the polyfill automatically), you should load your polyfill before you load Velocity. The requirement that the polyfill be loaded by anything that might need it is not special to Velocity but a general rule of using polyfills: load a polyfill before the code that needs it.

**Comment by MattyBalaam** [comment]
Ah, OK. That makes sense, thanks for the clarification.
