### ISSUE TITLE
"scroll" and anchor links within an iFrame on iOS

### ISSUE THREAD

**Issue by Agentrouble** [julianshapiro/velocity#653]
Hello there,

I'm currently working on a project that will be rendered inside an iFrame. 

I've decided to use velocity to make scroll animation when it comes to anchor links within my pages. 

It works perfectly in iFrames when using Chrome for Android and for PC. But when it comes to iOS, it just won't work at all. I've been working on two iPad to test my project, using iOS8 and iOS9. 

You can use the following codePen to see a simple reproduction of the bug : 
http://codepen.io/Agentrouble/pen/ONWpKB

As you can see, trying to click on a link will result in the whole iFrame bugging out and flickering. 

It's worth mentionning, that my code is working out perfectly out of an iFrame.  I've been looking for an alternative to workaround this issue, and it is not possible for me to avoid iFrames on this one.

Have a good day

**Comment by Rycochet** [comment]
Sadly I'm going to make a very unhelpful comment here - iFrames on iOS are some of the most annoying things around - I've had quite a few projects in the past that have had to use them, and the end result is always work-arounds and sidestepping the bug that is Safari - there's quite a lot of helpful posts on StackOverflow - but generally you need to treat an iFrame on iOS as a black box that doesn't behave properly - don't try to scroll it - scroll outside or inside, but not the window within the iFrame itself :-/

**Comment by Agentrouble** [comment]
.Yeah I'm realising the hard way that iFrame are really tough to deal with.

Fortunately, I found a workaround just now by testing out different things. It works both for iOS8 and iOS9.

The codepen http://codepen.io/Agentrouble/pen/ONWpKB contains what is necessary.

The "container" option must be filled with the direct parent of our anchor elements. 
This container must have a defined height, width, overflow-x, overflow-y and a position (like it's specified in the doc). 

I'm leaving this open up until I'm sure everything is working out perfectly.

**Comment by Rycochet** [comment]
Hopefully this will help someone else - an iOS workaround for something relating to iFrames ;-)
