### ISSUE TITLE
Is it possible to animate a single numerical value using velocity. 

### ISSUE THREAD

**Issue by JoyKrishnaMondal** [julianshapiro/velocity#657]
hey, 

Is it possible to sync lets say a counter to scale animation of a box ? where the counter shows the scale value.

In [popmotion ](https://popmotion.io/) you can attach a key-value pair ( that is not a CSS ) and have it ease animate over a duration. 

Is something like that possible with velocityJS - is it possible to animate things _besides_ css properties.

**Comment by MattyBalaam** [comment]
http://julian.com/research/velocity/#progress

**Comment by JoyKrishnaMondal** [comment]
Ahh. Thanks ! 

Is there a chatroom/gitter for beginner velocity users ? 

thanks !

**Comment by Rycochet** [comment]
@JoyKrishnaMondal Please use [StackOverflow](http://stackoverflow.com/tags/velocity.js) for support questions (as noted on the front page of the project), this is meant for bug tracking...
