### ISSUE TITLE
velocity + Backbone + Jquery setup does not seem to work

### ISSUE THREAD

**Issue by siddo420** [julianshapiro/velocity#659]
I am new to Velocity and cant seem to make it work in my code. here is what I tried:

I tried including velocity script tag after jquery script tag but on Backbone elements $el, I don't see any .velocity property.

I then tried to lazy load (usng labjs) velocity after Jquery (using normal script tag).
```
$LAB.wait( function(){
	    $( function(){
		 window.jQuery = window.$ = $; 
		});
	  }) //jquery is loaded already, now downloading velocity next
	 .script( function(){
		return cdn_addr + 'js/vendor/velocity/velocity.min.js' 
	  })
//rest of the code is here
```
However, view.$el.velocity is 'undefined'. Similarly, if I access a DOM element using jquery $('li#324re') I still dont get a velocity property there.

What am I doing wrong?

**Comment by siddo420** [comment]
Please note that .animate is working fine.

**Comment by Rycochet** [comment]
I don't know the system you're using to load it, but sounds like Velocity isn't finding jQuery at all (or possibly not the correct version of jQuery) - I'd suggest tracking down with a couple of logging statements and a custom velocity copy with logging - you could shim the RequireJS functions to make sure it's using the correct one instead...

**Comment by siddo420** [comment]
I haven't worked with RequireJS.

Is it possible to force velocity to make use of JQuery?

Something like Velocity.jquery($);

**Comment by Rycochet** [comment]
Velocity uses jQuery if it exists on the window object when it's loaded - if it doesn't exist then it uses it's own shim instead.

RequireJS lets you specify that Vlocity requires jQuery - so it won't try to load Velocity until after jQuery has loaded (there's several other threads mentioning it) - it's a really good way of doing things, the same as labjs in terms of loading, but most libraries support it and let themselves be loaded as modules without any extra work (thanks to the shim, Velocity needs an extra line of work).

**Comment by siddo420** [comment]
I have already made sure (thru debugging messages) that 'window.jQuery = window.$ = $;'  gets executed before Velocity script is loaded.

Do you know if 'window.jQuery = window.$ = $; ' is the right way of attaching JQuery object to window? 

I have read your documentation and other threads. And, changing the module system at this point will take a long time (and doesn't seem to be the issue here, see below). 

I tried the following:
```
.wait( function(){
	    $( function(){
		 window.jQuery = window.$ = $; 
		 DEBUG && console.error( 'Loading Jquery... ' );			
		});
	  })
	 .script( function(){
		DEBUG && console.error( 'Loading Velocity' );
		return cdn_addr + 'js/vendor/velocity/velocity.min.js' 
	  }).wait(function(){
	    $("body").velocity({ opacity: 0.5 });
	  }) 
```
"Loading Jquery" is printed before "Loading Velocity" and also the opacity is applied to the body element (I can see that of course). However, velocity is not doing anything in the example below:

The code below keeps scrollbar at the bottom of container when new contents are added to container (cv).
```
cv.$el.animate({ scrollTop: cv.$el.prop( "scrollHeight" )}, this.first_time ? 0 : 1000 );
```
However, replacing '.animate' with '.velocity' does not do anything and I can see that 'typeof .velocity' is function, so its available. 

We still have the issue of 'undefined' in some other part of code, but I am investigating on that.

**Comment by siddo420** [comment]
looks like I needed velocity UI for that ... seems to work after loading velocity UI.

I will report back on the 'undefined' issue or close this issue.

**Comment by siddo420** [comment]
Please disregard the last message, it was animate that I used (not .velocity), so velocity and velocityUI both dont seem to work  in the following case:

```
cv.$el.animate({ scrollTop: cv.$el.prop( "scrollHeight" )}, this.first_time ? 0 : 1000 );
```

**Comment by Rycochet** [comment]
Velocity has totally different use of scroll - though if `$.fn.velocity` doesn't exist then it's because the global window jQuery is changing after Velocity has been loaded.

**Comment by siddo420** [comment]
>>Velocity has totally different use of scroll

Does that mean its not a drop-in replacement of .animate? 

In the example below, velocity is available on the element but its not doing anything.
```
cv.$el.velocity({ scrollTop: cv.$el.prop( "scrollHeight" )}, this.first_time ? 0 : 1000 );
```
However, animate works fine (replacing velocity with animate from example above.
```
cv.$el.animate({ scrollTop: cv.$el.prop( "scrollHeight" )}, this.first_time ? 0 : 1000 );
```

**Comment by Rycochet** [comment]
http://julian.com/research/velocity/#scroll

**Comment by siddo420** [comment]
I've looked at that link before, but this time I tried making the new child view a "direct child" of the container. That seems to have worked but I'm still testing.
