### ISSUE TITLE
Value function only called once for "backgroundColor"

### ISSUE THREAD

**Issue by ericdolson** [julianshapiro/velocity#660]
I have 4 elements that I am trying to animate at once, but I also need to choose an appropriate background-color for each element. I made a thinned out and reproducible example [here](http://codepen.io/ericdolson/pen/EKXVEb).

To skip the demo, here is what is going on...

```
var $boxes = $(".box");  // Say we have 4 elements here

$boxes.velocity({
  backgroundColor: function(i) {
    console.log("backgroundColor[" + i + "]");
    return (i % 2 == 0) ? "#ccc" : "#f00"
  },
  zIndex: function(i) {
    console.log("zIndex[" + i + "]");
    return 0;
  }
}, {
  duration: 500,
  queue: false
});
```

If I want to change the background-color based on the element's index, I would use a value function like I did above. Obviously the zIndex value function is not necessary because it just returns 0, but it helps prove my point.

When I run this, my log looks like:

```
backgroundColor[0]
zIndex[0]
zIndex[1]
zIndex[2]
zIndex[3]
```

So the backgroundColor function only ran once! What's more, because it only ran once, all 4 elements get assigned the color that was resolved from the single value function call. In this case, i == 0 so all elements are `#ccc`.

Another thing to point out is that if I change `return (i % 2 == 0) ? "#ccc" : "#f00"` to `return (i % 2 == 0) ? "notvalid" : "#f00"`

my logs look like:

```
backgroundColor[0]
backgroundColor[0]
zIndex[0]
backgroundColor[1]
zIndex[1]
zIndex[2]
zIndex[3]
```

In this case, [0] stays white/clear and all the others turned red.

It is if the backgroundColor value-function is saying "Once we find a valid color, apply it to everything else. No need to call this function again."

How can I accomplish what I am trying to do? I think this is a bug, but am I wrong and this is expected behavior? I know I could hack the system and break out my elements into 2 separate arrays and act on them separately, effectively circumventing the value function, but I would prefer a better solution.

Thanks!

**Comment by Rycochet** [comment]
@kenwheeler  Looks like an actual bug to me.

**Comment by ericdolson** [comment]
I have traced what I think is the issue to [here](https://github.com/julianshapiro/velocity/blob/master/velocity.js#L2791).

It looks like for colors it is passing the regex test and get the endValue right away and then generates a backgroundColorRed, backgroundColorGreen, and backgroundColorBlue property based on it. But the problem is that any logic then the original value function is now gone and it is as if I originally said

```
{
  backgroundColorRed: 204,
  backgroundColorGreen: 204,
  backgroundColorBlue: 204
}
```
without value function logic.

**Comment by ericdolson** [comment]
I just re-did my [example](http://codepen.io/ericdolson/pen/JXJKjN) now that I know that `backgroundColor` is jut a convenience for the rgb properties. Now when I run 

```
var $boxes = $(".box");  // Say we have 4 elements here

$boxes.velocity({
  backgroundColorRed: function(i) {
    console.log("backgroundColorRed[" + i + "]");
    return (i % 2 == 0) ? 204 : 255
  },
  backgroundColorGreen: function(i) {
    console.log("backgroundColorGreen[" + i + "]");
    return (i % 2 == 0) ? 204 : 0
  },
  backgroundColorBlue: function(i) {
    console.log("backgroundColorBlue[" + i + "]");
    return (i % 2 == 0) ? 204 : 0
  },
  zIndex: function(i) {
    console.log("zIndex[" + i + "]");
    return 0;
  }
}, {
  duration: 500,
  queue: false
});
```

To me, this is a usable workaround. I am not excited about it, but I believe it is better than trying to divide up my elements arrays and call more than on `.velocity()` function in the end.

I would still love to see the convenience function work somehow though :)

**Comment by Rycochet** [comment]
Agreed - the convenience attribute should behave consistently with the direct attributes - thanks for tracking it down, hopefully it'll be a simple case of moving some code from one place to another :-)

**Comment by Rycochet** [comment]
When I initially looked at this I thought it was going to be a "wontfix" - then realised that simply skipping any properties where both start and end are functions (or only start if no end) would let it work the same way and be somewhat more logical - plus a minor optimisation on the way ;-)
