### ISSUE TITLE
Opacity animation force starts from zero

### ISSUE THREAD

**Issue by mu3** [julianshapiro/velocity#661]
From the [docs](http://julian.com/research/velocity/#displayAndVisibility):

> Further, if opacity is simultaneously animated, it'll be forced to a start value of 0. This is useful for fading an element back into view

I can't find a way to disable this behavior, here's a [pen](http://cdpn.io/e/vGZoZo) showing the difference between `.animate` and `.velocity`.
I ended up with a `.is(":visible")` check but that seems to me weird.

**Comment by Rycochet** [comment]
As you've not mentioned it, have you tried [forcefeeding](http://julian.com/research/velocity/#forcefeeding)?

**Comment by mu3** [comment]
Yes, but in my case I'm applying a few styles (let's say fading in) in a few places and then fadeIn in other. So this is a problem because once it faded the div out I want next calls to start from the current value (ideally resolve «animation finished» promise immediately if it's already in a final state).
Surely I can complicate the whole story with the promises or some state-flag-vars but the default jQuery's and CSS' behavior is simpler since I'm defining all style changes in one place.
Stop call is not a solution because of easing.
I think there's has to be an option for forcefed start as a current value (computedStyle) or option to disable force reseting opacity animation start to 0.

**Comment by Rycochet** [comment]
The `fadeIn` code is simply a normal velocity ui call - https://github.com/julianshapiro/velocity/blob/master/velocity.ui.js#L299 - maybe it shouldn't forcefeed, not sure - you can replace it with one without forcefeeding, but as it'd change the current behaviour maybe it needs more feedback from all of us community members on what makes more sense ;-)

**Comment by Rycochet** [comment]
The ui-pack has been rewritten as css animations matching animate.css
