### ISSUE TITLE
Hook function failed on SVG fill and stroke attributes.

### ISSUE THREAD

**Issue by guopengliang** [julianshapiro/velocity#663]
These doesn't seem to work:
`Velocity.hook(someDOMNode, "fill", "#FFF");`
`Velocity.hook(someDOMNode, "stroke", "#FFF");`
`// These values doesn't work either: "#FFFFFF", "white", "rgba(255, 255, 255, 1)", "transparent"`

Using Velocity.js v1.2.3 (without jQuery) with React.js and Webpack.

**Comment by Rycochet** [comment]
http://julian.com/research/velocity/#arguments

`Velocity(someDOMNode, {"fill": "#FFF"});`

**Comment by guopengliang** [comment]
@Rycochet  Ooops... I forgot to type `.hook` in the examples (I have corrected them).

**Comment by Rycochet** [comment]
Ah, that makes more sense ;-)

I don't know for sure, but looks like those two are registered hook types - so you should be getting and setting `"strokeRed"`, `"strokeGreen"`, `"strokeBlue"`, and `"strokeAlpha"` instead - at least while accessing through `.hook`, anyone else have more experience of this?

**Comment by Rycochet** [comment]
The hook function is now deprecated, see the `"style"` command documentation.
