### ISSUE TITLE
Cache display property for slideDown/fadeIn?

### ISSUE THREAD

**Issue by darrylyeo** [julianshapiro/velocity#664]
By default, an element's `display` is set to its native type after a `slideDown` or `fadeIn`.

Compare this to jQuery, which caches the initial `display` value and is able to restore it regardless of whether it started as its native `display`.
http://jsfiddle.net/darrylyeo/bpf4f1um/3/

Can Velocity achieve a similar functionality, without having to manually override the `display` on a case by case basis?

**Comment by Rycochet** [comment]
Maybe when we first set the display value to "none" it should `getComputerStyle` the current one if it's not already cached (and only cache the non-"none" value) - not sure what it's doing right, but definitely not that at least ;-)

**Comment by Rycochet** [comment]
The ui-pack animations have been rewritten
