### ISSUE TITLE
background-color should be valid input

### ISSUE THREAD

**Issue by AnilRedshift** [julianshapiro/velocity#667]
Repro is trivial: Just try to queue up a velocity animation to change the `background-color` to `#000`. It will fail. However, passing in `backgroundColor` succeeds.

Most of the code is set up to allow animating both `background-color` and `backgroundColor` but a small section of code in the `start` handler is missing this normalization code. This causes the code to fail to append the `Red`, `Green` and `Blue` styles. This cascades as a problem in `Css.Values.getUnitType` which now defaults to `px` because it fails the following regex below:
```            
getUnitType: function (property) {
                if (/^(rotate|skew)/i.test(property)) {
                    return "deg";
                } else if (/(^(scale|scaleX|scaleY|scaleZ|alpha|flexGrow|flexHeight|zIndex|fontWeight)$)|((opacity|red|green|blue|alpha)$)/i.test(property)) {
                    /* The above properties are unitless. */
                    return "";
                } else {
                    /* Default to px for all other properties. */
                    return "px";
                }
            },
```

The fix is to add `CSS.Names.camelCase` *somewhere* to the init codepath. I have created a motivating PR [here](https://github.com/julianshapiro/velocity/pull/666) to better describe the issue.

Thanks!

**Comment by Rycochet** [comment]
I think this sort of thing should be checked globally - follow Angular2's example and accept either version in all places it can happen (this is a good case for unit tests) ;-)

**Comment by Rycochet** [comment]
Fixed by https://github.com/julianshapiro/velocity/commit/5b7ec85b42b54b1c5d324220c7fd8dcca99e4e64 - all property values are camelCase before playing with them now.

**Comment by AnilRedshift** [comment]
Thank you!!! :tada: 🎊 :tada: :taco:
