### ISSUE TITLE
Velocity Scroll has different speeds depending on which menu link selected

### ISSUE THREAD

**Issue by filippolcr** [julianshapiro/velocity#668]
I've a One Page Scrolling Template with parallax effect with a navigation menu with some link.
The layout is made by some section:

```
<section id="section1" class="">
</section>
<section id="section2" class="">
</section>
...
```

and navigation-menu

```
<ul>
  <li>
    <a href="#section1"></a>
    ... (other links)
  </li>
</ul>
```

and a js with velocity scroll: 

```
  // Velocity Smooth Scroll
        // bind click event to all internal page anchors
        $('a[href*="#"]').on('click', function(e) {
            // prevent default action and bubbling
            e.preventDefault();
            e.stopPropagation();
            // set target to anchor's "href" attribute
            var target = $(this).attr('href');
            // scroll to each target
            $(target).velocity('scroll', {
                    duration: 3000,
                    offset: 0,
                    easing: 'ease-in-out',
                     mobileHA: false
            }
      });
```

If I'm on first section and I want, for example, scroll to last section, scroll speed is different if I wanted , for example, to go to the second section.

I'd like the scroll speed is always the same, independently of which link I select.

But I do not know how to do,because Velocity.js always takes 3 seconds for complete the scroll event.

Is there a way to do it? 

I hope I was clear

**Comment by Rycochet** [comment]
This isn't an issue so should be asked on stackoverflow and not the bug tracker.

Personally I'd use `getBoundingClientRect` on the elements to find their absolute positions, work out the difference, and set the `duration` based on that.

**Comment by filippolcr** [comment]
You're right, I apologize for being wrong. I close this issue and republish on Stackoveflow.
