### ISSUE TITLE
Velocity changes css display:flex to display:block

### ISSUE THREAD

**Issue by cheekybuddha** [julianshapiro/velocity#672]
Hi,

Is this a bug or a feature?

I run a velocity animation on a div with `display:flex`.

When the animation finishes the element(s) have inline css `display:block,` which knackers how the elements should look.

[Here is a fiddle to demonstrate](https://jsfiddle.net/cheekybuddha/sudpv31g/47/).

STR:
1. Load. There are 2 divs - their display is flex.
2. Click button 'Hide' - velocity animation and the divs disappear.
3. Click button 'Show' - velocity animation and the divs re-appear. But now display = block.
4. Click button 'Set flex' - divs have display reverted to flex and return to how they should look.
5. Repeat 2,3,4.

Is it not possible to use velocity with `display:flex`?

tia,

d

**Comment by Rycochet** [comment]
As per the docs - http://julian.com/research/velocity/#displayAndVisibility

`$('.my_btn').velocity("transition.expandIn", {stagger: 75, display: "flex"});`

**Comment by cheekybuddha** [comment]
Perfect! Many thanks!

Sorry to clog up the issue list, not having rtfm properly.

d
