### ISSUE TITLE
can't animate width 0 -> width auto

### ISSUE THREAD

**Issue by lastobelus** [julianshapiro/velocity#673]
I am trying to animate the insertion of elements in a horizontal list. Their contents can have varying widths.

I start with the style:
```
.v-hide-horiz {
  opacity: 0;
  width: 0;
}
```
animating to a fixed width behaves as desired:
```
$element.velocity({ opacity: 1, width: 177 });
```

However, when I do:
```
$element.velocity({ opacity: 1, width: "auto" });
```
velocity instead sets the width to 0.
I have also tried:
```
$element.velocity({ opacity: 1, width: 177 }, {width: "auto"});
```
in the hopes that I could animate the `li` to the minimum size and then have any extra width pop in, but in this case also velocity instead sets width to 0.

Is there a way to animate to width auto? or should I just switch to using css transitions for this particular animation?

**Comment by Rycochet** [comment]
It doesn't know the actual width to animate to - and css animations and transitions are the same, there's a work-around here: https://stackoverflow.com/questions/3508605/how-can-i-transition-height-0-to-height-auto-using-css - however the only way to do it correctly is to get the width as a number and animate to that (ie, in one frame set the width to `auto`, immediately read the innerWidth property to force it to recalc sizes, then set back to 0 and force it to recalc again before animating to the number you read).
