### ISSUE TITLE
SVG  textpath does not animate startoffset

### ISSUE THREAD

**Issue by wahahachan** [julianshapiro/velocity#674]
I guess the official doc mentioned the startOffset attribute in SVG is supported, but I can't get it work.

The follow jsfiddle demo:
https://jsfiddle.net/pnf6ucu6/2/

**Comment by Rycochet** [comment]
Velocity animates css values, and only a couple of non css values that are hard coded such as "scroll" - to do this you'd need to use a `progress` callback and possibly a tween value - see the docs for details http://julian.com/research/velocity/#progress

**Comment by wahahachan** [comment]
Correct me if I am wrong. The progress callback is just a function being called during the animation. It has nothing to do about the velocity library ignoring  the startOffset attribute. And the official homepage stated that startOffset is supported.

**Comment by Rycochet** [comment]
I had a look in the official homepage and there's no mention of startOffset hence my earlier reply - http://julian.com/research/velocity/#svg - using the progress callback lets you write a small snippet to convert the tween value into a startOffset attribute - once code is coming out again then we might have a look into animating attributes differently, but for now things are unlikely to change...

**Comment by wahahachan** [comment]
The page just mention:
First, not all CSS properties can be applied to SVG elements. (See the dropdown below for a list of supported properties.) 

The 18th item of the dropdown list is startOffset

**Comment by Rycochet** [comment]
Ah, I missed that - however it is referring to CSS properties, and that's an attribute and not a css property - so in this case I'd say the docs are wrong :-/

**Comment by Rycochet** [comment]
All SVG properties on individual elements should be supported correctly now.
