### ISSUE TITLE
Index passed to value functions does not respect original array order

### ISSUE THREAD

**Issue by ProjektMinu** [julianshapiro/velocity#675]
When you call Velocity on an array of elements and use a  value function for one of the properties, the function receives an index as its first parameter. 

You'd expect this index to always be the element's index in the array. 

Nevertheless, the index is influenced by the elements' single per-element queues, which might lead to a totally different order: [Here is a fiddle](http://codepen.io/projectMinu/pen/qZwVaM)

**Comment by Rycochet** [comment]
Fixed
