### ISSUE TITLE
Translation and rotation

### ISSUE THREAD

**Issue by zaidrashid** [julianshapiro/velocity#677]
Im trying to do a translate after a rotation but I don't seem to get what I am expecting. 

Here's the transformation
$("div")
.velocity({translateX : 150}, 1000)
.velocity({rotateZ : "90deg"}, 1000)
.velocity({translateY : 150}, 1000);

With this transformation, the div will return back to the original position. I understand that the X-Y axis has changed after the rotationZ, but if I did a translationX, it will do the translation along the previous X-axis instead. (translateX : 150 will just remain on the same position instead). How do I make it go down along the Y-axis (or the correct X-axis) after doing a 90 degrees rotation?

Here's my demo: http://jsfiddle.net/65xCP/202/

**Comment by philippklodt** [comment]
@zaidrashid
Unfortunately there is no way to move that element downards in Velocity (without resorting to hacks). 
For this reason I wrote an [extension to Velocity](https://github.com/philippklodt/velocity/tree/VelocityTFF) that lets you define the order of transform beforehand. 
With it, if you call ...
```javascript
$.Velocity.transformSequence($('div'), ['translateX', 'translateY', 'rotateZ']);
```
... before your code it works as desired.

@all
I think this is a very good example of what is wrong with Velocity's approach to transform animation.

**Comment by Rycochet** [comment]
I was trying to figure out a reply to this with that exact point - the transform shortcuts do make it somewhat impossible right now, but it needs more thought and planning - possibly remembering the order they're added, and having a `transform` option to reset or force order. It definitely needs discussion and planning to end up with something that works correctly and in a semi-obvious way for people who don't read the docs properly.

**Comment by philippklodt** [comment]
I agree, it should remain somehow intuitive. My problem was that I needed to repeat the same transform multiple times and there is no way (not even with 'hacks') to achieve this.
I suppose though that most people will not need this and would be happy with just the possibility to determine the order somehow before the velocity calls. 
I think the easiest way would be to make sure that the transforms are reliably left in the order in which they are introduced by calls to `velocity()` and `hook()` (easiest in terms of amount of code modification).

**Comment by Rycochet** [comment]
This will need a little bit more thought, maybe #459 would do it - but it needs something in v2 I think

**Comment by philippklodt** [comment]
Just saw the help sign, so I wanted to comment on this..
#459 sort of solves it, but it has some issues (like it crashes when the `queue` option is used).

So currently I think there's only the following workaround (put this somewhere before the velocity call):
```javascript
$.Velocity.hook(elements, 'translateX', 0);
$.Velocity.hook(elements, 'translateY', 0);
```
[Demo here](http://jsfiddle.net/ogcozsfr/1/).

Note: For 3D properties it will sometimes be necessary to do something as ugly as
```javascript
$.Velocity.hook(elements, 'translateZ', '0.01px');
```
instead (because of #224).

**Comment by Rycochet** [comment]
For v2 I'd rather read the parts in order, and keep that order when setting things - have something internal that's similar to that list idea, so it can be addressed / overridden when needed...

**Comment by kritollm** [comment]
I have the same problem. I wrote a script to translate CSS animations with classes and animation keyFrames to Velocity.ui effects. It worked, but some animations like cube was wrong because there was wrong order of translate and rotate.

I have a very simpe solution which I will implement myself anyway. Support arrays:

Instead of: 
```javascript
Velocity(element, {
    width: "500px",
    property2: value2
}, {
    /* Velocity's default options */
    duration: 400,
    easing: "swing",
    queue: "",
    begin: undefined,
    progress: undefined,
    complete: undefined,
    display: undefined,
    visibility: undefined,
    loop: false,
    delay: false,
    mobileHA: true
});
```

support this:

```javascript
Velocity(element, [
    [width: "500px"],
    [property2: value2],
    [property3, [value3, forceFeedValue]
}], {
    /* Velocity's default options */
    duration: 400,
    easing: "swing",
    queue: "",
    begin: undefined,
    progress: undefined,
    complete: undefined,
    display: undefined,
    visibility: undefined,
    loop: false,
    delay: false,
    mobileHA: true
});
```

No investigation needed and easy to implement.
