### ISSUE TITLE
VMD error: Uncaught TypeError: $ is not a function

### ISSUE THREAD

**Issue by lmartins** [julianshapiro/velocity#680]
Tried loading it via bookmark and in the console, for both ways I get this message. 
In this particular site jQuery is running under the `jQuery` and not `$`. Any way to get around this?

**Comment by Rycochet** [comment]
Not entirely sure - having a quick look at the code doesn't show anything obviously using it untested - if it still happens on the latest (unminified) v1.3.0 can you give a line number for me to check out :-)

**Comment by lmartins** [comment]
I went with a different route, but thanks for checking it out.
