### ISSUE TITLE
Using a sequence with inbuilt events

### ISSUE THREAD

**Issue by sanjshah** [julianshapiro/velocity#681]
Hi,

Using the example on the page I can use the following:

`
            var mySequence = [
	    { e: $(".Reject"), p: { translateX: 100 }, o: { duration: 1000 } },
	    { e: $(".Approve"), p: { translateX: 300 }, o: { duration: 1000 } }
            ];
`
however is t possible to substitute the translateX with an inbuilt transition i.e.

            var mySequence = [
	    { e: $(".Reject"), p: { transition.slideLeftOut: 100 }, o: { duration: 1000 } },
	    { e: $(".Approve"), p: { transition.slideRightIn: 300 }, o: { duration: 1000 } }
            ];

Any help is appreciated.

Thanks

**Comment by philippklodt** [comment]
This should work:
```javascript
var mySequence = [
    { e: $(".Reject"), p: 'transition.slideLeftOut', o: { duration: 1000 } },
    { e: $(".Approve"), p: 'transition.slideRightIn', o: { duration: 1000 } }
];
```

**Comment by sanjshah** [comment]
Thanks Philip,

But that did not work, I also tried:

    { e: $(".Reject"), p: {'transition.slideLeftOut':100}, o: { duration: 1000 } },
    { e: $(".Approve"), p: { 'transition.slideRightIn': 100 }, o: { duration: 1000 } }

but that did not work either.

**Comment by philippklodt** [comment]
Passing the effect name as string *does* work for me: [Demo here](http://codepen.io/projectMinu/pen/pyMaGY)

So the problem almost certainly is not with Velocity.

**Comment by Rycochet** [comment]
@philippklodt You left the `, o: { duration: 800 }` in the first one, but taking that out makes no difference so I'm with you there.

@sanjshah Can you provide a JSFiddle which doesn't work properly for you, then we can start to track it down...

**Comment by sanjshah** [comment]
many thanks Philip and Rycochet, that is working fine as you have displayed.

Regards
