### ISSUE TITLE
Back and Forward button broken when using Velocity for anchor navigation

### ISSUE THREAD

**Issue by monolux** [julianshapiro/velocity#682]
With something like this

```
$('.menu-a').on('click', function(e) {
	var hash  = this.hash,
		$hash = $(hash)
		
		addHash = function() {
			window.location.hash = hash;
		};

	   $hash.velocity("scroll", { duration: 700, easing: [ .4, .21, .35, 1 ], complete: addHash });

	// e.preventDefault();
});
```
the functionality of the back and forward button in the browser are broken.

[Have a look at this fiddle](https://jsfiddle.net/tgf20e9k/), click one link then click the back button numerous times and you can observe how the scrollbar goes back just a tiny bit with each click on the back button instead of going back to the last point in user history as would be expected per "normal" browser behaviour.

Thank you for any help or having a look at this. Would love to be able to use this for smooth animation and surly will, just trying to find a way to also keep the back and forward button working.

**Comment by thetanz-geoff** [comment]
Not a velocity issue. Your $(window).scroll event handler is being called repeatedly as velocity animates the scroll, adding multiple states to your history via your call to "pushState".

If you chop out your $(window).scroll handler altogether, you'll be closer to seeing the behavior you want. Consider suppressing the event handler for the duration of the velocity animation (e.g. set a boolean flag before scrolling, clear it after.)

**Comment by monolux** [comment]
Thank you for your info. Yes, I did realize that pushing the state to the history on scroll will obviously create a window history event for each scroll position and therefore only move a fraction of the scrollbar when clicking the back button after scrolling. I do understand the way you mean to set a boolean flag before and after scrolling and am doing something similar and it works. **This ticket should be closed**.
