### ISSUE TITLE
Test failures in Chrome when zoomed out

### ISSUE THREAD

**Issue by joliss** [julianshapiro/velocity#685]
At 75% zoom in Chrome, we get a few failing test cases. In Firefox it works fine.

<img width="631" alt="velocity js tests ubzxv" src="https://cloud.githubusercontent.com/assets/524783/15854425/a9e00722-2ca1-11e6-86ac-47f6b9c96e39.png">

Perhaps this isn't even worth fixing. Just thought I'd let you know in case you're interested.

**Comment by Rycochet** [comment]
Think this might be a problem in the tests themselves, but won't know until I get a chance to look in there, thanks :-)

**Comment by julianshapiro** [comment]
Yeah this is like a result of the kinda hacky way the tests run to try to mimic real-world animation behavior. Thanks for posting, @joliss! Will close for now.
