### ISSUE TITLE
Minify source is not working - it's auto add a comment.

### ISSUE THREAD

**Issue by lehoangdung0612** [julianshapiro/velocity#687]
Hi,

I use this module with minify and it didn't work cause the regex "/[\/*]/" (line 3064) has changed to a comment.

Could you help me to fix it ?

Thanks,
Dung

**Comment by Rycochet** [comment]
Check with whatever you are using to minify - there's now a Gruntfile showing how the current source gets it done, maybe just make sure you're using the non-minified source as a starting point.
