### ISSUE TITLE
Bug: `tweenValue` always `null` in `progress` callback

### ISSUE THREAD

**Issue by bramus** [julianshapiro/velocity#688]
The docs [state](http://velocityjs.org/#progress) that a `tweenValue` is passed into the `progress` callback.

When [trying this out](http://codepen.io/bramus/pen/zBzwpd) however, `tweenValue` always remains `null`.

**Comment by Rycochet** [comment]
"The current value of the dummy *tween* animation property," - you forgot to set a `tween` value in there, so there's no tweenValue to pass...

**Comment by bramus** [comment]
Aha, got it now. Thanks.
