### ISSUE TITLE
Version 1 is being updated!

### ISSUE THREAD

**Issue by Rycochet** [julianshapiro/velocity#691]
Work has started on cleaning up the source and removing possible problems etc (see #671)

Velocity 1 is ~~now just being bugfixed etc~~ still being developed - it will retain compatibility with legacy Internet Explorer (and other older browsers).

I've just pulled quite a lot of bugfixes, and gone through fixing various source issues, so can people please test the new 1.3.0 release - the current tests all pass, so want a little real-world testing before it gets pushed to npm (as 1.3.1 - with more fixes etc) :-)

I'll spend a little more time pulling in more fixes from issues where possible.

~~Hopefully I'll get some time to tweak and push the 2.0.0 branch within the next couple of days - all depends how busy I end up being over the weekend.~~

**Comment by thasmo** [comment]
Nice to see progress being made! Not sure what version 1.3.0 refers to, I can't find a release nor a tag. I've to admit that I've stopped using velocity.js due to it's inactivity but I'm happy to see new releases being prepared and I'm looking forward using it on projects in the future!

**Comment by Rycochet** [comment]
Meh, it didn't tag / release - thought something was up - the current build is 1.3.0 - has all the pulls and fixes and strict mode etc - I'll try to get that sorted in the morning!

**Comment by joshburgess** [comment]
Thanks for the update. I see the jQuery dependency was stripped out. Can we get a new version published to npm with just that change in the meantime? I had forked the project (& react-velocity) to use a version without jQuery and would like to be able to stop using that fork ASAP.

**Comment by Rycochet** [comment]
v1.3.1 will be the next one published to npm - simply so that there's time for the new bugfixes to be tested more first - there's a lot of changes gone into this version, and I want to make sure that it won't break anything - so the more people that manually test things the happier I'll feel - sadly I simply don't have the time to put into writing more tests right now...

**Comment by Rycochet** [comment]
Just a quick note - v1.3.1 is going to be later in the week (before Friday) - I've simply been too busy to do the bits I needed to get it out...

**Comment by joshburgess** [comment]
Cool. Looking forward to it.

For 2.0, has there been any thought to switching from exposing the Velocity function globally to exposing it as a named export (to be friendlier to people working in node/npm/webpack/etc. enviroments)? Maybe, this should be a separate request.

**Comment by Rycochet** [comment]
That's part of the update - currently it forces the global object even when not using it via require etc - the v2 build will not expose that globally unless the file is included directly without a loader (or that's the plan at least) ;-)

**Comment by joshburgess** [comment]
Nice! Feel free to make this a public branch if you'd like some help.

**Comment by Rycochet** [comment]
As soon as it's converted to Typescript and has the build script done and building a near identical output then it's becoming a branch on here. Due to the complete lack of time I'm not going to be able to do anything more on it till next week at the earliest though - probably only needs a day or two of getting my head down :-)

**Comment by julianshapiro** [comment]
Hey everyone! Chatting with Rycochet now. He's some some really incredible work on behalf of this project. SO lucky to have him.

We're going to put a pause on this roadmap as we're bringing on a new maintainer. Making an announcement in a separate thread. The new maintainer and Rycochet will keep you updated!

**Comment by thasmo** [comment]
@Rycochet @kvirani Will version 1.3.0 be properly released/tagged on npm and GitHub soon or will this be skipped for now?

**Comment by Rycochet** [comment]
Sorry for the delay - we were both hit by unexpectedly busy weeks - and will be meeting on Monday to work out things - this should get properly tagged and released at some point soon though :-)

**Comment by Rycochet** [comment]
Highlights of our meeting:

* Typescript on hold (no v2 for the near future, putting efforts into improving things before addressing the idea again)
* Clean up issues - fixes where possible
* Clean up pull requests
* Learn the details of the codebase

---

* Add new features (but not breaking API etc)
* Modularise the codebase
* Need performance tests (I miss jsperf) for some (internal) code change ideas
* Need feedback for ideas that will be posted in due time (said with a big grin) :-P

---

As issues are cleaned up could people who follow Velocity please let us know suggestions and ideas that would improve matters - we're learning the codebase and cleaning things first, but will be working out more solid plans and ideas that can improve Velocity and help everyone realise that Velocity is the best animation library for a reason :-)
