### ISSUE TITLE
Pause and resume is essential but not implemented

### ISSUE THREAD

**Issue by lluxx** [julianshapiro/velocity#694]
Great and fast animation library, but lacks pause, resume, restart etc. This is unexplainable. 

The best use case of this library are games. Because none of the other (even game dedicated) libraries gave me boost in performance like this one and Gsap. But I was so disappointed when I discovered that it lacks those features. 

It is very graphics intensive game and I need every bit of performance I can get, but without pause and resume, I can't make it.

**Comment by julianshapiro** [comment]
GSAP is a better choice for games. Velocity's focus is UI animation.

**Comment by Rycochet** [comment]
Going to weigh in here and say that from a UI perspective this would actually be useful too - recently had a request for a sort of demo interactive - fake mouse moving and firing off click / drag events etc to show the users (in this case young children) how to use the interface.

Being able to change the animation speed, pause & resume, and play the animation itself backwards from an arbitrary point (ie, all part of the same internal code) would give more options to that.

While there are several libraries better for game development, it does depend largely on the game itself - the sheer number I've played online that could easily be done with Velocity shows how little animation is actually needed when the gameplay is good.

**Comment by dolanb12** [comment]
Hello, and thanks for this much-needed feature!

Just a reminder that this hasn't been added to the documentation.

Cheers,

**Comment by Rycochet** [comment]
https://github.com/julianshapiro/velocity/wiki/Command---pause

Needs better documentation, but it's in there ;-)
