### ISSUE TITLE
VeloctityJS is adding display:none to detached dom elements while animating

### ISSUE THREAD

**Issue by afroradiohead** [julianshapiro/velocity#695]
## Issue
- When elements is detached from dom
    - VelocityJs automatically adds display:none to the css

## Request
- When elements are detached from dom
    - VelocityJs **should not** automatically add display:none to the css

## Reason
Come on ya'll, i just wanna animate things that aren't in DOM. I love this library a lot.

## Code Example
https://jsfiddle.net/kx4ek408/3/

**Comment by Rycochet** [comment]
I think that's a side effect of it not being in the DOM. When anything is removed from the DOM it doesn't have a position etc, exactly the same as having `display:none;` - I'm not sure about getComputedStyle and `display` itself, but got a feeling that the same thing happens - so Velocity's cache is finding it's hidden, and then running with that.

Have you tried setting the `display` option manually?

**Comment by afroradiohead** [comment]
I did. And I can't tell if it does this weird thing were it animates the other values from a 0 value instead of the one that's set.

i.e. {width:400} will start at {width:0} on a $el.velocity({width:6000}, {duration:1000}) animation

**Comment by afroradiohead** [comment]
Solved it. Apparently you have to set the display:block on a detach element before it event begins animating, otherwise it'll default it to display:none, or something like that:

https://jsfiddle.net/kx4ek408/6/
