### ISSUE TITLE
IE11 strict mode error

### ISSUE THREAD

**Issue by nathanh752** [julianshapiro/velocity#696]
While I was creating a basic svg animation using velocity I noticed that the latest Velocity (1.3) doesn't work on Internet Explorer 11.

Other browsers work and earlier version of velocity also works on 'Internet Explorer 11'.
IE11 developer tools show the following error:

> Assignment to read-only properties is not allowed in strict mode

In the unminified version the error seems to happen on line 1614 (according to my developer tools):
`element.className += (element.className.length ? " " : "") + className;`

Demo:
http://codepen.io/anon/pen/QKyOJz

**Comment by Rycochet** [comment]
Had a quick look at this - firstly it doesn't work without changes as it's mixing https and http (probably as I automatically redirect to https when available - it's worth doing for security).

What I did notice was that error being made from jQuery code, but I didn't see it coming from Velocity - both use the same code for it. Strangely the `className` attribute is supposed to be fully supported on IE, so not quite sure what's going on there. Will leave this open for the moment until we've got time to check things properly - but technically that line doesn't actually need the `.length` on it as we're just checking to see if it's got an empty string or not.

**Comment by jstevens79** [comment]
I'm running into the same issue. Went back to a previous version for now, which works with IE 11.

**Comment by Rycochet** [comment]
If someone has the time to do it - grab the latest version and remove the `"use strict"` in there - and see if it still causes the same problem? I'm not sure when I'll get a chance to look into it more...

**Comment by nathanh752** [comment]
@Rycochet I did some extra testing and removing the "use strict" solves it.  So I did some more research (as I don't like removing the "use strict" as a solution). 

First off: IE11 doesn't seem to support the "element.classList" and falls into the else part of the statement:

> else {
> element.className += (element.className.length ? " " : "") + className;
> }

All other browsers I tested (edge, firefox and chrome) do support it and never fall into the else part of the statement and only do:

> if (element.classList) { 
> element.classList.add(className); 
> }

The problem seems to be that element.className returns an **SVGAnimatedString object**.
IE11 (without the "use strict") doesn't seem to care about this and when it sees the `element.className.length` it will result in an "undefined" as it can't get the length of a single object. The variable `element.className` (on the same line) doesn't get modified because IE can't put add a string in a variable that contains an object.

Now if you add the "use strict", then IE11 suddenly realizes that what is happening shouldn't be allowed to happen and raises an issue about it.
The object in `element.className` has 2 properties: `animVal` and `baseVal`. Both of these properties seem to return the same thing. But what I understand from [https://www.w3.org/TR/SVG/coords.html#InterfaceSVGAnimatedTransformList](https://www.w3.org/TR/SVG/coords.html#InterfaceSVGAnimatedTransformList) is most of the time both of them will be the same, but if any animation is running, it will be reflected in the `animVal`.

I'm not really sure if you need the `baseVal` or the `animVal`. But if I add the `baseVal` like this: 

> if (element.classList) {
>     element.classList.add(className);
> } else {
>    if (element.className.toString() === '[object SVGAnimatedString]'){
>        element.className.baseVal += (element.className.baseVal.length ? " " : "") + className;
> } else {
>element.className += (element.className.length ? " " : "") + className;
>    }
> }

It all starts working (with the "use strict" intact) in all the browsers I tested it in (chrome, firefox, IE11, edge). 

Also note that you may need to to edit the 'removeClass' function in the same way to something like this:
> if (element.classList) {
> element.classList.remove(className);
> } else {
> if (element.className.toString() === '[object SVGAnimatedString]'){
> element.className.baseVal = element.className.baseVal.toString().replace(new RegExp("(^|\\s)" + className.split(" ").join("|") + "(\\s|$)", "gi"), " ");
> } else {
> element.className = element.className.toString().replace(new RegExp("(^|\\s)" + className.split(" ").join("|") + "(\\s|$)", "gi"), " ");
> }
> }

**Comment by Rycochet** [comment]
@nathanh752 Awesome hunting, I'll put that in first thing tomorrow, thanks!!! :-)

**Comment by Rycochet** [comment]
@nathanh752 Can you check if the latest version fixes it? I did things a different way which is hopefully more compatible (and works) :-)

**Comment by nathanh752** [comment]
@Rycochet Looks like it is working here too. 
(Just note that I'm also on win 10, but from my past experiences IE11 behaves pretty much the same)

**Comment by Rycochet** [comment]
Marking as closed then - considering it's essentially the same thing jQuery does now hopefully it'll hit every use case :-)
