### ISSUE TITLE
Strange behavior with animation of css3-transformed elements

### ISSUE THREAD

**Issue by R-G-B** [julianshapiro/velocity#698]
When we've got a text with some css3-transformation, like:
` transform: rotate(-90deg);`
during an animation process
`            $("body> .btn").velocity({
                left: "65%",
            }, 600 );`
it looks like velocity is "turning off" our transformation for the animation process, and after the end of animation, it turns on our transformation again:
https://i.gyazo.com/4f95f0c054971e6c2f5b7e297e33b8d7.gif
If we are trying to do the same with jquery's animate() everything works well
Is there any way to fix that?

**Comment by Rycochet** [comment]
Hidden in the docs - http://velocityjs.org/#mobileHA

Basically it's replacing the value to enable hardware acceleration, so make sure to turn it off.

**Comment by R-G-B** [comment]
Thanks a lot, but isn't it better to make it false by default? I understand that it's a question of performance, but without your answer I've never noticed that hidden property

**Comment by Rycochet** [comment]
It's one of the major speed boosts that needs to be true by default - but it also needs to understand if there's already something using that and to turn it off if it would break anything - sadly transform is a really awkward attribute to get anything useful from (see #269).
