### ISSUE TITLE
isTweening in Velocity.js?

### ISSUE THREAD

**Issue by PierBover** [julianshapiro/velocity#700]
What's the GSAP isTweening equivalent in Velocity?

I can't seem to find anything similar in the docs.

**Comment by makshh** [comment]
You can check if element has class `velocity-animating`.

**Comment by PierBover** [comment]
That's a bit ugly tbh. The engine should have something faster that doesn't need to check the DOM.

**Comment by makshh** [comment]
`var $element = $('.element').velocity('slideUp');`

`$element.data().velocity.isAnimating`

**Comment by PierBover** [comment]
That makes more sense.

Thanks @makshh !

**Comment by Rycochet** [comment]
Just be aware that this is unsupported behaviour - and may change in future versions (it should get an announcement if we change how it stores data though)
