### ISSUE TITLE
Add support to set non-integer values

### ISSUE THREAD

**Issue by dcalhoun** [julianshapiro/velocity#702]
Originally discussed in #366, it'd be great if velocity allowed for setting non-integer values. Specifically, I'd like to remove values changed by velocity.

For example, within a registered effect, the `reset` attribute would reset "prep" styles for the animation:

``` javascript
Velocity.RegisterEffect('slideInUp', {
  defaultDuration: 1000,
  calls: [
    /* ...animations... */
  ],
  reset: {
    bottom: 'auto',
    left: 'auto',
    position: 'static',
    right: 'auto',
    top: 'auto'
  }
})
```

Passing an empty string could also be used to merely remove the values:

``` javascript
Velocity.RegisterEffect('slideInUp', {
  defaultDuration: 1000,
  calls: [
    /* ...animations... */
  ],
  reset: {
    bottom: '',
    left: '',
    position: '',
    right: '',
    top: ''
  }
})
```

It may also be helpful to [add support for `Velocity.hook` to remove values](https://github.com/julianshapiro/velocity/issues/224#issuecomment-99817556) as well.

**Comment by dwelle** [comment]
Also setting up non-integer values before the animation, such as custom `display` etc, in a property map called e.g. `setup`, would be great too.

**Comment by Rycochet** [comment]
Needs a bit of discussion and planning, but I'm thinking about using #697 for this - needs to be able to set the value at the start or end (so needs `"start"` and `"end"` easings), with a possibility to reset at the actual end (`"running"`?).

Having a `reset:{...}` in the options is a separate issue to non-integer values so needs to be split out from this one.

**Comment by dwelle** [comment]
@Rycochet  #697 LGTM, but it addresses only animateable props containing numbers somewhere in the value. Like you said, what @dcalhoun and I talk about is a separate issue.

**Comment by Rycochet** [comment]
@dwelle Actually wrote the base code for it several weeks ago, so it deals with strings on both sides - currently non-matching strings (not including digits) are dealt with as an error, but it needs to expand to have unit changes, and if it also recognised the easings above then it could handle the text based case of switching between the two values.

**Comment by Rycochet** [comment]
In V2 (currently the develop branch) you can now use the specific easings ```"at-start"```, ```"during"``` and ```"at-end"``` for purely string based properties. Just of note, if it has a "matching" number string/number pattern then it's treated as a number for easings.
