### ISSUE TITLE
Add editorconfig

### ISSUE THREAD

**Issue by ftonato** [julianshapiro/velocity#706]
> EditorConfig helps developers define and maintain consistent coding styles between different editors and IDEs.
>
> — [EditorConfig](http://editorconfig.org/)

```shell
# .editorconfig
root = true

[*]
indent_style = tab
indent_size = 8
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true

[*.md]
trim_trailing_whitespace = false
```

**Comment by kvirani** [comment]
Totally agree. Though I believe it's 4sp atm. Wanna submit a PR for this?

**Comment by ftonato** [comment]
I will submit a PR ;)

**Comment by Rycochet** [comment]
Spacing in the source is actually 1 tab right now - even though there's about 2x as many projects on GitHub using spaces as tabs - my personal view has always been "use tabs as then the coder can decide what spacing they want to display". Pretty much all of the arguments against tabs basically come back to ideas that were relevant over a decade ago ;-)

This is the sort of thing that is relevant for when we have automated testing and code style requirements - the argument about spaces / tabs would take up a large chunk of time ;-)
