### ISSUE TITLE
Force feeding doesn't work well on 3D transforms

### ISSUE THREAD

**Issue by PascalPixel** [julianshapiro/velocity#708]
Wondering why, but when dealing with 3D transforms the Velocity animation really stutters unless you first manually feed the original values into Velocity (in a sequence).

Manual input fixed it but seems like might needed to report?

**Comment by Rycochet** [comment]
Can you supply a JSFiddle showing this, and which browser is it happening on?

**Comment by PascalPixel** [comment]
@Rycochet It looks messy, but this was quite some work to strip out of the full code

https://jsfiddle.net/de1pzaqq/

The issue in detail:
1. One div lies flat on the floor, velocity is told to turn it 90* up, before starting this animation, it moves the div down. Manually entering the CSS for the div in the Velocity sequence makes it smooth.
2. Same thing with the second smaller div, it starts on the first one, yet when the animation starts, it starts all the way in the left corner.

**Comment by PascalPixel** [comment]
@Rycochet issue is with `translate3d()`, should be `translateX() translateY() translateZ()`, maybe we can add a note in the docs? Sorry this was a loose end!

**Comment by Rycochet** [comment]
Probably needs a hook to handle it, but it's not as simple as the RGB type ones - once #697 can get done it will handle things a lot better :-)
