### ISSUE TITLE
v1.3.0/v1.3.1 not published to npm

### ISSUE THREAD

**Issue by tonybaroneee** [julianshapiro/velocity#709]
Can you please publish 1.3.0 and 1.3.1 to npm since they are tagged releases here in git? Thanks!

**Comment by cgmartin** [comment]
a workaround I'm using for now is npm installing with the git method, using the "v1.3.1" tag:

```bash
# npm install <githubname>/<githubrepo>[#<commit-ish>]
$ npm install julianshapiro/velocity#v1.3.1
```

*via the [npm install docs](https://docs.npmjs.com/cli/install)*

**Comment by tonybaroneee** [comment]
Yep, that works, but I'd rather not rely on that. I hope to bring to their attention that they might be forgetting to `npm publish` after tagging a release in git. It's been two releases since the last publish. 😄

**Comment by cgmartin** [comment]
@tonybaroneee aye, hopefully a temporary workaround. the jquery dependency in the current published version drove me to this. was too painful to wait.

**Comment by Rycochet** [comment]
It's actually that I don't have permission to publish to npm - pinging @kvirani as he should hopefully get this sorted out with @julianshapiro 

On a related note, think there's enough new fixes in there that v1.3.2 isn't far away ;-)

**Comment by kvirani** [comment]
@tonybaroneee thanks for your patience, both 1.3.0 and 1.3.1 have been published.

**Comment by tonybaroneee** [comment]
Much appreciated!
