### ISSUE TITLE
Is there a JSON schema?

### ISSUE THREAD

**Issue by cannontrodder** [julianshapiro/velocity#711]
Is there a schema file anywhere to document the various objects we pass into velocity.js? Useful for intellisense etc

**Comment by Rycochet** [comment]
Sadly not - at some point I need to try and figure them all out for real TypeScript references - being plain JavaScript made the latest addition take well over twice as long partly because of this lack.

**Comment by Rycochet** [comment]
Velocity V2 is now a Typescript project, and the full public interface of all datatypes and structures is available in the `index.d.ts` file in the root. If you are not using Typescript then hopefully the code is clear enough - and I strongly suggest learning Typescript and migrating any other projects you use to it (it makes it significantly easier to develop, and allows use of future Javascript technologies that aren't available in all browsers yet - it is also at its heart simply an extension of Javascript).
