### ISSUE TITLE
Bug with firefox and backgroundPositionY

### ISSUE THREAD

**Issue by maximusnikulin** [julianshapiro/velocity#715]
He there! I have a problem with backgroundPositionY and step animation in VelocityJS. I need to change this property and it works in Chrome but doesn't work in Firefox; How can I fix it ? There is some hooks for jquery but is there some ones for velocityJS? 
I would use backgroundPosition:X Y, but it is not permitted in Velocity.js
Thanks.

**Comment by Rycochet** [comment]
Closing as no fiddle - one thing of note, some browsers can set `backgroundPositionX` and not get it, and get `backgroundPosition` and not set it, so it's not an easy fix.

Of note - if using forcefeeding, `backgroundPosition: ["0px 0px", "10px 10px"]` is perfectly valid now.
