### ISSUE TITLE
Fixed elements disappear during scroll on mobile

### ISSUE THREAD

**Issue by quentin-sommer** [julianshapiro/velocity#716]
Hi, I'm building a website with a fixed top area (nothing very original) with buttons that scrolls to different content sections when clicked.

During the scroll the fixed elements disappear and only appear back at the end of the animation.

Here's a jsfiddle:
https://jsfiddle.net/c61cbj9o/4/

You'll have to use a mobile user-agent to see the bug, using chrome for example

While clicking on the scroll buttons the "visual indicator" disappear during animation

Let me know if this isn't explicit !

**Comment by Rycochet** [comment]
It probably something to do with layers and GPU acceleration - try turning the transform off with `mobileHA:false` and see if that helps.

**Comment by quentin-sommer** [comment]
It fixed it, thanks!

**Comment by Rycochet** [comment]
Elements with `position:fixed` are always a pain, but I'll try to get a note in the documentation for this specific problem.
