### ISSUE TITLE
$.Deferred never settles if element is removed from document, while Promise works

### ISSUE THREAD

**Issue by futpib** [julianshapiro/velocity#717]
```js
$('#it').velocity('slideUp').promise().then(() => {
	alert('resolved'); // never gets called
}, () => {
	alert('rejected'); // never gets called
});

$('#it').remove();
```

Fiddles:
* The one with `$.Deferred` that does not work (you never see the alert) https://jsfiddle.net/prthszg7/5/
* Analogous code with `Promise` does work https://jsfiddle.net/k04pw25w/3/

**Comment by Rycochet** [comment]
jQuery before version 3 did not use real promises - this is an issue with old versions of jQuery - https://jquery.com/upgrade-guide/3.0/#breaking-change-and-feature-jquery-deferred-is-now-promises-a-compatible
