### ISSUE TITLE
Issue animating position for mobile devices

### ISSUE THREAD

**Issue by mckennach** [julianshapiro/velocity#719]
I'm trying to simply animate a div from left: x to left: y. It works great on my browser, but once I deploy it to a mobile device it gets very glitchy. I made a very basic example of the issue, which you can see through the Chrome mobile simulator. 

http://codepen.io/mckennach/pen/ObbOmg

**Comment by Rycochet** [comment]
Add `mobileHA:false` to your options - specifically, you're animating a large area, and it's pushing it all onto the GPU, which isn't quite able to keep up.

Alternatives include using `paddingLeft` or `translateX` - but I don't think they'd help.

Btw, `.stop()` is jQuery, and has nothing to do with Velocity - you want `.velocity("stop")` for the same effect.

**Comment by mckennach** [comment]
Thank you!
