### ISSUE TITLE
Publish 1.3.2 to NPM.

### ISSUE THREAD

**Issue by treycordova** [julianshapiro/velocity#721]
I'm not sure if there's some process that's holding this back, but 1.3.2 was released 11 hours ago, yet the NPM registry doesn't reflect that release. Thanks!

**Comment by Rycochet** [comment]
I forgot to ping @kvirani when releasing, done so now - hopefully we'll get 1.4.0 out sometime in the next two weeks too :-)

**Comment by prewk** [comment]
I don't wanna be a "+1" guy but... :)

**Comment by attenzione** [comment]
it's already ```1.4```, but not npm :(

**Comment by Rycochet** [comment]
I don't have access to publish on npm, so pinged again.

**Comment by kvirani** [comment]
Sorry folks. Was on vacay. I've published 1.3.2 and 1.40 to npm. heads up re minor issue: The title in the [README in the 1.4.0 tag](https://github.com/julianshapiro/velocity/blob/1.4.0/README.md) was incorrectly set to 1.3.2, so npmjs.org will have the wrong title in the README.
