### ISSUE TITLE
Vanilla JS method breaks if jQuery is included

### ISSUE THREAD

**Issue by pietrogregorini** [julianshapiro/velocity#722]
I'm developing a website in Wordpress where I use just vanilla JavaScript and no other frameworks, so while using Velocity I use function `Velocity(...)`. While testing I need to activate the Debug Bar which relies on jQuery, but when doing it, Velocity is looking for jQuery method instead giving the error `ReferenceError: Can't find variable: Velocity`. How can I resolve this issue? Sincerely, I don't want to modify all the `Velocity(...)` functions with jQuery callback and then modify them again when testing is done. Hope there's a solution for this.

**Comment by Rycochet** [comment]
Currently Velocity says "Oh, here's jQuery, let's connect to that instead" (same for Zepto) - so it can't do both, you need to add a line (after loading Velocity) to copy it over -

```javascript
window.Velocity = window.Velocity || (window.jQuery || window.Zepto || {}).Velocity;
```

**Comment by pietrogregorini** [comment]
I know, that's what I supposed, just that I was in need of your piece of code to make it works. Thanks.

**Comment by MattyBalaam** [comment]
Alternatively you can try what I do and use an IIFE

(function(window, document, velocity, undefined){

// all your your code here

}) (window, document, window.jQuery ? window.jQuery.Velocity : window.Velocity);

**Comment by Rycochet** [comment]
```javascript
(function(window, document, Velocity, undefined){

// all your your code here

}) (window, document, (window.jQuery || window.Zepto || window).Velocity);
```

ps. use ` ```javascript` at the top to get code highlighting

**Comment by IAMtheIAM** [comment]
@Rycochet 
You can also use ```js for short ;)
