### ISSUE TITLE
Velocity animating children of form, instead of form itself

### ISSUE THREAD

**Issue by attenzione** [julianshapiro/velocity#723]
We have encountered strange things with 1.3.2, velocity animating children of <form> element, however it's applied to form element

example is here: https://jsfiddle.net/m3sw4r63/

**Comment by attenzione** [comment]
i've investigated the code and the problem is in ```Type.isWrapped``` which return true for form elements, because form have length property [#L565](https://github.com/julianshapiro/velocity/blob/master/velocity.js#L565)

I think solution is to add ```!Type.isNode(variable)``` to second part of condition or change order of ```if``` statement here [#L530](https://github.com/julianshapiro/velocity/blob/master/velocity.js#L530)

**Comment by Rycochet** [comment]
Doh, nice catch - changed the `isWrapped()` method as that should always return correctly wherever it's used - also fixed it so you can pass the result from `document.querySelector()` or `document.getElementsByTagName()` etc :-)

**Comment by glasser** [comment]
We ran into this one today. Do you think you can release a 1.4.1 that fixes this?

**Comment by Rycochet** [comment]
I need to know that the issue tacked onto the end of #697 has also been fixed - then can release an update for both of them - hopefully by the end of the weekend either way.
