### ISSUE TITLE
Allow 0% duration for  compatibility with css keyFrames

### ISSUE THREAD

**Issue by kritollm** [julianshapiro/velocity#726]
I made a css animations to Velocity effects script and found a bug that is easy to fix.

To simulate css key frames I use the 0% keyframe as force feeding (same as css), but 0(%) is false so the value is replaced with 1 (100%).

Line 135:
```javascript
/* Assign the whitelisted per-call options. */
    opts.duration = redirectDuration * (durationPercentage || 1);
```

change to:

```javascript
/* Assign the whitelisted per-call options. */
    durationPercentage = (durationPercentage || durationPercentage === 0) ? durationPercentage : 1;
    opts.duration = redirectDuration * durationPercentage;
```

**Comment by Rycochet** [comment]
Maybe better with this instead?

```javascript
opts.duration = redirectDuration * (Type.isNumber(durationPercentage) ? durationPercentage : 1);
```

**Comment by kritollm** [comment]
It's an option, but where is Type defined? Can't find it. My solution is fast and safe without a lot of testing to check for null, infinity etc. In other words, if durationPercentage is not === 0, then Velocity.ui  work the same as before. The durationPercentage isn't checked for numbers anywhere else.

**Comment by Rycochet** [comment]
`Type` is an internal and that specific one is just a shortcut to `typeof X === "number"` - but being a function lets the optimiser at it supposedly. Not sure if it's available inside VelocityUI though.

Looking at the source itself (which I didn't do earlier) I'm not really seeing a benefit to the `|| 1` unless there's only a single call there. For all the other ones it adds up to one, so might be an idea to pre-check the calls, and count how many don't have a number - then average out the remaining lenth.

Ie, same effect, more code, but also more future proof...
