### ISSUE TITLE
Info: using RunSequence with Custom Effects

### ISSUE THREAD

**Issue by giulianovelli** [julianshapiro/velocity#727]
I made a sequence where a drawer opens from the left than the text contained by the drawer slide in from the left. The text is comprised of a list of links and I would like to use stagger to make them appear one after the other. I have tried all the combinations of code and looked everywhere but it seems to use stagger I have to make a Custom Effect and to make the animation sequential I have to use a Sequence. I can't understand how to use them together (if it is possible at all).

Is there a way to combine the two to get the effect I want? (If I use a callback to run the second animation (the links) there is an ugly pause between the two transitions.)

**Comment by Rycochet** [comment]
Can you put up a JSFiddle showing it - then I've got something to play with while figuring this out :-)
