### ISSUE TITLE
Add possibility to pass properties in an array of properties to preserve property order.

### ISSUE THREAD

**Issue by kritollm** [julianshapiro/velocity#730]
As I understand there is no way to preserve the order of properties in Velocity. I wrote a script to translate CSS animations with classes and animation keyFrames to Velocity.ui effects. It worked, but some animations like cube was wrong because there was wrong order of translate and rotate.

I have a very simple solution which I will implement myself anyway. Support arrays:

Instead of: 
```javascript
Velocity(element, {
    width: "500px",
    property2: value2
}, {
    /* Velocity's default options */
    duration: 400,
    easing: "swing",
    queue: "",
    begin: undefined,
    progress: undefined,
    complete: undefined,
    display: undefined,
    visibility: undefined,
    loop: false,
    delay: false,
    mobileHA: true
});
```

support this:

```javascript
Velocity(element, [
    [width: "500px"],
    [property2: value2],
    [property3, [value3, forceFeedValue]
}], {
    /* Velocity's default options */
    duration: 400,
    easing: "swing",
    queue: "",
    begin: undefined,
    progress: undefined,
    complete: undefined,
    display: undefined,
    visibility: undefined,
    loop: false,
    delay: false,
    mobileHA: true
});
```

Should be easy to implement.

**Comment by Rycochet** [comment]
Little out of date now - if you want to pass separate values then it can't maintain the order, however if you want to have a set animation you can easily do:

```javascript
Velocity(element, {
   transform: ["rotateZ(25deg) translateX(25px)", "rotateZ(52deg) translateX(73px)"]
}, {
   ...options
});
```

I'm in the middle of the code to allow it to automatically manage unit changes too - expect later this weekend (when we'll get a whole new minor version number) ;-)

**Comment by kritollm** [comment]
That's all I need, wasn't aware of the transform property. Very good.

**Comment by Rycochet** [comment]
It's not just the transform property - can pass any two strings, and as long as they match bar the numbers (and soon - units) it'll animate between the two - so you can include `calc()` etc inside ;-)

**Comment by bravokiloecho** [comment]
Is this still working @Rycochet? I can't seem to reproduce any animations with transforms using the code you've written above...

Thanks!

**Comment by Rycochet** [comment]
@bravokiloecho No reason why it wouldn't - but do check that the strings are identical apart from the numbers + units, if there's any text that doesn't match then it won't work.

**Comment by bravokiloecho** [comment]
The only difference was I was using Velocity with jQuery, so it looked like:
```
$element.velocity({
   transform: ["rotateZ(25deg) translateX(25px)", "rotateZ(52deg) translateX(73px)"]
}, {
   ...options
});
```

Could that be the issue?

**Comment by Rycochet** [comment]
The `{...options}` is an example for the options object - you'd need to change that to include `duration` etc - or just remove it entirely to go with the defaults :-)

**Comment by bravokiloecho** [comment]
Oh sorry, I had actually filled that in! I added a forcefeed opacity rule to test that it's working in principle (and it is). It's just the transform bit that's not working.

**Comment by Rycochet** [comment]
Ah, not sure - all I can say is that we're working on stuff for V2, and will make sure that it gets put in for a proper test - which should catch what's going on... It might be some of the legacy V1 code getting in the way somewhere where it could create a `transform` property  it shouldn't overwrite it though.

**Comment by bravokiloecho** [comment]
Hmm ok, thanks for your help!
