### ISSUE TITLE
boxShadowBlur and textShadowBlur animation look wrong in MS Edge

### ISSUE THREAD

**Issue by n3dst4** [julianshapiro/velocity#732]
Steps:

1. Open [Velocity's animation test tool](http://codepen.io/julianshapiro/full/oHaCy/) in Chrome or Firefox
2. Observe the pretty shadow effect
3. Open the same page in MS Edge

Expected:

The same pretty shadow effect

Actual:

A big solid black border effect.

Tested on:

Microsoft Edge 38.14393.0.0
Chrome 54.0.2840.99 m

Screenshot

Chrome:
![2016-12-12 10_13_42-](https://cloud.githubusercontent.com/assets/280206/21095511/af8be114-c053-11e6-8424-57104e933d09.png)

Edge:
![2016-12-12 10_18_51-](https://cloud.githubusercontent.com/assets/280206/21095674/6d6bfa7a-c054-11e6-8e8f-ed949bf8cbe6.png)

**Comment by n3dst4** [comment]
As far as I can tell, the generated shadow property is constructed in an older format which Edge has somehow chosen to drop support for. The text-shadow for example is in the format `color offset-x offset-y radius blur`, while the official format is `color offset-x offset-y blur`.

**Comment by MattyBalaam** [comment]
It's going to be a test which was made to make it compatible with IE https://github.com/julianshapiro/velocity/issues/388

**Comment by Rycochet** [comment]
Needs to be looked into, but currently (1.4.0+) you can ignore those split bits, and use the entire string value directly - `{boxShadow:["red 0px 0px 25px", "blue 10px 10px 15px"]}` etc :-)
