### ISSUE TITLE
Question - How to fadeOut and SlideDown at the same time?

### ISSUE THREAD

**Issue by jason-engage** [julianshapiro/velocity#734]
What's the syntax to perform two macros at the same time on the same element? Thanks

**Comment by Rycochet** [comment]
You'd have to choose one, and manually run the other without a queue (so it runs simultaneously) - personally I'd just `fadeOut` with opacity, and run the `slideDown` one normally:

```
Velocity(elements, {
   opacity: [0, 1]
}, {
   queue: false
});
Velocity(elements, "slideDown");
```
