### ISSUE TITLE
Publish 1.4.1 to NPM

### ISSUE THREAD

**Issue by lukeapage** [julianshapiro/velocity#736]
Its missing, only 1.4.0 is present.

**Comment by Daniesy** [comment]
+1

**Comment by kvirani** [comment]
@Rycochet and I just published 1.4.2 which has an additional IE8 fix since. Didn't publish the 1.4.1 tag since the package.json was not correctly set. Hope that's good enough for now. 

That said, if you specifically want 1.4.1 then re-open this issue and we'll get that fixed.
