### ISSUE TITLE
Velocity slower than $.animate for animating scrollTop

### ISSUE THREAD

**Issue by alysson-pina** [julianshapiro/velocity#737]
After running many tests, could determine that $.velocity is worse than $.animate in terms of performance to animate window scrollTop.

Ran the following benchmark test to verify:

```
var time = Date.now(); 

for( var i=0; i<100000; i++ ){
    $( 'body' ).animate( {
        scrollTop: '100px'
    }, 0 );
}

console.log(  Date.now() - time );
```

vs

```
var time = Date.now(); 

for( var i=0; i<100000; i++ ){
    $( 'body' ).velocity( {
        scrollTop: '100px'
    }, 0 );
}

console.log(  Date.now() - time );
```

**Comment by Rycochet** [comment]
Several issues with your premise there:

* You're adding to a queue, the final time is related to setting up the queue, and not the animation.
* Velocity handles `scroll` differently, see http://velocityjs.org/#scroll - so the Velocity test isn't actually doing anything at all.
* Your Velocity code is also setting up a jQuery object first (and while Velocity might give a jQuery method, that's convenience and not requirement).

While you might be right, it's unlikely - and your code is incapable of proving anything I'm afraid.
