### ISSUE TITLE
IE8 error, 'hasOwnProperty' not supported on window.performance

### ISSUE THREAD

**Issue by a10nik** [julianshapiro/velocity#738]
Velocity throws 
> Object doesn't support property or method 'hasOwnProperty'

on load.

To reproduce the error, just include `<script src="https://cdnjs.cloudflare.com/ajax/libs/velocity/1.4.1/velocity.js"></script>` into empty html and open it either in IE8 emulation mode or in a real IE8.

It's happening since https://github.com/julianshapiro/velocity/commit/7255f4cf267ed5434cbc4206378f19a5909d3211. In IE8 for some reason `window.performance` is not considered a proper Object and therefore lacks its prototype methods including `hasOwnProperty`.

In case you're planning to discontinue IE8 support, better declare it on the main page and close the issue.

**Comment by Rycochet** [comment]
A lot of IE8 "objects" aren't really objects at all - need to note all of the IE fixes for version 2 where they're getting removed (hopefully a couple more releases before then though).
