### ISSUE TITLE
Question - scrollbound animations

### ISSUE THREAD

**Issue by makshh** [julianshapiro/velocity#741]
[ScrollMagic Velocity.js Plugin](http://scrollmagic.io/docs/animation.Velocity.html)

> With the current version of Velocity scrollbound animations (scenes with duration) are not supported.
This feature will be added as soon as Velocity provides the appropriate API.

Is there a possibility that it will be implemented in the near future?

**Comment by Rycochet** [comment]
That made absolute no sense to me until I had a look at it - so translating:

Timeline control to allow manual positioning and changing direction etc.

It's planned, but not sure when it's going to get done, I don't think I'm going to get much time for coding on Velocity over the next month at least...

**Comment by Rycochet** [comment]
This is now available within V2 - documentation explaining how to do it is a little behind though. Have a look at `anim=Velocity(...); anim.velocity("option", "percentComplete"[, 0.5])`

**Comment by makshh** [comment]
Hi,

Could you give me an example? I don't quite understand that.

I've tried this, but I think it's not correct (isn't second parameter a duration?):

```js
var anim = $('#el').velocity({
  backgroundColor: '#eee'
});

anim.velocity({
    backgroundColor: '#111'
}, 'percentComplete', 30);
```

**Comment by Rycochet** [comment]
The second call sets the current "position" within the animation to 50% of the way through it (it moves the start time accordingly).

```javascript
var anim = $('#el').velocity({
  backgroundColor: '#eee'
});

anim.velocity("option", "percentComplete", 0.5);
```

**Comment by makshh** [comment]
Hmm, can you look at this? I thought I would see something between `#eee` and `#333`.

https://codepen.io/makshh/pen/ddWNGP

**Comment by Rycochet** [comment]
It's still a running animation - use "pause" and "resume" commands if you're wanting to pause it...

Velocity is an animation library, if you're just wanting to get the values it would supply then there's also the "tween" action called identically to a normal animation, but with "tween" as the first argument, and a percentage for the second argument - then it'll return the values that would be animated to at that specific point in time if the animation was live (it returns different types depending on the number of properties, see the wiki) -

```javascript
var backgroundColor = $('#el').velocity("tween", 0.5, {
  backgroundColor: '#eee'
});
```

**Comment by makshh** [comment]
Ok, I think I finally understood what you are trying to explain to me :)

https://codepen.io/makshh/pen/oEWeGG?editors=1010

Do you think it's ok? Is it maybe possible in Velocity 1.x?

**Comment by Rycochet** [comment]
Not going to be possible in V1 at all, that's only going to get important fixes as a compatibility support for old browsers.

MotorCortexJS is using this extensively so give complete control over an entire multi-element animation, they're currently testing their next version and using V2 to drive it.
