### ISSUE TITLE
The above 1.32 version does not support IE8？

### ISSUE THREAD

**Issue by yi-huan** [julianshapiro/velocity#742]
In IE8,
When I when using 'slideDown', codes are always wrong.
**Array.prototype.slice: 'this' 不是 JavaScript 对象**

**Comment by Rycochet** [comment]
Can you give me a JSFiddle where it happens, it *should* be working. IE8 support won't be removed till v2.0.0

**Comment by Rycochet** [comment]
Doh, just found the issue - https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/slice#Streamlining_cross-browser_behavior - I'll get that fixed!

**Comment by yi-huan** [comment]
I'm sorry for so long.
I find it still not available in IE8.
Prompt information:
**SCRIPT5009: “cloned”未定义
velocity.js (546,6)**
I changed to **return clone;** , it still can't work.

I'll stick the code in JSFiddle when I'm free tomorrow.
