### ISSUE TITLE
Upgrade to 1.4.2 has stopped animation working in IE9

### ISSUE THREAD

**Issue by garethadavies** [julianshapiro/velocity#746]
Hi,

I have recently upgraded from version 1.3.1 to 1.4.2 (alongside velocity-react v1.2.1) and have noticed that all my animations have stopped working in IE9 (see error in console below)

![screen shot 2017-02-06 at 14 32 42](https://cloud.githubusercontent.com/assets/1398606/22651295/7dfab366-ec7a-11e6-9dae-f5c6a7967135.png)

Has IE9 support been dropped?

I have tracked down the point IE9 stopped working to this commit: https://github.com/julianshapiro/velocity/commit/04e6c35cf1ebed41c909ed77467ea8e7d18ad00c?diff=split

I can revert back to 1.3.1 but it'd be great to be able to use the latest code.

Thanks

**Comment by Rycochet** [comment]
I'm really busy in general right now, but will try to look into this asap.

Please be aware that using any form of Browser / Document Mode is wrong and broken - you need to actually run in IE9 to test things (via BrowserStack, or a virtual machine etc) - I've been hit by things working in newer IE when telling it to behave like an older one, but breaking on the real browser (and vica-versa).
