### ISSUE TITLE
Consistent handling of option queue=true

### ISSUE THREAD

**Issue by joonis** [julianshapiro/velocity#748]
At time the option `queue=true` creates a custom queue I think.
But it would be consistent to treat this the same way as it is done for `queue=""`.
Because `queue=true` should be just the opposite of `queue=false`.

**Comment by Rycochet** [comment]
Not sure what you mean here - http://velocityjs.org/#queue

`queue:"abc"` is a custom queue.
`queue:""` is a custom queue with an empty name.
`queue:true` is the default queue.
`queue:false` is run without a queue.

**Comment by joonis** [comment]
Really? Here I have the following behaviour:

`queue:"abc"` is a custom queue which must be started manually.
`queue:""` is the default queue which starts automatically.
`queue:true` is a custom queue which must be started manually.
`queue:false` is run without a queue.

**Comment by Rycochet** [comment]
Ok, totally wrong behaviour - should be as in my reply (and the docs, which matches with jQuery), so this needs to be fixed and put into tests.

As this will break behaviour it'll have to be a revision to fix it (to bring it in line with documentation etc).

**Comment by joonis** [comment]
`queue:true` is not documented at all. At least on the Velocity website.

**Comment by Rycochet** [comment]
Nope, but it is on the jQuery one which is being used as the basis - it should be the default value (I've got a feeling it's not).

**Comment by joonis** [comment]
No. `queue` defaults to `""`.

**Comment by Rycochet** [comment]
It uses jQuery .queue directly (or via the polyfill) - so it defaults to the same as jQuery.

**Comment by joonis** [comment]
https://github.com/julianshapiro/velocity/blob/master/velocity.js#L676

**Comment by Rycochet** [comment]
...Hence why I've tagged it as a bug - a string queue by definition needs to be manually started - this looks like specific behaviour that shouldn't be in there. The default needs to be correct, and the code needs to support it.

**Comment by Rycochet** [comment]
In v2 ```queue:true``` is not permitted, and will result in a console warning and use of the default queue.
