### ISSUE TITLE
Reset styles and rerun animation

### ISSUE THREAD

**Issue by stephan-fischer** [julianshapiro/velocity#750]
Hello,

i want rerun an animation, after i removed the extra styles, which 
added velocityjs. But it is not working. Here is a fiddle [fiddle](https://jsfiddle.net/1gxLuszc/1/).

```
var element = document.getElementById('animate');

var animate = function()
{
  Velocity(element, {translateX: 500},  {duration: 2000, queue: false, complete: function(){
		element.removeAttribute('style');
 		animate();
  }});
};

animate()
```

Have someone any idea, to manage this? Is there a reset function or something?

**Comment by Rycochet** [comment]
http://velocityjs.org/ - Read the "Secret Sauce" part near the top - basically Velocity caches the values, so removing them makes no difference.

Use ForceFeeding to provide the starting values you want to use - http://velocityjs.org/#forcefeeding

**Comment by stephan-fischer** [comment]
Hi Rycochet,

i hope you can answer on closed Issued. Exactly what i have fiddled, i need for banner ad development. And in this case is easer to not know the "starting values". Can the Cache be cleared by a function like "reset" - or "clear cache"? If not maybe its a good new feature.

**Comment by Rycochet** [comment]
Add the non-public `_cacheValues:false` to the options on the call - this might change in the future so we can give a public method to clear the cache rather than not saving it...

**Comment by stephan-fischer** [comment]
Thank you, yes i've tried this parameter before, but this parameter has no effect at all:
[https://jsfiddle.net/1gxLuszc/2/](https://jsfiddle.net/1gxLuszc/2/)

**Comment by Rycochet** [comment]
Damn, it definitely looks like it should work from the source, can confirm that it doesn't work. There is a hacky way to clear internal data, but I can't remember what it is (having never used it or looked at the cache code) - instead could you clear the values via Velocity with a duration of 0?
