### ISSUE TITLE
Loop not working (without jQuery)

### ISSUE THREAD

**Issue by stephan-fischer** [julianshapiro/velocity#751]
I  try to loop the element. If i want to loop infinite the element, this error 
occurred:
VM125 velocity.min.js:3 Uncaught TypeError: Cannot read property 'length' of null
    at Function.c.each (VM125 velocity.min.js:3)
    at n (VM125 velocity.min.js:3)
    at m (VM125 velocity.min.js:3)
    at VM125 velocity.min.js:4

Here is the fiddle: [https://jsfiddle.net/t1y1vhuk/1/](https://jsfiddle.net/t1y1vhuk/1/)

And if i use a value like 3 or 4, nothing happens

Thank you!

**Comment by stephan-fischer** [comment]
Ah if i remove the queue: false parameter it will work, but it should work with queue: false or?

**Comment by Rycochet** [comment]
There's an issue with how the `queue` option works. You should also be able to loop without it being in a queue. They're two separate things, which might have overlapping code when I get a chance to look into it.

**Comment by Rycochet** [comment]
No longer an issue in V2
