### ISSUE TITLE
SVG Path morph

### ISSUE THREAD

**Issue by endling9973** [julianshapiro/velocity#752]
Maybe this is not the proper place to ask this, so I'm really sorry if this is the case.

Is there a way to morph SVG paths with velocity?

FROM
"M292,129c55.2,0,193,125.8,193,181S365.7,506,310.5,506S136,355.2,136,300S236.8,129,292,129z"

TO 
"M230,38c55.2,0,348,57.8,348,113S391.2,569,336,569S55,456.2,55,401S174.8,38,230,38z"

If this is not currently available, is there any plans to offer this feature?

Thank you very much,
Best,

**Comment by Rycochet** [comment]
Use the `tween` value, and pass to and from via forcefeeding, then add a `progress` callback to copy the tween value into the path. Just make sure that the paths both have the same number of parts (ie, numbers are parsed out and tweened between the two values - but there's got to be the same number of them for it to work).

**Comment by endling9973** [comment]
Can you provide a code snippet? I will write an working example.

**Comment by Rycochet** [comment]
http://velocityjs.org/#forcefeeding
http://velocityjs.org/#progress

**Comment by endling9973** [comment]
Thank you.

So helpful.

http://stackoverflow.com/questions/42228003/is-it-possible-to-morph-a-svg-using-velocity-js
