### ISSUE TITLE
Loop is played only once in IE9

### ISSUE THREAD

**Issue by mozzi** [julianshapiro/velocity#753]
**Expected:** animation in code below had to be played 3 times in Ie9
**Result:** The loop in code below is played only once
also there are following error in console
`Velocity: First argument ([object HTMLDivElement]) was not a property map, a known action, or a registered redirect. Aborting.`

JsBIn link for testing: http://output.jsbin.com/wocideguzo/1
editor: http://jsbin.com/wocideguzo/1/edit?html,output

```
    $(".block").velocity(
      { backgroundColor: "#00A2FF" },
      {
        loop: 3,
        duration: 1000
      });
```

**Comment by Rycochet** [comment]
Maybe linked to #747, #746 might be related to (obvious code bug fixed, but not had time to test)

**Comment by Rycochet** [comment]
IE9 is no longer supported in V2
