### ISSUE TITLE
Reset value not apply in velocity ui

### ISSUE THREAD

**Issue by ericm546** [julianshapiro/velocity#755]
Since the commit 7b196f5, the reset values of velocity ui animations are not apply correctly in the complete step.

For example, if I have a square 
![Image](http://i.imgur.com/4PoTR1o.png)

And I apply the following animations: 
transition.perspectiveUpOut
transition.slideUpBigIn
After perspectiveUpOut is executed, the reset step won't be correctly apply and rotateX will stay to -180deg.
The square will look like that after transition.slideUpBigIn is executed
![Image](http://i.imgur.com/bz3a6E5.png)

**Comment by Rycochet** [comment]
The ui-pack animations have been rewritten
