### ISSUE TITLE
velocity can use for scroll reveal animation?

### ISSUE THREAD

**Issue by rae0724** [julianshapiro/velocity#758]
Hi, I am using velocity for the first time
And I am curious whether I can use this for scroll and revealing the items with animation
something like scrollreveal.js

**Comment by Rycochet** [comment]
@rae0724 Velocity is an animation library only - so if you want to animate something use Velocity, but you'd need to use other code (or libraries) to handle when things happen. It also has no timeline type control (will be added, but probably not for several months), so while animations can be paused, or run backwards, it is not currently possible to give fine control or do both simultaneously.
