### ISSUE TITLE
potential memory leak: elements using delay may not be released from internal delayedElements store

### ISSUE THREAD

**Issue by westhom** [julianshapiro/velocity#760]
Velocity permanently hangs onto DOM elements via its internal State.delayedElements store if "stop"/"finish" is not explicitly called before you remove an element from the DOM, even after velocity has completed. This causes growth of non-GCable detached nodes which can really add up over time depending on your use case.

[Demo fiddle here](https://jsfiddle.net/nz5ffffc/1/).

1. open chrome dev tools and go to Timeline tab; check "memory" in capture settings
2. press record button
3. press "makes stuff" button for a few rounds, e.g. 10 times
4. press trashcan button (collect garbage) in Timeline. 
5. Stop recording

Node count stays high after GC.

Rerun above steps after uncommenting marked line in makestuff(), and observe node count returns to baseline after GC.

**Comment by Rycochet** [comment]
I really need to have a look into how it does this - unifying pause and delay etc might be worth doing to simplify the code and remove potential leaks like this.

**Comment by Rycochet** [comment]
In V2 delay was rewritten to be a property on a running animation, there is on separate queue for it
