### ISSUE TITLE
Unexpected error when in non-strict mode and slideUp/slideDown redirects are involved

### ISSUE THREAD

**Issue by futpib** [julianshapiro/velocity#761]
Originally reproduced in IE9, though I expect it to reproduce wherever strict mode is not supported.

### Steps to reproduce
1. Run in no-strict-mode environment
2. Velocity.Promise is set to a Promise A+ implementation
3. Code:
```js
const element = document.createElement('div');
Velocity(element, 'slideDown').then(function () {
	console.log('resolved');
}, function (e) {
	console.log('rejected', e);
});
```
#### Expected
Prints 'resolved' (or 'rejected' if something went wrong)
#### Actual
Prints (in IE9)
```
Velocity: First argument ([object HTMLDivElement]) was not a property map, a known action, or a registered redirect. Aborting.
```

### Debugging thoughts
* No "rejection" callbacks are used in slideUp/slideDown redirect https://github.com/julianshapiro/velocity/blob/8c3d003/velocity.js#L4657
* `isUtility` affects `promiseData` creation
* `isUtility` is set depending on `Type.isWrapped(this)`
* `this === window` in unexpected places (no strict mode thing)
* `Type.isWrapped(windows) === true` (not sure if this is intended behaviour)

**Comment by Rycochet** [comment]
I've got a strong feeling that's been fixed in the latest release - can you just check what version of Velocity you're running against?

**Comment by futpib** [comment]
1.4.3, latest available on npm. Should I check against `master`?

**Comment by futpib** [comment]
Also #757 is somewhat related (the `Type.isWrapped(windows)` part of this issue)

**Comment by Rycochet** [comment]
@futpib Nope, that's cool - they're currently the same - drat, looks like I need to spend more time on IE9 too - hoping to get some time to look at the various obsolete IE issues over the weekend...

**Comment by futpib** [comment]
Just checked that #757 fixes this indeed.

**Comment by futpib** [comment]
Ok, so #757 fixes the original example code, but the "promise rejections are not propagated" part still holds. I'm gonna open another issue about that not related to IE9 or strict mode for less confusion.
