### ISSUE TITLE
'scroll' breaks when element has a relative parent before container

### ISSUE THREAD

**Issue by BenDTU** [julianshapiro/velocity#770]
When scrolling to an element, having a relatively positioned parent between the element and the parent will cause `scrollPositionEnd` to be set incorrectly. This is due to the use of .position(), which will return the element's position compared to the nearest relative parent.

Replicated here: https://jsfiddle.net/uhtn3Lg1/1/

**Comment by paddyobrien** [comment]
I just ran into this issue too. Looks like the problem has been known about for a long time and a PR was proposed back in 2015: https://github.com/julianshapiro/velocity/pull/564

**Comment by Rycochet** [comment]
It's a known change, but also a major break in behaviour that will hit anything already using it. There are a couple of other issues with `"scroll"` and its ease of use - so while it'll get fixed at some point, it'll be part of a major version number change...

**Comment by paddyobrien** [comment]
Thank you for replying, and thanks for the awesome library. Do you think this is a breaking change or a bug fix? (and hence ok for patch release)

From my perspective as a user of the lib this definitely felt like a bug. I'd be surprised if people were relying on this behaviour but perhaps I'm not seeing a use case.

**Comment by Rycochet** [comment]
It's a bug - but I can't assume that nobody is coding against it - so it's definitely a breaking change to fix it too :-/

**Comment by BenDTU** [comment]
Thanks for the reply - we're using the offset value to correct in the meantime, so it's not a huge deal.

**Comment by siddo420** [comment]
in my case, calculating offset value is almost impossible

**Comment by Discartyptics** [comment]
I too am encountering this issue... I'll look into using _offset_ in the meantime.

**Comment by Rycochet** [comment]
In V2 the `scroll` code has changed completely. Now you animate on the element that is scrolled directly, and pass it as any other property to be animated. While the code handling this may change slightly, the actual API for this will not. You can now use "`scroll`" / "`scrollTop`" and "`scrollLeft`".

There is no `"scroll"` command as in previous versions, so figuring out what to scroll is no longer an issue.
