### ISSUE TITLE
UI pack: Can’t use slideUp/Down or fadeIn/Out within Velocity.RegisterEffect

### ISSUE THREAD

**Issue by danielvdspuy** [julianshapiro/velocity#772]
I’d like to leverage slideUp/Down in my UI transition, but am unable to.

Have tried something like this:
```javascript
$.Velocity.RegisterEffect("transition.openDrawer", {
    defaultDuration: 800,
    calls: [
        [{ slideDown }, { duration: 1200 }],
        [{ opacity: 1 }, { queue: false }]
    ]
});
```

As well as:
```javascript
// line 4
        [slideDown, { duration: 1200 }],
```

Console output
> Uncaught ReferenceError: slideDown is not defined

Is this possible at present?

Many thanks.

**Comment by Rycochet** [comment]
Both of those are completely invalid Javascript, so not surprising that they don't work to begin with.

I don't know if it's possible to work, but I don't expect it to - feel free to try with valid code -
```javascript
["slideDown", { duration: 1200 }],
```

If not then it'll go on the todo list :-)

**Comment by danielvdspuy** [comment]
Sorry, I did actually wrap the method (or whatever slidedown is) in quotes, but didn’t update the example.

```javascript
$.Velocity.RegisterEffect("transition.openDrawer", {
    defaultDuration: 800,
    calls: [
        ["slideDown", { duration: 1200 }],
        [{ opacity: 1 }, { queue: false }]
    ]
});
```

So yeah, that doesn’t work. Console output:
> Uncaught SyntaxError: Unexpected token }

Which to me says that it expected a key and property

**Comment by Rycochet** [comment]
Cool, I didn't know and didn't expect it to, but good to hear :-)

**Comment by danielvdspuy** [comment]
Thanks for your help with my syntax. 😂

This is probably handy to have in the docs I guess, under UI pack > Effects: Registration.

Unfortunately, the queue prop doesn’t work for `slideDown`, i.e.:
```javascript
$.Velocity.RegisterEffect("transition.openDrawer", {
  defaultDuration: 2000,
  calls: [
      ["fadeIn", { duration: animationDuration.steady }],
      ["slideDown", { easing: animationBezier.swiftIn, queue: false }],
  ]
});
```

**Comment by Rycochet** [comment]
A lot of the props aren't passed on - but changing (which will happen) will be a breaking change in the future.
