### ISSUE TITLE
transform: scale() doesn't start from initial value

### ISSUE THREAD

**Issue by debaze** [julianshapiro/velocity#774]
Hi,

I noticed something I don't understand:

Initially I declare "transform: scale(0.6)" on an image (inline or in stylesheet makes no difference).
Then I animate scaling like so: $("#foo").velocity({scale:0.2}, {duration: 500})
But the animation starts from scale 1 instead of the displayed scale which is 0.6.

However, if I stop the animation using .velocity("stop"), the next animation starts from the correct (last reached) value.

Workaround is to 'force feed' the initial/last value in the .velocity call by querying the DOM explicitly, but possibly there is another fix..

Tested on Firefox 53 and on Chromium 53

Thanks for any feedback!
Joris

**Comment by Rycochet** [comment]
That's how transform works sadly, you need to use forcefeeding to bypass it - at some point this year I'm hoping to have the time to close the 2+ year old issue that can fix this (it's a lot of code, so not trivial, and quite a lot of bloat) - https://github.com/julianshapiro/velocity/issues/269

**Comment by debaze** [comment]
Thank you for your answer, I didn't know it was an outstanding issue, so sorry for repeating. Thanks for all the effort you've been putting into this awesome project!
