### ISSUE TITLE
boxShadowColor not work

### ISSUE THREAD

**Issue by zeroonea** [julianshapiro/velocity#778]
Hi the boxShadowColor attr is not work. It always add black color into box-shadow

seem it link incorrect output

Set boxShadow (boxShadow): rgb(0, 255, 0) 0px 0px calc(0px + 0.06759526299369244em) 0px

velocity.min.js:2343 
Set boxShadow (boxShadow): rgb(0, 255, 0) 0px 0px calc(0px + 0.06759526299369244em) 0px   calc(0px + 0.06759526299369244em)

velocity.min.js:2343 
Set boxShadow (boxShadow): 0px 255, 0) 0px 0px calc(0px + 0.06759526299369244em) 0px calc(0px + 0.06759526299369244em

velocity.min.js:2343 
Set boxShadow (boxShadow): 0px 0em 0) 0px 0px calc(0px + 0.06759526299369244em) 0px calc(0px + 0.06759526299369244em

velocity.min.js:2343 
Set boxShadow (boxShadow): 0px 0em 0em 0px 0px calc(0px + 0.06759526299369244em) 0px calc(0px + 0.06759526299369244em

velocity.min.js:2343 
Set boxShadow (boxShadow): 0px 0em 0em calc(0px + 0.10533222588809943em) 0px calc(0px + 0.06759526299369244em) 0px calc(0px +

**Comment by Rycochet** [comment]
Please supply a [demo](https://jsfiddle.net/mqv9L27u/) as requested in the [guidelines](https://github.com/julianshapiro/velocity/blob/master/CONTRIBUTING.md).

**Comment by zeroonea** [comment]
Here is the test case: https://jsfiddle.net/fjdpyrd7/5/

**Comment by zeroonea** [comment]
Is it bug?

**Comment by Rycochet** [comment]
Despite the very bad Velocity code ni there, it is a bug - looks like `boxShadow` (and possibly anything else where it splits it down) is doing it at a bad place preventing you from using them properly.

**Comment by zeroonea** [comment]
Are you plan to fix it in next release?

**Comment by Rycochet** [comment]
This is no longer an issue in Velocity V2.
