### ISSUE TITLE
Default queue does not run automaticaly since 1.4.3

### ISSUE THREAD

**Issue by nreynis** [julianshapiro/velocity#781]
It seems you have a regression with version 1.4.3.
If I queue two animations they will run automaticaly, that's the expected behaviour from default queue.
If I add more animations to the default queue they will also run automatically... well that's what happened before version 1.4.3, now only the first item added to the queue is runned.

Here is a codepen which reproduce the problem. The first time you click you have two translations, the second time only one. If you change the library version to 1.4.2 or less, the behaviour will be totally different.

https://codepen.io/anon/pen/XROPzM

**Comment by ywg** [comment]
Even though the second animation in the queue do not appears to run, it's "begin" and "complete" callback are called...
That's really weird.

**Comment by Rycochet** [comment]
Ouch - not sure what's going on there as nothing in 1.4.3 was touching the queue - there's something unintended, and I'll make it a priority to figure it out (but apologies for being so busy that it might take a while)

**Comment by ywg** [comment]
No problem, I'll downgrade to earlier version.

**Comment by Rycochet** [comment]
All handling has been rewritten in V2, please re-open if it doesn't work now (though `translateX` and other transform shortcuts no longer exist).

**Comment by nreynis** [comment]
Thanks, this works:
https://codepen.io/anon/pen/GGKMbd

While testing I found another but in queuing. I'll open a new ticket.
