### ISSUE TITLE
Velocity with Scrollmagic

### ISSUE THREAD

**Issue by fan-r-takei** [julianshapiro/velocity#782]
I'm trying to get velocity's Sequenced Animations to run with scrollmagic.
**This is the code taken from ScrollMagic's docs on Velocity.**
<script>
// init controller
var controller = new ScrollMagic.Controller();

// build scene
var scene = new ScrollMagic.Scene({triggerElement: "#trigger"})
	// trigger a velocity opaticy animation
	.setVelocity("#animate", {opacity: 0}, {duration: 400})
	.addIndicators() // add indicators (requires plugin)
	.addTo(controller);
</script>

**This is the sequence animation snippet taken from Velocity docs**
<script>
var mySequence = [
    { e: $element1, p: { translateX: 100 }, o: { duration: 1000 } },
    /* The call below will run at the same time as the first call. */
    { e: $element2, p: { translateX: 200 }, o: { duration: 1000, sequenceQueue: false },
    /* As normal, the call below will run once the second call is complete. */
    { e: $element3, p: { translateX: 300 }, o: { duration: 1000 }
];
$.Velocity.RunSequence(mySequence);
</script>

How can I add the sequence into scrollmagics?
var scene = new ScrollMagic.Scene({triggerElement: "#trigger"})
                .setVelocity <-- sequence here
                .addTo(controller);

Please help.
Thank you!

**Comment by Rycochet** [comment]
You'd need to take it up with ScrollMagic as we have nothing to do with it (unlike the other way around where they support us) - however logically I'd be looking to see if they support Velocity Sequences at all.

**Comment by fan-r-takei** [comment]
I see!

Thank you.
