### ISSUE TITLE
backgroundImage

### ISSUE THREAD

**Issue by marianoarga** [julianshapiro/velocity#783]
Is ther any way to animate the background change?, i'm trying the following:

```
$("#tag-id").velocity({
                        "background-image": "url('https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Google_2015_logo.svg/1200px-Google_2015_logo.svg.png')",
                },
                {
                    duration: 3000,
                }
);
```

**Comment by Rycochet** [comment]
Sadly not - you can use the `complete` callback (and animate the `tween` value). Saying that however, in Chrome at least if you have a css `transition:background-image 3s;` and you change it then it will fade from one to the other over that period of time rather than simply swapping images.
