### ISSUE TITLE
$.css is not a function

### ISSUE THREAD

**Issue by AmazingDreams** [julianshapiro/velocity#784]
[This line](https://github.com/julianshapiro/velocity/blob/9f4aacdacd9eff5a4abbd5154b8d367dcda2f047/velocity.js#L2090) casues an issue in a specific minified build I had:

`computedValue = $.css(element, property);`

I believe it should be:

`computedValue = $(element).css(property);`

**Comment by AmazingDreams** [comment]
Here is the diff that fixed my build:

```
     new webpack.optimize.UglifyJsPlugin({
       compress: {
-        warnings: false,
-        pure_getters: true,
-        unsafe: true,
-        unsafe_comps: true,
-        screw_ie8: true
+        warnings: false
       },
       comments: false,
-      mangle: true,
-      sourceMap: false
+      sourceMap: true
     }),
```

**Comment by klotim** [comment]
by looking at how the other was written, should it not be:
computedValue = CSS.(element, property);

**Comment by AmazingDreams** [comment]
This was some time ago so I don't remember exactly what the problem was. I believe the issue was on IE8 only. Probably it had to do with the `screw_ie8: true` property.

Anyway, I don't think jQuery works with `$.css(element, property)` according to their [docs](https://api.jquery.com/css/) or at least it is not documented.

**Comment by AmazingDreams** [comment]
No I just remembered I was wrong about it only occuring on IE8. My guess is that some uglify option removed the check or something and caused the code to always be executed instead of only for IE8.

**Comment by Rycochet** [comment]
The docs do state that IE8 isn't supported without jQuery directly, so might be something that got removed - http://velocityjs.org/#dependencies - I'm just glad that there's almost no reason to support any IE below 11 any more (and at work we make sure we specify that!)
