### ISSUE TITLE
Chrome Dev-Tools Animations Tab does not record Velocity's Animations

### ISSUE THREAD

**Issue by arendtio** [julianshapiro/velocity#785]
I know velocity.js since a while but never really tried to use it (due to a lack of application). Now I have a project where I would like to use it but found something slightly disturbing: In the Chrome Dev-Tools is a Tab called 'Animations' which is very useful as it records animations, lets you replay them, slow down or even pause. But Velocity's animations do not seem to be recorded by the tool.

My first guess would be that the tool only records CSS Animations but I am wondering what velocity does so differently that Chrome does not recognize the animations?

For a simple test:
- just visit http://velocityjs.org
- open the Chrome Dev-Tools Animations tab
- hover a link and you can see how chrome records the color transition
- trigger one of the demos, nothing happens in the animations tab

**Comment by Rycochet** [comment]
Chrome is giving a pure css animation debug tool there, Velocity is Javascript. The Chrome devs have no reason to do anything with Javascript changes to CSS styles, but you'd have to take it up with them.

**Comment by arendtio** [comment]
@Rycochet while I understand your argument, I do not know enough about velocity.js to understand if there is **any** way (e.g. micro CSS animation steps via JS) this could be fixed within velocity.js while maintaining it's other properties (no layout trashing).

I am asking this question because I think the chrome dev-tools module could be critical to velocity.js' future adaption. AFAIK you are the Lead-Dev for velocity.js and therefore I would like to ask you if there is some way to change velocity.js to work with the dev-tools module, while maintaining the other properties (is it somehow possible?.

If there is no way this could be done (e.g. any solution would introduce layout trashing?), please tell me and if there are ways please tell me why you would not like to change velocity.js in that way (too much work? breaks architecture? etc.).

**Comment by Rycochet** [comment]
Unfortunately it's a no - the only thing in common is that it's an animation, but it's like having two cars - one diesel and one gasoline, they both get you places, but the way the engine works is almost totally different.

It's not something that can be fixed as it's not something that's wrong. Future versions of Velocity will give a lot more control over things, but there's really no ETA simply because of a lack of time on my part (and very few people help beyond their own little improvement).
