### ISSUE TITLE
Reset visibility to allow toggle show/hide

### ISSUE THREAD

**Issue by sanjshah** [julianshapiro/velocity#786]
This is more of a question rather than an issue, I am trying resetting the state after exit transition so I can restart it, i.e. I first show a div using;

$(hypeDocument.getElementById(mydoc)).velocity("transition.flipXIn", { stagger: 250 }, { delay: 5000 });

Then close the div via:

$(hypeDocument.getElementById(mydoc)).velocity("transition.flipXOut", { stagger: 250 }, { delay: 5000 }, {visibility: "hidden"} );

However when I try to use the show again the div does not show? not sure how to reset the div to allow the toggle show / hide?

Any help is appreciated.

**Comment by Rycochet** [comment]
You're forgetting to add `{visibility:"visible"}` to the first one - that should then let you toggle between the two.
