### ISSUE TITLE
Animate scroll on mousewheel rolling

### ISSUE THREAD

**Issue by pingshunhuangalex** [julianshapiro/velocity#787]
Velocity works great when I want it to scroll to a specific position or an element.

Just wondering if there is a way to animate the scroll behaviour on mouse wheel rolling. I tried changing the parameter in the codepen [here](https://codepen.io/julianshapiro/pen/kBuEi) given by the official website, it doesn't seem to do anything... Tried adding velocity animation to event listener doesn't seem to work either.

Any help would be appreciated. Thanks.

**Comment by Rycochet** [comment]
Sadly things don't work that way - Velocity only animates to what you want, while the mouse scroll wheel comes before that. Saying that, there are several libraries around which do that, but not sure if any would let you use Velocity for it.

Essentially you just need to override the `mousewheel` event, and `event.preventDefault()` within the handler, and decide where it's going to animate to etc. Things to bear in mind is that touch devices have their own handling, and users can easily have different scroll amounts which you'd be overriding with this etc. It's also only supported on Chrome and Edge...

https://developer.mozilla.org/en-US/docs/Web/Events/mousewheel
https://developer.mozilla.org/en-US/docs/Web/Events/scroll
