### ISSUE TITLE
Version 2 beta & feedback wanted...

### ISSUE THREAD

**Issue by Rycochet** [julianshapiro/velocity#790]
Velocity is finally getting a lot of love and updates, sadly it's also going to lose support for older browsers (I'm planning to make a compatibility layer with polyfills for them, but that's low priority).

See the [Project](https://github.com/julianshapiro/velocity/projects/1) or the [develop branch](https://github.com/julianshapiro/velocity/tree/develop) :-)

Among other things, it is already converted to Typescript (that means nothing to anybody who isn't developing for Velocity directly - but looking at the code should show how similar things are).

It is also losing the requirement for any jQuery stuff - currently there's a shim for what we use, but that is being replaced by native calls and custom code.

The API for extending it is getting expanded and improved (and hopefully getting easier to use too). I'm planning to make use of the wiki on here, and there will eventually be the website on another branch (ideally built automatically from source comments, but will have to see what I can do).

I've linked quite a few open issues into the new project as I have a definite end goal for what's needed before release - but this is where anyone still reading this is needed:

## Current TODO before anyone else can help coding

> I'll remove this section once it's done - but as I don't want to push anything that breaks the tests I might have to take a day or two with in-progress major changes that I can't easily pull against. Saying that, code snippets etc are very welcome and I can fold them in manually :-)

- [x] Finish build environment (NodeJS and Grunt)
- [x] Split out the `.CSS` section.
- [x] Fix SourceMap generation (only for non-minified version).
- [x] Remove jQuery shim.
- [x] Split apart the main `Velocity(...)` function - it's still a couple of thousand lines long!
- [x] Finalise folder structure / file layout.
- [x] Finalise Velocity extending API (even if code not finished).

## I need your help

Firstly there is testing. While I'll make sure that the included tests are all succeeding before each push, they do not cover enough uses, and can quite easily miss things (yes, that's also TODO, but not as high priority - plus some tests need to change due to internal changes anyway).

## Things to test

* By default the beta patches `jQuery`, `Zepto` and native elements, as well as the native element finding methods.
* It also makes sure that anything returned can be chained via `.velocity(...)` (as jQuery used to etc).
* It *also* always includes the Promise too.

In other words, this is now valid -

```javascript
document.querySelectorAll("div")
   .velocity({opacity: 0})
   .velocity({opacity: 1})
   .then(function() {
      console.log("Muahahaha!");
   });
```

## Things to comment / ask in here

* Anything not on the [Project](https://github.com/julianshapiro/velocity/projects/1) page that already has an open issue (no, I'm not blanket adding, I will go through them afterwards and remove the ones that are fixed as a side effect etc).
* Anything not on the [Project](https://github.com/julianshapiro/velocity/projects/1) page that would be useful to add (for example, I've been looking a bit at the [Web Animations API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Animations_API).
* Clarification on how things are changing (don't worry about bad questions, I'd rather answer something seemingly obvious than forget to mention in).

## Things not to ask

* Is Velocity v1 being updated to fix *xyz*? (The answer is no, I've made significant progress in bugfixes and improvements that I hadn't even noticed were wrong simply by refactoring to Typescript, and the amount of time I've spent is equivalent to fixing a single "easy" bug in Javascript)

**Comment by cesasol** [comment]
This would still be compatible with jquery after the dependency drop?
Like loading the jquery stuff if it is defined or specified

**Comment by Rycochet** [comment]
It will automatically add the `$("div").velocity(...)` and `$.Velocity` values as before if it is loaded directly (ie, just via a `<script>` element), otherwise it will have a call that you can use it to add to anything "safely".

I also want to look into adding something to let it add to RequireJS style AMD jQuery if it exists, but will need some feedback on if it would be worth doing :-)

**Comment by wysisoft** [comment]
i'm starting to use velocity today for a web design tool I've been building (its all typescript/nodejs) - good luck!

**Comment by Rycochet** [comment]
I think that would be some sort of utility function. If it's "my top left at bottom right of parent" then a simple `{top: 100%, left: 100%}` does the job. I've got something that I could certainly use that sort of thing on - sliding from one element to another - will think about how to do it well, and any suggestions for how would be welcome :-)

**Comment by wysisoft** [comment]
the idea of positioning elements by making them children and using percentages isn't a bad one, it might fit my immediate needs. In case you decide to implement - If I were smart and determined I would look at the jquery implementation of positioning, but instead i'd probably just start using getboundingclientrect.

**Comment by michellomp** [comment]
@Rycochet When you say it's also going to lose support for older browsers do you mean ie10 or ie11 ?

**Comment by Rycochet** [comment]
@michellomp I'm taking out most of the workarounds that are for IE9 or lower - IE10 / 11 will need a Promise polyfill while in beta, but I'd like that to be optional (ie, there by default, but you can disable it to save a little memory per animation if you know it's not needed).

Until Windows 7 goes end-of-life IE11 will still be a "major use" browser, so it might need a polyfill or two to work, but I'll include them and make sure all tests pass on it. IE10 isn't as important - but tbh any browser (above IE8) should be able to work with polyfills supplying any ES5 methods used.

To be clear - any compatibility for older browsers that is removed (IE7 and below have never been supported) should be easy to re-add via an extra file which I plan to add to the repo - this will supply any missing functionality that can be added via other polyfills.

Due to the way some internals are changing the compatibility needs are currently unknown. Currently it uses (and handles if missing) `Array.isArray()`, `Object.assign()` and `[].prototype.slice()`. Once the dev branch gets the rest of jQuery removed (it's a headache I'm dealing with now - the queue system is very inefficient for the GC etc) then I'll be able to start looking at testing on older browsers via BrowserStack.

**Comment by Rycochet** [comment]
Just want to say sorry the next beta build is taking so long - I removed the jQuery queue code, which seemed like a semi-big job to start with, but unfortunately it had the knock-on effect of breaking a lot of the testing that was hard-coded to look at the data structures rather than what was happening, which ended up distracting from the initial change (which is still unfinished - it used to use closures for passing data, which is pretty inefficient especially when passing 3k animations for a stress test).

Added to that I've had a busy week, and am in fact away completely this weekend. Hopefully I'll get this current change finished by the middle of next week, and then I only need to redesign the extending API (so things that have been removed for efficiency can be added for legacy)... Crossing fingers it'll be that quick ;-)

**Comment by Rycochet** [comment]
I've had one more evening of coding since the last update, so not much has changed - the internal data structures are pretty solid now, just a couple of decisions still to be made such as how to handle `mobileHA` in a non-hacky way (almost tempted to make it a css thing on the `.velocity-animating` class so it can be overridden extremely easily - or rather with an extra `.velocity-animating-ha` class, or a custom attribute for the same effect (as attributes are lower css priority than classes) and it would take out the js overhead of it).

It's becoming very clear that the testing itself needs to be split out into it's own source tree next to the main source tree - won't be in the next push, but sometimes soon after then I think - make it easier to track down specific tests and improve them... Cut'n'paste work again ;-)

Some API design is coming on well in my head - attributes such as the old `backgroundColorRed` etc, as well as the whole `translateX` section are going to be via extra plugin only (and not really needed, so advised against except for easy compatibility).

This isn't a blog (honest), but I do want people to know things are actually happening :-)

**Comment by Rycochet** [comment]
Copied from the last commit log (I've only had about one evening again, so progress is slow) - 

WIP BUILD - TESTS NOT WORKING

Hopefully the caps made it obvious. The internals have changed significantly, so most of the tests can no longer work as they're checking internals rather than externals. This is completely clear from jQuery, and uses more ES6/7 features that TypeScript cleans up for us. There are several major slowdowns simply because it's mid-change (but I wanted to get something out to show where things are going). I've tried to mark some data structures as @deprecated where I remember to (things like `display` and `visibility` are going to become plain properties - they might stay in the options, but only as an alias).

Performance is currently pretty bad - not least because things like display and visibility are being set on every frame (the biggest slowdown is currently the css setting call as it's being overused multiple times on every frame on every animation).

Internal caching is currently disabled - not quite sure what's going wrong on it, but the only downside is a bit of memory waste.

Internal changes include the `tick`, `progress` and `complete` being on different loops (so doing stuff in them won't slow down animations), and "new" animations are now appended to the list and take effect from the next tick - anything "new" in the current tick (including the fake one that's called when adding anything) will get it's properties expanded then (convert from the loose combinations allowed, to the specific format needed internally).

Loops and repeats (yes, there's a new `repeat:10` option - same as loop but without reversing) are now lazy - it doesn't add a pair copies of the `"repeat"` call on the end of the animation queue for every number (so it's now possible to `loop:Number.POSITIVE_INFINITY` etc).

I also have a plan / design for overloading API for the `properties` - to start with it will get `scroll`, `display` and `visibility` added, the latter two to behave the same way as custom code within the tick currently behaves - hide at the end, show at the beginning. Scroll will get `scrollTop` and `scrollLeft` added (scrolling the window will automatically use the correct method), so you can scroll a specific item - I'd like my eventual plan to allow it to scroll to a specific item by passing that as the property value, but for now it'll take numbers. Other current types will be added the same way (using a lot of the currently commented out code from the old way I expect).

Just a quick note that this is still most definitely BETA - so don't use in production etc ;-)

**Comment by Rycochet** [comment]
Slow updates right now due to lack of time, but things are still moving ;-)

Finally ran into issues with the testing setup (see previous update) - so that's getting rewritten. Currently doing it as JS rather than TS - that might change, but as it's not supposed to touch the internals of Velocity for any reason (testing for effect, not cause), when I finally get it all updated it'll be somewhat more useful. A side effect of the few tests I've already updated is finding some rather stupid bugs I'd added through moving code around or not noticing when things weren't right. Also changing most code to use `let` rather than `var` which is also helping in a few cases.

I've also done some performance testing of `Object.create(null)`, and it's slow. So is `new Object()` to be fair. The downside of not using it is having to test every potential tween key (css style name) in case somebody has extended the Object prototype (or using `Object.keys(tweens)` which is a memory waste - and trying to stay away from that for mobile performance). So one change that is going to be made (second time around), is internally changing the tweens list into an array of Objects - with the property being a value of it (currently it's an Object with the key being the property).

Also done some performance testing on string replacement. It's used for the "css style" animations that everything is supposed to be moving over to - and it's not particularly good either. The best thing for joining various values into a new string (without wasting memory either) is `"".concat.apply("", array)`At the moment internally it stores two arrays - start, end - and one string - pattern. I'm going to be changing that to three arrays, with the pattern one being split out with a number between each string (to be filled by easing the start/end values), then just `.concat` the resulting array into the final string we set to the style.

A (relatively) minor change that has just helped things is moving the init code for new animations above the tween loop - basically it puts reading css values above the writing of css values in the animation frame, which should reduce overhead *slightly* - it does still need a good look through to make it take less time (comes back to the API bit there), as we don't want it to delay the animation frame values any longer than we have to (of note, the old code would interrupt each individual tween with the complete + next init whenever it happened - part of the reason why the complete has been unrolled)...

Anyway, still really busy, so slow going right now, hopefully it'll go quickly though :-)

**Comment by Rycochet** [comment]
Sorry for the almost three week break - between getting really busy and having several health issues I've not had much time, but feeling (almost) normal again, and got some time, so back to coding at home :-)

Made some more changes to lots of places, among them is slowly phasing out my general use of `var` in favour of `let` - it makes it a lot harder to get bad side-effects from re-using variables, and Typescript happily just changes the variable names so it can use `var` and not overlap. I also removed the cached data structures - they might get back in later, but for now it might very well be a case of premature optimisation.

A note on my testing. On top of the test suite (which is a pain, and slowly being updated) I also have a stress test page that lets me animate thousands of elements simultaneously. v1 and v2 are identical in performance up to around 1k elements, but v2 rapidly gets less effective after that. I'm trying to figure out exactly what's slowing it down, but there's still a lot of legacy code in it that needs moving / removing, and will make things more efficient. Splitting the `tick` (ie, called every frame) method up into different loops has helped a lot with some things (and almost wish I could do it for v1, but it's not built to support that).

For now, let's have a flow chart of how things work:

```
1. Add animation via Velocity() call or shortcut.
1a. Velocity normalises the options so we can deal with lazy coding and defaults.
1b. Copy all the relevant data on a per-element basis - AnimationCall.
1c. Add the AnimationCall to the per-element queue. If the queue is empty then add to the active animation list instead. (* see note below)

2. The per-frame method `tick` is called.
2a. If there are any new AnimationCall structures then expand the tweens in them with the current style/data.
2b. For each AnimationCall:
   i. If the animation is paused or delayed then skip this one. If it was previously paused or delayed then change the start time relative to now so it has the correct end time.
   ii. Use the per-tween easing (same as the AnimationCall easing if not set) to make the correct values for each tween. This is an array of strings and numbers that uses String.concat() to make a currentValue.
   iii. Set the currentValue to the property. Save as our most recent value for caching.
2c. For each AnimationCall:
   i. If there is a progress callback then call it (this is cached from 2b).
   ii. If it is complete then complete it, and unqueue the next animation.
```

So it's somewhat similar to v1, except anything that might want to read from the current styles is either first (2a with expanding tweens) or last (2c with callbacks) - this means that there can't be any stutters within the animations. In v1 a long callback could actually slow down everything else. In v2 that can't happen - unless you're setting custom values via using the Tween fake property. Part of the future API will include ways to bypass that for non-callback code. For example, the `display` and `visibility` options are going to become simple properties instead, and they will be treated the same way as the options were in v1.

### * 1c Note

Regarding 1c above. In v1, and pretty much every other Javascript library out there, the animations are treated as synchronous. What this means is that if you added an animation to elements `a+b+c` then it would run at the same time. If you first added one to `b`, and then to `a+b+c` then the two animations on `b` would overlap, and that's unlikely to be what was intended. Simply put, `a` is in charge, and it totally ignores anything running on any other elements, so if `b` was in charge of another queue, then it would be totally unrelated to `a` even if they shared one animation.

In v2 everything is split out to be a per-element queue. This means that the situation above can't happen. Instead each element would start at the correct time for their queue, with `b` starting later. Sadly that does mean that the `progress` callback is currently linked to `a` (I'm working out how to do things differently for that still). `b` would be in charge of the `complete` callback as it is the last one to start. There will be an option added at some point for `sync:true`, which may be the default so it's as close to other libraries as possible. In this case the total animation wouldn't start until every element (ie, `b` is last) has finished it's previous animation, and is ready for this next one.

It's not a situation that will be hit on very often, but for people that are trying to queue animations on different elements it makes a lot of sense. Add named queues, and I hope to see some clever use of it...

**Comment by Rycochet** [comment]
So it's been a very long month for me, but finally get back to updates.

The test code is now Typescript - it's not ideal yet, but means it should eventually just be accessing the public API in order to do tests. What this means is that all of the issues that are getting linked to this will eventually need tests to prove they work as expected - and that it's consistent. There shouldn't be any access to private internals by the test suite (as it is currently) simply because that's not a valid test. If it's not exposed, then you're not meant to use it ;-)

I've added the string based easings. These are "`at-start`", "`at-end`" and "`during`". They're not tested properly, but will be used for the two options "`display`" and "`visibility`" - which will be depreciated (as they are properties and should be treated as such). They'll also get used for any other string based properties, so you'll be able to do things like changing the `font` during an animation etc... I did realise it would also be useful for `:before` and `:after` pseudo-elements too, but that's definitely got to be a later thing (useful though...).

Speaking of easings - the call arguments for them have changed, as has the return value. Now they take the percentage, start value, end value, and property name - they then need to return the current value. Previously they just took a percentage and spat out a number to multiply the delta by. That's not as powerful (especially for user-supplied easings), even if it was slightly simpler. As a side effect they should be a tiny bit faster as the browsers can nearly all optimise the code for small functions a lot easier than looping larger functions.

Internally the code (though not the tests I realise) has all been changed to use `let` instead of `var`, as mentioned last month.

The Typescript definition file has been improved and is now used for the tests (another useful side effect of updating them) - this gives a good place to add documentation of all the public methods. There are still a lot of internal bits - some of which are unused - but it'll get cleaned up before release. It also gives a good place for me to see what's being used publicly and shouldn't be ;-)

I've noticed (and hopefully pulled out) quite a lot of cases of regular expressions being re-created on each call of a function. While the browsers might be able to handle that well, I'm not convinced, so have pulled them up into static variables so they're only created once.

**Comment by Rycochet** [comment]
Going to leave a quick note here for now, but for anyone watching the sheer amount of spam coming from here - we've got two new coders joining the team - @Duskfall and @alexdor - thanks to Andreas at https://kissmybutton.gr/ for seeing the potential in v2 and getting involved.

What this means for now is that I'm trying to organise the issues a little more, and will be opening new issues for various notes and plans (so that we can follow / comment / assign them more easily). The initial aim is to get Velocity 2 beta ready for them to use in [MotorCortex.js](http://motorcortexjs.com/) and then continuing development to get out of alpha and into beta / release.

Anyone looking at the project page will see another column added - basically it's there so that any issues that come up, (designs made, features added, etc) need to have tests proving the correct behaviour before they can be signed off. There's a couple of open issues where the behaviour wasn't specified and it resulted in something unexpected - and that's not good for developers using Velocity.

I've added several new issue labels. They're numbered, with 5 being the most important, and 1 the least important. There's also a zero - which means we've done the code, but it's not in a release yet - for future use anything that's fixed will get that, then any open issues with it will get closed when a new release is pushed.

**Comment by Rycochet** [comment]
Thought it was about time for another update (does anybody even read these things?), so here we go :-)

Velocity2 is getting closer to public beta testing!

Internally a lot of bugs have been squashed, and a lot of code has been replaced, and we have several APIs ready for use in the real world. While there's still several things to be done over the next week or so, we're starting to get onto the updating and fixing the tests (required so we can ensure that things are behaving as expected).

We now have an API for extending `"actions"`. Yes, those things that are passed as a string instead of the properties.

An action function is defined as:

```typescript
function myAction(args?: any[], elements?: HTMLorSVGElement[] | VelocityResult, promiseHandler?: VelocityPromise, action?: string): any
```

- The `args` are the arguments supplied (so `Velocity(elements, "myAction", 1, 2, 3)` would get `[1, 2, 3]` passed as an args array).
- The elements are passed next (it needs to handle no elements for when passed as the first argument of Velocity - such as `"finishAll"` etc) - because it can be chained you can check for a `.velocity` member on it, and if it has one then it should have a further `.animations` element within that, which is an array of the animations added by that previous call.
- The promiseHandler is there so you can resolve or reject the associated promise (if valid) - useful for reporting errors back to whatever is using it.
- Finally the actual action string is passed. This is useful as the registered action itself is the part of the name before any dot (`"."`), but this is the entire string - so for instance passing a queue via `"myAction.myQueue"`.
- The return value can be anything you wish to return, or simply return undefined (`return;` with no arguments) and it'll allow the call to be chained to another velocity function.

There's also a vastly improved argument parsing code in place - it saves as much time and memory as possible by not parsing things unless it actively needs it.

The number of open issues relating to V2 is going down pretty quickly, and I'm hoping we get a lot of them closed once we have tests written for them :-)

**Comment by kvirani** [comment]
Nice. Also @Rycochet I read every one of your awesome updates here... FWIW :)

**Comment by Rycochet** [comment]
## Happy New Year

It's been a while since I posted an update, so going to start with an apology - I had hoped to get a beta out for public testing by last week, thanks to IRL (friends more than family - it's been a busy December), there's not been enough time, so things are back to running late... We will catch up eventually though ;-)

There's been a lot of improvements since the last update, and a lot of bug fixes. The main code is now pretty much ready to go, though there are still a couple of things that are needed (such as handling of `"auto"` values without forcefeeding).

I've been sitting on the handing for the `scroll` properties for around a month now. It's in and works, but really not happy with how I did it so might get a rewrite before I push (and thanks to the aforementioned issues I've not had enough time to figure out a better way).

Performance has improved significantly with input from pretty much all of the team - it's now almost back to where it was for speed in high stress situations as it was in v1 (and just as fast for less than a thousand elements), but with significantly more capability (and less potential bugs) than before. The only thing that still affects the performance now appears to be memory use - and if you're not animating thousands of elements at the same time it's not something that's going to affect you.

I made an abortive start on the documentation at the beginning of December. but planning a slightly more thorough one this month - possibly using the Github Wiki to start with - it just needs the content written, formatting and layout is all secondary - there's a lot of changes and new stuff that needs to be documented simply because people aren't aware it's there (I've tried to cover the major points in this thread, partially to jog memory when writing them).

Finally - after v2 is released, v1 will be getting some bugfixes, not very many - but obvious things that people report. It's going to be a separate branch on here, but there will be people who don't can't update. As it'll be in maintenance mode, only bugs that are blatantly obvious (thanks going out to people posting PRs here) will get fixed - if it involves a lot of hunting down to find it (monolithic Javascript files are nasty) then they're unlikely to be fixed by us.

**Comment by Rycochet** [comment]
### So it's nearly time for a public beta!!!

At some point over the next two days I'll be branching the current code into a v1 branch, then merging the develop branch back into the master branch. Finally I'll promote an unstable Release for "2.0.0".

There is one major(ish) part not done yet - which is far more to do with designing an updated API when other things are public - and that part is the old UI Pack. The reason it's being held back is that I want to make it possible to treat a single effect as a single animation - and be able to scrub to any point along it in a simple way. The old UIPack basically chains animations that are each separate and only have a single duration that's shared. When there's been some feedback and bugfixes, it should give a clear indication of where to go with that.

So 2.0.0 is going to be the public beta. I'm not going to suffix it, but will increase the last digit, with 2.1.0 being the full public final version (and not marked as an unstable release any more). I don't know if the UIPack code will go in by then, as it will largely depend on both time and design (I am aiming to get it done). In terms of timescale, I expect this to be around the beginning of March, but it is dependant on coder availability.

In the run-up to this update I'm currently fixing some final tests, which is (hopefully) fixing the last obvious bugs (going to be up to you lot to report things as they're found). I'm also putting together the wiki pages on here, so the documentation for v2 will be purely wiki until it's final release (thanks to Github I can do that all via git too, so it will be updated as a single push). As part of that effort I'm also making some final minor fixes to the major API updates.

I will add a CHANGES text file with the major changes from v1 to v2 (there are quite a few for advanced use, but simple use is almost the same with the exception of scrolling).

The source code is now both self-documenting, and well-commented. There's still quite a lot of places it doesn't have enough (or isn't updated to v2 formatting standard) - so things like that are also good to be updated (we're open to Pull Requests once it goes public beta on the `master` branch).

Oh, and one thing that made it in since the last update - the internal code is now a lot closer to being able to animate arbitrary Objects... Doesn't mean much to many people. but it does mean that it could be used for more games and visualisation tools that aren't HTML based...

**Comment by Rycochet** [comment]
# I'm now happy with the code for v2 beta, and am writing / updating the wiki docs - I need some sleep, but will get released within 24 hours.

* Is it finished? No.
* Are the tests finished? No.
* Is the website up-to-date? No - and that will follow later (the wiki docs are part of the beta, hence being pushed at the same time).
* What is holding things up? People using and testing the new version, so any bugfixes can be made, and then the final APIs (that have been mostly designed) can be added.

**Comment by Rycochet** [comment]
# AND WE'RE LIVE!!!

Found a couple of small issues while doing documentation, but hopefully everything is now usable. There's more work to do, but this is enough for people to start giving feedback. In a week or two I'll start thinking about an NPM beta provided there is some public testing and feedback happening...
