### ISSUE TITLE
Animating table rows

### ISSUE THREAD

**Issue by neokio** [julianshapiro/velocity#791]
Let me begin by saying yes, I know it's 2017 and tables are hideous abominations in the eyes of DOM almighty. However it is still entirely acceptable to use tables for tabular data. In a few cases, I find it more efficient.

Table content doesn't animate very well, which makes for sucky UI. For the last four years I've  used the following method to animate table rows:

```html
<table>
<tr id="blah1"><td>1</td><td>2</td><td>3</td></tr>
<tr id="blah2"><td>4</td><td>5</td><td>6</td></tr>
<tr id="blah3"><td>7</td><td>8</td><td>9</td></tr>
</table>
```

```javascript
function fadeTR( el ){
	$(el).find('td')
		.wrapInner('<div style="display:block" />')
		.parent()
		.find('td > div')
		.animate({
			opacity: 0,
			height: 0
			}, 300, function(){
				$(this).parent().parent().remove();
			});
}

fadeTR('#blah2');
```

**MY QUESTION IS:**

Is there any way for `$('#blah2').velocity('slideUp');` and `slideDown` to work, without the above trickery?

**Comment by Rycochet** [comment]
Currently no - they work completely differently. In jQuery there's actual code going on, and doing something not unlike you code with adding that wrapper etc. In Velocity version 1 (yes, that is a label now) it was purely relating to animating elements, so no wrapping or manipulation was going on.

Velocity2 is on the way however, and among other things I want to get those two to animate the way people expect them to, so the internal API will be extended to make that possible - and that will be one of the included effects (though maybe moved to the UI-Pack - see #790 and comment for feedback and ideas)...

**Comment by Rycochet** [comment]
The ui-pack has been rewritten to be closer to css animations, so this is still not possible. It's something that doesn't belong within Velocity as it's manipulating the DOM in a non-animation way - so this is something that needs documented ideas, and (probably) not internal code.
