### ISSUE TITLE
Function ScrollTop Doesn't Work 

### ISSUE THREAD

**Issue by abdokouta** [julianshapiro/velocity#795]
Scroll to top doesn't work at all i don't know exactly what's the wrong with my code here is it
`// Back to top button
		// Display the button
		jQuery(window).on( "scroll", function() {
			if (jQuery(window).scrollTop() > jQuery(window).height()) { 
				jQuery('.back-to-top').fadeIn(500);
			}
			if (jQuery(window).scrollTop() < jQuery(window).height()) {
				jQuery('.back-to-top').fadeOut(500);
			}
		});
		// Scroll to top when clicked
		$('.back-to-top').on( "click", function(event) {
			event.preventDefault();
			$('html, body').velocity("scroll", { duration: 1200, easing: [1,0,.03,1.01], mobileHA: true, queue: false }); 
			// Docs: http://cubic-bezier.com
			// http://julian.com/research/velocity/#scroll
			return false;
		});`

**Comment by Rycochet** [comment]
Let me just quote the first line of scroll documentation that you've even got linked in there -

> Note that in both cases — whether scrolling is relative to the browser window or to a containing element — the scroll command is *always called on the element that is being scrolled into view.*

**Comment by abdokouta** [comment]
thanks for the tip, it just works fine after some modifications :)
