### ISSUE TITLE
V2: Remove legacy browsers and provide a polyfill for them

### ISSUE THREAD

**Issue by Rycochet** [julianshapiro/velocity#815]
- [ ] Remove legacy browser support.
- [ ] Provide a polyfill file to allow legacy browsers to run Velocity
  * This will be almost exclusively IE.

The non-exhaustive list of supported browsers:
* Chrome
* Firefox ESR >= 52
* IE >= 11
* Edge
* Safari >= 10

**Comment by jackocnr** [comment]
Yes please 🙏! Since April 2017 Microsoft has stopped supporting IE 8,9,10. Presumably removing support for these dinosaurs would result in a meaningful reduction in filesize?

**Comment by Rycochet** [comment]
I'm not sure exactly how much reduction they caused, as there's been so much other re-writing going on, but the end file size will be slightly larger I believe as I'm now considering including the UI-Pack with it as a single file - but we're also working on improving the custom-build part for people - the whole thing is very modular now and that makes it a lot easier (in theory) to have exactly what people want for their own needs. I do know that the capabilities have increased substantially, with a lot of new API stuff available for extension - and the file size is almost the same as before - with there still being some compatibility code in there... ;-)

**Comment by Rycochet** [comment]
Closing due to #927
