### ISSUE TITLE
Allow usage of pre-registered effects within sequences

### ISSUE THREAD

**Issue by nolde** [julianshapiro/velocity#816]
Allow sequences like this:

```javascript
Velocity.RunSequence([
  { e, p: { 'stroke-dasharray': length, 'stroke-dashoffset': length }, o: { duration: 0 } },
  { e, p: { 'stroke-dashoffset': 0 }, o: { duration: 1500 } },
  { e, p: 'transition.slideUpOut', o: { duration: 1500, sequenceQueue: false } }
])
```

**Comment by Rycochet** [comment]
V2 is currently being worked on, and sequences are getting an overhaul - once you've registered a sequence you will be able to use and refer to it as a normal Velocity call, which technically means that you'll be able to nest them. There will be a couple of changes to support that, but it will broadly be very similar to before (so the deprecated methods should be in there but giving warnings when used).

```Typescript
Velocity.registerEffect("name", {properties}, {effect options});

Velocity([elements], "transition.name", {options});
```

In V2, a `transition` will just run  as normal, but if you state in the effect options that it's a `callout` then it will ensure that after finishing all properties used are returned to their start values.

**Comment by nolde** [comment]
Sounds pretty good.
Thanks for the info!

**Comment by Rycochet** [comment]
RunSequence has been depreciated, Sequences are now in though, which allow you to register a named sequence (very similar to a CSS animation), then call it with custom options (though not values).

See the source code to any of the ui-pack effects in the `src-ui` folder.
