### ISSUE TITLE
Exception "cannot set property 'delayBegin' of undefined" after removing element data when using delay

### ISSUE THREAD

**Issue by mickylad** [julianshapiro/velocity#819]
Hi,

In our project we're getting an exception - `cannot set property 'delayBegin' of undefined` from [line 3030](https://github.com/julianshapiro/velocity/blob/39ef88aa95ef361e09bf309429d3d514eb898e2b/velocity.js#L3030) - at certain times when we specify a delay on our animation. We are using [`velocity-react`](https://github.com/google-fabric/velocity-react) so admittedly the issue could stem from that, however I'm struggling to get to grips with the code to really nail this down (or reproduce it in an isolated snippet, unfortunately).

It seems that we get into a state where we unmount a component that is animating, but also have a tick scheduled that determines that the corresponding element's animation is complete - `percentComplete` is calculated as 1 due to the time difference and [`completeCall`](https://github.com/julianshapiro/velocity/blob/39ef88aa95ef361e09bf309429d3d514eb898e2b/velocity.js#L4472) is called. At this point the element doesn't have any associated Velocity data, (I think) because `velocity-react` 's `velocity-transition-group` removes it when the component is unmounted.

In `completeCall` this is safe, as there's [a check for the existence of `data`](https://github.com/julianshapiro/velocity/blob/39ef88aa95ef361e09bf309429d3d514eb898e2b/velocity.js#L4515) on the element. However the [call to `$.dequeue`](https://github.com/julianshapiro/velocity/blob/39ef88aa95ef361e09bf309429d3d514eb898e2b/velocity.js#L4607) for the element at the end of `completeCall` ends up calling [the delay function that is queued in `processElement`](https://github.com/julianshapiro/velocity/blob/39ef88aa95ef361e09bf309429d3d514eb898e2b/velocity.js#L3007). That function assumes the Velocity data exists for the element and hence we get an exception when it tries to assign `delayBegin`.

I suspect this could be be caused in part by some blocking that causes a larger-than-normal delay before the tick and the queued delay function have a chance to run, but I've not had any luck reproducing it in an isolated example.

A straight-forward solution from our point of view would simply be to check for the existence of Velocity data at the start of the queued delay function and do nothing if data doesn't exist; certainly it seems that a tick can handle this case. However I'm not sure if the code is set up in such a way that it shouldn't be possible for this to occur.

I wonder if anyone with a better grasp of the code might be able to point me in the right direction?

The versions we're using are:
 ```
  "react": "16.0.0",
  "react-transition-group": "1.2.0",
  "velocity-animate": "1.5.0",
  "velocity-react": "1.4.4",
```

**Comment by Rycochet** [comment]
Looks like you've got a pretty good explanation of what's going on there. Sadly V1 is not going to get much more done to it - and likely only fixes (including this) *after* V2 is public.

In Velocity2 this is no longer possible due to how it works, in fact it doesn't use any of the jQuery queue code, and will be a lot better behaved due to the amount of work we're putting into the tests. Sadly it's several months away from being ready (I'm hoping it'll be complete by the end of the year - it's a separate branch on here so anyone can play, just still very beta).

**Comment by mickylad** [comment]
Ok, that's great to know - at least it sounds like we've got a decent understanding of it on our end. Thanks for a quick response, looking forward to the future versions!

**Comment by Rycochet** [comment]
Now using Velocity V2 beta (soon to be out of beta) - and things have changed a lot with delay - the old code is no longer relevant.
