### ISSUE TITLE
Inconsistent promise resolution after invoking "stop"

### ISSUE THREAD

**Issue by Alexey1** [julianshapiro/velocity#821]
Case 1. User: invokes animation with properties object, invokes "then" on the returned promise, invokes "stop". Velocity: resolves the promise.

Case 2. User: invokes animation with "fadeOut", invokes "then" on the returned promise, invokes "stop". Velocity: does not resolve the promise.

I expect Velocity either resolve the promise in both cases or not resolve it in both cases.

demo
https://jsfiddle.net/zbou928u/3/

actual output:
```
1 "a"
0 "b"
1 "b"
```

expected output:
either this:
```
0 "a"
1 "a"
0 "b"
1 "b"
```

or this:
```
0 "b"
1 "b"
```

**Comment by Rycochet** [comment]
The old sequences and transitions have been removed, promise resolution should now be consistent as the new Sequences code is functionally identical to any other animation (internally all animations are converted into simple sequences).
