### ISSUE TITLE
How to call chain animation without using jqurey

### ISSUE THREAD

**Issue by bookldk** [julianshapiro/velocity#822]
Velocity(document.body, { opacity: 0.5 }).Velocity(document.body, { opacity: 0.8 }) .?

**Comment by Rycochet** [comment]
Sadly the documentation hasn't caught up yet - chaining is always lower case (by convention with pretty much everything) - bearing in mind this is for version 2 beta (the develop branch):

```typescript
Velocity(document.body, { opacity: 0.5 }).velocity({ opacity: 0.8 });

document.body.velocity({ opacity: 0.5 }).velocity({ opacity: 0.8 });

document.querySelector("body").velocity({ opacity: 0.5 }).velocity({ opacity: 0.8 });

document.querySelectorAll("body").velocity({ opacity: 0.5 }).velocity({ opacity: 0.8 });
```

It will automatically extend the built in Elements etc, to make things as useful and simple as possible.

Going to leave this open until the documentation catches up :-)

**Comment by bookldk** [comment]
Velocity(document.body, { opacity: 0.5 }).velocity({ opacity: 0.8 })  error

Velocity(...).velocity is not a function

**Comment by bookldk** [comment]
document.querySelector(...).velocity is not a function

**Comment by Rycochet** [comment]
# bearing in mind this is for version 2 beta (the develop branch):

Version 1 is no longer developed and never supported chaining.
