### ISSUE TITLE
Reset appears not to work for transition.slideUpOut

### ISSUE THREAD

**Issue by mgussekloo** [julianshapiro/velocity#823]
The "reset" feature of transition.slideUpOut (UI Pack) relies on this call:
Velocity.animate(element, {translateY: [0,0]}, {duration: 0, queue: false});

But this doesn't seem to work. TranslateY: -20px remains in the element's Style-property. Like the reset-call is being ignored. 

What does work is:
Velocity.animate(element, {translateY: 0}, {duration: 0, queue: false});

Commenting out this part (velocity.ui.js, l. 225 - 230) makes it work again:
/* Format each non-array value in the reset property map to [ value, value ] so that changes apply
immediately and DOM querying is avoided (via forcefeeding). */
....

I think this may be a bug?

**Comment by Rycochet** [comment]
Looks like a weird bug that shouldn't be happening. All the UI Pack stuff is being rewritten for v2 (though not got onto that specific bit yet) - and it will have a better global method of resetting values. The various ```transform``` methods will also use ```transform``` directly, as the shortcuts are no longer needed nor desired in it.
