### ISSUE TITLE
How about supported ESModule for webpack or rollup with tree shaking

### ISSUE THREAD

**Issue by lichenhao** [julianshapiro/velocity#824]
RT, how about supported the source code with ES module for tree shaking.So it can be more tiny and some common code can be exported as vendor.

**Comment by Rycochet** [comment]
@lichenhao Have you had a look at the develop branch for how things are working for the near-ish future?

One low priority thing is supporting webpack so people will be able to pick and choose for custom builds. If you want to contribute then you're welcome to - currently the build uses Grunt and plain Typescript compilation for simplicity, but as an open source project we welcome any help people want to provide :-)

**Comment by lichenhao** [comment]
Cool !!!
The develop branch is very helpful~
So, how about published package contains the source code for typescript with the types info 

[publishing the typescript project with types definition](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html)

```javascript
// package.json
{
  "types": "src/index.ts"
}
```

**Comment by Rycochet** [comment]
That'll definitely be there and done in the most compatible manner before it goes public (as opposed to develop) - and it's actually ```"index.d.ts"``` which is supported without needing to add it to the package.json file supposedly ;-)

**Comment by Rycochet** [comment]
Added in 2.0.3 (though I noticed not all files were getting into the NPM release, so might be in 2.0.4)

**Comment by lichenhao** [comment]
Cool and thank you
