### ISSUE TITLE
Velocity's promise never resolves If elements animated with `stagger` are removed from DOM during animation

### ISSUE THREAD

**Issue by futpib** [julianshapiro/velocity#825]
Steps to reproduce:
1. Open http://jsfiddle.net/pr1wz3js/3/ (a browser with native `Promise` implementation is assumed)
2. Hit "breaks" button
3. Nothing printed to console.

What I expected: promise returned by `Velocity` is eventually either resolved or rejected.

What actually happens: promise is never settled.

**Comment by Rycochet** [comment]
Stagger and drag are both in V2, and have no bearing on whether it is resolved or not.
