### ISSUE TITLE
Declaring & require order for NPM

### ISSUE THREAD

**Issue by tophat1986** [julianshapiro/velocity#828]
A very simple suggestion to help the beginners of the world like me is to make a note for npm installation. 
'Velocity' needs declaring before jquery when using webpack!  I presume to load last in your main app.js file so that it overwrites/takes precedence over jquery (from my understanding).

Spent a while trying to get it to work because of this.  Cheers

**Comment by Rycochet** [comment]
Velocity doesn't yet support Webpack (it's not been looked into) - v1 doesn't use `app.ts`, and v2 is still being worked on and doesn't have anything to do with jQuery except for potentially extending jQuery.

Definitely on the todo list so you can have it working properly with jQuery (and anything else), as well as making sure it works as expected with webpack (I'd rather like to get the build over to using webpack at some point now it's so modular, but it's pretty low priority).
