### ISSUE TITLE
Transforms in V2

### ISSUE THREAD

**Issue by blowsie** [julianshapiro/velocity#836]
The v2 readme says

> Major Changes in Velocity V2
Transforms - Use these directly within CSS, don't try the old shortcuts as they don't exist.

Could you please provide an example of what this looks like? 

Here is a sample of my (v1) code;
```
   Works.ui.$scrollUp
                    .velocity('finish')
                    .velocity({
                      translateY: ['0%', '100%'],
                      opacity: 1,
                      translateZ: 0
                    }, {})
                  ;
```

**Comment by Rycochet** [comment]
Basically if it's not a valid css property (or `"tween"`) then it's not valid for Velocity on an `HTMLElement` - so just use the exact CSS you want it to actually display:

```javascript
Works.ui.$scrollUp
    .velocity('finish')
    .velocity({
        transform: ["translateY(0%) translateZ(0)", "translateY(100%)  translateZ(0)"],
        opacity: 1
    }, {})
```

SVG allows all CSS properties plus any valid attributes for that `SVGElement`.

**Comment by blowsie** [comment]
Fantastic thanks, just was not sure on the implementation as I could see it in the docs

**Comment by hackuun** [comment]
@Rycochet this is not working

`Velocity: Trying to pattern match mis-matched strings transform:["translateY(0%) translateZ(0)", "translateY(100%)  translateZ(0)"]`

**Comment by Rycochet** [comment]
@hackuun Is that using 2.0.2 or the current master code?

**Comment by hackuun** [comment]
@Rycochet `"velocity-animate": "^2.0.2"`

But it seems like no transforms are working. I tried example from Vue Docs too. It just doesn't working.

**Comment by sebastianschrama** [comment]
Yes, transforms are not working. :(

**Comment by richgcook** [comment]
Any resolve on this?
