### ISSUE TITLE
Install Velocity v2 from npm

### ISSUE THREAD

**Issue by sumbad** [julianshapiro/velocity#837]
How can I install Velocity v2 from npm?

**Comment by Rycochet** [comment]
It's not on NPM yet - once it is I'll update the readme (and close this).

**Comment by sumbad** [comment]
Thanks, and can you tell how soon you will do that?

**Comment by Rycochet** [comment]
I don't have any access to the NPM organisation, so I've sent a message to the person who does. From previous requests there it can be anything from later the same day to a couple of weeks later...

**Comment by sumbad** [comment]
Thank you so much for the speedy reply.

**Comment by Rycochet** [comment]
Available now with "`npm install velocity-animate@beta`" - version 2.1.0 will be a full release and drop the `beta` from the end.
