### ISSUE TITLE
Transitions in Velocity V2 not enabled yet

### ISSUE THREAD

**Issue by ibexnet** [julianshapiro/velocity#838]
#### Your system information

* VelocityJS version: 2.0.0
* Browser: Safary/Firefox/Chrome
* Operating System: OSx

#### Checklist

* Is this an issue with *code*?: Yes
* Is this an issue with *documentation*?: No
* Have you reproduced this in other browsers?: Yes
* Have you checked for updates?: Yes
* Have you checked for similar open issues?: Yes

> Please remember that this is an issue tracker, support requests should be posted on StackOverflow - see CONTRIBUTING.md

#### Please describe your issue in as much detail as possible:
With the new version 2.0.0 beta I'm unable to use any transition all other effect works.
On the browser console I can see class and style change while the transition is in progress but on the browser the target elements just change the css property without animation.
The same code with velocity 1.5 work as expected.

#### Steps for reproducing this issue (code):

1. put this code on html page:
include .. jquery|velocity|velocity.ui
<body>
 <div>This is a test</div>	
</body>
<script>
$("div").velocity('transition.slideDownIn',{ duration: 1000, easing: "ease-out", delay:400 });
</script>

2. load the page

#### JSFiddle example showing issue in action (code):

> Go to https://jsfiddle.net/Rycochet/mqv9L27u/ - click the "Fork" button at the top, create the example and copy the new URL back here.
https://jsfiddle.net/rjwq92h1/

**Comment by Rycochet** [comment]
https://github.com/julianshapiro/velocity/blob/master/V2_CHANGES.md

> # Currently disabled / not updated:
> 
> * UI-Pack

Might not be clear from that, but the "UI-Pack" is all transitions and callouts - the way they are called will stay the same, however the way they are created and how they behave is having major changes, so they should get in there in about two weeks or so.

The plan is to allow more fine-grained control over them while playing, in V2 you can read and write data on a single running animation by using the return value from its creation - and sequences need that same control available. With how it stands with V1 they were adding a sequence of steps to the animation queue, and that prevents them from being handled in that way.

**Comment by ibexnet** [comment]
ok, I'm sorry but I did not understand it.
thanks

**Comment by Rycochet** [comment]
No worries - that's the whole point of public beta testing :-)

**Comment by Rycochet** [comment]
https://github.com/julianshapiro/velocity/wiki/Advanced---Sequences
