### ISSUE TITLE
Unitless CSS like line-height is now forced to pixels in v2.0.1

### ISSUE THREAD

**Issue by repertor** [julianshapiro/velocity#839]
In v1, setting `lineHeight: 5` set it to `5` in CSS, which is a valid value in CSS.

Now, in v2, it forces a px unit on that value, such that `5` is made into `5px`

From MDN (https://developer.mozilla.org/en-US/docs/Web/CSS/line-height)

> The used value is this unitless <number> multiplied by the element's own font size.
The computed value is the same as the specified <number>. In most cases, this is the preferred way to set line-height and avoid unexpected results due to inheritance.

I don't believe there are many unitless CSS possibilities, but this one is standard.

**Comment by Rycochet** [comment]
It definitely is standard, so that's something missed - will get this fixed and a specific test for it. There's a couple of unitless properties around, and where it can also do attributes it needs to have a little bit more understanding of how it works!
