### ISSUE TITLE
Special case on web.whatsapp.com. Animations not starting on a background page of a Chrome extension

### ISSUE THREAD

**Issue by cprcrack** [julianshapiro/velocity#842]
This is not an issue with Velocitiy.js but a request for help on quite an special case I'm dealing with. I hope using GitHub for this is not a big inconvenience. I'm the author of [WAToolkit](https://github.com/cprcrack/WAToolkit), a Chrome extension with more than 60,000 users. I have spent a couple of days trying to fix a bug in my extension without any luck. I believe the Velocity.js devs could help me because WhatsApp Web is using Velocity.js and I think it's related to my issue.

When there's not WhatsApp web tab open, WAToolkit loads web.whatsapp.com in a background page that is invisible to the user. This page cannot be viewed in any way, not even by a developer, but I can  open the Developer Tools, see the DOM representation and use the Javascript console. This way I realized that sometimes the "velocity-animating" class is added to some elements. The problem is that when loaded on the background page, the animations are apparently not actually run (the "velocity-animating" classes remain forever on the affected elements, and this does not happen on a regular foreground page).

I believe that as the animations are not run, their complete event is not fired and thus the page is not updating some elements that I need updated for the extension to work correctly. This may be because the page is not focused (and I have found no way to focus it programmatically, it may be impossible). I am able to access the Velocity object via window.Velocity, so I have tried using Velocity.mock = true; with no success. I also wanted to try element.velocity("finish") to see if could force the final state of the animation for the elements with class "velocity-animating", but there's no .velocity() method in any of those elements.

My aim is to skip this animations or apply some workaround, but I don't have access or knowledge about WhatsApps's source code, it's totally obfuscated. So could you think of any way of stopping the animations from happening, of maybe raising the "complete" event by calling the "finish" command in some way I'm not aware of without using element.velocity()? Unfortunately I don't know what version of Velocity.js they are using, and it may actually be a customized version, but I'm sure there's some workaround.

Any help or idea would be greatly appreciated.

**Comment by Rycochet** [comment]
I can tell you that it's using version 1.2.0 - so quite old, and with a lot of fixed issues since there - just look at the value of `Velocity.version` to see what's being used.

I've managed to put most of how V1 is doing things out of my mind, simply because it was a pain - but it's using jQuery for storing its data, if you have a look at `$(element).data("velocity")`, then it might give an idea of what's supposed to be animating - I'm afraid I can't give you any pointers to the specific data structures used as it's plain Javascript.

Addressing the elements directly is also a V2 thing, so you should be able to address via jQuery on the page: use something like `iframe.contentWindow.eval("$('.velocity-animating').velocity('finish')")` to tell them to finish - it needs to be run in the context of the background page or it won't actually work etc - a bit of a hack, but hopefully it makes sense ;-)

Hope that gives you at least a start in things - going to close this as it's not a Velocity issue, but do feel free to reply on here and I'll help where I can :-)

**Comment by Rycochet** [comment]
Just had a quick look on there, and it looks like it's not using jQuery - so you'd need to get an Array of elements to pass as the first argument for the `Velocity` function - `Velocity(Array.from(document.querySelectorAll('.velocity-animating')), 'finish')`

**Comment by cprcrack** [comment]
Thanks a lot! Using your comments I was finally able to find a [workaround](https://github.com/cprcrack/WAToolkit/commit/be01bf6cb3c878890b78b1e447f5450906d92888#diff-a7dd50216361b97bf086c642acf38b0fR410). I ended up using exactly your last suggestion except "finish" had no effect so I needed to use "stop" instead. And I actually needed to call "stop" several times with setTimeout(f, 0), probably because the stalled animations are [queued and "stop" keeps firing them](https://github.com/julianshapiro/velocity/wiki/Command---stop) until the queue is empty and the .velocity-animating class is not added any more.

Very hacky but happy :)

**Comment by Rycochet** [comment]
Just remember that `"stop"` doesn't call any complete handlers - only finish will do that... If you pass `true` as a second argument it should clear the queue as well.

**Comment by cprcrack** [comment]
Yes I don't know why it only works with "stop" honestly, can only think that it's related to some other event and not the complete event... or it may be totally unrelated to this at all and be a special side-effect of running this on a background page that cannot actually be displayed.

I tried passing true like this as a **third argument** (as I cannot use $element.velocity, only the window.Velocity object):

`Velocity(Array.from(document.querySelectorAll(".velocity-animating")), "stop", true);`

But it didn't seem to make any difference, I still need to call that several times with setTimetout(f, 0) until the .velocity-animating class is not added any more, so I just stuck with the current solution.
