### ISSUE TITLE
Transforms w/ Value Operators in 2.0

### ISSUE THREAD

**Issue by anthonybruno** [julianshapiro/velocity#843]
#### Your system information

* VelocityJS version: 2.0.1
* Browser: Chrome 64.0.3282.167
* Operating System: Mac OS

#### Checklist

* Is this an issue with *code*?: No
* Is this an issue with *documentation*?: Yes
* Have you reproduced this in other browsers?: Yes
* Have you checked for updates?: Yes
* Have you checked for similar open issues?: Yes

#### Please describe your issue in as much detail as possible:
I'm currently attempting to add value operators to a `translateY` value however since the way transforms are handled 2.0+ I'm having difficulties properly formatting my code.

#### Steps for reproducing this issue (code):

```js

$el.velocity({
  transform: 'translateY(-=200px)'
}, 100);

```

**Comment by Rycochet** [comment]
Value operators aren't supported in V2 yet - I want to get them in there again, but it's not something that's easy to do (we no longer just animate single numbers), and there will have to be changes in how it's specified. Currently I'm leaning towards something like `translateY(*-200px)`.

While it would be relatively easy to add it for "normal" values, it wouldn't be future proof or very powerful compared to everything else. The code around that is in the process of being rewritten so ideas are welcome (it's in src/Velocity/tween.ts if you want to look).

**Comment by Rycochet** [comment]
Value operators exist on numbers now - you can use `+=`, `-=`, `*=`, and `/=` on any number in a string and Velocity will try to match it together.

Please note that while `transform` itself pretty much requires forcefeeding to work (browser standards etc), these may effectively kill values by putting them into nested `calc` strings, so it's strongly advised to use forcefeeding where possible.
