### ISSUE TITLE
Animating background color has a delay when animating multiple elements

### ISSUE THREAD

**Issue by CiriousJoker** [julianshapiro/velocity#846]
#### Your system information

* VelocityJS version: 2.0.1
* Browser: Chrome
* Operating System: Windows 10

#### Checklist

* Is this an issue with *code*?: [Yes]
* Is this an issue with *documentation*?: [No]
* Have you reproduced this in other browsers?: [Yes/No]
* Have you checked for updates?: [Yes]
* Have you checked for similar open issues?: [No]

#### Please describe your issue in as much detail as possible:
Animating background color has poor performance when animating multiple things in a for loop.

#### Steps for reproducing this issue (code):

This is my code:

```
        // Yellow via velocity to check if velocity lags in general
        $("#answer__card_4").velocity({ backgroundColor: "#f0ff00" });
        for (let i = 0; i < this.currentQuestion.answers.length; ++i) {
            const card = $("#answer__card_" + i);

            // Change color depending on some stuff
            if (i == index) {
                if (index == this.currentQuestion.correct) {
                    // Green applied via css
                    card.addClass("answer__card--correct");
                } else {
                    // Red animated using velocity
                    card.velocity({ backgroundColor: colorWrong });
                }
            } else if (i == this.currentQuestion.correct) {
                card.addClass("answer__card--correct"); // Green
            }
        }
```

This is the result: [Video](https://i.gyazo.com/722eddc9ab0bf2f09e04b8e299b96a90.mp4)

Note that this seems to only occur on backgroundColor animations. Scaling the things instead works instantly.

#### JSFiddle example (This has no noticable performance issues, most likely because the DOM is so simple)

[Link](https://jsfiddle.net/7k78otjr/)

**Comment by CiriousJoker** [comment]
Holy shit im dumb ...

So, apparently, the animation library doesn't play well with Materialize's waves-effect. After disabling it, it all works instantly.

**Comment by CiriousJoker** [comment]
Just adding to that:
If I put the waves-effect on the parent or child element (to achieve the same waves), everything will run smoothly, it just fucks it up when its on the same element.

**Comment by Rycochet** [comment]
Any idea why? My initial opinion is that it's something to do with caching values, but I don't know that library - is it something that can be fixed?

**Comment by CiriousJoker** [comment]
I have absolutely no idea... The waves effect works in the way that a new element is (I think) appended to the one with the waves effect. This new div is then animated. No idea why that would interfere with your lib though.. I might check back tomorrow if I don't forget
