### ISSUE TITLE
Poor performance when using % values in staggered lists

### ISSUE THREAD

**Issue by CiriousJoker** [julianshapiro/velocity#847]
#### Your system information

* VelocityJS version: 2.0.1
* Browser: Chrome
* Operating System: Windows

#### Checklist

* Is this an issue with *code*?: [Yes]
* Is this an issue with *documentation*?: [No]
* Have you reproduced this in other browsers?: [Yes]
* Have you checked for updates?: [Yes]
* Have you checked for similar open issues?: [Yes]

#### Please describe your issue in as much detail as possible:
The performance is really poor when translating % values within staggered effects. If I use normal integers, the performance is pretty good.

Again, the performance issues don't exist in the jsfiddle version probably because of the simple DOM, but they're real...

#### Steps for reproducing this issue (code):

Here's the code:
```
            $.Velocity.RegisterEffect("custom.fadeOutRight", {
                defaultDuration: 500,
                calls: [
                    [{
                        opacity: [0.5, "easeOutCubic", 1],
                        translateX: ["30%", "easeOutCubic", "0%"]
                    }]
                ]
            });

            $(".answer__card").velocity("custom.fadeOutRight", { stagger: 100 });
```
The code differs from the jsfiddle version, because transform: "translateX(30%)" didn't seem to work at all and vice versa.

#### JSFiddle example showing issue in action (code):

[JSFiddle](https://jsfiddle.net/j6fpen2o/)

**Comment by Rycochet** [comment]
The whoe registerEffect section is being completely removed / rewritten right now - in addition that `translateX` doesn't exist in V2...

**Comment by CiriousJoker** [comment]
Will the successor have a different signature or work differently in any way?
How comes that I can use translateX anyway? I've checked with yarn, I have v2.0.1

**Comment by Wouter125** [comment]
What's the successor of RegisterEffect, I can't find any information in the v2.0 wiki / documentation.

**Comment by Rycochet** [comment]
It's not finished yet - but it'll have a different signature - closer to parallel CSS animations.

You'll be able to register it to run when requested (with anything from one to many elements with different animations in parallel), or you'll be able to pass in a sequence directly and run one without having to register it first.

Once it's finished it'll go in the wiki (just busy with a new job and the normal weekly events I run etc).

**Comment by Rycochet** [comment]
Stagger has only just been added to V2, and the new Sequences are there too - feel free to re-open (with an updated fiddle) if they have the same problem :-)
