### ISSUE TITLE
IE compatibility issue

### ISSUE THREAD

**Issue by kennethkawamoto** [julianshapiro/velocity#848]
Velocity 2.0.1 causes _object doesn't support property or method 'velocity'_ error on IE 9 upwards. I reverted Velocity 1.2.2 and that works perfectly on all browsers. (Also, I cannot animate the height of an element with 2.0.1 on Safari. Again works perfectly with 1.2.2.) Has anyone experienced the same...?

**Comment by Rycochet** [comment]
There's a new issue template for a reason... IE9/10 are no longer supported (by Microsoft or Velocity).

**Comment by kennethkawamoto** [comment]
Same for Edge 16...

**Comment by Rycochet** [comment]
Fill out an issue template and it can get looked at - cross-browser support has got a couple of issues including in Safari that I know of, but it's related to code being rewritten at the moment - hopefully everything comes together correctly when it's done...
