### ISSUE TITLE
V2 Public Release Update

### ISSUE THREAD

**Issue by Rycochet** [julianshapiro/velocity#851]
So things are rather hectic right now, and I was hoping to get V2 out of beta by the beginning of March - but it's having to get pushed back a couple of days / weeks.

We have a rough roadmap of what needs to be done for the next couple of minor versions (that pesky second digit), but actually need to sit down and work out some exact requirements.

Right now V2.1.0 (the first non-beta) is being held up largely by me and the sequence rewrite. The future sequence code will look very similar to CSS animations - for instance the old `"callout.bounce"` effect now looks like this:

```javascript
"bounce": {
	"duration": 1000,
	"0%,20%,53%,80%,100%": {
		transform: ["translate3d(0,0,0)", "easeOutCubic"]
	},
	"40%,43%": {
		transform: ["translate3d(0,-30px,0)", "easeInQuint"]
	},
	"70%": {
		transform: ["translate3d(0,-15px,0)", "easeInQuint"]
	},
	"90%": {
		transform: "translate3d(0,-4px,0)"
	}
}
```

When addressing multiple elements that need different animations, the value would be an array instead of an object - with them cycling through the elements (so the element would get the `index % array.length`'nth animation).

The duration listed (and any `"easing"` if there too) are defaults that can be overridden when calling the animation.

Finally - you'll be able to pre-register the animation with a name for later use, or pass the animation directly (with a few caveats that are still being decided) - so you can manually design things without polluting the namespace.

Calling the animations is still to be decided, but I'm likely to have `"callout.bounce"` to have it reset any values when finished and `"transition.bounce"` would leave them at the end values, together with `"runSequence.bounce"` that would effectively mean the same as `"transition"`. For all of them the name of the animation can be after a dot, or as a separate argument following it (it's one of many standards we're trying to lock down in V2).

**Comment by Rycochet** [comment]
Just thought I should put an update on here. I'm seriously busy with normal work and social activities (I run various things etc), so I don't have enough time to do what I need to for polishing the release.

However.

Currently I'm trying to fight packaging bugs and inconsistencies caused by swapping to RollupJS (I may have to just go back to Webpack, which isn't ideal for use-cases). The code itself is almost all correct, with just the UI-Pack data needing to be split back into its own file (currently it's part of the main build, and `velocity-ui.js` is actually not doing anything at all except complaining).

The code itself looks like it's about right except for any bugs that I might be able to squash (check the `rollup` branch, as there are fixes on there). If anyone wants to  have a look at getting it to work then feel free :-)

Sequences are now completely done, as above, but no prefix needed or wanted (they may come later).

As soon as building is done we'll be good for packaging, and then it simply needs the docs merged and updated (from the wiki) and public non-beta version released... Hopefully within a couple of weeks (I had hoped for the start of this month, but I'm away for the next couple of days again, and don't have enough time...)

**Comment by Rycochet** [comment]
We have a new live beta version - 2.0.3 - and I'll try to do what I can for documentation over the next day.

RollupJS was a pain - had to do some nasty tricks in the end (like installing itself as a local package - meaning any time you run `"npm install"` it's got to have run an odd number of total times or it'll fail to build anything) - but it does work well enough apart from that. Could probably make things a little bit nicer looking, but that's not as important for building - having it working is the important bit!

Anyone who wants to see how much work was involved should feel free to have a look at the merge that came in - https://github.com/julianshapiro/velocity/commit/128e49833a2fc4d0e992751f2d318cd1678deea3 - there are some things I can't do (like automatically creating a single typedef file), but ~6k lines added and a further ~20k lines changed may give some explination as to why it's taken two months to get here - not to mention that I've really not had very much time to work on it in any given week.

My next steps are getting the documentation updated and into a usable state (ie, need to build from wiki / markdown to flat HTML so we can get an updated technical website), and having a quick look at any of the bugs with JSFiddles that I can try to track down and fix.

**Comment by Rycochet** [comment]
2.0.5 is now out, and things are getting very close to a release.

The documentation (wiki) needs to be convertible to a static html file - ideally something that looks like [FlatDoc](http://ricostacruz.com/flatdoc/) due to the example sidebar - but that project hasn't been touched in years so may have to roll something semi-custom.

My final bit of code in the main TODO is adding the rest of the options that will support it as per-element option callbacks - not everything will get it, but hopefully enough for people ;-)

Expect a final release before the end of the month!!!

**Comment by makshh** [comment]
Maybe https://github.com/mkdocs/mkdocs for docs. There are also good themes like mkdocs-material.

**Comment by Rycochet** [comment]
@makshh Looks good - except that I want this to be a node project, and that requires a separate python install for it, otherwise I'll remember that for other things - currently looking at a combination of octonode for grabbing the GitHub wiki pages, and various markdown converters, with a custom theme :-)

**Comment by exodus4d** [comment]
Hi, any news about the 2.0 release? ;)

**Comment by Rycochet** [comment]
Retiring this in favour of #927
