### ISSUE TITLE
Obtaining tween value in progress callback

### ISSUE THREAD

**Issue by jsneden** [julianshapiro/velocity#853]
#### Your system information

* VelocityJS version: 2.0.1
* Browser: Chrome
* Operating System: Windows

#### Checklist

* Is this an issue with *code*?: Yes
* Is this an issue with *documentation*?: Yes
* Have you reproduced this in other browsers?: Yes
* Have you checked for updates?: Yes
* Have you checked for similar open issues?: Yes

#### Please describe your issue in as much detail as possible:
Hello, I see a similar issue was raised recently in https://github.com/julianshapiro/velocity/issues/841 but the reference wiki page for the [Progress Option](https://github.com/julianshapiro/velocity/wiki/Option---Progress) doesn't seem to exist anymore. It's not obvious to me how to obtain the eased tween value in the progress function in v2. The second and third parameters (complete and remaining) provide a percentage complete in terms of time, but they do not account for the easing function.

#### Steps for reproducing this issue (code):

In previous versions it was easy to obtain the eased tween value as the 5th parameter in the progress function (for performing non-CSS animations like changing path data) like so:

```js
let progress = (elements, complete, remaining, start, tween) => {
	// initialPaths, startPaths and endPaths are an array of SVG paths
	initialPaths.forEach((path, index) => {
		// The interpolate function relies on the tweened value from Velocity to morph from startPath into endPath
		path.interpolate(
			startPaths[index],
			endPaths[index],
			tween
		).paint();
	});
};

let element = document.querySelector('svg');
let properties = { tween: 1 };
let options = {
	duration: 600,
	easing: 'easeInOut',
	progress: progress
}

return Velocity(element, properties, options);
```

#### JSFiddle example showing issue in action (code):

See console output of progress arguments:
https://jsfiddle.net/a7fkmxov/4/

**Comment by Rycochet** [comment]
Don't know how the wiki page got removed there - I'll have a look when I get home. The `start` timestamp is no longer passed to the callback as it's completely useless for anything (it's no longer a timestamp), so just shift the args after it left by one.

https://github.com/julianshapiro/velocity/blob/master/index.d.ts#L117 -

```typescript
/**
 * A callback used for progress tracking.
 */
type VelocityProgress = (this: VelocityExtended & HTMLorSVGElement[], elements?: VelocityExtended & HTMLorSVGElement[], percentComplete?: number, remaining?: number, tweenValue?: number, activeCall?: AnimationCall) => void;
```

**Comment by jsneden** [comment]
Thanks for the response! Unfortunately, I'm getting an empty string as the value of the 4th argument. See updated JSFiddle: https://jsfiddle.net/a7fkmxov/7/

**Comment by Rycochet** [comment]
Ok, the downside of having a public wiki is some idiot deleted a file on it - m4ks@o2.pl I'm looking at you...

The issue there is actually slightly different - it's not got a value to tween to, so it's got a bug and adding "px" to the end - which has no corresponding start value as it's not css - if you use `[1, 0]` as the value it works properly - so while the bug report is incorrect, there's an underlying bug to be fixed ;-)

**Comment by makshh** [comment]
@Rycochet It was me, I'm really sorry for that. I wasn't aware that you can delete things on GitHub Wiki and I probably deleted this file accidentally...

**Comment by Rycochet** [comment]
@makshh No harm done - the wiki is actually another git, so was simple to undo that ;-)

**Comment by Rycochet** [comment]
The way units are handled has changed, this seems fixed now.
