### ISSUE TITLE
Object does not support the property or method "assign" in IE11

### ISSUE THREAD

**Issue by forethoughtde** [julianshapiro/velocity#855]
#### Your system information

* VelocityJS version: 2.0.2
* Browser: Internet Explorer 11
* Operating System: Windows 10

#### Checklist

* Is this an issue with *code*?: Yes
* Is this an issue with *documentation*?: No
* Have you reproduced this in other browsers?: No
* Have you checked for updates?: Yes
* Have you checked for similar open issues?: Yes

> Please remember that this is an issue tracker, support requests should be posted on StackOverflow - see CONTRIBUTING.md

#### Please describe your issue in as much detail as possible:
Error message says that "object does not support assign property or method"

#### JSFiddle example showing issue in action (code):
https://jsbin.com/limayofumo/edit?html,css,js,output

**Comment by Rycochet** [comment]
Doh, didn't realise it wasn't supported in IE11 - I'll put a polyfill wrap around it!
