### ISSUE TITLE
how to turn off rAFProxy in my console?

### ISSUE THREAD

**Issue by VicoErv** [julianshapiro/velocity#858]
#### Your system information

* VelocityJS version:  2
* Browser:  firefox quantum
* Operating System:  windows

#### Checklist

* Is this an issue with *code*?: [Yes]
* Is this an issue with *documentation*?: [No]
* Have you reproduced this in other browsers?: [No]
* Have you checked for updates?: [Yes]
* Have you checked for similar open issues?: [Yes]

**Comment by Rycochet** [comment]
It was turned off in the latest build on here - it'll make it onto npm with the next beta release, together with better background tab handling.
