### ISSUE TITLE
Documentation out of date

### ISSUE THREAD

**Issue by Crisfole** [julianshapiro/velocity#862]
#### Your system information

* VelocityJS version: 1.7.0
* Browser: n/a
* Operating System: n/a

#### Checklist

* Is this an issue with *code*?: No
* Is this an issue with *documentation*?: Yes
* Have you reproduced this in other browsers?: N/A
* Have you checked for updates?: Yes
* Have you checked for similar open issues?: Yes

#### Please describe your issue in as much detail as possible:

Velocity 1.7.0 appears to have added an `Actions` section for use without jQuery instead of a direct call to `Velocity.[commandname]`. There are other major differences between the Velocity library as installed from npm and the documentation. Looks like it may need a complete rewrite.

**Comment by Rycochet** [comment]
The first proper line in the readme on here -

# IMPORTANT: velocityjs.org refers to V1, not V2 beta - use the wiki for documentation!

Until V2 gets out of beta the documentation on there is not getting updated.

Velocity V2 has nothing to do with jQuery at all any more (though can still be used in the same way with it).

Not sure where you're getting a 1.7.0 from, that number doesn't exist anywhere, the master branch is 2.0.x, and the v1 branch is 1.5.1

**Comment by Crisfole** [comment]
Typoed the version number.

**Comment by Crisfole** [comment]
That line needs to be in two or three places that aren't where it is right now:

 1. The Velocityjs.org page. It's not much of an update, and it'll stop stupid questions like this one.
 2. The Github description where you have "Accelerated JavaScript animation. http://VelocityJS.org" currently. The README is not buried below the fold on my very large, high res monitor. The bold large font also makes my eyes glaze over it.
 3. It should probably also go in CONTRIBUTING.md

**Comment by Rycochet** [comment]
Ah, fair enough re typo.

1. I've got no access to the website, hence updating it isn't really an option - I'm leaving that chase for when it's worth doing.
2. Again - not an admin on the page so can't change it.
3. Good point!
