### ISSUE TITLE
Npm package doesn't include typing definitions

### ISSUE THREAD

**Issue by ernestbofill** [julianshapiro/velocity#863]
#### Your system information

* VelocityJS version: 2.02

#### Checklist

* Is this an issue with *code*?: No
* Is this an issue with *documentation*?: No
* Have you reproduced this in other browsers?: No
* Have you checked for updates?: Yes
* Have you checked for similar open issues?: Yes

#### Please describe your issue in as much detail as possible:
The npm package doesn't include typing definitions. The package.json files states `"types": "index.d.ts",` but index.d.ts is not part of the bundle.

#### Steps for reproducing this issue (code):

1. `npm install velocity-animate@beta`
2. Cannot use in typescript because there are no types

**Comment by Rycochet** [comment]
Doh - it's in the Github repo, but forgot to add it to the `"files"` part of the package.json - will be fixed for the next npm version!

**Comment by ernestbofill** [comment]
@Rycochet  Do you expect a release soon?

**Comment by Rycochet** [comment]
I'm annoyingly busy - there's only two things holding up release right now - packaging (been trying to get RollupJS working, but it's too complex a project for it apparently), and documentation needs updating reformatting from the Wiki to a "website" style (probably via Github Pages so it can use the same files).

If anyone wants to help with either they're very welcome to ;-)
