### ISSUE TITLE
ScrollLeft Lead to ”Maximum call stack size exceeded”

### ISSUE THREAD

**Issue by huangxiaona** [julianshapiro/velocity#866]
#### Your system information

* VelocityJS version: 2.0.2
* Browser: chrome
* Operating System: windows 7

#### Checklist

* Is this an issue with *code*?: Yes
* Is this an issue with *documentation*?: No
* Have you reproduced this in other browsers?: No
* Have you checked for updates?: Yes
* Have you checked for similar open issues?: Yes

> Please remember that this is an issue tracker, support requests should be posted on StackOverflow - see CONTRIBUTING.md

#### Please describe your issue in as much detail as possible:
Just try to simply make a scroll animation but get this error

#### Steps for reproducing this issue (code):

1. Velocity(document.body, {scrollTop: 100}, {duration: 500})

![image](https://user-images.githubusercontent.com/15116694/39340717-3764cfea-4a02-11e8-9851-f5690ba06d03.png)

**Comment by Rycochet** [comment]
Can you check it against the non-minified version on the `rollup` branch as a similar bug was found and fixed recently - https://raw.githubusercontent.com/julianshapiro/velocity/rollup/velocity.js

Got a feeling this one has slipped through, but want to prioritise my time this weekend :-)

**Comment by josuak** [comment]
I have the same issue, using this non-minified version didn't help for me

**Comment by dritter** [comment]
I have the same Issue with scrollTop:
```JavaScript
$container
                .velocity({
                    scrollTop: height
                }, {
                    duration: ((height / config.scrollSpeed) * 1000),
                    easing: "linear",
                    done: function(){
                        // Load next site, if scrolling is at the bottom,
                        // and timeout is over
                        $('html').scrollTop(0);
                        $('body').scrollTop(0);
                        $container.scrollTop(0);
                        defer.resolve();
                    }
                });
```

My StackTrace is:
```
getPropertyValue (getPropertyValue.ts:102)
(anonymous) (scroll.ts:62)
getPropertyValue (getPropertyValue.ts:102)
(anonymous) (scroll.ts:64)
getPropertyValue (getPropertyValue.ts:102)
(anonymous) (tweens.ts:23)
expandProperties (tweens.ts:88)
VelocityFn (core.ts:377)
scroll (index.php?dev=true:178)
successHandler (index.php?dev=true:261)
(anonymous) (jquery.js:3256)
j (jquery.js:3099)
fireWith (jquery.js:3211)
x (jquery.js:8264)
(anonymous) (jquery.js:8605)
load (async)
send (jquery.js:8622)
ajax (jquery.js:8166)
showNext (index.php?dev=true:215)
showNextLoop (index.php?dev=true:304)
mainLoop (index.php?dev=true:315)
(anonymous) (index.php?dev=true:325)
(anonymous) (jquery.js:3256)
j (jquery.js:3099)
fireWith (jquery.js:3211)
x (jquery.js:8264)
(anonymous) (jquery.js:8605)
load (async)
send (jquery.js:8622)
ajax (jquery.js:8166)
(anonymous) (index.php?dev=true:86)
(anonymous) (index.php?dev=true:328)
```
I am using VelocityJS 2.0.2.

From a quick look, it seems like [scroll.ts](https://github.com/julianshapiro/velocity/blob/2.0.2/src/Velocity/normalizations/scroll.ts#L62) calls [getPropertyValue.ts](https://github.com/julianshapiro/velocity/blob/2.0.2/src/Velocity/css/getPropertyValue.ts#L102) in a loop. The entry point is in [tweens.js](https://github.com/julianshapiro/velocity/blob/2.0.2/src/Velocity/tweens.ts#L23).

I don't have time to hunt that bug down, but I hope the infos help a bit.

**Comment by Rycochet** [comment]
There isa . related bugfix on the Rollup branch - if you've got time then feel free to test it - otherwise that'll be pulled back into master when I get it building properly for release (RollupJS seems to have problems in some complex situations, so it's eaten a lot of time that could have been put into doing useful things if it just worked as in their documentation).

**Comment by dritter** [comment]
Allright. If I try the `rollout` branch, another Error is raised: 
[eurega.test-1526567172139.txt](https://github.com/julianshapiro/velocity/files/2013592/eurega.test-1526567172139.txt)

**Comment by huangxiaona** [comment]
Sorry, too long to check my email. i've tried many things but still got nothing success, i just had to give up and find other way.  I'm going to close the issue and thanks everyone for giving suggestions
