### ISSUE TITLE
how to call the new ui-pack animations in v2?

### ISSUE THREAD

**Issue by vesper8** [julianshapiro/velocity#869]
Hey there, so I'm sorry if I am not reading this properly but I'm just really confused.

I've read in many places that the UI-Pack functionalities don't work for V2 yet.. but I'm super confused because on the main readme.md you have this

```
https://cdnjs.cloudflare.com/ajax/libs/velocity/2.0.2/velocity.ui.min.js
```

This is a 2.0.2 version of the UI-Pack.. is this being auto-generated in error or something? I just figure if you are making available a v2 version of the UI-Pack here then maybe that means it's working now?

But I can't figure out how to call it.

previously I was simply doing ```
$('.v--modal').velocity('transition.swoopIn');```

And this worked with version 1.5.1

now I'm using Velocity with Vuejs so it seems I have to call it differently.

so I'm doing it like this

```
import velocity from 'velocity-animate';
```

and then in my code

this works
```
velocity($('.v--modal'), { opacity: 1 }, { duration: 300 });
```

this doesn't work anymore, since I'm not including the js file directly and importing in vue instead
```
$('.v--modal').velocity('transition.swoopIn');
```

and this also doesn't work

```
velocity($('.v--modal'), 'transition.swoopIn');
```

I also tried rebuilding the swoopIn animation with the new syntax

```
      velocity(
        $('.v--modal'),
        {
          opacity: [1, 0],
          transform: "translateX(25px) scale(1.2)",
          transformOriginX: ['100%', '50%'],
          transformOriginY: ['100%', '100%'],
          scaleX: [1, 0],
          scaleY: [1, 0],
          translateX: [0, -700],
          translateZ: 0,
        },
        { duration: 850 },
      );
```

but this also doesn't work.

BTW I am importing the velocity-animate (which I installed with NPM @beta)

But I am manually including the https://cdnjs.cloudflare.com/ajax/libs/velocity/2.0.2/velocity.ui.min.js because there doesn't seem to be a npm package for that

I basically just really want to use the old animations in V2.. specifically the swoopIn animation.. and I don't mind rewriting it but would really love an example of how to write it using the new syntax because I'm just lost with trying to port over the old way of doing things to the new way

And like I mentioned, just really confused about whether the UI animations are working or not yet.. because I can see from your commit messages that you did very recently pull them in.. but I can't find any example of how to actually make calls to them.. despite the V2 of the UI package being available on your readme

apologies for the annoyance.. really like your package and looking forward to using V2 without issues

**Comment by vesper8** [comment]
thank you very much for adding a lot of clarity with your reply.. i understand much better now. I went back to using 1.5.1 for now but am really excited about using the new version and I hope you find the time to release 2.0.3 this weekend!

Cheers! keep up the fine work!

**Comment by Rycochet** [comment]
Leaving open as this question needs answering until the documentation catches up ;-)

**Comment by Rycochet** [comment]
This is now live on the master branch (still tagged beta right now)

**Comment by dolanb12** [comment]
I'm noticing the easing isn't working correctly when switching over from 1.5. Are there further options needed or is this an issue? Using slideOutDown, slideInDown, etc.

Thanks!

**Comment by Rycochet** [comment]
@dolanb12 The documentation will get done this weekend but they do work, just remember not to use any prefix (like transition or callout) on them - and when using them they replace the properties argument - so you can otherwise use options with them as they are just another animation -

```javascript
document.querySelectorAll(".myElements", "slideOutDown", {duration, 3000, progress: () => {...}, complete: () => {...}, ...etc});
```

**Comment by brunoamaral** [comment]
I just tried this with: $0.velocity("slideOutDown", {duration: 3000});

And I am getting an error:
`velocity.es5.js:4313 VelocityJS: First argument (slideOutDown) was not a property map, a known action, or a registered redirect. Aborting.`

What did I miss?

**Comment by Rycochet** [comment]
@brunoamaral Have you remembered to load the UI-Pack (`velocity.ui.js`) file too?

**Comment by brunoamaral** [comment]
@Rycochet thank you, that was it. I am using the new version and didn't know I had to attach `import 'velocity-animate/velocity.ui.min.js';` to have the UI pack. Thank you 🙂

**Comment by jascci** [comment]
Hello @Rycochet ,

I just stumbled upon this post as I was trying to understand how to use the V2 UI pack which I'm quite excited about.  
I understand that it's supposed to work now.  Are there some examples of how they're used?  
I tested a few, but could't get all of the effects to work and didn't find any example page in the Wiki.  Here's the codepen link:
https://codepen.io/pingowingo/pen/MXoOeB

Thanks a lot for any feedback.

**Comment by Rycochet** [comment]
@jascci There's a big example in the wiki for creating them - https://github.com/julianshapiro/velocity/wiki/Command---registerSequence

**Comment by jascci** [comment]
Hi @Rycochet,

I understand that the ui pack effects have been created and registered as sequences using the technique that is described in your aforementioned wikipage.  However, do you have a working example of all the effects?  In my codepen example, I could not get the simple "bounce" effect to run, which was referenced from the wiki doc [here](https://github.com/julianshapiro/velocity/wiki/Advanced---Sequences).

**Comment by Rycochet** [comment]
Ugh, looks like something is going wrong - I'm away this weekend so will have a quick look tonight, but next weekend I'm wanting to get the final polish done so it can come out of beta - and that means this needs to be working properly ;-)

**Comment by jascci** [comment]
Thanks @Rycochet, for looking into it despite your busy schedule.  I'll be looking forward to your response.

**Comment by jascci** [comment]
Hi @Rycochet,
Have you had a chance to look?  Thanks.

**Comment by Rycochet** [comment]
@jascci I was away all weekend, so will get a chance to look at it this coming weekend when I do the push out of beta.

**Comment by Salitehkat** [comment]
Hi, sorry to insist, i am also trying to use the bounce + shake effect and no matter how much i read and apply different codes, nothing works. Please, if you have some time can you check the above code? I am not using jquery,  but like 

elem.velocity("bounce");

Thanks a lot for your time.

**Comment by Rycochet** [comment]
@Salitehkat That's pretty much exactly it - just look through the wiki - https://github.com/julianshapiro/velocity/wiki/Advanced---Sequences

**Comment by Salitehkat** [comment]
Thanks so much for answering. 

I am loading an external svg, and animating an element inside callling:

**gen = document.getElementById('gen');**

When i write 

**gen.velocity("bounce");**

it gives me the following error:

**velocity.min.js:485 bad type {fn: ƒ, sequence: Array(9)} transform null**
and
**velocity.min.js:902 Error: <circle> attribute transform: Expected '(', "translate3d(0,0px,0)".** 

18 times. 

I am adding velocity like this: 

**<script src="//cdnjs.cloudflare.com/ajax/libs/velocity/2.0.3/velocity.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/velocity/2.0.3/velocity.ui.min.js"></script>**

What can it be? a problem because its an svg? 

thanks again and sorry the disturb

**Comment by Rycochet** [comment]
Try 2.0.5 - looks like the README lists the wrong version number for Cloudflare (that's the reason I don't use it) - the top of the README does list which version is available on there, it's just not in the text.

**Comment by Salitehkat** [comment]
Merci, I will.
