### ISSUE TITLE
Infinite repeating or looping animation stuck if the browser tab went hidden and back active

### ISSUE THREAD

**Issue by huansern** [julianshapiro/velocity#871]
#### Your system information

* VelocityJS version: 2.0.2
* Browser: Chrome (66.0.3359.181), Firefox (60.0.1), Safari (11.0.3)
* Operating System: macOS High Sierra v10.13.3

#### Checklist

* Is this an issue with *code*?: Yes
* Is this an issue with *documentation*?: No
* Have you reproduced this in other browsers?: Yes
* Have you checked for updates?: Yes
* Have you checked for similar open issues?: Yes

#### Please describe your issue in as much detail as possible:
Pausing a repeating/looping animation, switch to the other tab, then switch back to the original tab and then finally resume the repeating animation. The animation will appear being stopped as the `percentComplete` is stuck at 1 after the current iteration complete. Using a custom easing function to console log the `percentComplete` value shows that it stuck at 1 but the animation is still running. Obviously the expected result would be the animation repeating indefinitely until the next `pause` or `stop` command. However, I still not sure if I am doing it wrong in [here](https://jsfiddle.net/speeds/0fs39vg5/) since this could be the expect result.

#### Steps for reproducing this issue (code):

1. Create an infinitely repeating animation.
```
Velocity(document.querySelector('#rect'), {
  x: [170, 'linear', 10]
}, {
  duration: 2000,
  repeat: true
})
```
2. Pause the animation when the tab is hidden
```
Velocity(document.querySelector('#rect'), 'pause')
```
3. Resume the animation when the tab is active
```
Velocity(document.querySelector('#rect'), 'resume')
```

#### JSFiddle example showing issue in action (code):
https://jsfiddle.net/speeds/0fs39vg5/

On the side note, the same thing happens if we `stop` or `finish` the animation and then create a new repeating ones on the same element.

**Comment by Rycochet** [comment]
For some reason the JSFiddle you were using had the 1.2.4 version of Velocity in there too - but tested with 2.0.3 and it works as expected now. Not sure where it was going wrong there, but might be something that's been fixed with the other major changes.
