### ISSUE TITLE
Glitch in animation with backwards option

### ISSUE THREAD

**Issue by dolanb12** [julianshapiro/velocity#872]
#### Your system information

* VelocityJS version: 0.7.0
* Browser: Chrome
* Operating System: Win10

#### Checklist

* Is this an issue with *code*?: [Yes]
* Is this an issue with *documentation*?: [No]
* Have you reproduced this in other browsers?: [Yes] Firefox, Edge
* Have you checked for updates?: [Yes]
* Have you checked for similar open issues?: [Yes]

> Please remember that this is an issue tracker, support requests should be posted on StackOverflow - see CONTRIBUTING.md

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen.

(On JSFiddle, below)
All works fine when navigating forward and backwards from screen to screen.
_Except_, when I navigate forwards (by clicking anywhere), then navigate backwards with the back button, and then navigate forwards again -- there is a stutter in the animation.

I have found that by removing the `backwards: true` option (which is set on the fade-in animation), the issue goes away. However, this option ensures my animation to load items in the order I need them to.

Any suggestions on how to fix this issue?

Thank you!

#### Steps for reproducing this issue (code):

1. 
2. 
3. 

#### JSFiddle example showing issue in action (code): [JSFiddle](http://jsfiddle.net/dolanbrendan12/dsrm45dj/2/)

> Go to https://jsfiddle.net/Rycochet/mqv9L27u/ - click the "Fork" button at the top, create the example and copy the new URL back here.

**Comment by Rycochet** [comment]
Can you test it with Velocity V2 beta - V1 isn't supported, and V0.7.0 became unsupported almost 4 years ago - in fact 0.8.0 was released 3 days later...

**Comment by dolanb12** [comment]
Apologies, this fiddle began an experiment. Just copied the info from a pen
I found.

So V2 didn't isn't loading transitions correctly. slideUpIn, slideUpOut,
etc. are simply fading in/out. The delay and stagger seem to be working
fine.

Upon more experimentation, V1.5.0 loads transitions correctly, but I still
have the original problem (as in 0.7.0): with `backwards: true` being the
culprit.

Here are fiddles with V2.0.2 <http://jsfiddle.net/dolanbrendan12/xs8ykhsv/>
and V1.5.0 <http://jsfiddle.net/dolanbrendan12/q3wmx8g8/>, for convenience.


Any suggestions?

Thanks for your help.  : )

Brendan

**Comment by dolanb12** [comment]
Update: Got it to work with V1.5.0. Just not with 2.0.2.

**Comment by Rycochet** [comment]
V2 doesn't have the old style transitions - they're now named to match the animate.css transitions directly, see other issues for details (I really need to get the documentation done!)

**Comment by dolanb12** [comment]
Got it! Totally understand. I'll wait until 2.0.3 is ready. : )

Thanks for the help.
