### ISSUE TITLE
Queue does not work if duration isn't set explicitly [v2.0.3]

### ISSUE THREAD

**Issue by nreynis** [julianshapiro/velocity#874]
#### Your system information

* VelocityJS version: 2.0.3
* Browser: FF60, Chrome 66, Edge 40
* Operating System: Windows 10

Queue works only if an explicit duration is used. If you rely on the default duration (400ms) it does not works.

#### JSFiddle example showing issue in action (code):
https://codepen.io/anon/pen/jKNaqg

**Comment by Rycochet** [comment]
That's weird, it should be grabbing the default value if it's not explicitly provided :-(
