### ISSUE TITLE
how to completely remove style animations when it ends

### ISSUE THREAD

**Issue by alex-shatalov** [julianshapiro/velocity#882]
i have animation like that

velocityHelpers.registerEffect({
    calls: [[{ translateX: ['100%', '0%'] }]]
  })

and after it complete i what to remove translateX at all from styles
reset: { translateX: 'null' } or any another value like 0, 'inherit', '' did not help.

so is it possible to remove translateX ?

**Comment by brunoamaral** [comment]
I believe you can call the .reverse() method to undo the animation. Does that help?

**Comment by alex-shatalov** [comment]
@brunoamaral, all animations works well. Reverse will return to start value. But i need to remove  translateX from div="style: transform: translateX(0%)", because presence of that property in style breaks some css.  Doing it by selecting element and manipulate dom when complete callback fired i think is not good

**Comment by Rycochet** [comment]
This is a StackOverflow support question.
