### ISSUE TITLE
vue.js: Uncaught (in promise) undefined , if i change pages , it will be filled with my console

### ISSUE THREAD

**Issue by krisGooooo** [julianshapiro/velocity#891]
vue mounted():

  setInterval(function () {
      Velocity(t.$refs.top, {
        opacity: [0.3,1]
      }, {
        duration: 2500,
      });

      Velocity(t.$refs.str01Top, {
        opacity: [0,1]
      }, {
        duration: 2500,
      });   
    } ,2500)

**Comment by mateusmoura** [comment]
????

**Comment by schester44** [comment]
what was the solution @krisGooooo
