### ISSUE TITLE
Deprecated "options.display" used, this is now a property: block

### ISSUE THREAD

**Issue by Frohmen** [julianshapiro/velocity#893]
#### Your system information

* VelocityJS version: 2.0.5

I don't understand what I should do instead, and the documentation doesn't mention anything about this.

**Comment by Rycochet** [comment]
That's about as plain English as it can be. Use it as a property...

```javascript
element.velocity({left:"10px", display:"block"});
```

**Comment by Frohmen** [comment]
That is exactly what I'm doing and what's causing the error.

**Comment by Rycochet** [comment]
No, to cause the error you're doing:

```javascript
element.velocity({left:"10px"}, {display:"block"}); // Don't do, this is wrong!!!
```

**Comment by Frohmen** [comment]
What about: First argument (slideDown) was not a property map, a known action, or a registered redirect. Aborting.

**Comment by Rycochet** [comment]
https://github.com/julianshapiro/velocity/wiki/Advanced---Sequences

**Comment by Frohmen** [comment]
But after I have included velocity.ui.min.js on my page and used slideInDown instead I get a similar error: velocity.min.js?d442af1e1c5a8d37c8808d391f6f99fa:6 VelocityJS: First argument (slideInDown) was not a property map, a known action, or a registered redirect. Aborting.
