### ISSUE TITLE
I don't know where should I place my message so let it be here.

### ISSUE THREAD

**Issue by ZaqTheDuck** [julianshapiro/velocity#894]
'queue' doesn't work with loops. I found a solution: using setInterval() with a counter. 

PS I think that the pearson reading it must know this, so please don't downvote me or something like that, I just wanted to share this lifehack and didn't know where could I do that.

**Comment by Rycochet** [comment]
The correct place for this is StackOverflow - it's also wrong now as it's only related to v1, which is not supported any more.
