### ISSUE TITLE
Project is dead ?

### ISSUE THREAD

**Issue by riiccardo** [julianshapiro/velocity#895]
I opened a issue about a new version (v2) about **a year ago**.

But I have not seen any changes since then

is project dead ?

**Comment by Rycochet** [comment]
If you've not seen any changes then you've obviously not opened your eyes - just look no the Code page and you see changes up to 3 months ago - I've just been extremely busy and not had time to put into a non-paying project lately.

Secondly, you opened your issue in February, that's also not a year ago - and it was also answered and closed after being opened.

This is an issue tracker, if you want to waste my time on stupid comments then it'll give me even less incentive to find time for Velocity - if on the other hand you want to help then how about putting some of your time into coding for it?
