### ISSUE TITLE
Treat 'visibility' like 'display'

### ISSUE THREAD

**Issue by wonderfool** [julianshapiro/velocity#9]
It would be great if we could have a "visibility" option that behaves the same way as Velocity's "display" option - i.e. when set to "visible" it is applied up front, and when set to "hidden" it is applied at the conclusion of the animations.  

Also, Velocity is great.

**Comment by leevigraham** [comment]
@julianshapiro To confirm adding visibility: visible to a fadeIn animation should change the visibility css attribute to visible before any animation starts allowing me to measure the height of the element? I'm currently seeing the opacity:0 *and* display:none.

**Comment by julianshapiro** [comment]
yup, please post a fiddle if you're having issues. would like to see it. ty!
