### ISSUE TITLE
All Href are disabled. Why?

### ISSUE THREAD

**Issue by mavatar** [julianshapiro/velocity#905]
#### Your system information

* VelocityJS version: 
* Browser: 
* Operating System: 

#### Checklist

* Is this an issue with *code*?: [Yes/No]
* Is this an issue with *documentation*?: [Yes/No]
* Have you reproduced this in other browsers?: [Yes/No]
* Have you checked for updates?: [Yes/No]
* Have you checked for similar open issues?: [Yes/No]

> Please remember that this is an issue tracker, support requests should be posted on StackOverflow - see CONTRIBUTING.md

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen.

#### Steps for reproducing this issue (code):

1. 
2. 
3. 

#### JSFiddle example showing issue in action (code):

> Go to https://jsfiddle.net/Rycochet/mqv9L27u/ - click the "Fork" button at the top, create the example and copy the new URL back here.

**Comment by Rycochet** [comment]
Haven't a clue what this is talking about...
