### ISSUE TITLE
SlideDown and SlideUp

### ISSUE THREAD

**Issue by MadZee-M** [julianshapiro/velocity#907]
#### Your system information

* VelocityJS version: 2.05
* Browser: Chrome
* Operating System: Win 10

#### Checklist

* Is this an issue with *code*?: [Yes]
* Is this an issue with *documentation*?: [No]
* Have you reproduced this in other browsers?: [Yes]
* Have you checked for updates?: [Yes]
* Have you checked for similar open issues?: [Yes]

Good day! 

Sorry for my English :)

I'm trying to create Actions, But after executing the code, some kind of bug happens.
If you click on the slideUp twice, the slideDown works more or less normally.

What could be the problem?
Thank!

[https://playcode.io](https://playcode.io/303165?tabs=console&script_2.js&output)

**Comment by Rycochet** [comment]
I'm really not sure what you're trying to achieve there, it's possible to do what you want, but like trying to use a sledgehammer to tighten a screw - `registerAction` isn't designed for creating animations, and you've got such complicated code that I've really not got the time to try and track it down.

Have a look at the two files that actually add what you need, and if you need to do your own versions then just copy and adjust them (using `registerSequence`)

https://github.com/julianshapiro/velocity/blob/master/src-ui/sliding_entrances/slideInDown.ts
https://github.com/julianshapiro/velocity/blob/master/src-ui/sliding_exits/slideOutUp.ts

For code support you should go to StackOverflow, this isn't a bug with Velocity.

**Comment by MadZee-M** [comment]
> I'm really not sure what you're trying to achieve there, it's possible to do what you want, but like trying to use a sledgehammer to tighten a screw - `registerAction` isn't designed for creating animations, and you've got such complicated code that I've really not got the time to try and track it down.
> 
> Have a look at the two files that actually add what you need, and if you need to do your own versions then just copy and adjust them (using `registerSequence`)
> 
> https://github.com/julianshapiro/velocity/blob/master/src-ui/sliding_entrances/slideInDown.ts
> https://github.com/julianshapiro/velocity/blob/master/src-ui/sliding_exits/slideOutUp.ts
> 
> For code support you should go to StackOverflow, this isn't a bug with Velocity.

Thanks for your reply! 
I copied this piece of code to them v1 and slightly redid it.

**Comment by designosis** [comment]
Could I trouble someone for guidance on how sliding is supposed to work in v2?

I'd like jQuery to trigger a velocity `slideInDown`, pushing content below it down as it slides in.

https://jsfiddle.net/designosis/9xjpnmf0/

Two separate problems are happening:
1. It fades in, doesn't slide. What secret handshake is required to get sliding to work?
2. Content isn't sliding. I know it's not supposed to, since velocity uses `visibility` and `opacity`, not `display`, for its magic. Any advice on how to achieve what I want?

**Comment by Rycochet** [comment]
It looks like there's an issue with the `transform` handling - not quite sure what's going on there, but there's another report about it not working on iOS (#920). I'm currently in the (slow-ish) process of updating everything and adding proper unit tests to hopefully prevent issues like this happening.

As far as getting it working, you can register a replacement (maybe give it another name) which doesn't suffer from the issue (note `translate(x,y)` and `translate3d(x,y,z)` both have this issue, but `translateY` works properly) - 

```js
Velocity("registerSequence", "slideInDown", {
	"duration": 1000,
	"0%": {
		transform: "translateY(-100%)",
		visibility: "visible",
		opacity: "0",
    display: "block",
	},
	"100%": {
		transform: "translateY(0%)",
		opacity: "1",
	},
});
```

If you want the element below it to slide down at the same rate then it'd need more work, and a separate animation that could sync with the first one etc :-)

**Comment by designosis** [comment]
I'm having so many problems figuring out how to get basic v1 functionality in v2 that I've given up :)
Is there a migration guide for v1 -> v2?

**Comment by Rycochet** [comment]
They are practically identical for all bar a few things - there's a [V2_CHANGES](https://github.com/julianshapiro/velocity/blob/master/V2_CHANGES.md) file that lists the changes, but the basic functionality has remained the same so you need to give more details with what you are having problems with. The biggest thing is to simply not touch the website - trying to figure things out relative to that will never work - look at the [wiki](https://github.com/julianshapiro/velocity/wiki) instead!
