### ISSUE TITLE
Android 4.4.4

### ISSUE THREAD

**Issue by xuqinghua** [julianshapiro/velocity#908]
#### Your system information

* VelocityJS version: 2.0.5
* Browser: Mozilla/5.0 (Linux; Android 4.4.4; MI 3C Build/KTU84P) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/33.0.0.0 Mobile Safari/537.36 MicroMessenger/6.7.2.1340(0x2607023A) NetType/WIFI Language/zh_CN
* Operating System: Android 4.4.4;

#### Checklist

* Is this an issue with *code*?: [Yes/No]
* Is this an issue with *documentation*?: [Yes/No]
* Have you reproduced this in other browsers?: [Yes/No]
* Have you checked for updates?: [Yes/No]
* Have you checked for similar open issues?: [Yes/No]

> Please remember that this is an issue tracker, support requests should be posted on StackOverflow - see CONTRIBUTING.md

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen.

#### Steps for reproducing this issue (code):

1. 
2. 
3. 

#### JSFiddle example showing issue in action (code):

> Go to https://jsfiddle.net/Rycochet/mqv9L27u/ - click the "Fork" button at the top, create the example and copy the new URL back here.

**Comment by Rycochet** [comment]
Not a bug report...
