### ISSUE TITLE
Velocity transform overwrite my css transform

### ISSUE THREAD

**Issue by subdance** [julianshapiro/velocity#910]
I use 
```
transform: translate(-50%, -50%);
```
to center an element.<br>
but when I add this 
```
Veocity(element,  {transform: ['scale(0.3)', 'scale(1)']}, {duration: 500});
```
the element scales successfully, but will also move to the palce where the css transform preperty not working.

**Comment by Rycochet** [comment]
That's not a bug, in fact it's exactly how it's designed to work - if you want to use both then add your translate to the same transform animation -

`Velocity(element,  {transform: ['translate(-50%, -50%) scale(0.3)', 'translate(-50%, -50%) scale(1)']}, {duration: 500});`
