### ISSUE TITLE
I accidently "pushed" two files into velocity

### ISSUE THREAD

**Issue by David263** [julianshapiro/velocity#912]
#### Your system information

* VelocityJS version: 
* Browser: 
* Operating System: 

#### Checklist

* Is this an issue with *code*?: [Yes/No]
* Is this an issue with *documentation*?: [Yes/No]
* Have you reproduced this in other browsers?: [Yes/No]
* Have you checked for updates?: [Yes/No]
* Have you checked for similar open issues?: [Yes/No]

> Please remember that this is an issue tracker, support requests should be posted on StackOverflow - see CONTRIBUTING.md

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen.

#### Steps for reproducing this issue (code):

1. 
2. 
3. 

#### JSFiddle example showing issue in action (code):

> Go to https://jsfiddle.net/Rycochet/mqv9L27u/ - click the "Fork" button at the top, create the example and copy the new URL back here.

**Comment by David263** [comment]
I don't know very much about github. I was trying out GitHub Desktop on Windows 10 and it said I had two files to be pushed. I wanted to find out more, so I clicked something to view the files. Instead, the program did lots of operations (getting a delta was one of them) and it looked like it could have pushed two files into the Velocity project. I apologize for any messing up I have done.

**Comment by Rycochet** [comment]
You don't have write access to it, so you haven't actually done anything - don't worry, and good luck with learning more about Github! :-)
