### ISSUE TITLE
Security issue - How to report you about it ?

### ISSUE THREAD

**Issue by alberto-f** [julianshapiro/velocity#918]
Hello, I have noticed a security issue. How should I expose the issue ? I dont know how to get it fixed but I can reproduce it easily. Since it is already happening, do you prefer that I disclose it in here ?

**Comment by Rycochet** [comment]
Depending how "bad" it is then up to you - if you're unsure then you can send it to me (my username at my username dot com for email) :-)

If you know a fix for it then feel free to PR it, but understandable if not ;-)

**Comment by alberto-f** [comment]
I dont know from where it can come. Is the velocityjs site public for code review ? Im not security researcher though.

**Comment by Rycochet** [comment]
It's not - forwarded your message to @julianshapiro - the old website will (probably) get retired and moved over to github sites, but needs time to finish the updated docs among other things :-)
