### ISSUE TITLE
Animating scrollTop on scrollable elements

### ISSUE THREAD

**Issue by zhoumao1** [julianshapiro/velocity#919]
I mentioned earlier that using $(element).velocity('scroll', {container: viewElement}) is fine
Now use Velocity(Element, {})??    
What can I do to achieve scrollTop

**Comment by Rycochet** [comment]
https://github.com/julianshapiro/velocity/wiki/Property---ScrollTop

**Comment by ImSeaWorld** [comment]
No answer to his question there.

**Comment by Rycochet** [comment]
> No answer to his question there.

If you don't think that pointing at the exact documentation that shows how to use `scrollTop` is not an answer, then you might be reading the wrong question...

**Comment by ImSeaWorld** [comment]
Yeah obviously it's me...
