### ISSUE TITLE
Changing width and translate at the same time causes crash

### ISSUE THREAD

**Issue by joeraad** [julianshapiro/velocity#928]
#### Your system information

* VelocityJS version: 2.0.6
* Browser: Chrome/Safari
* Operating System: Windows 10

#### Checklist

* Is this an issue with *code*?: No
* Is this an issue with *documentation*?: No
* Have you reproduced this in other browsers?: Yes
* Have you checked for updates?: Yes
* Have you checked for similar open issues?: Yes

#### Please describe your issue in as much detail as possible:

I wanted to change the dimensions of a video container and then make the video bigger while repositioning it to be centered in the container. https://jsfiddle.net/0j869yqw/1/
```
document.getElementById("div1").velocity({width:"100px", transform:"translateX(-50px)" }, {
     duration: 100,
     easing: "swing",
     loop: false,
     delay: 0,
})
```

I ended up using the on progress function percentage complete to manually change the transform like so https://jsfiddle.net/wcd27as5/3/
```
document.getElementById("div1").velocity({width:"100px", }, {
     duration: 100,
     easing: "swing",
     loop: false,
     delay: 0,
     progress: function(elements, percentComplete, activeCall){
       translate=50*percentComplete
       document.getElementById("div1").style.transform="translateX("+translate+"px)"
     },
})
```

#### Steps for reproducing this issue (code):

1. change width and transform at the same time
2. or change transform in the progress function of the width change

#### JSFiddle example showing issue in action (code):
https://jsfiddle.net/0j869yqw/1/

**Comment by Rycochet** [comment]
The issue is that there's no deconstruction to know what the starting value of `transform` should be - if you forcefeed it with 0 then it works perfectly well -

```js
document.getElementById("div1").velocity({
    width:"100px",
    transform:["translateX(-50px)", "translateX(0px)"]
}, {
     duration: 100,
     easing: "swing",
     loop: false,
     delay: 0,
})
```

Going to leave this open as it relates to being able to "just work" where this is something that has never been supported, and should be!

**Comment by joeraad** [comment]
Oh ok thanks for the clarification. I misunderstood how forcefeeding worked and was doing it wrong so it didn't do anything when I ran it.
