### ISSUE TITLE
"This expression is not a callable" when instanciating Velocity

### ISSUE THREAD

**Issue by bolinocroustibat** [julianshapiro/velocity#934]
#### Your system information

* VelocityJS version: 1.5.2
* Browser: Chrome 101
* Operating System: MacOS

#### Problem description

When calling creating a `Velocity` instance after installing it with npm and importing it (`npm install velocity-animate`), I get this VSCode error:
`This expression is not callable.
  Type '{ State: { isMobile: boolean; isAndroid: boolean; isGingerbread: boolean; isChrome: any; isFirefox: boolean; prefixElement: HTMLDivElement; prefixMatches: {}; scrollAnchor: any; ... 4 more ...; delayedElements: { ...; }; }; ... 13 more ...; resumeAll: (queueName: any) => void; }' has no call signatures.js(2349)`

#### Example

    import Velocity from 'velocity-animate';

    Velocity(
        element,
        { left: newPosition[0], top: newPosition[1] },
        {
            duration: duration,
            step: function () {},
            complete: function () {},
        }
    );

**Comment by Rycochet** [comment]
Velocity v1 isn't supported any more, and wasn't designed for `npm` use really - it adds a global `Velocity` (or `window.Velocity`) which might be usable (ie, import, then use - no trying to get anything from the import) - don't know if that would work but it might do!

**Comment by bolinocroustibat** [comment]
Thanks for answering. FYI and for other folks passing by this issue, since then I've been trying with velocity v2, importing the local package velocity v2 with npm. Adapting a bit the arguments to Velocity function in the v2 format, it works great.

`npm install --save /lib/velocity-2.0.5`

`import Velocity from "velocity-animate";`

Follow doc from Velocity v2 wiki for usage: https://github.com/julianshapiro/velocity/wiki/Basic---Arguments
