### ISSUE TITLE
Help Wanted: Do a better job than me on the slideDown/slideUp sequences

### ISSUE THREAD

**Issue by julianshapiro** [julianshapiro/velocity#96]
Velocity's packaged slideUp/slideDown sequences are ugly. They're the only part of Velocity's codebase that I don't like: https://github.com/julianshapiro/velocity/blob/master/jquery.velocity.js#L2681

To tackle recoding them, you'll first need to read the docs on Sequences (http://VelocityJS.org/#sequences) and `display` toggling (http://VelocityJS.org/#display).

Next, here's a snippet you can use to quickly test your fork. Make sure this runs the same in your fork as it does in the current version of Velocity:

``` javascript
$element
    .css({ overflow: "scroll", height: 400 })
    .delay(1500)
    .hide()
    .velocity("slideDown", 1000)
    .velocity("slideUp", 1000)
    .velocity("slideDown", "easeInOutQuad", 1000, function() { console.log("All done!") });
```

If you have any questions about why the current slide sequences are coded they way they are, ask here. It would be my pleasure to expand on my existing decisions (which I don't think are necessarily very sound).

Two things I'll preemptively point out:
- Overflow toggling is done so that scrollbars don't show during the animation (to parallel jQuery's implementation, but it's also a good idea from an aesthetic standpoint).
- Reverting to a height of "auto" (if appropriate) is an ugly necessity. Refer to the code for more info.

Finally, I'm looking for an enhancement: Don't re-trigger the slideDown animation if the element is already visible. Likewise, don't re-trigger slideUp if the element is already hidden.

**Comment by 4ants** [comment]
How can we prevent animation "stacking" when using "slideDown" and "slideUp"? In JQuery I used "stop"?

Example (on click function):

var elem = document.getElementById('#test');
Velocity(elem, elem .clientHeight > 0 ? 'slideUp' : 'slideDown');

**Comment by MattyBalaam** [comment]
The simple answer is by using Velocity(elem, 'stop').

The long answer is that I just tried it and it causes some issues with caching heights if used before an animation has been completed.

**Comment by 4ants** [comment]
Yes, I have tried that. Animation is messed up then.

**Comment by eddneal** [comment]
@MattyBalaam Did you find a solution to prevent the animation "stacking" which didn't cause the height caching issue? Thanks in advance.
