### ISSUE TITLE
Request: Include UI Pack file in package.json (for npm)

### ISSUE THREAD

**Issue by feross** [julianshapiro/velocity#97]
I want to use `velocity.ui.js` but it's not published to npm.

`npm install velocity-animate`

``` bash
$ ls node_modules/velocity-animate
README.md          jquery.velocity.js package.json
```

Not sure why it didn't get published -- can you look into this?

**Comment by oompt** [comment]
Anyone know of a similar workaround as above, but for jspm?

**Comment by RandallGit** [comment]
with just npm how would I use velocity-ui-pack?

**Comment by feross** [comment]
@RandallGit Can you open a new issue instead of posting in one that's almost a year old.
